### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by hija621** [RivrsMc/SeasonSky-Issues#10]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Hija621

### Pseudo discord

hija621

### Que s'est-il passé ?

Le nombre requis de côtelettes pour le premier rangs est bloqué pour certains 

### Étapes à suivre pour reproduire le bug

Avoir Les presrequis du premier rang
Faire /rang

### Qu'aurait-il dû arriver ?

Avoir le bon nombre de côtelettes 

### Date et heure de la production du bug

08/07 20h

### Serveur

Tous

### Screen / vidéo

![image-13](https://github.com/RivrsMc/SeasonSky-Issues/assets/135941180/0715e3c2-0177-492a-97fa-81da84717df3)

### Information supplémentaire

Pour certains ça fonctionne ou fonctionnais avant

**Comment by LuluxClient** [comment]
C'est fixed
