### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by AlphaMew56** [RivrsMc/SeasonSky-Issues#100]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

ToujoursPyre

### Pseudo discord

_Pyre

### Que s'est-il passé ?

Je ne peux pas récupérer les items que j'ai mit dans le crystal de mon île.

### Étapes à suivre pour reproduire le bug

Aller dans l'interface de gauche du crystal et essayer de reprendre un item.

### Qu'aurait-il dû arriver ?

J'aurai du avoir une nouvelle interface pour savoir le nombre de bloc dont j'ai besoin.

### Date et heure de la production du bug

13-07 14:11:12

### Serveur

island-01

### Screen / vidéo

![2023-07-13_14 13 43](https://github.com/RivrsMc/SeasonSky-Issues/assets/62618882/031aa2a8-668c-4a5c-9b72-70b408737bc2)

### Information supplémentaire

UUID: da0c9ad1-ed02-4cc9-931f-ae8385ca4ca6
Position: -7205 102 -14404 SuperiorWorld
Ping: 25ms

**Comment by LuluxClient** [comment]
Tu ne peux pas récupérer les objets non permanent de ton Crystal d'île, tu as le bouton à gauche pour voir tu as combien d'objet et combien de niveau cela te rapporte
