### ISSUE TITLE
[BUG] Clear arc du chasseur tp

### ISSUE THREAD

**Issue by Kutakimochi** [RivrsMc/SeasonSky-Issues#101]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Kutakimochi

### Pseudo discord

Kutakimochi#0879

### Que s'est-il passé ?

J'étais a la ferme de jean et lorsque j'ai /is mon arc du chasseur dans la 2ème main a despawn, j'ai déja perdu 2 arc comme ca, cela n'arrive pas a chaque tp mais des fois ci

### Étapes à suivre pour reproduire le bug

1. être a la ferme de jean avec un arc du chasseur dans la 2ème main
2. faire /is
3. et des fois perdre son arc

### Qu'aurait-il dû arriver ?

j'aurais du garder mon arc

### Date et heure de la production du bug

13-07 15:52:42

### Serveur

island-04

### Information supplémentaire

UUID: 9a5af67d-a45d-4d99-bac2-f922ae376afd
Position: 14394 100 3597 SuperiorWorld
Ping: 21ms

**Comment by LuluxClient** [comment]
Est ce que tu effectuais des actions précises pour faire despawn ton objet dans ta 2eme main / est ce que tu avais des cosmétiques activés peut être en avance ?

**Comment by Kutakimochi** [comment]
Nan pas spécialement
après je te conseil d'attendre je suis pas 100% sur parce que je le remarque pas directement, on m'a dit que je l'ai peut etre /trash mais comme on ne voit pas la 2ème main dans le /trash je ne pense pas.

**Comment by LuluxClient** [comment]
Je n'arrive pas à le reproduire, n'hésite pas à re ouvrir une issue si le bug persiste.
