### ISSUE TITLE
[BUG] les /classement ne sont pas synchro

### ISSUE THREAD

**Issue by Amateur2Drapeau** [RivrsMc/SeasonSky-Issues#102]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MaelEnFrance

### Pseudo discord

maelenfrance

### Que s'est-il passé ?

le /classement ne se synchronise pas entre les serveurs, le top 1 poisson peché island 6 est peut etre le top 3 island 4, pareil pour les autres classements (jobs comprit)

### Étapes à suivre pour reproduire le bug

/jobs

### Qu'aurait-il dû arriver ?

les serveurs auraient dû synchro les classements

### Date et heure de la production du bug

13-07 16:20:35

### Serveur

island-06

### Screen / vidéo

x

### Information supplémentaire

UUID: ccf4c91d-a9da-442e-94df-2a03f6b3cb1a
Position: 5390 39 -3632 SuperiorWorld
Ping: 21ms

**Comment by LuluxClient** [comment]
Nous allons voir pour faire un système full synchronisé, je laisse cette issue ouverte

**Comment by NoHere32** [comment]
Un plugin custom sera fait prochainement
