### ISSUE TITLE
[BUG] Xp fonte mineur

### ISSUE THREAD

**Issue by Isweazu** [RivrsMc/SeasonSky-Issues#104]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Isweazu

### Pseudo discord

xx4040

### Que s'est-il passé ?

Je ne sais pas si c'est fais exprès ou un oublis lors du changement niveau de la fonte (joueurs ect) mais les haut fourneau ne donnent plus d'xp mineur, mais les fours normaux en donnent mais avant le changelog ça en donnait en haut fourneau aussi ^^'

EDIT : le haut fourneau ne donne pas d'xp uniquement si il était déjà posé, même si on rentre dans l'interface / sors, pour avoir l'xp jobs par la suite il faut le casser et le re-poser à chaque fois

### Étapes à suivre pour reproduire le bug

Faire fondre des minerais dans les hauts fourneau, ça ne donne pas d'xp

### Qu'aurait-il dû arriver ?

Avoir de l'xp sauf si ça a été modifié et que ce n'est pas un simple oubli

### Date et heure de la production du bug

18h22 le 13/07

### Serveur

island 06

**Comment by itsme-to** [comment]
Bonjour @Isweazu, j'ai fait quelques tests, j'aimerais un avoir un peu plus d'informations pour essayer de le résoudre:
- Est-ce que le probleme existe toujours ?
- Que veux-tu dire par "re-poser à chaque fois" comment ça chaque fois ?

**Comment by Isweazu** [comment]
> Bonjour@Isweazu, j'ai fait quelques tests, j'aimerais un avoir un peu plus d'informations pour essayer de le résoudre :
> 
> * Est-ce que le problème existe toujours ?
> * Que veux-tu dire par "re-poser à chaque fois" comment ça chaque fois ?

Oui il existe toujours, en gros, si le haut fourneau est déjà posé, après une deco-reco pas exemple, ils ne donneront pas d'xp même en ouvrant le four.
Pour le résoudre il faut à chaque fois (chaque déco-reco) casser et re-poser le haut fourneau, aucun problème avec un four normal

**Comment by entropy-hub** [comment]
à tester dans la nouvelle version RivrsJobs

**Comment by NoHere32** [comment]
Good dans la journée
