### ISSUE TITLE
Bug is permission

### ISSUE THREAD

**Issue by Jspppppp** [RivrsMc/SeasonSky-Issues#105]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Jspppppp

### Pseudo discord

Mathéo#8230 / Jspppppp (l'ours)

### Que s'est-il passé ?

Hello, en gros une fois j'ai mi que mon mate Pireus ne pouvais pas bypass la fermeture de l'ïle grace au /is permission peusdo. Après je lui est re permis de pouvoir bypass mais à chaque redémarrage la permission saute et quand je ferme l'île il se fait kick et je suis obliger de re /is permission Pireus.

### Étapes à suivre pour reproduire le bug

Expliquer dans le Que s'est-il passé ?

### Qu'aurait-il dû arriver ?

Expliquer dans le Que s'est-il passé ?

### Date et heure de la production du bug

A chaque redem

### Serveur

Island 3

**Comment by LuluxClient** [comment]
Donc tes permissions se reset à chaque redem c'est bien ça ? Je vais tenter 2-3 trucs en dev pour voir comment bien reproduire ce bug

**Comment by Jspppppp** [comment]
Hello, yes c'était ça. Apparament la ça marche mon pote pouvais pas open les coffres après redem (un autre mate) et la il peut !

**Comment by Jspppppp** [comment]
Par contre, Pireus quand je close l'is il et tej

**Comment by LuluxClient** [comment]
Hello @Jspppppp est ce que ce bug est toujours d'actualité ?

**Comment by Jspppppp** [comment]
Hello normalement non donc tu peux close si tout est bon pour toi @LuluxClient ^^
