### ISSUE TITLE
[BUG] Up rank Ingénieur

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#106]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

Il y a un problème pour les missions, ca compte les missions facile au lieu des difficiles comme écrit
La couleur de la quete nous montre la quete facile d'ou le problème

### Étapes à suivre pour reproduire le bug

1. etre batisseur
2. regarder ce qu'il faut pour up rank ingénieur

### Qu'aurait-il dû arriver ?

ca devrait etre des missions difficiles qui devrait etre compté

### Date et heure de la production du bug

13/07/2023 19:51

### Serveur

island 02

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/be5c9dc2-99d9-48e2-a525-f3f7e1651c5d)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/cfa0ba9f-7ef4-4b2d-8d95-6f62a2181793)

### Information supplémentaire

plus d'info contacté Nelylife

**Comment by LuluxClient** [comment]
Fixed
