### ISSUE TITLE
[BUG] Les hauts fournaux fonctionnent mal pour les gains jobs mineur

### ISSUE THREAD

**Issue by 1therence** [RivrsMc/SeasonSky-Issues#107]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [x] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

therence1

### Pseudo discord

Thérence

### Que s'est-il passé ?

J'ai 3 fours automatiques (3Blast Furnace qui tourne h 24) , eux me rapporte des gains Mineur.
J'ai une salle (220 Blast Furnace) mais eux quand je mets des minerais dedans je gagne rien.

### Étapes à suivre pour reproduire le bug

/

### Qu'aurait-il dû arriver ?

Recevoir mes gains jobs sur les blast furnace dans ma salle . . .

### Date et heure de la production du bug

00h25 +/-

### Serveur

Island-03

### Screen / vidéo

https://youtu.be/V6aB1Cg5mzw

**Comment by Alex96x2** [comment]
J'ai le même souci, il faut a chaque fois que je casse et repose les blast furnace pour que l'xp soit compter, alors que je suis seul sur mon île donc personne ne peut intéragir avec.
