### ISSUE TITLE
[BUG] Reconnexion sur les îles aventures 

### ISSUE THREAD

**Issue by XiiqKii** [RivrsMc/SeasonSky-Issues#11]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

biorn11

### Pseudo discord

xiiqkii

### Que s'est-il passé ?

Bonjour, mon pseudo ig est biorn11 j'ai etais kick du serveur pour AFK normal jt afk sur mais spawner , apres ce kick je spawn directement en mode aventure la ou je suis mort apres que le pack de texture ce remais , j'ai fais des test a chaque deconnection ont ce tp en aventure pour les petit pc cela et embetant sachant comme moi que maintenant on perd le stuff

### Étapes à suivre pour reproduire le bug

Je ne sais pas mais evité que quand on ce reconnecte au serveur ont sois directement dans le monde Aventure

### Qu'aurait-il dû arriver ?

Je n'aurais pas du spawn en monde aventure mais sur mon is et donc pas perdre mon stuff ducoup s'il vous plait puis je avoir un remboursement je suis mort vers 19h44 dans les alentour entre 19h40 et 19H50

### Date et heure de la production du bug

08-07 19:44:00

### Serveur

Aventure

### Screen / vidéo

je n'est pas

### Information supplémentaire

UUID: 215f2f77-6006-4909-9e38-2286a9aed1bf
Position: -378 -13 552 Island
Ping: 1788ms

**Comment by LuluxClient** [comment]
Salut ceci n'est pas vraiment un bug, nous possédons plusieurs spawn et il se peut que tu avais déco sur l'un des serveurs spawn où tu étais dans les mondes aventure, néanmoins je vais te rembourser et @Asherate si tu pourrais add une protection au login si possible de X secondes dans le RivrsEssentials (config)

**Comment by itsme-to** [comment]
L'inventaire est maintenant plus perdu dans le monde aventure. Cela répare donc le problème
