### ISSUE TITLE
[BUG]  PETS XP METIER ne fonctionne pas

### ISSUE THREAD

**Issue by NairodKimbo** [RivrsMc/SeasonSky-Issues#110]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

KimboNairod

### Pseudo discord

Nairodkimbo

### Que s'est-il passé ?

J'ai l'impression que l'on ne reçoit pas l'exp métier bonus que l'on devrait recevoir à l'aide de nos pets.

Oui le pets est dans ma barre active /pets et si je casse une buche avec ou sans le pet je gagne toujours 0.44xp bucheron par exemple.

### Étapes à suivre pour reproduire le bug

Essayer de casser une buche avec un pets ayant le bonus +20% xp metier bucheron,

Recommencer sans le bonus et constater que l'exp reçu est le même

### Qu'aurait-il dû arriver ?

Recevoir de l'exp bonus

### Date et heure de la production du bug

A chaque bûche farmé

### Serveur

island 6

**Comment by NoHere32** [comment]
Le boost ne s'active pas a la seconde de l'activation du pets.
