### ISSUE TITLE
[BUG] Poissons du fleuve secret péchable sur les is

### ISSUE THREAD

**Issue by Alex96x2** [RivrsMc/SeasonSky-Issues#111]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

alex96x2

### Pseudo discord

alex96x2

### Que s'est-il passé ?

On peut pêcher les poissons du fleuve secret sur les is. 
Voici les poissons péché sur mon is pour le moment :
- Homard
- Pieuvre
- Poulpe
- Crabe

### Étapes à suivre pour reproduire le bug

/

### Qu'aurait-il dû arriver ?

Ne pas pouvoir pêcher les poissons du fleuve secret

### Date et heure de la production du bug

14-07 12:03:51

### Serveur

island-01

### Information supplémentaire

UUID: f65b8a07-d770-46b7-8fc1-f24c89ac73ce
Position: -7209 100 8984 SuperiorWorld
Ping: 23ms

**Comment by itsme-to** [comment]
Effectif au prochain merge
