### ISSUE TITLE
[BUG] Houe du Soleil QUETE

### ISSUE THREAD

**Issue by Krashoou** [RivrsMc/SeasonSky-Issues#112]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Krashou

### Pseudo discord

Krashou#0118

### Que s'est-il passé ?

La HOUE du Soleil ne compte pas dans les quetes es ce que c'est normal ou bug ? J'ai demander plusieurs fois sans reponse

### Étapes à suivre pour reproduire le bug

Ecrire ne compte pas pour les quetes si c normal

### Qu'aurait-il dû arriver ?

Valide les quetes

### Date et heure de la production du bug

14/07/22 13H30

### Serveur

SKYSEASON

**Comment by LuluxClient** [comment]
Duplicate #24
