### ISSUE TITLE
[BUG] Boulbi Jaune Or ne multiplie pas les gains

### ISSUE THREAD

**Issue by Amateur2Drapeau** [RivrsMc/SeasonSky-Issues#113]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MaelEnFrance

### Pseudo discord

maelenfrance

### Que s'est-il passé ?

Le pet qui est sensé multiplié les gains de blé d'or ne le fait pas (pareil pour celui qui le fait avec les rubis)

### Étapes à suivre pour reproduire le bug

Gagner des blés d'or avec le pet

### Qu'aurait-il dû arriver ?

Multiplier le gain

### Date et heure de la production du bug

x

### Serveur

x

### Information supplémentaire

UUID: ccf4c91d-a9da-442e-94df-2a03f6b3cb1a
Position: 5429 44 -3618 SuperiorWorld
Ping: 21ms

**Comment by Asherate** [comment]
Hello, les gains sont bien multipliés, le nouveau gain n'est juste pas actualisé dans le message que tu reçois.
Je laisse @ArDiDEx mettre ça à jour si possible

En te souhaitant une bonne journée !

**Comment by ArDiDEx** [comment]
good dés le prochain restart
