### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by LeRoiDesCons** [RivrsMc/SeasonSky-Issues#115]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Stooff_

### Pseudo discord

Le roi des cons !!! (steve_stev

### Que s'est-il passé ?

le cosmetique legendaire du poulpe ne fonctionne plus
on a un vieu poulpe plat mais pas le cosmetique

### Étapes à suivre pour reproduire le bug

jai rien fait de special

### Qu'aurait-il dû arriver ?

avoire mon cosmetique

### Date et heure de la production du bug

hier

### Serveur

seasonsky

**Comment by itsme-to** [comment]
Effectif au prochain merge
