### ISSUE TITLE
[BUG] /pub désynchro

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#116]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

le /pub fait que sur le serveur ou est la personne

### Étapes à suivre pour reproduire le bug

1. acheter /pub
2. voir qu'il y a un bug de désychro

### Qu'aurait-il dû arriver ?

ca devrait etre envoyer comme les messages c'est a dire sur tout les serveur

### Date et heure de la production du bug

14/07/2023 23:21

### Serveur

island 02

**Comment by Asherate** [comment]
Hello je viens de me connecter en jeu pour essayer, j'ai ramener un double compte au spawn02, et depuis mon compte principal au island03, la pub était bien envoyée sur les serveurs, et les joueurs ont bien tous vu mon message, pourrais-tu me dire lors de ton prochain /pub si le soucis est toujours d'actualité ?

**Comment by LupusArctos4** [comment]
NelyLife n'a meme plus acces a la commande mais peut etre demain apres le redem ca sera bon
