### ISSUE TITLE
[BUG] Exp de Forgemage

### ISSUE THREAD

**Issue by Azeertyy420** [RivrsMc/SeasonSky-Issues#117]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Azeertyy

### Pseudo discord

Azeertyy#9672

### Que s'est-il passé ?

lors du craft d'item ex: plastron en cuir si l'item est drop lors du craft (craft avec q) il ne donne pas d'exp de travail

### Étapes à suivre pour reproduire le bug

préparer le craft de n'importe quel objet donnant de l'exp de travail et appuyer q sur l'objet a droite

### Qu'aurait-il dû arriver ?

obtention d'expérience

### Date et heure de la production du bug

18h54 2023-07014

### Serveur

seasonsky

**Comment by NoHere32** [comment]
Sécurité anti duplication xp.
