### ISSUE TITLE
[BUG] La permission "sauter sur les plantations" empeche la bonemeal sur les baies

### ISSUE THREAD

**Issue by Amateur2Drapeau** [RivrsMc/SeasonSky-Issues#118]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MaelEnFrance

### Pseudo discord

maelenfrance

### Que s'est-il passé ?

La permission "sauter sur les plantations" empeche la bonemeal sur les baies

### Étapes à suivre pour reproduire le bug

Ne pas avoir la perm de casser les plantations en sautant sur les cultures et mettre de la bone meal sur les baies sucrés

### Qu'aurait-il dû arriver ?

Séparer les deux perms 

### Date et heure de la production du bug

x

### Serveur

x

### Information supplémentaire

UUID: ccf4c91d-a9da-442e-94df-2a03f6b3cb1a
Position: 5386 38 -3637 SuperiorWorld
Ping: 22ms

**Comment by NoHere32** [comment]
Report fait a omer.

**Comment by ArDiDEx** [comment]
Hey, omer (créateur du plugin de skyblock) a fix le soucis et nous avons mis l'update sur le serveur depuis ~3jours
merci du report
