### ISSUE TITLE
[BUG] Bois compacté d'acajou qui est du jungle

### ISSUE THREAD

**Issue by TokyoSlayers** [RivrsMc/SeasonSky-Issues#119]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

TokyoSlayer

### Pseudo discord

TokyoSlayer

### Que s'est-il passé ?

Buche d'acajou compacter c'est des buche de jungle

### Étapes à suivre pour reproduire le bug

compacter des buche d'acajou

### Qu'aurait-il dû arriver ?

compacter des buche d'acajou pour avoir des buche d'acajou enchante

### Date et heure de la production du bug

15-07 10:04:07

### Serveur

island-01

### Information supplémentaire

UUID: 19f21192-6642-4c84-8213-939eb0e38f8d
Position: 1790 298 3608 SuperiorWorld
Ping: 23ms

**Comment by Tharkuban** [comment]
Bois de jungle = acajou, il y a 0 bug

**Comment by TokyoSlayers** [comment]
non jungle = jungle et acajou = acajou

**Comment by itsme-to** [comment]
Bonjour, ce n'est pas un bug c'est bien la même chose.
https://fr-minecraft.net/item-17_03-buche-d-acajou.html
