### ISSUE TITLE
[BUG] Items passage de rangs non pris en compte

### ISSUE THREAD

**Issue by Slylokss** [RivrsMc/SeasonSky-Issues#12]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Slyyyyy_

### Pseudo discord

Sly

### Que s'est-il passé ?

Les items demandés aux joueurs pour le passage de rang sont par moments non pris en compte alors qu'il sont bien dans l'inventaire du joueur. (vérifié en vocal)
Le problème en question était sur les côtes de porc crues demandés pour le passage au rang 2.

### Étapes à suivre pour reproduire le bug

Faire la commande /rang pour accéder aux rangs, cliquer sur le rang 2 puis, observer que les items ne sont pas pris en compte alors qu'ils sont bien dans l'inventaire du joueur.

### Qu'aurait-il dû arriver ?

Comptabiliser les items demandés pour pouvoir passer au rang supérieur.

### Date et heure de la production du bug

8 Juillet, 18h.

### Serveur

Server île

**Comment by LuluxClient** [comment]
Fixed
