### ISSUE TITLE
[BUG] Crabe (poisson pêché)

### ISSUE THREAD

**Issue by Ninjaduff** [RivrsMc/SeasonSky-Issues#120]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

OpticalD

### Pseudo discord

OpticalD

### Que s'est-il passé ?

J'ai pecher un crabe sur mon ile

### Étapes à suivre pour reproduire le bug

pecher sur son ile

### Qu'aurait-il dû arriver ?

ne pas loot un crabe

### Date et heure de la production du bug

15-07 13:28:29

### Serveur

island-05

### Screen / vidéo

<img width="534" alt="image" src="https://github.com/RivrsMc/SeasonSky-Issues/assets/22250027/d71f8a9d-37e7-4c1d-914c-75bc181f1a22">

### Information supplémentaire

UUID: f3e13c76-29f1-4b3b-a638-80f42aa38fa7
Position: -10827 100 1788 SuperiorWorld
Ping: 135ms

**Comment by itsme-to** [comment]
Effectif au prochain merge
