### ISSUE TITLE
[BUG] L'xp du pet PINGU et FROUSSARD

### ISSUE THREAD

**Issue by Saakrr** [RivrsMc/SeasonSky-Issues#121]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Saakrr

### Pseudo discord

.sakr

### Que s'est-il passé ?

J'ai besoin d'un éclaircissement je dirai car le pet pingu doit donner 20% d'xp fermier au niveau 15.
Or, une patate donnant 0.2 d'xp, 20% représente alors 0.04
On devrait donc gagner 0.24. Nonobstant on ne gagne que 0.22
A priori, le pets froussard ne donne carrément aucun bonus d'xp fermier.
Ce qui me fait donc penser qu'il y a 10% qui semblent ne pas être codés correctement pour nos pauvres amis les familiers de la ferme

### Étapes à suivre pour reproduire le bug

Rien a dire de plus

### Qu'aurait-il dû arriver ?

Rien a dire de plus

### Date et heure de la production du bug

Le 15/07/23

### Serveur

Eternals

**Comment by mrsxnshxne** [comment]
Hey, ça sera fix au prochain redem, si il y a encore des soucis reviens vers nous !
