### ISSUE TITLE
[BUG] Raccommodage ne fonctionnant pas sur la houe du soleil

### ISSUE THREAD

**Issue by Manyy820** [RivrsMc/SeasonSky-Issues#123]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Manyy820

### Pseudo discord

Many

### Que s'est-il passé ?

La houe du soleil perds de la dura et raccommodage ne la répare pas alors qu’avant tout marchait bien

### Étapes à suivre pour reproduire le bug

utiliser la houe du soleil je n’ai rien fait de spécial 

### Qu'aurait-il dû arriver ?

La joue devrait regagner sa dura avec mending et surtout ne ps en perdre

### Date et heure de la production du bug

13/07

### Serveur

je ne m’en souviens ps

**Comment by ArDiDEx** [comment]
hey! je viens d'essayer et la houe ne perd pas de dura de mon côté
