### ISSUE TITLE
[BUG] Pas d'effet sur l'armure de l'aventurier /durabilité

### ISSUE THREAD

**Issue by LLucrece** [RivrsMc/SeasonSky-Issues#124]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Lucrece

### Pseudo discord

Lucrece

### Que s'est-il passé ?

L'armure ne donne pas les effets prévue et la dura est tres faible 

### Étapes à suivre pour reproduire le bug

mettre de l'armure
constater

### Qu'aurait-il dû arriver ?

.

### Date et heure de la production du bug

15/07 à 16h34

### Serveur

serv2

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/135556343/15eeb288-e7c1-4887-8ed2-1a13d3664ab4)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/135556343/7e4c8d30-17b9-424f-9e74-523890d613bf)

**Comment by NoHere32** [comment]
good au prochain transfert.
