### ISSUE TITLE
[BUG] 20% exp en plus pet pingu

### ISSUE THREAD

**Issue by Matthlo** [RivrsMc/SeasonSky-Issues#126]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Devil_Mat

### Pseudo discord

Devil_Mat

### Que s'est-il passé ?

Le pet ice pingu level 15 ne donne pas les 20% supplémentaire d'exp qu'il devrait donner

### Étapes à suivre pour reproduire le bug

prendre le pet, le monter lvl 15 et voir que l'exp ne change pas si on l'a d'actif ou non

### Qu'aurait-il dû arriver ?

20% d'exp du métier femrier en plus

### Date et heure de la production du bug

15-07 18:30:13

### Serveur

island-06

### Information supplémentaire

UUID: dc01ab71-4f55-4b33-b957-739769858646
Position: 7203 99 -1805 SuperiorWorld
Ping: 22ms

**Comment by mrsxnshxne** [comment]
Hello !
Ca sera fix au prochain redem
