### ISSUE TITLE
[BUG] Armure ne donnant pas les effets 

### ISSUE THREAD

**Issue by Djopro10** [RivrsMc/SeasonSky-Issues#128]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Djopro

### Pseudo discord

DjoPro_

### Que s'est-il passé ?

L'armure aventurier full me donne pas les effets de speed 2 et de force 1

### Étapes à suivre pour reproduire le bug

mettre l'armure sur soit, et regarder qu'il ne donne effectivement pas les effets.

### Qu'aurait-il dû arriver ?

me donne les effets

### Date et heure de la production du bug

16-07 00:26:29

### Serveur

island-05

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139657981/1d06693f-f758-4ee0-b1f9-fead114906a9)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139657981/eed0c495-2065-400b-8f82-f7ccfe7947e1)

### Information supplémentaire

UUID: 8d5ec3b1-f71f-4de0-9343-860d79bf4695
Position: 1828 99 8 SuperiorWorld
Ping: 30ms

**Comment by Exidotaku** [comment]
Je confirme, j'ai aussi le full stuff et ca ne me donne rien comme effet
