### ISSUE TITLE
[BUG] Ma pioche ne fonctionne pas

### ISSUE THREAD

**Issue by Guaapeton** [RivrsMc/SeasonSky-Issues#129]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Guaapeton

### Pseudo discord

guapeton_

### Que s'est-il passé ?

j'ai eu une pioche des ombres dans la box du monde aventure et elle est sensé vendre auto mon charbon en x1.5 mais je recup tous les charbons et elle vend rien

### Étapes à suivre pour reproduire le bug

miner et recup le charbon sans qu'il soit vendu

### Qu'aurait-il dû arriver ?

le charbon aurait du etre vendu auto

### Date et heure de la production du bug

16-07 00:31:51

### Serveur

Spawn-01

### Information supplémentaire

UUID: fb78d090-0270-4057-9dbe-d732e85e46de
Position: -428 -20 616 Island
Ping: 26ms

**Comment by itsme-to** [comment]
Bonjour, c'est normal, les items customs ne fonctionne que sur les îles personnelles
