### ISSUE TITLE
[BUG] Barre d'information non visibles pour utilisateurs feather client

### ISSUE THREAD

**Issue by Slylokss** [RivrsMc/SeasonSky-Issues#13]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Slyyyyy_

### Pseudo discord

Sly

### Que s'est-il passé ?

J'ai pu observer en vocal par une capture d'écran qu'un joueur, jouant avec Feather client n'avait pas la barre qui indiquait l'argent, les Scoins, le niveau d'île et le fly. 

### Étapes à suivre pour reproduire le bug

Se connecter au server avec Feather client

### Qu'aurait-il dû arriver ?

Afficher la barre d'infos.

### Date et heure de la production du bug

8 Juillet, 18h.

### Serveur

Tous servers

**Comment by LuluxClient** [comment]
Cela vient du feather client ou de ses mods, le bug vient du joueur et non du serveur.
