### ISSUE TITLE
[BUG] Level 50 mineur 

### ISSUE THREAD

**Issue by VloKee** [RivrsMc/SeasonSky-Issues#130]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

VloKee_

### Pseudo discord

vlokee_

### Que s'est-il passé ?

Bonjour,
Au level 50 mineur il est écrit que nous recevons le pet taupe diamant cependant en faisant /jobs claim nous récupérons un pet terri cyan

### Étapes à suivre pour reproduire le bug

Passer level 50 mineur
Faire /jobs claim

### Qu'aurait-il dû arriver ?

J'aurais dû obtenir le pet taupe diamant 

### Date et heure de la production du bug

16/07/2023 a 2h10

### Serveur

Seasonsky

**Comment by itsme-to** [comment]
Bonjour, ce n'est pas un bug, c'est bien le nom de pet. 
Celui-ci donne bien du diamant comme ressource
