### ISSUE TITLE
[BUG] Les abeilles ne spawnent pas 

### ISSUE THREAD

**Issue by PainPerduPrime** [RivrsMc/SeasonSky-Issues#131]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

PainPerdu_

### Pseudo discord

painduper

### Que s'est-il passé ?

J'ai fait spawn une ruche de façon normale mais aucune abeilles n'a spawn dedans ni même ne sort de la ruche.

### Étapes à suivre pour reproduire le bug

Faire spawn une ruche

### Qu'aurait-il dû arriver ?

Faire spawn des abeilles

### Date et heure de la production du bug

Aujourd'hui

### Serveur

seasonsky

### Screen / vidéo

![2023-07-16_14 37 19](https://github.com/RivrsMc/SeasonSky-Issues/assets/139691077/ba1f0a94-ce22-43f2-a376-d676e4c90490)

**Comment by Asherate** [comment]
Hello c'est normal, le spawn des abeilles est désactivé pour des raisons de performances.
