### ISSUE TITLE
[BUG] Porblème avec le nombre de coffre de vente

### ISSUE THREAD

**Issue by Ibigau0** [RivrsMc/SeasonSky-Issues#132]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Ibigau_

### Pseudo discord

crocs_mcdo

### Que s'est-il passé ?

Je suis batisseur, je devrais avoir au moins 15coffres de ventes, mais j'en dispose actuellement de 9.

### Étapes à suivre pour reproduire le bug

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de la production du bug

.

### Serveur

.

**Comment by NoHere32** [comment]
Après des test toutes les limite sont correct tu dois avoir des coffre de vente a d'autres endroit.
