### ISSUE TITLE
[BUG] Hache royale + Coffre

### ISSUE THREAD

**Issue by Naalyah** [RivrsMc/SeasonSky-Issues#133]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nalyah

### Pseudo discord

Nalyah

### Que s'est-il passé ?

Les coffres cassés avec la hache royale ne drop rien.. 
Perte de la totalité du coffre

### Étapes à suivre pour reproduire le bug

Casser un coffre avec une hache royale

### Qu'aurait-il dû arriver ?

Drop des items du coffre dans l'inventaire ou au sol

### Date et heure de la production du bug

20h50

### Serveur

Eldoria

**Comment by ArDiDEx** [comment]
Hey
ça devrait être patch depuis le redémarrage de 5h du matin
bon jeu
