### ISSUE TITLE
[BUG] aucunes applications possible de livres enchantés sur les Bottes de l'aventurier

### ISSUE THREAD

**Issue by Diable664** [RivrsMc/SeasonSky-Issues#134]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Diable64

### Pseudo discord

Diable64

### Que s'est-il passé ?

j'ai voulu appliquer des enchantements sur les bottes de l'aventurier (applicable sur tout type de bottes) cependant nous pouvons pas modifié cet item alors qu'il est marqué le contraire. 

![2023-07-16_22 16 01](https://github.com/RivrsMc/SeasonSky-Issues/assets/139715488/7fd8f995-c444-4338-a1a3-26d2656763d6)

### Étapes à suivre pour reproduire le bug

![2023-07-16_21 20 23](https://github.com/RivrsMc/SeasonSky-Issues/assets/139715488/df6bf732-c3b4-453f-891d-408df383a945)

### Qu'aurait-il dû arriver ?

L'obtention des bottes de l'aventurier avec comme enchantements
protection 4 solidité 4 : enchantements de base sur les bottes  
agilité aquatique 3 et solidité 3 : enchantements du livre

### Date et heure de la production du bug

22:00.00

### Serveur

SeasonSky

### Screen / vidéo

![2023-07-16_21 20 23](https://github.com/RivrsMc/SeasonSky-Issues/assets/139715488/95637c9b-2d5c-4490-82c4-bc8b046388ba)

### Information supplémentaire

![2023-07-16_22 11 10](https://github.com/RivrsMc/SeasonSky-Issues/assets/139715488/eda941b9-034d-4bec-a7c6-5bf79a181d74)

**Comment by NoHere32** [comment]
good au prochain transfert
