### ISSUE TITLE
[BUG] mission difficile de pêche 

### ISSUE THREAD

**Issue by ReblochonIGP** [RivrsMc/SeasonSky-Issues#136]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

ReblochonIGP

### Pseudo discord

Barigo69

### Que s'est-il passé ?

bonjour, j’ai repérer un bug sur l’es mission difficile de pêche pour les étiquettes et selles. Quand on pêche des étiquettes et des selles. Cela ne se comptabilise pas dans la mission et celle ci reste à 0 .

### Étapes à suivre pour reproduire le bug

avoir une mission difficile de pêche où il faut pêcher sois des étiquette, sois des selles et pêcher ceux-ci. La mission reste à 0 .

### Qu'aurait-il dû arriver ?

si l’on pêche l’un d’entre eux, la mission doit les comptabiliser 

### Date et heure de la production du bug

Dimanche 16 juillet a 15h

### Serveur

Seasonsky

**Comment by itsme-to** [comment]
Bonrjour @ReblochonIGP, tu avais une canne à pèche spécial ?

**Comment by ReblochonIGP** [comment]
J’ai la canne à pêche royale, mais avec n’importe quelle canne à pêche cela ne marche pas
