### ISSUE TITLE
[BUG] Incohérence dans les poissons nécessaires au passage de rang Ingénieur.

### ISSUE THREAD

**Issue by uvsq22107694** [RivrsMc/SeasonSky-Issues#137]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

W4nKizZz

### Pseudo discord

wankizzz

### Que s'est-il passé ?

Il y a un deux problèmes concernant les poissons nécessaires au passage au rang d'ingénieur. 
1. Le 3 eme poissons se nomme "Saumon Royal" mais possède l'image du "Poisson chat"
2. en passant la souris sur l'enclume en haut il est dis que les poissons pour passer le grade sont : 32 Poissons perroquet, 32 Truite arc en ciel, 32 Hippocampe. Alors que sur les image on peut voir 16 poissons perroquet, 32 poissons Lion et 32 Saumon royal (ou poisson chat)

### Étapes à suivre pour reproduire le bug

il faut etre batisseur et faire /rang puis regarder les rang ingénieur

### Qu'aurait-il dû arriver ?

chaque poisson bien décris de façon cohérente.

### Date et heure de la production du bug

17/07/23

### Serveur

Seasonsky

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/91540224/13555937-84c8-466f-9578-a53b1a3e0143)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/91540224/76f1465e-58d7-4243-bc06-3dccf86c37af)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/91540224/0daf3d12-85ef-4a6b-ae7c-e3568fefd078)

**Comment by uvsq22107694** [comment]
Suplément les screens des skins respectifs des poissons
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/91540224/3d2e4b37-1fab-463a-af1e-5912578a08c9)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/91540224/7e60f848-2e47-4da5-a670-13374060fb8d)

**Comment by LuluxClient** [comment]
fixed
