### ISSUE TITLE
[BUG] Spawn dans le /aventure lors du join sur le serveur

### ISSUE THREAD

**Issue by Gaetan666** [RivrsMc/SeasonSky-Issues#138]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

TicTacMenthe200

### Pseudo discord

TicTacMenthe200

### Que s'est-il passé ?

Lorsqu'on join le serveur on apparait dans le monde aventure 

### Étapes à suivre pour reproduire le bug

Le bug est random en apparence, parfois lors de la connection, on spawn dans le monde aventurier

### Qu'aurait-il dû arriver ?

Spawn au spawn ou sur l'île

### Date et heure de la production du bug

20h30 17/07

### Serveur

monde aventure

**Comment by ArDiDEx** [comment]
Hey, ça devrait être patch au prochain redémarrage
merci du report
