### ISSUE TITLE
[BUG] perte d'objet durant la tp

### ISSUE THREAD

**Issue by Shymul** [RivrsMc/SeasonSky-Issues#139]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Shymul

### Pseudo discord

Shymul#1915

### Que s'est-il passé ?

je me suis aperçue que au moment de me tp dans un autre serveur exemple spawn si entre le moment de validé la tp et la tp ex les 2 sec avant la tp au spawn je venais a prendre un item dans mon inventaire avec le  clic gauche pour par exemple le ranger et ne le reposais pas avant la téléportation  l'item étais clear et n'étais pas droper au sol a l'endroit de ma téléportation se qui peut bêtement détruire des item précieux
 

### Étapes à suivre pour reproduire le bug

choissiser de vous téléporter au spawn au a un monde aventure sans être dans le serveur de celui si . entre le moment devalidé la téléportation et la téléportation prenez un item de votre inventair comme si vous vouliez le déplacer sans l'y reposé et attendez d'être téléporté

### Qu'aurait-il dû arriver ?

l'item aurait du se reposé a l'emplacement de l'inventaire ou il a été pris ou être dropez au sol

### Date et heure de la production du bug

18/07 environ 3H30 

### Serveur

seasonsky

### Screen / vidéo

le fichier étant trop lourd je ne peux pas l'envoyer

### Information supplémentaire

aucune

**Comment by ArDiDEx** [comment]
ça devrait être fix dés le prochain restart (les items dropperont au sol)
merci du report
