### ISSUE TITLE
[BUG]  

### ISSUE THREAD

**Issue by Dragen911** [RivrsMc/SeasonSky-Issues#14]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Heimdll

### Pseudo discord

dragen091

### Que s'est-il passé ?

Les eponges ne donne pas d'is value alors qu'elle devrait donné 25

### Étapes à suivre pour reproduire le bug

deposer des eponges dans le cristal

### Qu'aurait-il dû arriver ?

recevoir de l'xp pour l'ile 

### Date et heure de la production du bug

08-07 22:00:39

### Serveur

island-01

### Information supplémentaire

UUID: 30b58244-30b6-4d62-bc24-3d72049e5164
Position: 3587 100 1819 SuperiorWorld
Ping: 25ms

**Comment by LuluxClient** [comment]
Salut je n'ai pas ce soucis là, pourrais-tu tenter de retirer tes éponges et de les remettre sur le crystal d'île et me dire si cela fonctionne @Dragen911

**Comment by Dragen911** [comment]
Je vient de tester ca a fonctionner surement un bug  du a l'afflu de connection hier ^^ desoler du derangement
