### ISSUE TITLE
[BUG] Affichage du menu shop décalé

### ISSUE THREAD

**Issue by TeFliX12** [RivrsMc/SeasonSky-Issues#140]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

TeFliX12

### Pseudo discord

TeFliX12

### Que s'est-il passé ?

Quand j'ai voulu acheté plus d'un stack de terre, l'affichage de mon inventaire est remonté.

### Étapes à suivre pour reproduire le bug

1- Faire /shop
2- Ouvrir le menu blocs
3- Sélectionner la terre
4- Choisir d'acheter plus de 1 stack

### Qu'aurait-il dû arriver ?

L'affichage de l'inventaire devrait être normal 

### Date et heure de la production du bug

18/07/2023 à 8h30

### Serveur

Eldoria

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139850595/30b317a7-87a9-4fa0-aef8-5cc4717a820d)

**Comment by itsme-to** [comment]
Effectif au prochain merge
