### ISSUE TITLE
[BUG] Shop cuivre non Waxed

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#141]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

l'ajout des différents tiers d'oxydation c'est bien dans le shop je trouve ca cool mais non waxed ca ne sert à rien vu qu'ils vont s'oxydé avec le temps et par la même occasion si vous les mettez en waxed mettaient aussi le bloc non oxydé parce que c'est utile

### Étapes à suivre pour reproduire le bug

1. ouvrir le shop
2. aller dans la catégorie bloc
3. aller a la dernière page

### Qu'aurait-il dû arriver ?

les blocs devrait etre des blocs waxed

### Date et heure de la production du bug

18/07/2023 9:22

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/18c4e3d0-1fd7-41a0-8301-84270c3b0b30)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/c9ed6559-0f7a-48d1-b136-1120d82513a4)

**Comment by LupusArctos4** [comment]
d'ailleurs les blocs de copper non modifier donc le "block_of_copper" ne s'oxyde pas et il n'est d'ailleurs pas présent dans le shop en modifier

**Comment by mrsxnshxne** [comment]
Hello, nous avons désactivé l'oxydation et le waxing des blocs de copper donc aucun soucis avec cela !
Les blocs de copper Exposed, Weathered et Oxidized arrivent au prochain redémarrage, je ferme l'issue
