### ISSUE TITLE
[BUG] XP et Argent métier pécheur

### ISSUE THREAD

**Issue by Joordaan420** [RivrsMc/SeasonSky-Issues#143]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Joordaan420

### Pseudo discord

Jordan420

### Que s'est-il passé ?

Pour le métier de pêcher on peux cuire le poisson pour gagner de l'xp de et l'argent mais dans le fumoir l'xp et l'argent est pas donner

### Étapes à suivre pour reproduire le bug

Juste mettre le fumoir et cuire du poison 

### Qu'aurait-il dû arriver ?

avoir de l'xp et argent 

### Date et heure de la production du bug

17/07/2023

### Serveur

island_01

**Comment by entropy-hub** [comment]
à tester dans la nouvelle version RivrsJobs

**Comment by NoHere32** [comment]
Good dans la journée
