### ISSUE TITLE
[BUG] Impossible de forger un livre Meding et curse of vanishing sur des items modde

### ISSUE THREAD

**Issue by JulesBecquet** [RivrsMc/SeasonSky-Issues#144]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

UpsilonJOESTAR

### Pseudo discord

Juulo

### Que s'est-il passé ?

Il est impossible de forger un livre Meding et curse of vanishing sur des items modde ou rename par le serveur.
![2023-07-18_13 04 05](https://github.com/RivrsMc/SeasonSky-Issues/assets/97103445/c3d7842d-82aa-484c-9ed9-f64d57d6abb7)

### Étapes à suivre pour reproduire le bug

utiliser une enclume

### Qu'aurait-il dû arriver ?

mending aurait du se fusionner avec l'armur 

### Date et heure de la production du bug

18-07 13:05:06

### Serveur

island-04

### Screen / vidéo

![2023-07-18_13 26 41](https://github.com/RivrsMc/SeasonSky-Issues/assets/97103445/668a43b3-8251-4313-aca5-c98f645dc18b)
![2023-07-18_13 26 58](https://github.com/RivrsMc/SeasonSky-Issues/assets/97103445/c450768f-3175-477d-94ae-c206fa7abc53)

### Information supplémentaire

UUID: 63448ad5-c71d-41ad-a236-18b6ce043ee3
Position: -16192 103 -12597 SuperiorWorld
Ping: 12ms

**Comment by NoHere32** [comment]
Hello, cela était un soucis avec l'items.
