### ISSUE TITLE
Pioche des ombres 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#146]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0isan 

### Pseudo discord

Nami_san

### Que s'est-il passé ?

Pioche des ombres :
La pioche des ombres elle est censé vendre automatiquement le charbon lors du minage hors elle le fait pas du tout

Il me semble que je l'ai déjà report mais pas pour la même chose. 

### Étapes à suivre pour reproduire le bug

Miner de charbon avec 

### Qu'aurait-il dû arriver ?

Vendre automatiquement le charbon de base 

### Date et heure de la production du bug

18 juillet, 17h06

### Serveur

Global

**Comment by mrsxnshxne** [comment]
Aucun soucis de mon côté après test, ce serait possible d'avoir éventuellement plus d'info ?

**Comment by NoHere32** [comment]
Hello, les effet des outils ne fonctionne que sur ta propre île.
