### ISSUE TITLE
[BUG] Eclozr niveau max bug

### ISSUE THREAD

**Issue by stephane2000** [RivrsMc/SeasonSky-Issues#147]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

stephane2000

### Pseudo discord

stephane2000

### Que s'est-il passé ?

On peut augmenter le niveau de l'eclozr au dela du niveau 5
Il faut bloquer MAX lvl 5

### Étapes à suivre pour reproduire le bug

Mettre des engrenages une fois niveau 5 et PAF il passe niveau 6 

### Qu'aurait-il dû arriver ?

Rester niveau 5 max

### Date et heure de la production du bug

18 Juillet à 18h 

### Serveur

Island

**Comment by LuluxClient** [comment]
Fixed au redem
