### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by kka1as** [RivrsMc/SeasonSky-Issues#148]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

kkalas

### Pseudo discord

kkalas

### Que s'est-il passé ?

L armure de l aventurier ne donne pas le bonus indiqué de l armure complète a savoir speed 2 force 1

### Étapes à suivre pour reproduire le bug

t

### Qu'aurait-il dû arriver ?

t

### Date et heure de la production du bug

t

### Serveur

t

### Screen / vidéo

t

### Information supplémentaire

t

**Comment by NoHere32** [comment]
good au prochain transfert
