### ISSUE TITLE
[BUG] Boulbi Rose mal config

### ISSUE THREAD

**Issue by Amateur2Drapeau** [RivrsMc/SeasonSky-Issues#15]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MaelEnFrance

### Pseudo discord

maelenfrance

### Que s'est-il passé ?

Le pet Boulbi Rose a un multiplicateur de vente de tranche de melon alors qu'il n'en vend pas

### Étapes à suivre pour reproduire le bug

x

### Qu'aurait-il dû arriver ?

x

### Date et heure de la production du bug

x

### Serveur

x

### Screen / vidéo

x

### Information supplémentaire

x

**Comment by LuluxClient** [comment]
Fixed
