### ISSUE TITLE
[BUG] Name_tag non compté dans les quêtes

### ISSUE THREAD

**Issue by Warnel0** [RivrsMc/SeasonSky-Issues#150]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Warnell

### Pseudo discord

warnel0

### Que s'est-il passé ?

10 étiquette pécher, le compteur de ma seul quete pecher des etiquette dans mon inventaire ne bouge pas

### Étapes à suivre pour reproduire le bug

10 étiquette pécher, le compteur de ma seul quete pecher des etiquette dans mon inventaire ne bouge pas

### Qu'aurait-il dû arriver ?

10 étiquette pécher, le compteur de ma seul quete pecher des etiquette dans mon inventaire ne bouge pas

### Date et heure de la production du bug

18-07 22:56:26

### Serveur

island-05

### Information supplémentaire

UUID: 6966561c-144c-40a6-b117-95d6af9b10ea
Position: -5436 204 1795 SuperiorWorld
Ping: 17ms

**Comment by P1roxx** [comment]
Il se passe la meme chose avec les nénuphard

**Comment by LuluxClient** [comment]
Quelle quête c'est exactement ? Tu avais quoi comme canne à pêche

**Comment by Warnel0** [comment]
Toutes les quetes autres que morue saumon pufferfish et peche, avec une canne royal
________________________________

**Comment by LuluxClient** [comment]
Ils ont été retiré des missions temporairement le temps d'un fix, ce soucis ne devrait pas revenir une fois le fix sortie.
