### ISSUE TITLE
[BUG] Pets sans effet multiplicateur

### ISSUE THREAD

**Issue by Pireus91** [RivrsMc/SeasonSky-Issues#151]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Pireus

### Pseudo discord

Pireus

### Que s'est-il passé ?

Bonjour,
J'ai obtenue un pet épique avec le lv25 du métier aventurier et une fois ouvert j'ai eu un pet "Woody
![Capture d’écran 2023-07-18 081950](https://github.com/RivrsMc/SeasonSky-Issues/assets/139948498/499eacaa-1a9b-49d2-ba9d-00d89d780cbc)
 bordeaux" qui n'as aucun effet "multiplicateur d'efficacité" d'afficher.

### Étapes à suivre pour reproduire le bug

aucune idée sur la reproduction du bug (c'était le 1er œuf épique obtenue et ouvert)

### Qu'aurait-il dû arriver ?

un effet multiplicateur d'efficacité aurais du être afficher dans la description du pet

### Date et heure de la production du bug

18/07/2023

### Serveur

island-03

### Screen / vidéo

![Capture d’écran 2023-07-18 081950](https://github.com/RivrsMc/SeasonSky-Issues/assets/139948498/47e2e049-bcdd-4bac-b8b6-6d8d63daf487)

**Comment by NoHere32** [comment]
Good au prochain transfert
