### ISSUE TITLE
Pet : Philo Rouge 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#153]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0isan 

### Pseudo discord

Nami_san

### Que s'est-il passé ?

Lors du Lvl 50 Alchimiste nous somme censé recevoir un pets : Philo Rouge œil fermenté

Hors de la réception de celui ci petit erreur c'est un Philo rouge uniquement d'œil d'araignée simple. 

### Étapes à suivre pour reproduire le bug

Monter le Lvl Alchimiste /jobs claim Alchimiste posséder Philo rouge

Ensuite regarder la description dans le jobs claim et celui de pets 

### Qu'aurait-il dû arriver ?

Aucune idée mais j'imagine que du coup c'est Philo rouge pour les œils fermenté pour l'alchimiste.

### Date et heure de la production du bug

19 juillet / 15h42

### Serveur

Global 

### Screen / vidéo

![Screenshot_20230719_153154_com discord](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/f74d1267-a4c5-4137-b699-7273329ed148)
![Screenshot_20230719_153129](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/3c6142d3-4554-477a-b649-3013f643d058)

**Comment by NoHere32** [comment]
Hello, ceci est juste une erreur de desc menu palier jobs alchimiste sera good au prochain transfert
