### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by stephane2000** [RivrsMc/SeasonSky-Issues#154]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

stephane2000

### Pseudo discord

stephane2000

### Que s'est-il passé ?

Mettre le pet "Sapinette" dans un Eclozr rend l'eclozr inutilisable

### Étapes à suivre pour reproduire le bug

Mettre le pet "Sapinette" dans un Eclozr

### Qu'aurait-il dû arriver ?

L'Eclozr aurait du s'ouvrir

### Date et heure de la production du bug

19/07 a 22h

### Serveur

Partout

**Comment by NoHere32** [comment]
good au prochain transfert
