### ISSUE TITLE
[BUG] Mangrove Woody  Eclozr

### ISSUE THREAD

**Issue by Zwartkat** [RivrsMc/SeasonSky-Issues#155]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Zwartkat 

### Pseudo discord

Zwartkat 

### Que s'est-il passé ?

Le pet mangrove_woody fait bug l'Eclozr 

### Étapes à suivre pour reproduire le bug

Mettre le pet mangrove_woody dans un eclozr

### Qu'aurait-il dû arriver ?

Ouverture de l'interface lors un clic sur l'eclozr

### Date et heure de la production du bug

1:40 20/07

### Serveur

Ile

**Comment by NoHere32** [comment]
good au prochain transfert
