### ISSUE TITLE
[BUG] Boulbi Vert - Health Boost 2

### ISSUE THREAD

**Issue by Founny** [RivrsMc/SeasonSky-Issues#156]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Isaac______

### Pseudo discord

isaac____

### Que s'est-il passé ?

J'ai équipé le pet Boulbi Vert (lvl 15) qui doit donner l'effet bonus de vie II (+4 coeurs).
Je n'ai aucun cœur en plus et lorsque je l'équipe je prends 2,5 coeurs de dégats (qui se régénèrent normalement)

### Étapes à suivre pour reproduire le bug

1. Équiper Boulbi Vert au niveau 15

### Qu'aurait-il dû arriver ?

Je devrais avoir 4 coeurs en plus

### Date et heure de la production du bug

04:22 | 20/07

### Serveur

island-02

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/39631165/59e6d7d8-0f91-43e9-a71d-1e5dc73a94eb)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/39631165/1a1d473a-254e-4d23-b440-fa2ca8cb0240)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/39631165/ef545858-347e-44c9-bb6d-27b2600b05cc)

**Comment by Founny** [comment]
à noter: lorsque le pet est équipé et que je change de monde j'ai bien les cœurs en plus qui disparaissent peu de temps après
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/39631165/e0bf2dd4-a82f-4a06-ae6a-9f4c2866c0d8)

**Comment by Asherate** [comment]
Hello ! Ce sera fix au prochain redémarrage :)
