### ISSUE TITLE
[BUG] Xp jobs farmer avec mouton

### ISSUE THREAD

**Issue by Bisemuth** [RivrsMc/SeasonSky-Issues#157]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Bisemuth

### Pseudo discord

Bisemuth

### Que s'est-il passé ?

Lorsque je tond un mouton stack en 4 je ne récupère que l'xp d'un seul mouton tondu cela est embetant d'acheter des spawner a mouton pour au final se faire avoir comme cela

### Étapes à suivre pour reproduire le bug

clique droit avec cisaille sur un mouton stack et regarder le nombre d'xp gagné

### Qu'aurait-il dû arriver ?

on devrais avoir le nombre d'xp gagné pour un mouton multiplier par le nombre de mouton alors que non

### Date et heure de la production du bug

20/07/2023 14h

### Serveur

island 3

### Screen / vidéo

![2023-07-20_14 04 29](https://github.com/RivrsMc/SeasonSky-Issues/assets/140075026/56e55f3d-2333-42c3-af5f-ffac26f21cb9)

### Information supplémentaire

sur le screen j'ai un pets qui donne 20% supplémentaire sur le job farmer

**Comment by NoHere32** [comment]
good au prochain transfert
