### ISSUE TITLE
[BUG] Pas d'effet luck en portant le casque du pécheur

### ISSUE THREAD

**Issue by LLucrece** [RivrsMc/SeasonSky-Issues#158]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Lucrece

### Pseudo discord

Lucrece

### Que s'est-il passé ?

Pas d'effet luck en portant le casque du pécheur

### Étapes à suivre pour reproduire le bug

Pas d'effet luck en portant le casque du pécheur

### Qu'aurait-il dû arriver ?

Pas d'effet luck en portant le casque du pécheur

### Date et heure de la production du bug

20/07 à 15h17

### Serveur

serv2

**Comment by Jspppppp** [comment]
Hello, si y'a faut que tu mettes le chapeau dans ta barre en dessous de l'xp vanillah après tu passes ton curseur dessus et clique droit pour l'équiper et tu auras

**Comment by LLucrece** [comment]
c'etait pour nély ^^, merci je lui dirait
