### ISSUE TITLE
[BUG]  Animation Dragonnet

### ISSUE THREAD

**Issue by Xin0u** [RivrsMc/SeasonSky-Issues#159]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Xinou

### Pseudo discord

Xinou

### Que s'est-il passé ?

Aucune animation dans l'eclozr de la par du pet Dragonnet
 le autres pets ont une animation  tandis que le pet Dragonnet ne l'a pas

### Étapes à suivre pour reproduire le bug

1 Obtenir  le pet dragonnet 
2 le placer dans l'éclozr
3 regarder le pet 

### Qu'aurait-il dû arriver ?

le pet doit être animé
tandis que le pet doit être animé 

### Date et heure de la production du bug

tous le temps

### Serveur

toute les islands

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139914502/e6a1d34b-c2aa-4a8b-9f9b-d6e2188f0fd5)

**Comment by LuluxClient** [comment]
Un petit soucis au niveau de son animation idle, un fix est en cours
