### ISSUE TITLE
[BUG] XP du métier pêcheur anormalement élevé

### ISSUE THREAD

**Issue by Amateur2Drapeau** [RivrsMc/SeasonSky-Issues#16]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MaelEnFrance

### Pseudo discord

maelenfrance

### Que s'est-il passé ?

XP du métier pêcheur anormalement élevé

### Étapes à suivre pour reproduire le bug

Pêcher en dehors l'is

### Qu'aurait-il dû arriver ?

gagner moins

### Date et heure de la production du bug

08/07/2023

### Serveur

Spawn

**Comment by Acterax** [comment]
On ne peut plus exp le pecheur au spawn
