### ISSUE TITLE
[BUG]  Full set aventurier bug

### ISSUE THREAD

**Issue by Xin0u** [RivrsMc/SeasonSky-Issues#160]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Xinou

### Pseudo discord

Xinou

### Que s'est-il passé ?

j'ai équipé mon set aventurier mais je n'ai pas reçu l'effet (force 1/speed 2)

### Étapes à suivre pour reproduire le bug

1 équipé le set
2 regarder les effets 

### Qu'aurait-il dû arriver ?

je dois recevoir l'effet (force 1/speed 2)

### Date et heure de la production du bug

tous le temps

### Serveur

toute les serveurs

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139914502/243a456a-c29c-4ba7-a6df-699216a49927)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139914502/bfc1a575-1491-4667-9be2-b4e58899f8da)

**Comment by NoHere32** [comment]
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/123643370/64aebae6-cd96-4bc4-8b5a-ecfe653c6f6d)
