### ISSUE TITLE
Report : ticket >> Armure explorateur 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#161]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0isan 

### Pseudo discord

Nami_san

### Que s'est-il passé ?

Armure explorateur ne possède pas les effets suivant
> Speed 1
> haste 1

### Étapes à suivre pour reproduire le bug

Posséder l'armure en question, tester les effets 

### Qu'aurait-il dû arriver ?

Faire fonctionner les effets proposer sur l'armure explorateur 

### Date et heure de la production du bug

20/07 20h44

### Serveur

Global

### Screen / vidéo

![Screenshot_20230720_203941](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/5f1d33e4-5ac1-4d33-a491-8069c481087c)

**Comment by Nam0i** [comment]
![Screenshot_20230720_204543](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/1a8e3d96-5475-4071-8b6b-38a2b3990a88)
Je me suis tromper de screnn

**Comment by itsme-to** [comment]
Déjà en issue en cours desssus #128
