### ISSUE TITLE
Problème /generateur

### ISSUE THREAD

**Issue by TheLouuKa** [RivrsMc/SeasonSky-Issues#162]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

LouuKa_

### Pseudo discord

.-.louka

### Que s'est-il passé ?

J'ai constaté avec un autre joueur qui a le même problème, quand on monte le mineur lvl 20 on doit débloqué le dernier palier dans /generateur, cependant sa ne veux pas s'actualisé même après plusieurs déco / reco 

### Étapes à suivre pour reproduire le bug

lvl 20 mineur  > /generateur

### Qu'aurait-il dû arriver ?

Débloquer le dernier palier "bastion"

### Date et heure de la production du bug

20-07 20:38:47

### Serveur

island-03

### Screen / vidéo

![2023-07-20_20 44 34](https://github.com/RivrsMc/SeasonSky-Issues/assets/140109392/9fe31577-9c72-47a8-a98e-0d366699d074)
![2023-07-20_20 44 44](https://github.com/RivrsMc/SeasonSky-Issues/assets/140109392/aec11b41-3546-45d0-864b-25e5595341ef)

### Information supplémentaire

UUID: 3717550f-f4f3-4597-bee9-6176808b32be
Position: -12626 103 -9041 SuperiorWorld
Ping: 34ms

**Comment by LuluxClient** [comment]
Fixed, c'est le niveau 25 !

**Comment by TheLouuKa** [comment]
Sa marche !
