### ISSUE TITLE
[BUG] Flèches qui tombent à l'infini en dehors des limites

### ISSUE THREAD

**Issue by Garmyuc** [RivrsMc/SeasonSky-Issues#163]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Garmyuc

### Pseudo discord

Garmyuc

### Que s'est-il passé ?

J'ai tiré plusieurs flèches dans le ciel (pour chasser des phantoms) et j'ai remarqué que, depuis, il y en a qui tombent du ciel (en dehors de la zone accessible) sans arrêt. Si vous allez voir sur mon île, c'est derrière les arbres.

### Étapes à suivre pour reproduire le bug

1. Tirer des flèches normales dans le ciel avec un arc basique (peut-être en faisant en sorte de les faire retomber dans le vide ou en dehors des limites).
2. Regarder dans la direction dans laquelle on a lancé les flèches (ça fait des trainées qui descendent du ciel).

### Qu'aurait-il dû arriver ?

Je pense que les flèches aurait dues tomber et disparaître.

### Date et heure de la production du bug

17 ou 18 juillet, le soir

### Serveur

SeasonSky

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/140108371/6b3168cb-2750-4a4f-b611-692a372caee8)

**Comment by itsme-to** [comment]
Les flêches sont toujousr présente, coté Nord - Ouest

**Comment by LuluxClient** [comment]
Fixed, désormais les flèches vont despawn après 300 ticks.
