### ISSUE TITLE
Report ticket > Armure aventuriers 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#164]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0isan 

### Pseudo discord

Nami_san

### Que s'est-il passé ?

Armure aventuriers ne possède pas les effets suivant
> Speed 2
> Force 1

### Étapes à suivre pour reproduire le bug

Posséder l'armure en question, tester les effets 

### Qu'aurait-il dû arriver ?

Faire fonctionner les effets proposer sur l'armure aventuriers 

### Date et heure de la production du bug

20/07 20h44

### Serveur

Global

### Screen / vidéo

![Screenshot_20230720_203941](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/5f1d33e4-5ac1-4d33-a491-8069c481087c)
![Screenshot_20230720_205042](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/cd7808c6-77de-4044-aa66-1c9453237ca2)

**Comment by Pireus91** [comment]
il y as déjà un ticket ouvert sur ce sujet #160

**Comment by itsme-to** [comment]
Je ferme l'issue comme elle existe déjà
