### ISSUE TITLE
[BUG] Tournoi de Farm Carotte non comptabilisé

### ISSUE THREAD

**Issue by Smasheur** [RivrsMc/SeasonSky-Issues#165]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Smasheur

### Pseudo discord

CLD

### Que s'est-il passé ?

le concours de récolte de carottes ne fonctionne pas 

### Étapes à suivre pour reproduire le bug

le score n'augmente pas

### Qu'aurait-il dû arriver ?

mon score aurai du augmenter apres la recolte de carottes

### Date et heure de la production du bug

20-07 22:09:47

### Serveur

island-06

### Information supplémentaire

UUID: 2da9cd24-2a58-4bd4-956e-98e336eb6ae9
Position: 19821 90 -9021 SuperiorWorld
Ping: 21ms

**Comment by Jspppppp** [comment]
Ça marche impect island 3

**Comment by itsme-to** [comment]
Bonjour, est ce que tu utilisais un item en particulier pour casser les carottes ?

**Comment by Smasheur** [comment]
Bonjour j’ai essayé de plusieurs manières : à la main, avec une houe mais ça n’a rien fait je n’ai cumulé aucun point.

Envoyé de mon iPhone

Le 21 juil. 2023 à 10:59, Théo Dufrene ***@***.***> a écrit :

﻿

Bonjour, est ce que tu utilisais un item en particulier pour casser les carottes ?
