### ISSUE TITLE
[BUG] Pioche Royal récupération d'item

### ISSUE THREAD

**Issue by Joordaan420** [RivrsMc/SeasonSky-Issues#167]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Joordaan420

### Pseudo discord

Jordan420

### Que s'est-il passé ?

Quand on casse un block qui contient des objets t'elle que ( four , dispenser , dropper , hopper ) 
cela nous redonne l'objet en question mais pas se qu'il est a l'intérieur 

### Étapes à suivre pour reproduire le bug

1. Placer un four , dispenser , dropper , hopper
2. Mettre des objets dedans 
3. Casser avec la pioche royal

### Qu'aurait-il dû arriver ?

Voir pour redonner les items dans le contenant 

### Date et heure de la production du bug

9h

### Serveur

island-01

**Comment by LuluxClient** [comment]
Fixed !
