### ISSUE TITLE
[BUG] Perte d'XP - Ferme de Jean

### ISSUE THREAD

**Issue by Tweentyy** [RivrsMc/SeasonSky-Issues#168]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Tweenty_

### Pseudo discord

tweenty_

### Que s'est-il passé ?

J'ai perdu mon XP en mourant dans la Ferme de Jean

### Étapes à suivre pour reproduire le bug

Avoir des niveaux et mourir dans la ferme

### Qu'aurait-il dû arriver ?

Ne pas perdre mes niveaux d'xp, comme dans les autres zones

### Date et heure de la production du bug

21-07 12:57:27

### Serveur

island-01

### Information supplémentaire

UUID: 277fe165-4dbe-48c3-93bb-229088819d90
Position: -16199 -12 16246 SuperiorWorld
Ping: 18ms

**Comment by Tweentyy** [comment]
https://youtu.be/Ct9-lIfGWgo

**Comment by LuluxClient** [comment]
Uniquement les légendes ne perdent pas leurs XP, merci de faire une suggestion pour ceci.
