### ISSUE TITLE
Report : Houe Laboureur 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#169]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0isan 

### Pseudo discord

Nami_san

### Que s'est-il passé ?

Houe du Laboureur : une fois atteint la durabilité 0 ou en dessous de 3000 nous devons la réparer hors lors du /forgeron ceci ne fonctionne pas sur la houe du Laboureur 

### Étapes à suivre pour reproduire le bug

Utiliser la houe pour pouvoir la réparer avec le /forgeron

### Qu'aurait-il dû arriver ?

Pouvoir la réparer avec le forgeron 

### Date et heure de la production du bug

13h13 21/07

### Serveur

Global

**Comment by NoHere32** [comment]
patch effectif au prochain transfert
