### ISSUE TITLE
[BUG] Chapeau pêcheur

### ISSUE THREAD

**Issue by Amateur2Drapeau** [RivrsMc/SeasonSky-Issues#170]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MaelEnFrance

### Pseudo discord

maelenfrance

### Que s'est-il passé ?

Le chapeau du pêcheur ne donne pas Luck I, et s'il est équipé alors que l'effet Luck I était déjà présent (grace à un pet par exemple) l'effet disparait. Le déséquiper engendre le meme effet

### Étapes à suivre pour reproduire le bug

Avoir Luck I
Equiper ou Déséquiper le chapeau

### Qu'aurait-il dû arriver ?

Conserver Luck I

### Date et heure de la production du bug

x

### Serveur

x

**Comment by Jspppppp** [comment]
Hello, le chapeau donne bien ! Il faut l'équiper d'une certaine manière. En gros tu le mais dans ta haut barre et tu cliques droit dessus faut pas le glisser dans l'inventaire
