### ISSUE TITLE
Ticket > perte exp map aventure 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#171]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0isan 

### Pseudo discord

Nami_san

### Que s'est-il passé ?

Lors d'un voyage en map aventure particulièrement dans la farme de jean.
Si on se fait tuer on perds pas notre stuff mais on perds tout notre exp.
Logiquement nous sommes pas censé le perdre fin normalement. 

### Étapes à suivre pour reproduire le bug

Farm des mobs mourir dans la farme à Jean avec de l'exp, perte de tout l'exp

### Qu'aurait-il dû arriver ?

Sans doute ne pas la perdre. 

### Date et heure de la production du bug

21juillet 14h17

### Serveur

Global

### Screen / vidéo

![Screenshot_20230721_141307](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/fadd65af-a5a2-413f-8cbb-680b558dd663)

**Comment by LuluxClient** [comment]
Uniquement les legendes ne perdent pas leurs EXP
