### ISSUE TITLE
[BUG] Le replanteur ne fonctionne pas avec les citrouilles/pastèques

### ISSUE THREAD

**Issue by Amateur2Drapeau** [RivrsMc/SeasonSky-Issues#173]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MaelEnFrance

### Pseudo discord

maelenfrance

### Que s'est-il passé ?

Le replanteur ne fonctionne pas avec les citrouilles/pastèques, alors qu'il fonctionne avec le blé ou les patates, ici il ne plante pas les graines

### Étapes à suivre pour reproduire le bug

Planter pour la premiere fois des pastèques ou citrouille

### Qu'aurait-il dû arriver ?

Le replanteur devrait les planter

### Date et heure de la production du bug

21-07 15:14:52

### Serveur

island-06

### Information supplémentaire

UUID: ccf4c91d-a9da-442e-94df-2a03f6b3cb1a
Position: 5375 58 -3575 SuperiorWorld
Ping: 23ms

**Comment by ArDiDEx** [comment]
Hey! Je viens d'essayer et de mon côté les melon seeds & pumkin seeds se plante bien (testé avec la houe royale)

**Comment by Amateur2Drapeau** [comment]
> Hey! Je viens d'essayer et de mon côté les melon seeds & pumkin seeds se plante bien (testé avec la houe royale)

Pour la houe royale ok mais le joueur m'a signalé avec le replanteur. C'est donc normal qu'avec la houe ce soit fonctionnel mais pas le replanteur ?

**Comment by ArDiDEx** [comment]
> > Hey! Je viens d'essayer et de mon côté les melon seeds & pumkin seeds se plante bien (testé avec la houe royale)
> 
> Pour la houe royale ok mais le joueur m'a signalé avec le replanteur. C'est donc normal qu'avec la houe ce soit fonctionnel mais pas le replanteur ?

C'est quoi "le replanteur" ?

**Comment by ArDiDEx** [comment]
Hey, du nouveau sur ce qu'est un replanteur?

**Comment by ArDiDEx** [comment]
je close l'issue pour inactivité du coup
