### ISSUE TITLE
[BUG] L'armure de l'aventurier ne donne pas force 1

### ISSUE THREAD

**Issue by Kutakimochi** [RivrsMc/SeasonSky-Issues#174]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Kutakimochi

### Pseudo discord

Kutakimochi#0879

### Que s'est-il passé ?

Je n'ai pas force 1 avec l'armure

### Étapes à suivre pour reproduire le bug

avoir l'armure

### Qu'aurait-il dû arriver ?

avoir force 1

### Date et heure de la production du bug

21-07 19:23:52

### Serveur

Spawn-02

### Information supplémentaire

UUID: 9a5af67d-a45d-4d99-bac2-f922ae376afd
Position: -108 -52 -82 IslandPirate
Ping: 182ms

**Comment by Xin0u** [comment]
le  bug à déjà étais report #160

**Comment by Kutakimochi** [comment]
C'était avant le patch, dans ce patch y'a écrit fixe des armures mais l'effet force 1 n'est toujours pas la

**Comment by NoHere32** [comment]
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/123643370/ca3958ac-dcf3-4918-b3e1-cdff15b461be)
