### ISSUE TITLE
[BUG] Pet mouette ne spawn pas

### ISSUE THREAD

**Issue by ReDModded** [RivrsMc/SeasonSky-Issues#175]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

ReDModded

### Pseudo discord

science_and_astronomie

### Que s'est-il passé ?

Le pet mouette( pièce d'or) reste en passif , il ne veut pas sortir .

### Étapes à suivre pour reproduire le bug

Alors /pets et cliquer pour sortir de le pets de sa maison.

### Qu'aurait-il dû arriver ?

Le pets aurait du sortir, pour le nourrir l'utiliser etc

### Date et heure de la production du bug

21-07 19:55:36

### Serveur

Spawn-04

### Information supplémentaire

UUID: d9944ffe-57f2-4187-bd9f-0d0facf331c9
Position: -93 -57 -142 IslandPirate
Ping: 23ms

**Comment by NoHere32** [comment]
good
