### ISSUE TITLE
Ticket > Codex social niveau 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#176]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0isan 

### Pseudo discord

Nami_san

### Que s'est-il passé ?

En gros malgré le report et le patch en rapport avec le codex, les joueurs arrvent toujours à dépasser le Lvl 6 donc jusqu'au lvl25.

Visiter les endroits du codex ne s'enregistre toujours pas donc certains en abusent donc gagne sans doute des récompenses en plus ou des Lvl en plus. 

### Étapes à suivre pour reproduire le bug

Je ne sais pas trop les étapes exact de ce bug.
Mais voir le ticket ci dessous 

### Qu'aurait-il dû arriver ?

Rester sur un Lvl 6 comme tout le monde ne pas le dépasser pouvoir enregistrer les emplacement du codex 

### Date et heure de la production du bug

20h00/ 21juillet 

### Serveur

Global

### Screen / vidéo

![Screenshot_20230721_195432_com discord](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/11292618-c947-4f15-bb29-c8fde5d63ab8)
![Screenshot_20230721_195834_com discord](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/acd8ddac-bb86-405c-9d26-2046eb5f1901)
![Screenshot_20230721_195844_com discord](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/0a53b5af-ea75-4d75-87ab-523dfd3b16c9)
![Screenshot_20230721_195901_com discord](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/fbd1aab5-94d7-4ca2-ae39-40f606e267ce)
![Uploading Screenshot_20230721_195908.jpg…]()

**Comment by LuluxClient** [comment]
@falistos il faudrait reset le user dans la bdd: Mafouta

**Comment by Isweazu** [comment]
> @falistos il faudrait reset le user dans la bdd: Mafouta

Hello, y'en a un qui vient de me report à nouveau le bug, a reset aussi je pense : Maky1308
