### ISSUE TITLE
[BUG] BOULBI BLANC OR

### ISSUE THREAD

**Issue by GasaiDYuno** [RivrsMc/SeasonSky-Issues#177]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

GasaiDYuno

### Pseudo discord

gasaidyuno

### Que s'est-il passé ?

Ayant acheté un **BOULBI BLANC OR** au /ah, il ne veut pas s'invoquer.
Or il marque bien "Votre familier est sortie de sa maison".
J'ai essayé de désequipper réequipper.
Egalement essayer de déco reco, le mettre dans mon inv et le remettre dans l'interface /pets, rien n'y change.
Ce qui rend impossible à le monter avec des bonbons.

### Étapes à suivre pour reproduire le bug

1. Mettre le pet dans le /pets avec clic droit
2. Essayer de l'invoquer dans le /pets
3. S'apercevoir qu'il ne s'invoque pas et qu'il y a toujours écrit statut : PASSIF

### Qu'aurait-il dû arriver ?

ça aurait dû l'invoquer

### Date et heure de la production du bug

21-07 22:13:30

### Serveur

island-01

### Information supplémentaire

UUID: 93d9818f-2517-499c-a119-f2a279b207f6
Position: -16201 99 -3 SuperiorWorld
Ping: 10ms

**Comment by NoHere32** [comment]
good
