### ISSUE TITLE
[BUG] Pet Pirate  Squelette

### ISSUE THREAD

**Issue by LaBaane** [RivrsMc/SeasonSky-Issues#178]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

LaBaane_

### Pseudo discord

labananeflambee_

### Que s'est-il passé ?

une fois équipé, le pet reste en passif, impossible de le sortir pour lui donner des bonbon malgré les messages du chat qui disent qu'il est sortit

### Étapes à suivre pour reproduire le bug

1.Equiper le pet 
2.click geuche dessus pour le sortir

### Qu'aurait-il dû arriver ?

le pet aurais du sortir 

### Date et heure de la production du bug

21/07/2023 

### Serveur

SeasonSky

**Comment by NoHere32** [comment]
good
