### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ReDModded** [RivrsMc/SeasonSky-Issues#179]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

ReDModded

### Pseudo discord

science_and_astronomie

### Que s'est-il passé ?

Quand on clic sur la collection d'un joueur au hasard, on tombe sur le menu principal 

### Étapes à suivre pour reproduire le bug

Ouvrir le tchat, cliquer sur un pseudo, cliquer sur "collection".

### Qu'aurait-il dû arriver ?

Lorsque l'on appui sur "collection" on est censé voir la collection du joueur .

### Date et heure de la production du bug

22-07 00:05:32

### Serveur

island-02

### Screen / vidéo

https://github.com/RivrsMc/SeasonSky-Issues/assets/140198588/720167d7-ed60-492d-99f7-bc2705a28cd5

### Information supplémentaire

UUID: d9944ffe-57f2-4187-bd9f-0d0facf331c9
Position: 7234 51 5393 SuperiorWorld
Ping: 551ms

**Comment by NoHere32** [comment]
Aucun bug repérer
