### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ePlanete** [RivrsMc/SeasonSky-Issues#180]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Planetee

### Pseudo discord

planete

### Que s'est-il passé ?

**Le pet Sapinette ne donne pas +20% du métier bucheron**

### Étapes à suivre pour reproduire le bug

Prendre le pet l'activer regarder

### Qu'aurait-il dû arriver ?

au lieu de 0.36xp pour un buche de Sapin il devrait avoir +

### Date et heure de la production du bug

22-07 02:13:45

### Serveur

island-03

### Information supplémentaire

UUID: f68e0a6f-b737-4aaf-87db-969c7b94d535
Position: 3606 245 -12640 SuperiorWorld
Ping: 17ms

**Comment by NoHere32** [comment]
Hello, le boost s'active au bout de environ 1 / 2 minutes.
