### ISSUE TITLE
[BUG] Casque Pirate

### ISSUE THREAD

**Issue by NeyyKooo** [RivrsMc/SeasonSky-Issues#181]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Neyykoo_

### Pseudo discord

_._uwu_.

### Que s'est-il passé ?

Casque Pirate + mending 

### Étapes à suivre pour reproduire le bug

Mettre un casque pirate dans l'enclume plus un livre meding 

### Qu'aurait-il dû arriver ?

un casque meding 

### Date et heure de la production du bug

22-07 09:08:09

### Serveur

island-04

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/140211242/59ddb6ba-55fe-4f57-853b-413d4b06661e)

### Information supplémentaire

UUID: 04fbeb04-9ef6-48eb-945f-7f2a484fc7a2
Position: 7202 46 7236 SuperiorWorld
Ping: 30ms

**Comment by LuluxClient** [comment]
On ne peut pas mettre de livre d'enchantements sur des items comme du fer ou autre, il faudrait voir si nous pouvons rajouter le support pour faire cela sinon cela risque de ne pas être possible / le casque ne devrait pas perdre de durabilité

**Comment by LuluxClient** [comment]
Donc à voir ce que dit Ardidex

**Comment by ArDiDEx** [comment]
> On ne peut pas mettre de livre d'enchantements sur des items comme du fer ou autre, il faudrait voir si nous pouvons rajouter le support pour faire cela sinon cela risque de ne pas être possible / le casque ne devrait pas perdre de durabilité

Hey, ça ne sera pas possible
