### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by edbdb** [RivrsMc/SeasonSky-Issues#184]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

edbdb

### Pseudo discord

edbdb

### Que s'est-il passé ?

Bonjour, mon chapeau de pirate ne me donne pas l'effet "force 2"

### Étapes à suivre pour reproduire le bug

Bonjour, mon chapeau de pirate ne me donne pas l'effet "force 2"

### Qu'aurait-il dû arriver ?

Bonjour, mon chapeau de pirate ne me donne pas l'effet "force 2"

### Date et heure de la production du bug

22-07 12:34:28

### Serveur

Seasonsky Eldoria

### Information supplémentaire

UUID: 3f14bb4b-5ed7-4562-a5fc-2fd1b2c72aac
Position: 14472 100 -16219 SuperiorWorld
Ping: 8ms

**Comment by LuluxClient** [comment]
Aucun soucis de mon côté, merci de bien répondre au question et non simplement c/c le premier message.
