### ISSUE TITLE
[BUG] Grappin

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#185]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

je ne sais pas si c'est fait exprès ou pas mais le grappin (au moins celui du lvl 10 forge mage) nous fait juste bup en l'air et non nous  projette en l'air et vers l'avant comme le faisait à la V3, actuellement leur utilité est nul vu qu'il nous fait pas avancer

### Étapes à suivre pour reproduire le bug

1. avoir le grappin
2. l'utilisé

### Qu'aurait-il dû arriver ?

ca serait mieux qu'il propulse en l'air et vers l'avant pour qu'il ait une vrai utilité

### Date et heure de la production du bug

22/07/2023 14:18

### Serveur

all

**Comment by NoHere32** [comment]
Hello, après des test il envoie bien dans la direction ou tu vise.
