### ISSUE TITLE
[BUG] Pet Roi des Pirates

### ISSUE THREAD

**Issue by ePlanete** [RivrsMc/SeasonSky-Issues#187]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Planetee

### Pseudo discord

planete

### Que s'est-il passé ?

Mon ami possède le pet roi des pirates et le bonus 30% ne marche pas

### Étapes à suivre pour reproduire le bug

Avoir le pet, taper des monstres

### Qu'aurait-il dû arriver ?

+ d'xp

### Date et heure de la production du bug

22-07 14:29:10

### Serveur

island-03

### Information supplémentaire

UUID: f68e0a6f-b737-4aaf-87db-969c7b94d535
Position: 3606 245 -12636 SuperiorWorld
Ping: 12ms

**Comment by NoHere32** [comment]
good au prochain transfert
