### ISSUE TITLE
[BUG] /ase

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#189]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

des fonctionnalités ne sont pas disponible

### Étapes à suivre pour reproduire le bug

1. payer le /ase
2. click droit avec un flint

### Qu'aurait-il dû arriver ?

on devrait pouvoir avoir acces au fonctionnalité

### Date et heure de la production du bug

22/07/2023 15:55

### Serveur

all

**Comment by LupusArctos4** [comment]
j'avais oublier le screen 
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/1e286dcf-bab9-41b2-a57b-a0843861eeb2)

**Comment by LupusArctos4** [comment]
En gros quand on click sur les items ça met : vous n'avez pas accès à cette commande

**Comment by NoHere32** [comment]
Après plusieurs test avec les perms secondaire le soucis est toujours pas surement ce qui a été fait pour permettre de mettre le premium tout en bas dans le luckperm

**Comment by LupusArctos4** [comment]
Pour info je suis citoyen et légende
