### ISSUE TITLE
[BUG] Double récompenses de quête

### ISSUE THREAD

**Issue by Isweazu** [RivrsMc/SeasonSky-Issues#19]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Isweazu

### Pseudo discord

xx4040

### Que s'est-il passé ?

Les quêtes terminée (niveau facile) donnent des doubles récompenses à la complétion

### Étapes à suivre pour reproduire le bug

Finir une quête facile

### Qu'aurait-il dû arriver ?

N'avoir qu'une seule récompense et non 2

### Date et heure de la production du bug

00.49 le 09-07

### Serveur

Ile

### Screen / vidéo
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/138036771/dc795a8b-067f-4ab4-a251-d413d3e6d880)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/138036771/0d341ca6-fd78-40ed-88f0-f9bb1472b23d)

_No response_

**Comment by Isweazu** [comment]
Apparement ça va mieux

**Comment by LuluxClient** [comment]
Salut ceci n'est pas un bug, tu gagnes plusieurs récompense en 1 quête, pour la quête facile c'est entre 1 et 2 récompenses
