### ISSUE TITLE
[BUG] Pet Roi des Pirates argent

### ISSUE THREAD

**Issue by TheMalaKaye** [RivrsMc/SeasonSky-Issues#190]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

TheMalaKaye

### Pseudo discord

MalaKaye

### Que s'est-il passé ?

j ai pas reçus l'argent que mon pet pirate  devais me donner il est niveau 11 et 
au niveau 1 il devrai me donner 10K et
au niveau 10 il devrai me donner 20K 
soit un Total de 30K et je ne reçois que 20K sur les 30K que je devrai car j ai aussi le pet Luffy qui est niveau 1 et me donne 5K a se niveau la et donc lui me donne bien les 5K

### Étapes à suivre pour reproduire le bug

Attendre une heur que le pets vous donne l'argent

### Qu'aurait-il dû arriver ?

j aurai du avoir 30K avec mon pet pirate soit en plus de mon pet luffy niveau 1 qui me donne 5K
j'aurai du avoir un totale de 35K

### Date et heure de la production du bug

22/07/2023 16H15

### Serveur

island-02

### Screen / vidéo

preuve dans le Tchat il est marquer que j ai reçus 25K alors que je devrai en recevoir 35K pour le total de mais deux pet
https://image.noelshack.com/fichiers/2023/29/6/1690035012-bug-pet.png
preuve de mais deux pet :
**Pets Roi des pirate (dois recevoir 30K)**
https://image.noelshack.com/fichiers/2023/29/6/1690035144-pets-roi.png
**Pets Luffy (dois recevoir 5K)**
https://image.noelshack.com/fichiers/2023/29/6/1690035150-pets-luffy.png

**Comment by LLucrece** [comment]
je crois que ca marche pas comme ca.
c'est une augmentation de l'argent par heure, pas une somme

**Comment by NoHere32** [comment]
Hello, comme a pu le dire lucrece c'est une augmentation pas une addition.
La desc sera modifier au prochain transfert
