### ISSUE TITLE
[BUG] Tonte mouton stack

### ISSUE THREAD

**Issue by Jspppppp** [RivrsMc/SeasonSky-Issues#192]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Jspppppp

### Pseudo discord

Mathéo#8230 / Jspppppp (l'ours)

### Que s'est-il passé ?

Quand je tonds un mouton, le stack entier est tondu.

### Étapes à suivre pour reproduire le bug

1. Avoir une cisaille 
2. Clique droit sur un stack de mouton (2 au mini)
3. Voir que ça tond les 2 

### Qu'aurait-il dû arriver ?

Tondre un seul mouton (1 par 1)

### Date et heure de la production du bug

All

### Serveur

Island 3 (et autre je suposse)

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139492099/25f5bf22-e807-49f9-bd5a-e7447ddc6a43)

https://youtu.be/YQp4xL3uuT0

**Comment by LuluxClient** [comment]
Une erreur de notre part, un oublie de push mais cela devrait être bon au redem !
