### ISSUE TITLE
[BUG] Dispawn boss du /pirate serveur 1

### ISSUE THREAD

**Issue by LLucrece** [RivrsMc/SeasonSky-Issues#193]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Lucrece

### Pseudo discord

Lucrece

### Que s'est-il passé ?

J'etais avec tifalik et quelque joueurs, on est tous mort et en revenant le boss avait disparu

### Étapes à suivre pour reproduire le bug

-faire le boss
-mourrir 
-pleurer

### Qu'aurait-il dû arriver ?

le boss aurait du rester

### Date et heure de la production du bug

23/07 à 18h07

### Serveur

serveur pirate 1

### Screen / vidéo

https://cdn.discordapp.com/attachments/1112054057041936474/1132343227819761805/2023-07-22_18.06.53.png

**Comment by LuluxClient** [comment]
Fixed au redem !
