### ISSUE TITLE
[BUG] Modification du casque pirate

### ISSUE THREAD

**Issue by Rapha-off** [RivrsMc/SeasonSky-Issues#196]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

rapha_off

### Pseudo discord

Rapha_off

### Que s'est-il passé ?

J'ai voulue ajouter un enchantement dessus car il est écrit que nous le pouvons alors que ce n'est pas le cas 

### Étapes à suivre pour reproduire le bug

Mettre son casque dans l'enclume puis le livre

### Qu'aurait-il dû arriver ?

Avoir l'enchantement sur le casque pirate

### Date et heure de la production du bug

22/07/2023 a 22h15

### Serveur

island-4

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/140278362/fd8c83d5-601a-4d3a-8df2-d4311000a85c)

**Comment by LuluxClient** [comment]
Duplicate of #181
