### ISSUE TITLE
[BUG] /rewards non réinitialisé 

### ISSUE THREAD

**Issue by Absal0n78** [RivrsMc/SeasonSky-Issues#197]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Absal0n

### Pseudo discord

Absalon

### Que s'est-il passé ?

Bonjour,

Le 22/07 à 23:59 j'avais récupéré tous les rewards du /rewards.
J'ai remarqué le 23/07 à 00:14 que les rewards ne s'étaient pas réinitialisés et qu'ils le seraient dans "23h 46min". En clair, je perds un jour de rewards. 

### Étapes à suivre pour reproduire le bug

1. Faire /rewards

### Qu'aurait-il dû arriver ?

Les rewards auraient dû être réinitialisés et j'aurais dû pouvoir les récupérer.

### Date et heure de la production du bug

23-07 00:14:00

### Serveur

island-02

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/140210288/c2db0056-e614-4e96-ba32-d4ceb7f334fa)

### Information supplémentaire

UUID: 7c86fda2-e088-42ad-a164-7854d92bf8d9
Position: 14397 30 -25206 SuperiorWorld
Ping: 26ms

**Comment by entropy-hub** [comment]
Pas réussi à reproduire le bug, peut-être un problème de sync sur le moment?
Je close en attendant, à voir si le bug se reproduit. ça m'a l'air d'être un cas isolé
