### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by DeadPour2Vrai** [RivrsMc/SeasonSky-Issues#199]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Dead140

### Pseudo discord

deadpour2vrai

### Que s'est-il passé ?

J'ai mis 75€ dans la caisse du monde "la ferme de jean" pour avoir la houe des dieux décris comme étant une houe qui "replante automatiquement" sauf qu'elle ne replante pas

### Étapes à suivre pour reproduire le bug

Loot la houe essayer de replanter et voir que ça ne fonctionne pas...

### Qu'aurait-il dû arriver ?

Elle aurait du replanter

### Date et heure de la production du bug

23-07 04:50:32

### Serveur

island-02

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/140292975/a8c16333-0e10-429c-b3c1-be5b17770ea2)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/140292975/c9326787-6436-4cdd-acbe-8c74b874dca5)

### Information supplémentaire

UUID: 9153f78f-95fa-44dd-a9f1-a543225225c1
Position: -21599 106 0 SuperiorWorld
Ping: 467ms

**Comment by NoHere32** [comment]
Aucun bug elle replante avec un clic droit.
