### ISSUE TITLE
[BUG] Mauvais titre donné au niv 50 alchimiste

### ISSUE THREAD

**Issue by Isweazu** [RivrsMc/SeasonSky-Issues#20]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Isweazu

### Pseudo discord

xx4040

### Que s'est-il passé ?

L'affichage du titre donné au niveau 50 alchimiste n'est pas le bon (titre mineur)

### Étapes à suivre pour reproduire le bug

Regarder dans le /jobs les palier alchimiste => 50

### Qu'aurait-il dû arriver ?

Récompense : titre alchimiste et non mineur

### Date et heure de la production du bug

00.52 le 09-07

### Serveur

Spawn

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/138036771/e8627c15-c5aa-4b70-8188-111fad925fcf)

**Comment by LuluxClient** [comment]
Problème d'affichage qui est réglé au redem / prochaine maj
