### ISSUE TITLE
[BUG] Pet Orby

### ISSUE THREAD

**Issue by M1STY87** [RivrsMc/SeasonSky-Issues#200]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

M1STY87

### Pseudo discord

m1sty87

### Que s'est-il passé ?

Le pet Orby au lvl 10 ne donne pas le boost de 10% xp mineur

### Étapes à suivre pour reproduire le bug

1: up Orby lvl 10
2: l'équipé
3: ne donne pas le boost mineur

### Qu'aurait-il dû arriver ?

donne +10% xp mineur

### Date et heure de la production du bug

23-07 08:51:35

### Serveur

island-06

### Information supplémentaire

UUID: 1f8d0384-cb52-4ff6-af5e-573a7bc44526
Position: 5428 58 -3575 SuperiorWorld
Ping: 29ms

**Comment by NoHere32** [comment]
Les boost de jobs ne sont pas actif a la seconde même de l'activation du pet il faut compter environ 1 minutes 30.
