### ISSUE TITLE
[BUG] Récompenses coup Boss Pirate

### ISSUE THREAD

**Issue by Jspppppp** [RivrsMc/SeasonSky-Issues#201]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Jspppppp

### Pseudo discord

Mathéo#8230 / Jspppppp (l'ours)

### Que s'est-il passé ?

Le Boss Pirate ne donne pas les récompenses quand on le tape.

### Étapes à suivre pour reproduire le bug

1. Attendre que le boss spawn
2. Le taper
3. Voir qu'on drop rien
4. Pleurer

### Qu'aurait-il dû arriver ?

Obtenir les récompences

### Date et heure de la production du bug

12 h 

### Serveur

Monde Aventure Pirate

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139492099/26f9bca5-6108-41a7-b066-194d2914df80)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139492099/4b31d6b2-6716-4885-9c29-2a87e6f8a877)

**Comment by LLucrece** [comment]
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/135556343/ab241c20-6bd2-4f3b-849d-12bbac054b87)
idem j'ai rien eu

**Comment by D3BoxOfficiel** [comment]
Corrigé

**Comment by Jspppppp** [comment]
Le classement est bien donné (j'ai eu la clé cos) mais pas les coups j'ai tappé sa me dit j'ai du copper 0 copper dans l'inv

**Comment by LLucrece** [comment]
ça sera sans doute réglé au prochain redémarrage
