### ISSUE TITLE
Ticket > /repair 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#202]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0isan 

### Pseudo discord

Nami_san

### Que s'est-il passé ?

Alors pour faire simple le /repair ne fonctionne pas du tout sur l'armure avanturier déjà tester avec 3légendes

### Étapes à suivre pour reproduire le bug

Utiliser l'armure ensuite faire /repair afin de pouvoir réparer l'armure

### Qu'aurait-il dû arriver ?

Pouvoir le réparer directement avec la commande. 

### Date et heure de la production du bug

23juillet 14h40

### Serveur

Global 

### Screen / vidéo

![Screenshot_20230723_143741](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/45254e63-9f88-4a56-a314-7f54a643d67a)
![Screenshot_20230723_143721_com discord](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/e16873f7-fc74-4369-a24e-78e495fde310)

**Comment by Nam0i** [comment]
https://www.youtube.com/watch?v=M0OPhkj2rHo
Voici une vidéo avec

**Comment by Nam0i** [comment]
https://www.youtube.com/watch?v=M0OPhkj2rHo
Voici une vidéo avec

**Comment by LuluxClient** [comment]
L'item se repair bien mais juste l'affichage du "display durability" qui ne s'update pas normalement, il faudrait rajouter la compabilité à itemsadder

**Comment by LuluxClient** [comment]
Après ceci pourra être ignoré vu que la durabilité devrait se mettre à jour dès qu'elle perd de la dura.
