### ISSUE TITLE
[BUG] Hache royal / Coffre royal

### ISSUE THREAD

**Issue by KatsuyaTV** [RivrsMc/SeasonSky-Issues#203]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

KatsuyaTV

### Pseudo discord

KATSU#7393

### Que s'est-il passé ?

Lorsqu'on casse un coffre royale avec une hache royale il se trasnforme en coffre normal.

### Étapes à suivre pour reproduire le bug

Poser le coffre royale, le récupérer avec une hache royale.

### Qu'aurait-il dû arriver ?

Recuperer le coffre royale qui vend auto.

### Date et heure de la production du bug

17h00 23/07/2023

### Serveur

06

**Comment by ArDiDEx** [comment]
Hey ça sera fix cette nuit avec le redémarrage
Merci du report
