### ISSUE TITLE
[BUG]  Recyclage 

### ISSUE THREAD

**Issue by Zwartkat** [RivrsMc/SeasonSky-Issues#204]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Zwartkat 

### Pseudo discord

Zwartkat 

### Que s'est-il passé ?

On peut vendre les items d'autres mondes aventures dans l'interface de recyclage 

### Étapes à suivre pour reproduire le bug

Par exemple 
1. Ouverture du menu recyclage dans le canyon des profondeurs
2. Recyclage "Tout vendre" avec un item de la ferme de Jean
3. Vente de l'item

### Qu'aurait-il dû arriver ?

Conservation des items non liés au monde 

### Date et heure de la production du bug

19:00 23/07

### Serveur

Aventure (spawn)

**Comment by NoHere32** [comment]
Hello, seul le menu change pas ce qui échange.
