### ISSUE TITLE
[BUG] Compta Selle Quête

### ISSUE THREAD

**Issue by Jspppppp** [RivrsMc/SeasonSky-Issues#205]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Jspppppp

### Pseudo discord

Mathéo#8230 / Jspppppp (l'ours)

### Que s'est-il passé ?

Les selles ne compte pas dans les quêtes

### Étapes à suivre pour reproduire le bug

1. Avoir une quête pêcher x selles 
2. En pécher 1 
3. Voir que ça compte pas 

### Qu'aurait-il dû arriver ?

La selle compte dans la quête

### Date et heure de la production du bug

All 

### Serveur

Island 

### Screen / vidéo

https://youtu.be/KTM9FwEoIwU

**Comment by LuluxClient** [comment]
Salut je n'arrive pas à reproduire le problème @Jspppppp peux-tu me faire une vidéo ?

**Comment by Jspppppp** [comment]
Salut ! J'ai mi un lien dans screen / vidéo : https://youtu.be/KTM9FwEoIwU 
Sinon jpeut send discord dit moi.

**Comment by Isweazu** [comment]
> Salut je n'arrive pas à reproduire le problème @Jspppppp peux-tu me faire une vidéo ?

Je fais une petite update commentaire, ce sont les quêtes difficile minimum, pecher des objets, étiquettes, selles, nénuphares, qui ne fonctionnent pas

**Comment by LuluxClient** [comment]
Ils sont remove temporairement des missions le temps d'un fix.
