### ISSUE TITLE
[BUG] Indication "Terri Rouge foncé" incorrecte

### ISSUE THREAD

**Issue by Joliolo** [RivrsMc/SeasonSky-Issues#206]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Joliolo

### Pseudo discord

Joliolo

### Que s'est-il passé ?

Le "Terri Rouge foncé" indique donner de la redstone (pour moi ça signifie la redstone dust (poussiere)) mais farm des minerais (ore) de redstone

### Étapes à suivre pour reproduire le bug

Avoir le pet

### Qu'aurait-il dû arriver ?

Drop de la redstone (poudre) ou changer le nom de la ressource en minerais de redstone

### Date et heure de la production du bug

23/07/2023

### Serveur

Tous

### Screen / vidéo

![2023-07-23_20 26 47](https://github.com/RivrsMc/SeasonSky-Issues/assets/139632602/aab2d8ee-46e0-47ec-8fb7-3dead5224db7)

**Comment by NoHere32** [comment]
fix au prochain transfert
