### ISSUE TITLE
[BUG] Quete Avancé

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#207]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

on gagne 5 pieces

### Étapes à suivre pour reproduire le bug

1. finir une quete (ici poser des seaux de lave)

### Qu'aurait-il dû arriver ?

on aurait du gagner 5k ou 50k mais pas 5 pieces

### Date et heure de la production du bug

23/07/2023 22:05

### Serveur

island 02

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/c201fa49-91be-4d22-8759-c4d21eaf721a)

**Comment by LuluxClient** [comment]
Bonjour le +5$ devrait venir d'autre part, tu as gagné 40000 ce qui est l'une des récompenses possible de cette quête, il n'y a aucune récompense dans la quête qui donne +5$
