### ISSUE TITLE
[BUG] sur la bar de bosse

### ISSUE THREAD

**Issue by leroideminecarft** [RivrsMc/SeasonSky-Issues#208]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

leroideminecarft

### Pseudo discord

leroideminecraft

### Que s'est-il passé ?

je  me suis deco reco mais il y avais toujour sa

### Étapes à suivre pour reproduire le bug

je me suis juste connecter et j'ai installer le pack

### Qu'aurait-il dû arriver ?

voire correctement le texte des bares de bosses

### Date et heure de la production du bug

je ne sais plus 

### Serveur

eldoria

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/140382030/130c764d-459c-4030-adfc-e4854dbea19b)

**Comment by LuluxClient** [comment]
Ceci vient de votre launcher je pense @leroideminecarft pouvez-vous tester via le launcher officiel de minecraft sans mods ?

**Comment by leroideminecarft** [comment]
ok pas de probleme

**Comment by LuluxClient** [comment]
> ok pas de probleme

Je vous invite également à mettre dans vos options LANG -> POLICE UNICODE en "Non"

**Comment by LuluxClient** [comment]
Egalement s'assurer d'avoir ceci d'activé: 
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/62576432/b148c16a-afb8-4b9f-b2f7-4de252d65e3e)

**Comment by NoHere32** [comment]
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/123643370/b35f78d6-9add-43b6-86c5-6dcf002b52a3)

**Comment by leroideminecarft** [comment]
MEMEM AVEC LE LANCHER DE BASE

**Comment by LuluxClient** [comment]
> MEMEM AVEC LE LANCHER DE BASE

Tu as fais les 2 modifs ci dessus ?

**Comment by leroideminecarft** [comment]
OUI

**Comment by leroideminecarft** [comment]
meme avec le lancher de base 
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/140382030/2fe53ab7-485c-47ff-8f11-b68377db09c4)

**Comment by LuluxClient** [comment]
> meme avec le lancher de base
> ![image](https://user-images.githubusercontent.com/140382030/255564606-2fe53ab7-485c-47ff-8f11-b68377db09c4.png)

Tout fonctionne bien de ce que je vois ?

**Comment by leroideminecarft** [comment]
je nes plus la barre de bossr

**Comment by LuluxClient** [comment]
Sur ton screen tu l’as, tu n’as plus de soucis alors !

**Comment by leroideminecarft** [comment]
ok mrc
bonne journer
