### ISSUE TITLE
Nombre de hopper sur l'ile[BUG] 

### ISSUE THREAD

**Issue by Flytb1** [RivrsMc/SeasonSky-Issues#209]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Flytb

### Pseudo discord

Flytb

### Que s'est-il passé ?

La limite de Hopper sur mon ile est de 32. En revanche quand j'en casse 1 je ne peux plus le replacer ailleurs. Le serveur comptabilise le nombre de hopper qui ont été posés sur l'ile  et non le nombre de hopper actuellement posés. J'espère que c'est claire.
En bref, une fois ma limite de 32 atteinte même si j'en casse un ou plusieurs, je ne peux pas le reposer ailleurs 
Merci d'avance 

### Étapes à suivre pour reproduire le bug

P

### Qu'aurait-il dû arriver ?

La limite de hopper posable sur l'ile doit varier en fonction du nombre total de hopper actuellement sur l'ile et non le nombre de hopper qui ont été poser sur l'ile.

### Date et heure de la production du bug

24-07 10:34:32

### Serveur

island-03

### Screen / vidéo

[https://drive.google.com/file/d/18V5KwySpbnt8tmHbLOwlWCKu1JKrAf8_/view?usp=drive_link](url)

### Information supplémentaire

UUID: 004f33b3-ab2f-45e3-9044-fdaf17e4f40f
Position: 21606 101 -21599 SuperiorWorld
Ping: 15ms

**Comment by Asherate** [comment]
As-tu tenté de faire un /is recalc ?

**Comment by Flytb1** [comment]
Oui mais rien n'y fait

**Comment by LuluxClient** [comment]
Salut ta vidéo est en privé, pourrais-tu la mettre ne publique ?

**Comment by LuluxClient** [comment]
48h sans réponse, ticket fermé, aucun soucis de notre côté / manque d'informations.
