### ISSUE TITLE
Pioche des ombres 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#21]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0iSan 

### Pseudo discord

Nami_san 

### Que s'est-il passé ?

En gros la pioche des ombres quand tu mine avec elle casse tout et rien n'est récupérable pour n'importe quel bloc 

### Étapes à suivre pour reproduire le bug

1. Miner avec la pioche sur n'importe quel item

### Qu'aurait-il dû arriver ?

1.Miner Normal
2 récupérer les objets et vendre uniquement le charbon miner 

### Date et heure de la production du bug

9juillet 00h57

### Serveur

/

**Comment by LuluxClient** [comment]
L'effet autosell permet de rien récup et de casser des choses que t'es pas sensé casser comme l'eclozr

**Comment by mrsxnshxne** [comment]
J'ajoute que les spawners peuvent être cassés sans les drop et sans le message qui cancel l'event si on a pas Silk Touch (c'est le cas pour la pioche des ombres)

**Comment by ArDiDEx** [comment]
l'effet autosell drop désormais bien les items au sol si non vendable
