### ISSUE TITLE
[BUG] Boost pets forgemage non fonctionnel

### ISSUE THREAD

**Issue by PanzaniAuGet27** [RivrsMc/SeasonSky-Issues#211]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

PanzaniAuGet27

### Pseudo discord

Arcera

### Que s'est-il passé ?

Mon pets +20% legendaire forgemage ne fonctionne pas je n'est aucun boost

### Étapes à suivre pour reproduire le bug

prendre le pete fabriquer des plastron en cuir 

### Qu'aurait-il dû arriver ?

gagne + de xp

### Date et heure de la production du bug

10

### Serveur

seasonsky

### Screen / vidéo

[](url)

### Information supplémentaire

.

**Comment by LuluxClient** [comment]
Pourrais-tu m'indiquer le nom de ton pets ?

**Comment by PanzaniAuGet27** [comment]
Pets Tyrantus

Le ven. 28 juil. 2023 à 5:21 PM, Luca Améaume ***@***.***> a
écrit :

**Comment by LuluxClient** [comment]
J’ai push un fix potentiel, je te laisse le tester dès demain au redem à 5h

**Comment by LuluxClient** [comment]
Après plusieurs test un problème est survenue, la permission du boost pet est correcte mais fonctionne uniquement si la permission est attribué au joueur et non via le pet. Cela est un bug assez fréquent sur plusieurs pets. @falistos si tu peux faire un check de comment le système de permission fonctionne sur les pets ?

**Comment by LuluxClient** [comment]
Hello ceci devrait être fix !
