### ISSUE TITLE
[BUG] animation Mimique

### ISSUE THREAD

**Issue by Xin0u** [RivrsMc/SeasonSky-Issues#212]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Xinou

### Pseudo discord

Xinou

### Que s'est-il passé ?

Le pet Mimique n'a aucune animation et n'est pas centré dans l'éclozr

### Étapes à suivre pour reproduire le bug

1- Obtenir Mimique 
2-Le mettre dans l'eclozr
3- Regarder le pet bug

### Qu'aurait-il dû arriver ?

Il devrait être animé et centré dans l'éclozr

### Date et heure de la production du bug

tous le temps

### Serveur

toute les islands

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139914502/18c6d431-3edb-4b11-8999-34d92ed1dd4a)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139914502/243bc0b0-a7e9-4128-9186-325f2d9dd8a6)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139914502/5b2ab727-a01d-4ee0-9675-a4274ab09f7c)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139914502/d5e3cb23-45d5-4d02-8a39-cea9baf69159)

**Comment by Xin0u** [comment]
le pets fantasia violet et un comparatif

**Comment by Xin0u** [comment]
idem avec le tyrantus

**Comment by LuluxClient** [comment]
Petit soucis sur son animation idle, un fix arrivera en semaine
