### ISSUE TITLE
[BUG] boss pirate ne drop pas clé cosmétique

### ISSUE THREAD

**Issue by daikumierte** [RivrsMc/SeasonSky-Issues#213]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

daikumierte

### Pseudo discord

daikumierte

### Que s'est-il passé ?

Bonjour j'ai fait l'évents ou faut tuer le boss pirates et je n'est pas recu le copper ne la clés cosmétiques ( j'ai un rec) :/

### Étapes à suivre pour reproduire le bug

Taper le boss pirates toutes les 2 heures ?

### Qu'aurait-il dû arriver ?

recevoir les récompenses 

### Date et heure de la production du bug

16h - 16h10

### Serveur

aventures pirates

### Screen / vidéo

fichier trop volumineux :/

**Comment by LuluxClient** [comment]
Fixed
