### ISSUE TITLE
[BUG] Item moddé bugé 

### ISSUE THREAD

**Issue by ext0ller** [RivrsMc/SeasonSky-Issues#214]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

extoller

### Pseudo discord

extoller

### Que s'est-il passé ?

Bonjour il y as actuellement un bug/oubli car quand on casse avec La Pioche Royale ou Le Marteau Royal le nombre de blocs cassé n'est pas le bon

### Étapes à suivre pour reproduire le bug

casser blocs avec Pioche Royale Marteau Royal... et avec une quest peu importe la catégorie et la difficulté 

### Qu'aurait-il dû arriver ?

au lieu de comptabilisé 1 bloc sa aurait du comptabilisé 9 bloc(avec le marteau
et avec la pioche cela ne fonctionne pas du tout rien n'est comptabilisé

### Date et heure de la production du bug

N/A

### Serveur

island-01

### Screen / vidéo

https://github.com/RivrsMc/SeasonSky-Issues/assets/140436157/14fb9afc-75cb-472c-a80c-419476d24d9e

vidéo courte car sinon fichier trop volumineux

**Comment by LuluxClient** [comment]
Bug déjà report, le fix est en cours, merci d'utiliser un item qui TP pas les objets dans l'inv pour éviter les soucis avec les quêtes.
