### ISSUE TITLE
Bug Pets Mimique Boost 20% Métier non fonctionnel

### ISSUE THREAD

**Issue by DeadPour2Vrai** [RivrsMc/SeasonSky-Issues#215]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

dead140 / iDead_

### Pseudo discord

deadpour2vrai

### Que s'est-il passé ?

J'ai dépensé une fortune pour acheté le pet mimique et à ma grande surprise le boost métier mineur 20% ne fonctionne pas...

### Étapes à suivre pour reproduire le bug

Avoir mimique le mettre comme actif et faire des actions de mineur tel que miner ou encore fondre des minerais...

### Qu'aurait-il dû arriver ?

Le boost devrait "en théorie" fonctionner sur toutes les actions du métier mineur

### Date et heure de la production du bug

02h06

### Serveur

island-02

### Screen / vidéo

https://youtu.be/DEx2q4uk6ls

### Information supplémentaire

c'est la merde les flel je peux pas farm aled

(Merci de prendre le temps pour la demande)

**Comment by LuluxClient** [comment]
Fixed au prochain redem, l'exp sera bien boost par 1.2 et également il faut 1 minute pour que l'effet soit effectif
