### ISSUE TITLE
[BUG] glowing vert a la place de blanc dans le pet fantasia cyan lvl 15

### ISSUE THREAD

**Issue by J7KL** [RivrsMc/SeasonSky-Issues#216]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

J7KL_

### Pseudo discord

J7KL_

### Que s'est-il passé ?

la couleur n'est pas la bonne que le dit le pets

### Étapes à suivre pour reproduire le bug

améliorer le pets

### Qu'aurait-il dû arriver ?

avoir un glowing blanc a la place de vert 

### Date et heure de la production du bug

25/07/2023 vers 16h30

### Serveur

SeasonSky

**Comment by Asherate** [comment]
Hello, je viens de tester et j'obtiens bien un glowing blanc, pourrais tu me dire si le soucis est toujours d'actualité ?

**Comment by J7KL** [comment]
le soucis est toujours d'actualité

**Comment by LuluxClient** [comment]
Hello j'ai trouvé le soucis, cela est lié à une limitation minecraft et il prendra la couleur de ton pseudo, pour remédier au problème tu devrais désormais avoir accès à la commande /glow et à la couleur blanche, je te laisse tester et me dire si tout est bon au prochain redem

Edit: Cela cause des soucis sur nos système, je vais voir pour un autre moyen de le patch.
