### ISSUE TITLE
[BUG] Grapin et fishing rod

### ISSUE THREAD

**Issue by Amateur2Drapeau** [RivrsMc/SeasonSky-Issues#217]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MaelEnFrance

### Pseudo discord

maelenfrance

### Que s'est-il passé ?

Si le joueur lance sa canne principale (royale par exemple) et qu'il swap sur son grappin quand il voit le poisson arrivé, il aura les enchantements de la canne royale mais n'utilisera pas sa durabilité car il aura swap sur le grapin

### Étapes à suivre pour reproduire le bug

Lancer l'hamecon avec la canne principale
Voir le poisson
Swap sur le grapin
le pecher avec le grapin

### Qu'aurait-il dû arriver ?

Utiliser la dura de la canne/enlever l'hamecon lors du swap

### Date et heure de la production du bug

25-07 19:57:31

### Serveur

island-06

### Screen / vidéo

x

### Information supplémentaire

UUID: ccf4c91d-a9da-442e-94df-2a03f6b3cb1a
Position: -5403 -58 27064 SuperiorWorld
Ping: 14ms

**Comment by ArDiDEx** [comment]
Hey! 
Ça sera fix au prochain redem
Merci du report
