### ISSUE TITLE
[BUG] Replantage pets froussard lvl 20

### ISSUE THREAD

**Issue by Sekiigan** [RivrsMc/SeasonSky-Issues#218]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Sekigan__

### Pseudo discord

sekiigan_

### Que s'est-il passé ?

Lorsque j'équipe le pet " Froussard " qui au niveau 20 est censé replanter automatiquement le blé, avec ma houe royale, cela replante uniquement le bloc du milieu sur lequel j'ai cliqué et non en 3x3.

### Étapes à suivre pour reproduire le bug

Activé le pet Froussard niveau 20, et utiliser une houe royale sur du blé.

### Qu'aurait-il dû arriver ?

Cela aurais dû casser et replanter en 3x3

### Date et heure de la production du bug

25/07/23 18:00

### Serveur

Seasonsky

**Comment by LupusArctos4** [comment]
les houes replantant automatiquement désormais je pense que ton report n'est plus utile  @Sekiigan 
si je peux te conseiller en tant que joueur ton pet n'est pas perdu vu qu'il peut servir lors des event farm de 16h-18h2-20h-22h lors que c'est le blé qui tombe, avec le pet ca pourrait te permettre d'avoir des médailles et d'acheter des items dans le /farm-contest

**Comment by Alexis700** [comment]
Fix
