### ISSUE TITLE
[BUG] Pas de give d'xp aventurier par les mobs de la zone "La ferme de jean"

### ISSUE THREAD

**Issue by LLucrece** [RivrsMc/SeasonSky-Issues#22]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

lucrece

### Pseudo discord

Lucrece

### Que s'est-il passé ?

Pas de give d'xp aventurier par les mobs de la zone "La ferme de jean"
d'aprés NelyLife

### Étapes à suivre pour reproduire le bug

Aller dans la ferme de jean
taper un mobs
ne rien recevoir

### Qu'aurait-il dû arriver ?

on doit recuperer l'xp aventurier en tuant des mobs

### Date et heure de la production du bug

09-07 01:07:37

### Serveur

island-02

**Comment by LuluxClient** [comment]
Fixed
