### ISSUE TITLE
[BUG] la houe du soleil ne fait pas avancer dans les évent de farm et dans les quête 

### ISSUE THREAD

**Issue by MellowCrib28112** [RivrsMc/SeasonSky-Issues#220]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MellowCrib

### Pseudo discord

MellowCrib28112

### Que s'est-il passé ?

La houe du soleil ne fait pas avancer dans les évent de farm et dans les quête 

### Étapes à suivre pour reproduire le bug

demander en MP une vidéos je peut pas la mettre.

### Qu'aurait-il dû arriver ?

faire avancer la quête.

### Date et heure de la production du bug

depuis le debut ?

### Serveur

tous je pense

**Comment by Jspppppp** [comment]
Faut voir avec le staff mais c'est pas un bug normalement

**Comment by entropy-hub** [comment]
En attente du plugin d'items

**Comment by Alexis700** [comment]
Il faut utiliser des items qui n'ont pas d'effet pour compléter les quêtes, car il y aurait un trop gros déséquilibre avec les items qui casse et replante en 3*3 et les nouveaux items potentiellement ajoutable
