### ISSUE TITLE
[BUG] Bouteilles de Miel buguées avec les pets

### ISSUE THREAD

**Issue by Tweentyy** [RivrsMc/SeasonSky-Issues#221]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Tweenty_

### Pseudo discord

tweenty_

### Que s'est-il passé ?

Lorsque l'on récupère les bouteilles de miel de son pets, 16 bouteilles (pour nous) = 64 bouteilles (pour le pet)

### Étapes à suivre pour reproduire le bug

Récupérer les bouteilles de miel du pet et voir combien on en gagne. Comparer

### Qu'aurait-il dû arriver ?

Avoir 3x plus de bouteilles (et donc devoir faire bien plus de "tout récupérer" 

### Date et heure de la production du bug

17h00

### Serveur

island-01

### Screen / vidéo

https://github.com/RivrsMc/SeasonSky-Issues/assets/82669168/77e77b71-0d2a-4444-9921-2264f1f50459

### Information supplémentaire

9*4*16 n'est pas égal à 2176 mais 
9*4*64 par contre ça l'est bien (j'ai arrondi avec les emplacements utilisés)

**Comment by Tweentyy** [comment]
Le "retirer par 64/32" fonctionne correctement

**Comment by Jspppppp** [comment]
Yes quand il y en a 1536 on en récup un peut plus de 500 :/

**Comment by ArDiDEx** [comment]
Hey ça sera fix au prochain restart de cette nuit
Merci du report
