### ISSUE TITLE
[BUG] Revente pets émeraude non fonctionnelle 

### ISSUE THREAD

**Issue by Isweazu** [RivrsMc/SeasonSky-Issues#223]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Isweazu

### Pseudo discord

xx4040

### Que s'est-il passé ?

Le 50% sur la vente d'émeraude du pets mimique ne fonctionne pas.

### Étapes à suivre pour reproduire le bug

Avoir le pets mimique niveau 15 activé, revendre de l'émeraude pars le billet du /shop en les ayant en inventaire

### Qu'aurait-il dû arriver ?

Avoir le fameux multiplicateur de vente

### Date et heure de la production du bug

25/07 à 23h26

### Serveur

Island 06

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/138036771/a3b75991-5653-40a5-849c-f28520159953)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/138036771/d9754723-a75c-4ef8-a4f6-5e5f3c0c2da1)

**Comment by LuluxClient** [comment]
Ok soucis de mon côté, peux-tu retester ?

**Comment by Isweazu** [comment]
> Ok soucis de mon côté, peux-tu retester ?

Je viens de test à l'instant, ça fonctionne avec le /shop maintenant, la dernière fois ça ne fonctionnait pas, j'ai pas pensé à replay j'avais test avec un stack de 64 et je l'avas vendu 5k et quelques malgré le pet, la c'est good ça à l'air revenu
Par contre est-ce normal de ne pas pouvoir le cumuler aux sell-sticks dans un double chest ? (j'ai test aussi) mais je pref poser la questions au cas ou :)

**Comment by LuluxClient** [comment]
Pas de soucis, n'hésite pas à réouvrir une issue si le problème persiste.
