### ISSUE TITLE
[BUG] Orthographe description compacteur

### ISSUE THREAD

**Issue by Founny** [RivrsMc/SeasonSky-Issues#224]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Isaac______

### Pseudo discord

isaac____

### Que s'est-il passé ?

Fautes dans la description du compacteur

### Étapes à suivre pour reproduire le bug

-

### Qu'aurait-il dû arriver ?

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/39631165/0d243a8c-29ea-4f76-b3c2-0bd6c627046c)

sans les fautes: "afin de monter vos rangs"

réécrite d'une meilleure manière (subjectif donc): "les ressources de votre choix afin de monter de rang"

### Date et heure de la production du bug

26/07 1h30

### Serveur

is-02

### Screen / vidéo

-

### Information supplémentaire

-

**Comment by Asherate** [comment]
Merci ! C'est corrigé
