### ISSUE TITLE
[BUG] Niveau de Skills Reset 

### ISSUE THREAD

**Issue by Avilo95** [RivrsMc/SeasonSky-Issues#225]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Avilo95

### Pseudo discord

Avilo95

### Que s'est-il passé ?

Bonjour 

Suite à la maintenance causée par le rollback du 25/07, j'ai constaté que l'ensemble de mes métiers a été réinitialisé sur mon île. Cependant, mon niveau de Skyblock est resté intact.

### Étapes à suivre pour reproduire le bug

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de la production du bug

25/07/2023 23:00

### Serveur

Island 02

### Screen / vidéo

![Niveau ile](https://github.com/RivrsMc/SeasonSky-Issues/assets/140616347/bb2ee62a-ed79-4e3b-a7e5-c802d7e60a9d)
![miner](https://github.com/RivrsMc/SeasonSky-Issues/assets/140616347/86f629ba-b921-427a-a5e8-eab404b27dcb)
![fermier](https://github.com/RivrsMc/SeasonSky-Issues/assets/140616347/3d96deaa-6617-4e8d-b873-fdc1c2495952)
![bucheron](https://github.com/RivrsMc/SeasonSky-Issues/assets/140616347/4cf9b517-00e8-4514-a515-7df1b4643aba)

**Comment by Asherate** [comment]
@Avilo95 tu as pu récupérer tes stats ?

**Comment by Avilo95** [comment]
Non les niveaux dans les skills sont pas bon

**Comment by LuluxClient** [comment]
> Non les niveaux dans les skills sont pas bon

Hello possibilité que tu me listes en clair les niveaux que tu avais avant pour chaque métier

**Comment by Avilo95** [comment]
Alors la je suis incapable de te donner le niveaux des métiers  je peux juste te dire que je suis niveau 73 métiers

**Comment by LuluxClient** [comment]
Tente de me faire une liste avec quelque chose qui donnera au total 73
niveau.

**Comment by Avilo95** [comment]
un niveau dans un metier correspond a un niveau de skyblock ?

**Comment by LuluxClient** [comment]
Non il te donne de l’expérience de niveau skyblock pas un niveau complet

**Comment by Avilo95** [comment]
Je fais comment pour savoir a chaque niveau de skyblock combien d'xp il faut ?

**Comment by LuluxClient** [comment]
Tu dois juste check tes logs si tu avais afficher tes niveaux de métier ou
me dire tu te souvenais d’un peu près quoi

**Comment by Avilo95** [comment]
Je vais te dire a peut près parce que je sais pas pour les logs.
Mineur: 15
Fermier: 14
Chasseur: 17
Bucheron: 8
Forgemage: 12
Aventurier: 12
Alchimiste : 17
Pecheur : 0

**Comment by LuluxClient** [comment]
Ok je m’occupe de toi dans pas longtemps !

**Comment by LuluxClient** [comment]
c'est bon, je t'invite à check en jeu si tu as tout, si tu n'as rien reçu tu dois me ping et je dois refaire la manip lorsque tu es co !

**Comment by Avilo95** [comment]
la manip n'as pas du fonctionner comme j'étais deco

**Comment by NoHere32** [comment]
@LuluxClient
