### ISSUE TITLE
on ne récupère pas les items du boss pirate

### ISSUE THREAD

**Issue by Ryukor0** [RivrsMc/SeasonSky-Issues#226]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Ryukor_

### Pseudo discord

Ryukor

### Que s'est-il passé ?

je n'ai pas reçu les item quand j'ai réussi à taper le boss pirate ( avec les screens si dessous 5 fer et un hopper)

### Étapes à suivre pour reproduire le bug

il faut juste réussir à taper le boss pirate

### Qu'aurait-il dû arriver ?

récupérer les items que le chat nous donne

### Date et heure de la production du bug

26/07 à 18h

### Serveur

sur le /aventure monde pirate 

### Screen / vidéo

![Capture](https://github.com/RivrsMc/SeasonSky-Issues/assets/140638868/95639261-69d9-4f6b-ae75-d3bf2fece868)
![inv](https://github.com/RivrsMc/SeasonSky-Issues/assets/140638868/69d0abb9-1aad-4097-b431-1e6963118acd)

**Comment by NoHere32** [comment]
good
