### ISSUE TITLE
[BUG] MIMIQUE XP ET SAPINETTE XP 

### ISSUE THREAD

**Issue by ePlanete** [RivrsMc/SeasonSky-Issues#227]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Planetee

### Pseudo discord

planete

### Que s'est-il passé ?

Aucun ne donne l'xp bonus des métiers ça commence a faire longtemps en +...

### Étapes à suivre pour reproduire le bug

...

### Qu'aurait-il dû arriver ?

...

### Date et heure de la production du bug

26-07 23:38:22

### Serveur

island-03

### Information supplémentaire

UUID: f68e0a6f-b737-4aaf-87db-969c7b94d535
Position: 3623 245 -12627 SuperiorWorld
Ping: 6ms

**Comment by NoHere32** [comment]
Un boost de jobs s'active seulement au bout de 1 à 2 minutes après avoir été mis en passif. et il fonctionne.
