### ISSUE TITLE
[BUG] dura custom

### ISSUE THREAD

**Issue by Rasyalachaussette** [RivrsMc/SeasonSky-Issues#228]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Rasya_

### Pseudo discord

Rasya_#4498

### Que s'est-il passé ?

La durabilité Custom de l'épée lvl 45 chasseur50 est mal comptée.
Elle compte le nombre de mobs touchés et non les clics.
Il faudrait passer la dura à 1 clics/dura et non les mobs touchés.
Car avec Affilage 5 (Sweeping Edge) trop de monstres sont touchés par coup et l'épée perd entre 50 et 70 dura par coup.

### Étapes à suivre pour reproduire le bug

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de la production du bug

.

### Serveur

.

### Screen / vidéo

.

### Information supplémentaire

.

**Comment by ArDiDEx** [comment]
#92
