### ISSUE TITLE
[BUG] Pet Roi des Pirates

### ISSUE THREAD

**Issue by ePlanete** [RivrsMc/SeasonSky-Issues#229]
### Confirmation

- [x] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Étapes à suivre pour reproduire le bug

bah avoir le pet et taper des monstres

### Qu'aurait-il dû arriver ?

+ d'xp peut être ???

### Date et heure de la production du bug

27-07 00:45:20

### Serveur

Spawn-03

### Screen / vidéo

https://youtu.be/VTP0puj3R60

### Information supplémentaire

UUID: f68e0a6f-b737-4aaf-87db-969c7b94d535
Position: 92 57 -35 Island2
Ping: 10ms

**Comment by NoHere32** [comment]
Un boost de jobs s'active seulement au bout de 1 à 2 minutes après avoir été mis en passif. et il fonctionne.

**Comment by ePlanete** [comment]
> Un boost de jobs s'active seulement au bout de 1 à 2 minutes après avoir été mis en passif. et il fonctionne.

Ce qui est drôle C'EST QUE NON ! Dans quelle langue je dois le dire ??? En anglais ? Sérieux. Non ça ne marche pas, tjs pas après cette mise à jour ? Quand est-ce que vous allez écouter ceux qui joue au jeu ? Dites moi, la j’suis encore gentil mais je commence vraiment à m'énerver en fait
