### ISSUE TITLE
Épée dispawn 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#23]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0iSan 

### Pseudo discord

Nami_san

### Que s'est-il passé ?

En gros quand une personne clique droit avec l'épée sur l'eclozr l'épée disparaît n'importe laquelle.

### Étapes à suivre pour reproduire le bug

Clique droit avec une épée sur l'eclozr

### Qu'aurait-il dû arriver ?

Ne pas faire dispawn l'épée 

### Date et heure de la production du bug

9juillet 1:18

### Serveur

/

**Comment by LuluxClient** [comment]
Cela est fix et tu as été remboursé de ton épée !
