### ISSUE TITLE
Bug récompense boss pirate 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#230]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0isan

### Pseudo discord

Nami_san

### Que s'est-il passé ?

En gros lors du combat avec le boss pirate les gens ne reçoivent pas leurs récompenses hormis les messages comme, iron, hoppe,copper mais rien dans leurs inventaire.
Report en rapport avec 3 tickets ainsi qu'en jeux. 

### Étapes à suivre pour reproduire le bug

Battre le boss avoir des messages de récompenses sans rien recevoir 

### Qu'aurait-il dû arriver ?

Recevoir les récompenses dans l'inventaire. 

### Date et heure de la production du bug

27 juillet 1h11

### Serveur

Global

**Comment by NoHere32** [comment]
good au prochain transfert
