### ISSUE TITLE
[BUG] Canne a Pêche du Pirate

### ISSUE THREAD

**Issue by J7KL** [RivrsMc/SeasonSky-Issues#231]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

J7KL_

### Pseudo discord

J7KL_

### Que s'est-il passé ?

aucun items donné suite a la peche avec la canne a peche du pirate, ça met bien le message dans  le tchat mais ça ne donne pas de récompensse

### Étapes à suivre pour reproduire le bug

pêcher

### Qu'aurait-il dû arriver ?

avoir un loot grace au 10% de chance de drop un trésor

### Date et heure de la production du bug

27-07 09:04:31

### Serveur

island-06

### Information supplémentaire

UUID: 5eb6640e-ac7e-40d1-a01c-0c2cc6ca30ba
Position: -5404 108 -1800 SuperiorWorld
Ping: 13ms

**Comment by NoHere32** [comment]
Après plusieurs test l'effet fonctionne très bien
