### ISSUE TITLE
[BUG] Medusa exp boost

### ISSUE THREAD

**Issue by danphannguyen** [RivrsMc/SeasonSky-Issues#232]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Derlax

### Pseudo discord

Derlax

### Que s'est-il passé ?

Lorsque j'active mon pet medusa de lvl20 je ne reçois aucun boost d'exp contrairement à ce qui est écrit. J'ai vérifier sur l'affichage en haut de la barre de vie ainsi que dans le /jobs, mais je ne reçois pas d'exp supplémentaire.

### Étapes à suivre pour reproduire le bug

Pêcher avec Medusa activer dans la barre des pets

### Qu'aurait-il dû arriver ?

J'aurais du recevoir un boost d'exp pour le métier de pêcheur

### Date et heure de la production du bug

27-07 11:12:48

### Serveur

island-06

### Information supplémentaire

UUID: c6a9fed2-67de-477d-9816-4454388fa0ef
Position: -1781 100 23363 SuperiorWorld
Ping: 9ms

**Comment by NoHere32** [comment]
Les boost d'xp de jobs s'active entre 1minute et 2 minutes après le passage du pets en mode passif.

**Comment by danphannguyen** [comment]
Malheureusement pour revérifier j'ai pêcher pendant une dizaine de minutes, puis vidé mon inventaire et vérifié l'exp reçu. Et aucun boost n'est appliqué dessus, pour une perche je reçois 4.75exp comme une personne n'ayant aucun boost.
