### ISSUE TITLE
[BUG] Medusa pets exp boost

### ISSUE THREAD

**Issue by danphannguyen** [RivrsMc/SeasonSky-Issues#234]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Derlax

### Pseudo discord

Derlax

### Que s'est-il passé ?

Je refait un ticket car je ne reçoit pas le boost de mon pet "Medusa" pour le métier de pêcheur. 

### Étapes à suivre pour reproduire le bug

1. Enlever tout les pets de la barre des pets
2. Activer Medusa dans la barre passive ou de manière active ( peu importe )
3. Pêcher pendant 10min pour être sur que le pet soit activé
4. Vider son inventaire
5. Vérifier le nombre d'exp reçu pour le poisson

### Qu'aurait-il dû arriver ?

J'aurais du recevoir un boost de 20% d'exp ce qui n'est pas le cas. Après avoir effectué la démarche ci-dessus, je pêche une "Perche" et ne reçoit que 4.75exp ce qui équivaut à l'exp reçu sans boost. Pourtant mon pet Medusa est lvl20 et ce qui est étonnant est que les autres effets comme luck sont bien appliqués

### Date et heure de la production du bug

27-07 17:22:11

### Serveur

island-06

### Information supplémentaire

UUID: c6a9fed2-67de-477d-9816-4454388fa0ef
Position: -1780 100 23363 SuperiorWorld
Ping: 8ms

**Comment by NoHere32** [comment]
Les boost de jobs s'active en bout de 1minutes / 2 minutes
