### ISSUE TITLE
[BUG] Pets Luffy speed

### ISSUE THREAD

**Issue by Marsshiii** [RivrsMc/SeasonSky-Issues#235]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Marsshiii

### Pseudo discord

Marsshiii

### Que s'est-il passé ?

Mon pet luffy ne me donne plus Speed sachant qu'il est niveau 10 et que le speed II est déblocable au niveau 5 

### Étapes à suivre pour reproduire le bug

Equiper le pet Luffy 
Le monté level 5 et normalement débloquer speed II 

### Qu'aurait-il dû arriver ?

Débloquer Speed II permanent arpsè le passage du level 5 

### Date et heure de la production du bug

27/07 4h00

### Serveur

SeasonSky

**Comment by NoHere32** [comment]
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/123643370/18c8ddda-931d-450f-9c7b-2aca78660891)
