### ISSUE TITLE
[BUG] silk touch sur les pastèque

### ISSUE THREAD

**Issue by MellowCrib28112** [RivrsMc/SeasonSky-Issues#236]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MellowCrib

### Pseudo discord

MellowCrib28112

### Que s'est-il passé ?

avec silk touch ont n'a pas d'xp métier

### Étapes à suivre pour reproduire le bug

casser une pastèque avec une hache silk touch

### Qu'aurait-il dû arriver ?

avoir de l'xp

### Date et heure de la production du bug

depuis le debut ?

### Serveur

tous je pense

**Comment by NoHere32** [comment]
Ce n'est pas un bug.
