### ISSUE TITLE
Boost métier avec les pets marchent pas

### ISSUE THREAD

**Issue by kingo2389** [RivrsMc/SeasonSky-Issues#238]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

kingo2389

### Pseudo discord

pepito2389

### Que s'est-il passé ?

J’ai équipe deux pets: Pingu et Froussard, je les ai mis au niveau 15 et 5 respectivement pour avoir un boost de 20% sur pingu et 10% sur froussard pour le métier de farmeur sauf que avec et sans les pets je gagne exactement le même exp 

### Étapes à suivre pour reproduire le bug

Équiper les pets puis  casser une culture 
Deséquiper les pets puis casser une culture 

### Qu'aurait-il dû arriver ?

L’exp gagné devrait être plus important avec les pets équipé

### Date et heure de la production du bug

28/07/2023 19h00

### Serveur

Spawn 3

**Comment by LuluxClient** [comment]
Bonjour @kingo2389 est ce que tu as attendu 1m le temps que l'effet se prenne en compte ? si tu peux retester pour moi ? 

Si cela ne fonctionne toujours pas, ton problème est lié à celui ci qui est en cours de fix: https://github.com/RivrsMc/SeasonSky-Issues/issues/211#issuecomment-1657237754
