### ISSUE TITLE
[BUG] Mouton (Meurt tout seul + Tonte + Se stack pas . . .) 

### ISSUE THREAD

**Issue by tcookalex** [RivrsMc/SeasonSky-Issues#239]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Tcookalex

### Pseudo discord

Tcookalex

### Que s'est-il passé ?

Lors de la tonte du mouton (stacker a + 600) le mouton se tonte qu'une seule fois et drop qu'une laine après ça il ne la gagnera plus jamais. Par la suite l'entrée (stacker toujours à +600) meurt tout seul (1 par 1) comme si il subissait un entity craming. De plus, si le mouton est déjà tondu il ne se stack pas avec c'est prédécesseur.

### Étapes à suivre pour reproduire le bug

J’ai tout simplement tondu un mouton qui avait plusieurs stacks. 

### Qu'aurait-il dû arriver ?

Je vous avouerais que je ne sais rien, je ne sais pas si c’est normal comme interaction. d'après ce que l’on ma dit c’est pas normal. 

### Date et heure de la production du bug

19h40, 28/07/2023

### Serveur

island-03

### Screen / vidéo

https://www.veed.io/view/fc63910b-4372-4e06-bc44-989f9f4908ca?panel=share

**Comment by LuluxClient** [comment]
Un fix est en cours pour ce problème de collision et de tonte de mouton

**Comment by LuluxClient** [comment]
Un premier patch a été appliqué, désormais tu recevras toute les laines des moutons stack et ils ne vont plus mourrir
