### ISSUE TITLE
[BUG] Houe du soleil qui ne rapporte pas d'xp fermier

### ISSUE THREAD

**Issue by LLucrece** [RivrsMc/SeasonSky-Issues#24]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Lucrece

### Pseudo discord

Lucrece

### Que s'est-il passé ?

La houe ne donne pas d'xp fermier

### Étapes à suivre pour reproduire le bug

utiliser la houe

### Qu'aurait-il dû arriver ?

on devrait recuperer l'xp

### Date et heure de la production du bug

09/07 à 01h27

### Serveur

serv2

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/135556343/3047d7e9-3f7a-4ea8-a439-44b70469b445)

**Comment by LLucrece** [comment]
Elle ne marche pas non plus pour les quetes 
c'est une houe 1*1 se qui est dommage quand meme

**Comment by LLucrece** [comment]
Elle rapporte désormais l'xp 
mais ne replante plus et ne fait pas les quetes

**Comment by Alex96x2** [comment]
Pour moi elle replante bien, mais pas d'xp ni d'argent gagné

**Comment by Romariin** [comment]
Quand on casse avec ça ne prend pas en compte les quêtes

**Comment by Romariin** [comment]
Quand il reste de la place dans l'inventaire, mais qu'on possède plus de case dispo, les items drop au sol.
https://i.romarin.dev/IcGv.gif

**Comment by itsme-to** [comment]
Pour résumer:
Il ne reste que le fait que ça ne soit pas compté dans les quêtes, le reste fonctionne bien
