### ISSUE TITLE
Soucis avec les chunk et la limite d'enclume et l'entonnoir

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#241]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0iSan

### Pseudo discord

Nami_san

### Que s'est-il passé ?

Alors en rapport avec les entonnoir et les enclume je pense avoir un github dessus mais que je vois plus.
Mais une fois une enclume ou l'entonnoir casser il est toujours compter comme ci il était poser du coup par moment nous ne pouvons plus reposer l'enclume ou l'entonnoir, malgré le spam de /is reclac (je sais plus l'écrire pardon) ou encore le is lvl.
C'est sur pas mal d'is ainsi 

### Étapes à suivre pour reproduire le bug

Poser les enclume ou entonnoir et le casser souvent dans un même chunk 

### Qu'aurait-il dû arriver ?

Ne pas avoir le bug tout en respectant la limite d'enclume par chunk ou entonnoir 

### Date et heure de la production du bug

20h07 28 juillet 

### Serveur

Global

**Comment by LuluxClient** [comment]
C'est lié à notre limite, je pense qu'il y a un scan automatique toute les X temps, peux-tu testé si le bug est toujours présent sur l'île du joueur

**Comment by juste18** [comment]
On m'a dit de faire un report parce que ce problème implique aussi les spawners. Quand on les cassent ceux-ci sont toujours compté dans le is limit. D'après ce que j'ai pu voir le is limit est recalculer au reboot du serv

**Comment by LuluxClient** [comment]
Lorsque tu casses les spawners, tu utilises quoi comme outils ? (enchantement, outils custom ?, effets ?, pets actif ?) Egalement est ce que tu pourrais m'envoyer le message que tu reçois dans ton chat lorsque la limite est atteinte

**Comment by juste18** [comment]
alors j'utilise une pioche effi 4 solidité 3 et silk touch. j'ai 5 pets en passif qui sont boulbi orange,woody marron, boulbi rose, boulbi jaune et terri bleu.
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/44949795/b521788c-9806-496a-b3cf-cbb4ee13aa95)

alors sur l'image y a que 9 spawners ducoup vu que j'en ai cassé plusieurs pour tester.
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/44949795/0230ee97-362e-42c4-89b9-05781744f3d7)

**Comment by LuluxClient** [comment]
Bug fix sauf pour les spawners, il y a déjà un ticket en cours pour celui là
