### ISSUE TITLE
[BUG] Pnj recycleur monde aventure Fleuve secret

### ISSUE THREAD

**Issue by Jspppppp** [RivrsMc/SeasonSky-Issues#242]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Jspppppp

### Pseudo discord

Mathéo#8230 / Jspppppp (l'ours)

### Que s'est-il passé ?

Le pnj recycleur du monde aventure : " Fleuve secret " à disparu.

### Étapes à suivre pour reproduire le bug

1. Être Batisseur 
2. Aller au /aventure " Le fleuve secret " 
3. Voir que le pnj et plus la (sauf sa charette)

### Qu'aurait-il dû arriver ?

Que le pnj sois la. 

### Date et heure de la production du bug

All 

### Serveur

Aventure : " Fleuve secret " 

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139492099/cbe1b96b-c357-4065-b5fe-c66d84a6ab99)

**Comment by LuluxClient** [comment]
Fixed au redem
