### ISSUE TITLE
[BUG] /glow

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#243]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

quand on choisie un glow ca nous donne le violet a chaque fois

### Étapes à suivre pour reproduire le bug

1. avoir un glow ou le premium
2. activé son glow

### Qu'aurait-il dû arriver ?

on devrait avoir le glow de la couleur choisie

### Date et heure de la production du bug

28/07/2023 22:32

### Serveur

all

**Comment by ArDiDEx** [comment]
Hey!
Le bug sera réglé au restart de cette nuit
Merci du report
