### ISSUE TITLE
[BUG] Pnj quête monde aventure

### ISSUE THREAD

**Issue by Isweazu** [RivrsMc/SeasonSky-Issues#244]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Isweazu

### Pseudo discord

xx4040

### Que s'est-il passé ?

Suite ticket, les pnj de quêtes des mondes aventures ne donnent aucune récompenses

### Étapes à suivre pour reproduire le bug

Faire la quête d'un pnj monde aventure, bob, poppy ect..

### Qu'aurait-il dû arriver ?

Avoir une récompense sauf si c'est fais exprès

### Date et heure de la production du bug

00h13 le 29/07

### Serveur

-

**Comment by LuluxClient** [comment]
Je n'ai pas de soucis de mon côté, pourrais-tu tester de ton côté et me dire exactement la quête et le NPC ?

**Comment by LuluxClient** [comment]
Aucune réponse
