### ISSUE TITLE
r

### ISSUE THREAD

**Issue by ePlanete** [RivrsMc/SeasonSky-Issues#245]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un### Étapes à suivre pour reproduire le bug

### Date et heure de la production du bug

29-07 12:21:31

### Serveur

island-03

### Information supplémentaire

UUID: f68e0a6f-b737-4aaf-87db-969c7b94d535
Position: 3618 245 -12632 SuperiorWorld
Ping: 14ms

**Comment by Jspppppp** [comment]
Perso le roi pirate marche, (je gagne 6.14 avec un mob moyen de la zone Fleuve secret sans le pet et 7.98 avec le pet) il faut juste attendre 1 / 2 minutes après l'avoir équiper (le temp que le boost se mette)

**Comment by ePlanete** [comment]
> Perso le roi pirate marche, (je gagne 6.14 avec un mob moyen de la zone Fleuve secret sans le pet et 7.98 avec le pet) il faut juste attendre 1 / 2 minutes après l'avoir équiper (le temp que le boost se mette) 

Pas moi
