### ISSUE TITLE
[BUG] Icône premuim et rangs mals affichés dans le tab

### ISSUE THREAD

**Issue by Founny** [RivrsMc/SeasonSky-Issues#246]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Isaac______

### Pseudo discord

isaac____

### Que s'est-il passé ?

Icône premuim et rangs mals affichés pendant quelques secondes

j'ai croisé cela plusieurs fois depuis le redémarrage de 5h05 (jamais vu avant)

### Étapes à suivre pour reproduire le bug

1. Ouvrir le tab

### Qu'aurait-il dû arriver ?

le caractère japonais adéquat aurait dû être présent dès le départ

### Date et heure de la production du bug

29/07 - ~9h

### Serveur

is-02

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/39631165/359c094c-0930-4bb9-aef5-55bcddea84a2)

**Comment by Founny** [comment]
note: je ne suis pas le seul à l'avoir

**Comment by LuluxClient** [comment]
C'est un bug récurrent et on travail dessus, c'est encore en beta et on travail dessus.

**Comment by LuluxClient** [comment]
Hello @Founny le bug a été corrigé, il faut attendre la maintenance de ajd à 22h30 pour que le patch soit appliqué en prod !
