### ISSUE TITLE
[BUG] Pioche des ombres qui empêche la création de boutiques

### ISSUE THREAD

**Issue by hija621** [RivrsMc/SeasonSky-Issues#247]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Hija621

### Pseudo discord

hija621

### Que s'est-il passé ?

Quand on veut créer une boutique (coffre de vente) avec une pioche des ombres, quand on met le prix dans le t'chat ça nous met impossible de créer cette boutique ici et casse le coffre

### Étapes à suivre pour reproduire le bug

Avoir un pioche des ombres
Cliquer sur un coffre pour creer une boutique
rentrer le prix

### Qu'aurait-il dû arriver ?

Créer la boutique

### Date et heure de la production du bug

29/07 15h

### Serveur

Island

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/135941180/6eaf5f4a-dac9-4de6-9842-59843a3dcc80)

**Comment by LuluxClient** [comment]
Ce n'est pas bug si tu n'as pas la pioche en main lorsque tu mets le prix
