### ISSUE TITLE
queste pirate enchante[BUG] 

### ISSUE THREAD

**Issue by pirateloic003** [RivrsMc/SeasonSky-Issues#248]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Akou58

### Pseudo discord

Akou58

### Que s'est-il passé ?

la queste pirate enchante des objets en or ne fonction pas avec les armures en or 

### Étapes à suivre pour reproduire le bug

Si vous essais avec des armures en or le nombre d'objets enchante n'augmentera pas 

### Qu'aurait-il dû arriver ?

le nombre d'objet enchantes aurais du augmenter 

### Date et heure de la production du bug

19h40

### Serveur

seasonsky

**Comment by LuluxClient** [comment]
Ce n'est pas un bug, la quête est que pour les outils, le message a été modifié, effectif au redem !
