### ISSUE TITLE
Non réception des récompenses lorsqu'on tue le boss pirate [BUG] 

### ISSUE THREAD

**Issue by Sky31921** [RivrsMc/SeasonSky-Issues#249]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Sky31921

### Pseudo discord

Sky_1134

### Que s'est-il passé ?

Lors de la mort du boss, le joueur n'a pas reçu les récompenses que ce dernier offrait. 
- x1 Netherite
- 1500 pièces d'or
- 1000 pièces d'or [3]
- x1 Hopper
- x5 Copper
- x5 Iron

### Étapes à suivre pour reproduire le bug

Tuer le boss pirate 

### Qu'aurait-il dû arriver ?

En temps normal, le joueur aurait dû recevoir les récompenses. 

### Date et heure de la production du bug

Mercredi le 26 Juillet 2023 vers 18h 

### Serveur

Aventure EVENT Pirate

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/140919792/a567afe0-7c38-484b-8047-ca1c5987bbd4)

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/140919792/8befc853-ec7e-4c76-8e22-df87b97091e4)

### Information supplémentaire

Bon courage avec les bugs et merci du taff que vous faites !

**Comment by NoHere32** [comment]
Bug résolu entre la production du bug et le report.
