### ISSUE TITLE
[BUG] Bug affichage classement métier 

### ISSUE THREAD

**Issue by Amateur2Drapeau** [RivrsMc/SeasonSky-Issues#25]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MaelEnFrance

### Pseudo discord

maelenfrance

### Que s'est-il passé ?

Pour mon ami le classement personnel est affiché en négatif, et le nombre total de joueur n'est pas le même pour nous deux

### Étapes à suivre pour reproduire le bug

Ouvrir le classement pêcheur (je n'ai pas testé avec les autres)

### Qu'aurait-il dû arriver ?

Le classement aurait dû bien s'afficher 

### Date et heure de la production du bug

09-07 01:44:25

### Serveur

island-06

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/120582644/c2f7b9df-aeca-4871-9f53-5e8c57397866)
![imagke](https://github.com/RivrsMc/SeasonSky-Issues/assets/120582644/d926c724-4a5a-4e94-a46c-6a17c99aefce)

### Information supplémentaire

UUID: ccf4c91d-a9da-442e-94df-2a03f6b3cb1a
Position: 5400 38 -3608 SuperiorWorld
Ping: 13ms

**Comment by LuluxClient** [comment]
Un fix arrivera très prochainement, cela est qu'un bug visuel.

**Comment by itsme-to** [comment]
Normalement a été fixé
