### ISSUE TITLE
[BUG] Bug pet replantation

### ISSUE THREAD

**Issue by Isweazu** [RivrsMc/SeasonSky-Issues#250]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Isweazu

### Pseudo discord

xx4040

### Que s'est-il passé ?

Suite ticket :  les pets lvl 20 froussard gribouille et pingu ( ceux qui replante lvl 20) ne replante pas toujours tout , tout a lheure je recoltais mon blé tout etais poussé et des fois de temps en temps ca ne replante pas meme en allant doucement

### Étapes à suivre pour reproduire le bug

Avoir l'un de ses pets levels 20 et utiliser la compétence qui replante auto les ressources

### Qu'aurait-il dû arriver ?

Ne pas avoir de soucis et que ça replante tout

### Date et heure de la production du bug

22h59 le 29/07

### Serveur

island 04

**Comment by LuluxClient** [comment]
Toujours d'actu @Isweazu ?

**Comment by LuluxClient** [comment]
Aucun soucis de mon côté
