### ISSUE TITLE
Retour du bug sur le pet mimique

### ISSUE THREAD

**Issue by DeadPour2Vrai** [RivrsMc/SeasonSky-Issues#251]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

dead140 / iDead_

### Pseudo discord

deadpour2vrai

### Que s'est-il passé ?

Bonsoir, comme à mon habitude je me suis co pour farm mon métier de mineur avec le pet mimique et j'ai constaté que le +20% du métier de mineur était de retour.

### Étapes à suivre pour reproduire le bug

Avoir un pet mimique

### Qu'aurait-il dû arriver ?

Le boost de 20% devrait être actif

### Date et heure de la production du bug

03H25

### Serveur

island-02

**Comment by LuluxClient** [comment]
Hello je n'ai pas le problème, assure toi de déco reco en ayant le pets activé
