### ISSUE TITLE
[BUG] Glitch EnderPearl

### ISSUE THREAD

**Issue by StoyDris** [RivrsMc/SeasonSky-Issues#252]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

StoyDris

### Pseudo discord

Std_S

### Que s'est-il passé ?

*Contexte* J'étais en train d'essayer d'adopter une endermite lorsque je me suis rappelé du bug vanilla qui consiste en jeter une enderpearl pixel perfect dans un bloc de verre, pour rentré dans celui-ci. J'ai testé et j'ai réussi.

### Étapes à suivre pour reproduire le bug

1. Prendre une ender pearl
2. Viser le coin précis d'un bloc de verre (ou plusieurs)
3. Lancer l'ender pearl jusqu'à ce que l'on sois tp dans le block de verre

### Qu'aurait-il dû arriver ?

Juste téléporter devant le block de verre à chaque fois.

### Date et heure de la production du bug

30-07 21:02:40

### Serveur

island-04

### Screen / vidéo

https://i.imgur.com/E92n2HU.png 
ou (la même image)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/140977280/d8da773d-29fb-46df-af02-d33b6df25bd9)

### Information supplémentaire

UUID: 43e6cbb2-918e-4ff5-9fd6-d093c95ba80e
Position: 5387 100 8992 SuperiorWorld
Ping: 14ms

**Comment by LuluxClient** [comment]
Mécanique vanilla, ceci ne sera pas fix
