### ISSUE TITLE
[BUG] Effet du Pet Medusa

### ISSUE THREAD

**Issue by danphannguyen** [RivrsMc/SeasonSky-Issues#253]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Derlax

### Pseudo discord

Derlax

### Que s'est-il passé ?

Pour le 3e report de bug que je fais, je vais décrire plus précisément ce bug.

Lors de l'activation en mode "Passif" du pets "Medusa" je ne reçois aucun boost d'exp. Et cela même après plusieurs heures d'activation.

### Étapes à suivre pour reproduire le bug

1/ Equiper le pets "Medusa"
2/ Pêcher 
3/ Regarder le nombre d'exp obtenu

### Qu'aurait-il dû arriver ?

J'aurais du recevoir un boost d'exp ce qui n'est pas le cas

### Date et heure de la production du bug

31 Juillet 14h53

### Serveur

Island-06

### Screen / vidéo

https://github.com/RivrsMc/SeasonSky-Issues/assets/77532827/67467c28-56c6-4304-b37a-de9d1478decc

### Information supplémentaire

Je me répètes, mais attendre 1 à 3min comme on m'a conseillé lors des deux derniers tickets que j'ai fais, ne règles en rien le bug

**Comment by ePlanete** [comment]
En gros quand tu fais /jobs, l'xp est calculé en fonction des passifs actifs, donc du pets, d'un pouvoir activé ou quoi. 

Donc ne tqt pas. J'ai le Medusa et il marche bien. Regarde après 1 / 3 minutes si en pêchant une coquille de Nautile tu obtiens 71.XX xp

**Comment by NoHere32** [comment]
Sans le pets
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/123643370/0a7c6b6f-9cd5-4caf-b02c-a1e7186d0def)

Avec le pets
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/123643370/349a39f9-553b-4bff-8b3b-1e184a825075)

**Comment by danphannguyen** [comment]
Ok bah j'ai bien les effets alors x), Merci beaucoup
