### ISSUE TITLE
[BUG] bug de durabilité de "l'épée du pirate" du coffre festival

### ISSUE THREAD

**Issue by KoganeSama** [RivrsMc/SeasonSky-Issues#254]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Son_Gohan_Sama

### Pseudo discord

KoganeSama

### Que s'est-il passé ?

après avoir farmé plusieurs mobs du canyon ,j'ai remarqué que ma durabilité de mon épée ne baissé pas.
mais peut-être que la rareté de l'épée est fais exprès ou non je poste cela ou cas ou

### Étapes à suivre pour reproduire le bug

avoir l'épée 

### Qu'aurait-il dû arriver ?

perdre de la durabilité je penses

### Date et heure de la production du bug

21h30

### Serveur

seasonsky 05

### Screen / vidéo

https://outplayed.tv/media/gRe8BB

**Comment by ePlanete** [comment]
Toi t'es le genre de mec qui dit au prof qu'il a oublié l'interro du jour

**Comment by juste18** [comment]
Il a raison, ça s'appelle un bug. Et c'est pile l'endroit où on report ce genre de problème

**Comment by LuluxClient** [comment]
@ArDiDEx Il faudrait add le support tu protection-test à l'effet boostXP

**Comment by ArDiDEx** [comment]
> @ArDiDEx Il faudrait add le support tu protection-test à l'effet boostXP

tous les effets l'ont par défaut (sauf un ou deux mais c'est des exceptions)

**Comment by ArDiDEx** [comment]
Hey
Le fix pour ça sera mis d'ici quelque jours
Merci du report
