### ISSUE TITLE
[BUG] Pas de changement de saison comme annoncer au début

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#255]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

On a changer de mois mais les interfaces n'ont pas changer et le shop n'a pas changer non plus

### Étapes à suivre pour reproduire le bug

1. fait /caldendar ou /shop

### Qu'aurait-il dû arriver ?

les interfaces aurait du passer en mode automne et le shop aurai du changer

### Date et heure de la production du bug

01/08/2023

### Serveur

all

**Comment by NoHere32** [comment]
Passage aujourd'hui.
