### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by StoyDris** [RivrsMc/SeasonSky-Issues#256]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

StoyDris

### Pseudo discord

Std_S

### Que s'est-il passé ?

*Contexte* Je triais mes coffres et mettais des items frames et en mettant une pioche des profondeurs dans une item frame je me suis redu compte qu'elle était mal scale / cadrée, elle devient énorme et dépasse largement de l'item frame.
Je ne sais pas si je doit vraiment faire une report pour cela mais je ne vois pas comment le signaler autrement.

### Étapes à suivre pour reproduire le bug

Prendre une pioche des profondeurs puis la mettre dans une item frame.

### Qu'aurait-il dû arriver ?

La pioche des profondeurs devrait se mettre normalement à la même taille que les autres items, sans dépasser l'item frame.

### Date et heure de la production du bug

01-08 14:15:42

### Serveur

island-04

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/140977280/c5cd795f-1490-45a8-ae42-93452f0393a2)

### Information supplémentaire

UUID: 43e6cbb2-918e-4ff5-9fd6-d093c95ba80e
Position: 5380 99 9000 SuperiorWorld
Ping: 15ms

**Comment by StoyDris** [comment]
pareil avec la pioche des ombres dcp

**Comment by ePlanete** [comment]
Et avec la pelle pirate

**Comment by NoHere32** [comment]
Patch dans la journée.
