### ISSUE TITLE
[BUG] Spawner limit 

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#257]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

Si on casse un spawner on ne peut pas reposer un spawner dans le chunk meme apres un /is recalc

### Étapes à suivre pour reproduire le bug

1. avoir un spawner
2. le poser dans un chunk ou il y a 11 dans un chunk => arriver à 12 qui est la limite
3. le casser
4. en reposer un autre et avoir un message pour dire qu'il y en a deja 12 dans le chunk

### Qu'aurait-il dû arriver ?

on aurai du pouvoir en reposer un pour de nouveau arriver a la limite qui est de 12

### Date et heure de la production du bug

01/08/2023 17:57

### Serveur

island 02

**Comment by juste18** [comment]
Déjà remonter dans un autre report

**Comment by LupusArctos4** [comment]
J'ai pas vu étant donner que c'est pas écrit dans les titres donc je ne peux point le deviner

**Comment by LuluxClient** [comment]
Un fix est en cours, c'est causé par une maj d'optimisation de notre plugin de stacker

**Comment by LuluxClient** [comment]
Fixed
