### ISSUE TITLE
[BUG] Item évolutif

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#258]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

les items évolutif n'évoluent pas

### Étapes à suivre pour reproduire le bug

1. avoir un item évolutif obtenu dans le BL de 19h
2. l'item n'évolue pas quand on passe les palliers mais ca change le nombre des palliers

### Qu'aurait-il dû arriver ?

les items aurait du évoluer

### Date et heure de la production du bug

01/08/2023 17:57

### Serveur

island 02

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/1e2f19cf-73c7-4af0-9f44-656b84ac501f)

**Comment by LuluxClient** [comment]
Uniquement le lore est update @ArDiDEx et non le name et l'effet et les enchantements

**Comment by ArDiDEx** [comment]
Hey, le bug devrait être fix avec le restart de cette nuit (les items déjà existant ne s'actualiseront niveau enchant et nom que au prochain level up malheureusement)
@LuluxClient tu pourras mettre renew sur les items evo bug lundi si tu es sur season?

**Comment by LupusArctos4** [comment]
Entre temps on a eu un autre ite evo (la pioche) et son level up a bien marcher mais du coup il nous reste la houe evo montée deja lvl max donc pas possible de la rendre fonctionnelle

**Comment by LuluxClient** [comment]
Fixed au redem
