### ISSUE TITLE
[BUG] l'event farm

### ISSUE THREAD

**Issue by MrYouchie** [RivrsMc/SeasonSky-Issues#259]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MrYouchie

### Pseudo discord

mryouchie

### Que s'est-il passé ?

Bonsoir pour l'event farm j'ai l'abonnement Premium  quand je recevoir les récompenses je reçois que celle de l'abonnement et pas celle de base

### Étapes à suivre pour reproduire le bug

Quand je clique sur récupérer la récompense je en reçois qu'une

### Qu'aurait-il dû arriver ?

recevoir les 2 récompenses

### Date et heure de la production du bug

depuis le début de l'évent farm 

### Serveur

Seasonsky

### Screen / vidéo

![2023-08-01_18 55 51](https://github.com/RivrsMc/SeasonSky-Issues/assets/141180838/85dbbd65-01bb-45e0-abeb-51d12d5451b2)
![2023-08-01_18 55 53](https://github.com/RivrsMc/SeasonSky-Issues/assets/141180838/86009635-a9ad-4969-95e0-f1bc48929168)

### Information supplémentaire

Si vous voulez pour d'info je peux faire une preuve vidéo sur ma prochaine récompense 
Merci

**Comment by LuluxClient** [comment]
Hello @MrYouchie normalement ceci est fix si tu peux check si ton bug est tjr d'actu !
