### ISSUE TITLE
[BUG] Seau infini devient vide

### ISSUE THREAD

**Issue by Amateur2Drapeau** [RivrsMc/SeasonSky-Issues#26]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MaelEnFrance

### Pseudo discord

maelenfrance

### Que s'est-il passé ?

Signalement du joueur : "Bonjour, je suis passé niveau 12 en fermier et j'ai donc récupérer le sceau d'eau infini. Pour le tester j'ai voulu mettre de l'eau sur le sol mais j'avais oublié que le sol était fait de dalle, quand j'ai fait clique droit, puis la dalle est devenue waterlogged mais mon sceau infini s'est transformé en sceau d'eau vide normale. "

### Étapes à suivre pour reproduire le bug

Utiliser le seau sur une dalle

### Qu'aurait-il dû arriver ?

Le seau aurait dû rester plein

### Date et heure de la production du bug

x

### Serveur

x

### Screen / vidéo

Aucun le joueur n'en a pas

**Comment by ArDiDEx** [comment]
Hello! Ça devrait désormais être fix
Peux-tu réessayer ?
