### ISSUE TITLE
[BUG] Quest

### ISSUE THREAD

**Issue by LesOrigines** [RivrsMc/SeasonSky-Issues#260]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

L3sOr1g1n

### Pseudo discord

LesOrigines

### Que s'est-il passé ?

https://clips.twitch.tv/DeterminedShortHyenaPoooound-eqDU7BcY7UNBROXF

### Étapes à suivre pour reproduire le bug

Finir une quest.

### Qu'aurait-il dû arriver ?

J'aurait du avoir minimun 25k 

### Date et heure de la production du bug

02-08 17:18:47

### Serveur

island-02

### Information supplémentaire

UUID: 9130a323-d00c-4599-8f23-566e50e9574e
Position: 1806 242 -5384 SuperiorWorld
Ping: 12ms

**Comment by LuluxClient** [comment]
Fixed
