### ISSUE TITLE
[BUG] Pet Draco

### ISSUE THREAD

**Issue by NiamoR320** [RivrsMc/SeasonSky-Issues#261]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

NiamoR320

### Pseudo discord

NiamoR

### Que s'est-il passé ?

J'ai essayer mon pet Draco lvl 5 qui es sensé nous donner + 20 % d'xp du métier fermier mais cela ne fonctionne pas quand il es activer 

### Étapes à suivre pour reproduire le bug

1. Faire sortir le pet
2. Casser une récolte
3. regarder l'xp donner 0.24

1. Sans pet
2. casser une récolte
3. regarder l'xp donné  0.24
4. 

### Qu'aurait-il dû arriver ?

Multiplier les 0.24 par 20%

### Date et heure de la production du bug

02-08 17:31:25

### Serveur

island-02

### Information supplémentaire

UUID: 317d8762-6cac-4294-80b9-284a8cfc1de9
Position: 5393 100 9005 SuperiorWorld
Ping: 16ms

**Comment by ePlanete** [comment]
Moi il marche, essaye avec du cacao c'est censé te donner 0,4x. 
Sache que l'effet du pets (l'activation comme la désactivation) mets 1 à 3 minutes avant de s'appliquer.
