### ISSUE TITLE
[BUG] Bug visuel drop box premium

### ISSUE THREAD

**Issue by Isweazu** [RivrsMc/SeasonSky-Issues#262]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Isweazu

### Pseudo discord

xx4040

### Que s'est-il passé ?

Une fois ouverte la box premium, j'ai gagné des quetes experte x2, dans le tchat ça indique x3

### Étapes à suivre pour reproduire le bug

Ouvirr une box et drop des quêtes experte

### Qu'aurait-il dû arriver ?

Un visuel sans fail :x

### Date et heure de la production du bug

18h07 le 02/08

### Serveur

spawn1

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/138036771/fb0d5fe2-e606-439d-ab47-888b67f97b54)

**Comment by itsme-to** [comment]
Effectif au prochain redémarrage
