### ISSUE TITLE
[BUG] Bug /pass

### ISSUE THREAD

**Issue by Isweazu** [RivrsMc/SeasonSky-Issues#263]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Isweazu

### Pseudo discord

xx4040

### Que s'est-il passé ?

Même sans avoir le premium, on peut avoir les 2 récompenses, normale/premium

### Étapes à suivre pour reproduire le bug

Passer un palier /farm et récup la récompense

### Qu'aurait-il dû arriver ?

Avoir que la récompense normale et pas la premium avec

### Date et heure de la production du bug

18h35 le 02/08

### Serveur

Island 2

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/138036771/74da943a-9112-494a-a65b-8b2c0dc90faa)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/138036771/137c8b47-c80c-4e65-a8a1-5275b6d3ac49)

**Comment by Founny** [comment]
J'ai eu le problème jusqu'au palier 4 je crois (après qu'il ait été censé être patch) mais pour le palier 5 et 6 tout a été bon
