### ISSUE TITLE
[BUG] Paramètres d'iles

### ISSUE THREAD

**Issue by Joordaan420** [RivrsMc/SeasonSky-Issues#264]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Joordaan420

### Pseudo discord

Jordan420

### Que s'est-il passé ?

Quand on active le paramètre pvp de notre is le pvp ne s'active pas 

### Étapes à suivre pour reproduire le bug

Aller dans les paramètre de l'is
Activer le pvp

### Qu'aurait-il dû arriver ?

Quand tu l'active on devrait pouvoir se taper

### Date et heure de la production du bug

00H00 01/08/23

### Serveur

Island_01

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/83576396/4f5f205c-03d9-4d07-9ad5-941d54b7be25)
![ad](https://github.com/RivrsMc/SeasonSky-Issues/assets/83576396/7116c828-a95f-4b1c-8d48-057cf5e01796)

**Comment by NoHere32** [comment]
Hello, le pvp ne sera pas activé sur les île désolé, Ce paramètre sera retiré du menu bientôt.
