### ISSUE TITLE
[BUG] Description item Box Premium

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#265]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

il y a un problème dans les descriptions des items suivant : 
- Clé Cosmétique
- Mission experte
- Ailes de mante religieuse 
- Couleur de chat jaune

### Étapes à suivre pour reproduire le bug

1. faire /abo
2. aller dans lootbox premium
3. regarder les descriptions des items

### Qu'aurait-il dû arriver ?

il ne devrait pas y avoir de problème de code couleur dans les descriptions des items

### Date et heure de la production du bug

02/08/2023

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/24a47d9b-e97a-4279-9e15-2be4234db8aa)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/9d844e0c-5c2c-44a6-8c95-5b21240c479d)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/414ccea6-633e-4800-b9b7-573b05ac6731)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/39a6bbc6-4ddc-4863-91c6-2b086b19d773)

**Comment by itsme-to** [comment]
Effectif au prochain redémarrage
