### ISSUE TITLE
Ticket > Bug récompense 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#266]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0iSan

### Pseudo discord

Nami_san

### Que s'est-il passé ?

En gros lors de la récupération du pallier 2 dans le /pass
Le premium tu es censé récupérer 2 œufs de Pets
Pour les personnes sans grade 1 œuf de pet
Hors lors de récupération du pallier la personne elle reçoit 3 œuf de pets même sans le grade premium

### Étapes à suivre pour reproduire le bug

Passer le pallier 2 récupérer la récompense sans le grade premium. 

### Qu'aurait-il dû arriver ?

Recevoir uniquement un œuf au lieu de 3

### Date et heure de la production du bug

11h32/3 août 

### Serveur

Global 

### Screen / vidéo

![Screenshot_20230803_112644_com discord](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/43545e30-62b8-4c67-9a09-e6f34dd38fb1)

**Comment by LuluxClient** [comment]
Fixed
