### ISSUE TITLE
[BUG] Interface encore en mode été

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#267]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

Problème dans l'interface :
- profil
- shop
qui sont en mode été toujours

### Étapes à suivre pour reproduire le bug

1. faire /shop ou /profil
2. et voir qu'il sont toujours en mode été

### Qu'aurait-il dû arriver ?

il aurait du etre en mode automne comme les autres

### Date et heure de la production du bug

03/08/2023

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/260ec820-fe51-468f-b82e-950247e356b1)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/aee4a21f-24c0-4d61-b114-f7f0c33435c6)

**Comment by ArDiDEx** [comment]
Le shop devrait être bon, le profil devra être changé par @Acterax
