### ISSUE TITLE
[BUG] Caisse Fôret Premium

### ISSUE THREAD

**Issue by stephane2000** [RivrsMc/SeasonSky-Issues#269]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

stephane2000

### Pseudo discord

stephane2000

### Que s'est-il passé ?

Il y a une Caisse Fôret Premium aux coordonnées 3 -24 -9 dans la Forêt Mystique

### Étapes à suivre pour reproduire le bug

Aller aux coordonnées et ouvrir la box

### Qu'aurait-il dû arriver ?

Ne pas y a voir de box

### Date et heure de la production du bug

13h30 04/08

### Serveur

Fôret Mystique, sur tout les spawns ducoup

### Screen / vidéo

/

### Information supplémentaire

/

**Comment by LuluxClient** [comment]
Fixed
