### ISSUE TITLE
[BUG] Cuivre oxyded waxed

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#270]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

les blocks de cuivre oxydé et waxed sont des block du spawn
d'apres le patch note https://discord.com/channels/733323948225462333/825719156346322954/1130818775067926630 (18 juillet 2023) le cuivre a été ajouter et les honey comb 

### Étapes à suivre pour reproduire le bug

1. acheter des honey comb, et des escaliers ou demi dalles
2. les waxed

### Qu'aurait-il dû arriver ?

rendre l'oxydation naturelle impossible et par la meme occasion enlever les honey comb du shop

### Date et heure de la production du bug

04/08/2023 13:47

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/a77c66d5-624b-403e-b3f3-b6157f911304)

**Comment by ArDiDEx** [comment]
Hey!

L'oxydation sera désactiver sur les escaliers et demi dalle dés le prochain restart
Je laisse @NoHere32 voir si il veut enlever les honey comb ou non

Merci du report

**Comment by LupusArctos4** [comment]
niquel merci

**Comment by NoHere32** [comment]
Hello, les honeycomb c'est fait exprès qu'ils soit au shop car non obtenable dans tout les cas le cirage des blocs est désactivé

**Comment by LupusArctos4** [comment]
le cirage est désactivé mais actuellement possible

**Comment by NoHere32** [comment]
sur les escalier et dalle juste ?

**Comment by LupusArctos4** [comment]
non sur tout les blocs on peutle faire actuellement

**Comment by NoHere32** [comment]
le patch arrive au redem si j'ai bien suivis ma discussion avec ardidex.

**Comment by LupusArctos4** [comment]
oui apres si tu désactive le cirage c'est good parce que la actuellement on peut avoir des blocs du spawn
