### ISSUE TITLE
Bug ticket pets

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#271]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0isan 

### Pseudo discord

Nami_san

### Que s'est-il passé ?

Alors le pets Spectralis niveau 10 est censé revendre les items 20% de plus que le shop hors même après l'avoir monter un lvl plus haut le pets ne fonctionne pas du tout en tout cas le bonus

### Étapes à suivre pour reproduire le bug

Monter le Spectralis niveau 10 ou 11 essayer de revendre les items afin que cela fonctionne. 

### Qu'aurait-il dû arriver ?

Revendre les items 20% de plus 

### Date et heure de la production du bug

4/08 15h03

### Serveur

Global

### Screen / vidéo

![2023-08-02_21 32 53](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/2eea6803-bb7e-4665-8ebf-cffe0c07a823)
![2023-08-02_21 38 29](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/b5946c9e-0be8-4938-a23e-7555532f319a)
![Uploading 2023-08-02_21.38.32.png…]()

**Comment by Asherate** [comment]
Fix au prochain merge :)
