### ISSUE TITLE
[BUG] Grappin

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#272]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

Le grappin du jobs forge mage ne fonctionne pas dans les dimensions comparer au grappin pirate

### Étapes à suivre pour reproduire le bug

1. avoir les 2 grappins
2. tester les 2 dans les dimensions

### Qu'aurait-il dû arriver ?

le grappin classique devrait marcher dans les monde aventure

### Date et heure de la production du bug

04/08/2023 15:40

### Serveur

island 02

**Comment by LuluxClient** [comment]
Uniquement le grappin pirate fonctionne dans toute les dimensions
