### ISSUE TITLE
Ticket trou map aventure 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#273]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0isan 

### Pseudo discord

Nami_san

### Que s'est-il passé ?

Il y a juste un trou dans le monde aventure des castors

Voici les coordonnées en question
-26 -27 -38

### Étapes à suivre pour reproduire le bug

/

### Qu'aurait-il dû arriver ?

/

### Date et heure de la production du bug

4/08 20h50

### Serveur

Global

### Screen / vidéo

![Screenshot_20230804_202645_com discord](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/d342f514-0a56-4a5d-b76c-1d5bbb9c033e)

**Comment by LuluxClient** [comment]
Fixed
