### ISSUE TITLE
Bug ticket > Farm Contest 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#274]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0isan 

### Pseudo discord

Nami_san

### Que s'est-il passé ?

Alors certaines en tout cas pas mal de personne lors du concours de Farm, il ne gagne pas du tout de point même en cassant à la main ou encore avec quelconque outils. 

LULUX EDIT:
- Le soucis provient d'un message indiquant que l'event farm est lancé alors que non

### Étapes à suivre pour reproduire le bug

Farm pendant le concours regarder les points monter (score) 

### Qu'aurait-il dû arriver ?

Voir le score monter au fur et à mesure du concours. 

### Date et heure de la production du bug

5 Août / 00h54

### Serveur

Global mais plus souvent du côté de l'is 1 et 4

**Comment by LuluxClient** [comment]
Aucun soucis de mon côté, le bug n'est pas un problème de comptabilisation mais un pb de message qui indique que l'event a démarré alors que non

**Comment by LuluxClient** [comment]
Un pêtit patch a été appliqué pour éviter ce message trompeur. @Kalouchette si tu traines ici il faudrait faire gaff avec l'option "delay" qu'il n'envoie pas le message "messages.currently-running" pendant le countdown et qu'il envoie le "messages.announcement"
