### ISSUE TITLE
[BUG] Mobs bugué dimensions Zombieland comme en v3

### ISSUE THREAD

**Issue by LLucrece** [RivrsMc/SeasonSky-Issues#275]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

lucrece

### Pseudo discord

Lucrece

### Que s'est-il passé ?

en farmant dans la dimension zombieland, des mobs se mettent à buggué, ils n'ont plus de hitbox et ils  ne bougent plus
comme en v3
alors que se n'est pas le cas pour les autre dimensions

### Étapes à suivre pour reproduire le bug

farmer et faire charger/décharger les chunks

### Qu'aurait-il dû arriver ?

les mobs ne devrait pas bugués

### Date et heure de la production du bug

05-08 16:08:41

### Serveur

Spawn-02

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/135556343/ba0855c6-2d94-4245-aba9-2388b6847aad)

### Information supplémentaire

UUID: 66a43a59-81b5-4ac7-923a-67ba4e9e1d9d
Position: 13 -17 -19 Island3
Ping: 31ms

**Comment by LLucrece** [comment]
c'est uniquement client

**Comment by LuluxClient** [comment]
Bug minecraft, ceci a été fix en 1.20.2 également mais l'update sera fait dans assez longtemps
