### ISSUE TITLE
[BUG] Houe du fermier fou

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#276]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

L'action de la houe ne correspond pas au lore de la houe car vous avez fait un retour en arrière par rapport à la début du serveur

### Étapes à suivre pour reproduire le bug

1. monter lvl 45 fermier

### Qu'aurait-il dû arriver ?

elle devrait etre comme la houe royale ou pirate c'est a dire casser et replanter automatiquement comme le lore

### Date et heure de la production du bug

05/08/2023 19:43

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/349104ae-84fc-4c3e-90ea-89544eec44e7)

**Comment by LuluxClient** [comment]
Fixed dès la prochaine maj
