### ISSUE TITLE
[BUG] Glow Cyan

### ISSUE THREAD

**Issue by Perine66** [RivrsMc/SeasonSky-Issues#277]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

NegaPi_

### Pseudo discord

negapi_

### Que s'est-il passé ?

Le Glow Cyan ne se met pas quand on veut l'utilisé

### Étapes à suivre pour reproduire le bug

/glow puis cliquer sur la couleur cyan

### Qu'aurait-il dû arriver ?

Le glow couleur cyan devrait se mettre autour du personnage

### Date et heure de la production du bug

05/08/23 21:07

### Serveur

Island 06

**Comment by LuluxClient** [comment]
aucun soucis de mon côté en dev et prod, je t'invite à retirer tes shaders si tu en as !

**Comment by Perine66** [comment]
Je n'ai aucun shaders et je viens de retester je ne le vois pas sur moi

**Comment by LuluxClient** [comment]
> Je n'ai aucun shaders et je viens de retester je ne le vois pas sur moi

es-tu dispo voc pour voir ça ensemble ?

**Comment by Perine66** [comment]
oui je suis dispo

**Comment by LuluxClient** [comment]
> oui je suis dispo

Go dans attente d'aide

**Comment by Perine66** [comment]
voila

**Comment by LuluxClient** [comment]
Fixed
