### ISSUE TITLE
[BUG] Pioche Du Pirate

### ISSUE THREAD

**Issue by Spam0000** [RivrsMc/SeasonSky-Issues#278]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Twitch_Spam

### Pseudo discord

Spam9999

### Que s'est-il passé ?

La pioche du Pirate vas moin vite que la pioche royal alors qu'elle a un niveau de différence 

Pioche Royale Efi 6
Pioche du pirate Efi 7 

### Étapes à suivre pour reproduire le bug

Tester les deux pioche 

### Qu'aurait-il dû arriver ?

Que la pioche du pirate marche mieux que la pioche Royale

### Date et heure de la production du bug

06/08/2023

### Serveur

Island-02 

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/57216670/d9cdeba0-bc5c-4c69-afe3-5ea28b684659)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/57216670/37e6f787-9e70-4e65-8a4e-d99c650c048e)

**Comment by LuluxClient** [comment]
Ce que tu vois c'est les stats du matériau de l'item et non de ses enchantements comme efficacité
