### ISSUE TITLE
[BUG] du /collection

### ISSUE THREAD

**Issue by Bellanny** [RivrsMc/SeasonSky-Issues#279]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Bienou

### Pseudo discord

Bellanny

### Que s'est-il passé ?

Au moment de mettre des items dans la collection avec le /collection, je ne pouvais rien faire comme cliquer sur les différente catégories afin de voir ce que j'avais déjà. Et dans le nom déjà en place j'avais ?/?. J'étais bien sur mon île au moment de le faire (islande 3). Mon soucis c'est produit le 5 aout mais aussi le 6 aout

### Étapes à suivre pour reproduire le bug

faire /collection et quand on veut afficher un clic gauche

### Qu'aurait-il dû arriver ?

l'ouverture des catégories, l'ajout des items et l'affichage

### Date et heure de la production du bug

06-08 15:16:51

### Serveur

island-03

### Screen / vidéo

https://github.com/RivrsMc/SeasonSky-Issues/assets/49778895/d2cf3b59-30b7-48ee-b37d-00655efaa9c6

### Information supplémentaire

UUID: 907f148a-1154-4359-99cd-9f757407b16c
Position: -3631 281 3469 SuperiorWorld
Ping: 13ms

**Comment by LuluxClient** [comment]
PEtit bug de refresh, si tu réouvres le menu cela ne devrait pas se reproduire

**Comment by Bellanny** [comment]
Bonjour après avoir mit des items en collections et n'ayant pas tous les items j'ai voulu rajouter les autres, je n'ai pas accès aux différents items dans les menus du /collections (voir vidéo) (cette fois je suis sur mon personnage principal)

https://github.com/RivrsMc/SeasonSky-Issues/assets/49778895/b1b94ca6-fbe3-499e-a4a3-bb67f9de1459
