### ISSUE TITLE
[BUG] Le shop de block de verrues du nether dirige vers les algues séchés

### ISSUE THREAD

**Issue by Amateur2Drapeau** [RivrsMc/SeasonSky-Issues#28]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MaelEnFrance

### Pseudo discord

maelenfrance

### Que s'est-il passé ?

Lorsqu'on veut vendre des blocks de verrues du nether cela ouvre le menu des algues séchés

### Étapes à suivre pour reproduire le bug

Ouvrir le shop des blocks de verrues du nether

### Qu'aurait-il dû arriver ?

Ouvrir le shop du block de verrue du nether

### Date et heure de la production du bug

x

### Serveur

x

### Information supplémentaire

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/120582644/2faa3c4c-a9f8-4790-9468-f6ed3b164d74)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/120582644/1cd40983-fd1d-4e34-8ee4-e6a8d6991ca2)

**Comment by NoHere32** [comment]
good au prochain redem
