### ISSUE TITLE
[BUG] Druste amé toucher de sois

### ISSUE THREAD

**Issue by Jspppppp** [RivrsMc/SeasonSky-Issues#281]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Jspppppp

### Pseudo discord

Mathéo#8230

### Que s'est-il passé ?

J'ai cassé une druste améthyste avec TOUCHER DE SOIS et je ne l'es pas récup. (Confirmation de Stephane que c'est pas normal)

### Étapes à suivre pour reproduire le bug

1. Avoir 500 k et une pioche toucher de sois 
2. Faire /shop
3. Acheter une drust amé, dans la cathé minerais
4. La poser
5. La casser avec tds 
6. Ne pas récup

### Qu'aurait-il dû arriver ?

Récup la drust avec la pioche tds 

### Date et heure de la production du bug

Tout le temp

### Serveur

Island

**Comment by Asherate** [comment]
Hello, stéphane à du se tromper 
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/131485092/c918f09e-3a40-47e9-8118-409630da53fe)

**Comment by Jspppppp** [comment]
En V3 on pouvais donc non c'est pas normal ^^

**Comment by Jspppppp** [comment]
Fin je suposse dcp
