### ISSUE TITLE
[BUG] Texture totem

### ISSUE THREAD

**Issue by Jspppppp** [RivrsMc/SeasonSky-Issues#282]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Jspppppp

### Pseudo discord

Mathéo#8230

### Que s'est-il passé ?

Le totem d'immortalité a la texture d'un des nouveaux pets

### Étapes à suivre pour reproduire le bug

Faire /collection 
Regarder l'iconne de la collec heroïque
Voir que la texture esg  un pet

Ou
Avoir un totem grace au bm
Voir que la texture est un pet

### Qu'aurait-il dû arriver ?

Avoir la texture vanillah

### Date et heure de la production du bug

Tout le temp

### Serveur

All

### Screen / vidéo

(Je seend en commentaire le 7 aout vers l'aprem)

**Comment by Jspppppp** [comment]
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139492099/0999924a-8fe6-44a6-9405-739212894146)

**Comment by LuluxClient** [comment]
Fixed dès la prochaine maj avec le pack update
