### ISSUE TITLE
[BUG] Classement du /pirate

### ISSUE THREAD

**Issue by NASTOUUH** [RivrsMc/SeasonSky-Issues#283]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

NASTOUH

### Pseudo discord

chrisgraph

### Que s'est-il passé ?

Des joueurs mon report que le classement du /pirate était bug, les stats n'affiches pas les bons résultats. Le joueur à 700k pièces d'or mais le premier n'a que 900 pièces d'or dans le classement. #

### Étapes à suivre pour reproduire le bug

• /pirate
• Classement pièce d'or

### Qu'aurait-il dû arriver ?

Les joueurs devrait avoir les bonnes stats

### Date et heure de la production du bug

07-08 09:12:36

### Serveur

Spawn-01

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/115428187/8ee4fb45-77c8-4c50-96f1-118bf3643501)

**Comment by Asherate** [comment]
@NASTOUUH tu aurais le pseudo du joueur qui t'as report ça ?

**Comment by Alexis700** [comment]
Il n'y a plus l'évent pirate
