### ISSUE TITLE
[BUG] Bug liquid & redstone

### ISSUE THREAD

**Issue by cvzxzerphire** [RivrsMc/SeasonSky-Issues#284]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Peugeot107

### Pseudo discord

Lapomme

### Que s'est-il passé ?

en gros j 'ai crée une machine 3x3 vertical et la lave du mid d' est en ouest ne se transforme pas en lave alors que l'on voit clairement la lave se poser sur l'eau

### Étapes à suivre pour reproduire le bug

je ne sais pas 

### Qu'aurait-il dû arriver ?

bah la lave doit se transformer en pierre/minerais 

### Date et heure de la production du bug

07-08 14:16:38

### Serveur

island-06

### Information supplémentaire

UUID: d527013d-918a-4eea-b745-1c12205ca4c0
Position: -1756 79 23424 SuperiorWorld
Ping: 16ms

**Comment by LuluxClient** [comment]
Hello @cvzxzerphire est ce que tu aurais une vidéo pour expliquer ton problème puisque je n'ai pas de soucis avec de la lave / j'ai mal compris ton soucis

**Comment by cvzxzerphire** [comment]
en gros mon problème c'est juste que la lave ne se transforme pas en pierre 

![2023-08-09_13 19 42](https://github.com/RivrsMc/SeasonSky-Issues/assets/103437758/de0aa74b-04d3-48b0-9e2f-6987e9fa427b)

**Comment by LuluxClient** [comment]
Résolu en jeu, soucis de design de sa farm.
