### ISSUE TITLE
[BUG] Quetes experte

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#285]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

La quête ne se bloque pas quand on a l’inventaire plein comme les quêtes facile, avancée ou difficile (voir vidéo)

### Étapes à suivre pour reproduire le bug

1. Être gardian / avoir une quete expert
2. Finir la quête quand on est full inventaire
3. Avoir plusieurs récompenses dans la quête pour qu’elle ne donne pas tout

### Qu'aurait-il dû arriver ?

Elle aurai du se bloquer

### Date et heure de la production du bug

07/08/2023

### Serveur

All

### Screen / vidéo

https://youtu.be/zlLgSr1E5Nc

**Comment by LuluxClient** [comment]
La vidéo est en privé @LupusArctos4 et nous avons pas de système "inventaire full" pour les récompenses des quêtes, c'est soit en global soit rien si je me trompe pas

**Comment by LupusArctos4** [comment]
Alors pour la vidéo c'est parce que nous avons des farms que nous (mon équipe et moi) ne voulons pas montrer à tout le monde donc si vous voulez voir la vidéo, il me faudrait votre adresse mail Google afin que je vous ajoute. 

Bas pourtant quand on est full inventaire c'est assez fréquent que la quête se bloque quand c'est un item qu'elle doit donner (exemple : un spawner, une plume de fly, etc.) parce que des fois je récup 2 récompenses sur les 3 et elle se bloque pour la dernière

**Comment by LuluxClient** [comment]
> Alors pour la vidéo c'est parce que nous avons des farms que nous (mon équipe et moi) ne voulons pas montrer à tout le monde donc si vous voulez voir la vidéo, il me faudrait votre adresse mail Google afin que je vous ajoute.
> 
> Bas pourtant quand on est full inventaire c'est assez fréquent que la quête se bloque quand c'est un item qu'elle doit donner (exemple : un spawner, une plume de fly, etc.) parce que des fois je récup 2 récompenses sur les 3 et elle se bloque pour la dernière

Après verification il n'y a aucun système comme ça, juste assure toi d'avoir de la place dans l'inventaire, sinon voici mon mail pour m'add sur la vidéo: REDACTED

**Comment by LupusArctos4** [comment]
Bon pour la vidéo j'ai aucune accès avec mon téléphone depuis les applications YouTube ou YouTube Studio
Mais du coup je ne peux pas te montrer à quel point que certaines farmes l'inventaire se remplit vite (tour à mob)

**Comment by LupusArctos4** [comment]
https://youtu.be/aeBcccd5mOQ
Bon voilà le lien dit moi si ca marche

**Comment by LupusArctos4** [comment]
https://youtu.be/aeBcccd5mOQ
Bon voilà le lien dit moi si ca marche

**Comment by LuluxClient** [comment]
Il faut juste faire attention, je ne vois aucun système comme ça dans nos autres quêtes. Je t'invite à faire une suggestion sinon ^^ !

**Comment by LupusArctos4** [comment]
Merci en tout cas pour ton temps passer sur le pseudo bug
