### ISSUE TITLE
Le Pet Luffy Ne Donne Pas Les 30% Aventurier

### ISSUE THREAD

**Issue by Jules141711** [RivrsMc/SeasonSky-Issues#286]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Jules141711

### Pseudo discord

Jules141711

### Que s'est-il passé ?

Le Pet Ne Donne Pas Le Bonus De 30%

### Étapes à suivre pour reproduire le bug

taper des mobs en aventure

### Qu'aurait-il dû arriver ?

j aurais du gagner les 30%

### Date et heure de la production du bug

Permanent

### Serveur

SeasonSky Aventure

**Comment by LuluxClient** [comment]
Hello @Jules141711 je viens de tester en prod et je n'ai pas de soucis, assure toi d'avoir le pet au bon niveau et de l'équiper et pour être sur de déco reco et attendre 1m. Merci de faire cette manip avec le pet et sans le pet pour voir la différence (retire bien tout tes pets)
