### ISSUE TITLE
[BUG] Récompense caisse de vote : Pioche de l'apprenti remplacée par rune de vente 1.0

### ISSUE THREAD

**Issue by paulsavary** [RivrsMc/SeasonSky-Issues#287]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

CrownFR

### Pseudo discord

CrownFR

### Que s'est-il passé ?

Dans la caisse de vote, le texte du chat m'a indiqué une Pioche de l'apprenti comme récompense, mais j'ai reçu une Rune de vente 1.0 à la place.

### Étapes à suivre pour reproduire le bug

Je pense que la liste des récompense a mal était update et qu'il suffit d'obtenir la récompense Pioche de l'apprenti pour reproduire le bug

### Qu'aurait-il dû arriver ?

J'aurais du recevoir une pioche de l'apprenti, ou le chat aurait du indiquer "Rune de vente" à l'obtention

### Date et heure de la production du bug

Le 08/08/2023 à 16h45 environ

### Serveur

Spawn-01

### Information supplémentaire

 Je n'ai pas besoin de pioche de l'apprenti je souhaite seulement report le bug

**Comment by LuluxClient** [comment]
Fixed au prochain redem !
