### ISSUE TITLE
[BUG] Épée despawn pour aucun raison

### ISSUE THREAD

**Issue by Cyfoox** [RivrsMc/SeasonSky-Issues#288]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Cyf0x

### Pseudo discord

legrandcyfox

### Que s'est-il passé ?

Bonjour,
Un item moddé (sabre Du corsaire) s'est transformé en tripwire hook.
Avant que cela n'arrive, j'ai acheté un item au shop (3x sable), peut-être que ça peut être lié. (les items achetés ont bien été reçu dans l'inventaire)

### Étapes à suivre pour reproduire le bug

(hypothèse)
acheter un item au shop

### Qu'aurait-il dû arriver ?

Ne pas disparaitre ?

### Date et heure de la production du bug

08-08 17:45:11

### Serveur

Spawn-02

### Screen / vidéo

![2023-08-08_17 48 29](https://github.com/RivrsMc/SeasonSky-Issues/assets/141756214/e4dee62e-03a5-4de8-8302-269565557247)

### Information supplémentaire

UUID: f1350387-3dea-423a-b302-99cb0efbc9a3
Position: 187 158 -1188 world
Ping: 11ms

**Comment by LuluxClient** [comment]
Ceci est impossible vu que c'est juste un objet retexturé mais qui est de base une épée en netherite donc au pire des cas tu aurais perdu la texture ou elle aurait bug mais en gardant sa description et effet et enchants.

Tu étais bien au spawn02 lors de ce bug comme indiqué dans ton report de bug ?

**Comment by LuluxClient** [comment]
J'ai check toute tes logs lié à une action lié à ton épée et j'ai aucune log (drop, container move, break etc...)

**Comment by Cyfoox** [comment]
Bonjour,Le bug s’est résolu 2-3 heures après mon report.Cependant, je constate dans mes coffres que de nombreux items « customs » devienne des Tripwire Hook avant de redevenir normal.Peut-être un soucis a investiguer 😉Belle journée !CyfoxLe 9 août 2023 à 13:29, Luca Améaume ***@***.***> a écrit :﻿
Ceci est impossible vu que c'est juste un objet retexturé mais qui est de base une épée en netherite donc au pire des cas tu aurais perdu la texture ou elle aurait bug mais en gardant sa description et effet et enchants.
Tu étais bien au spawn02 lors de ce bug comme indiqué dans ton report de bug ?
