### ISSUE TITLE
[BUG] blocs de spawn en blocs musicaux

### ISSUE THREAD

**Issue by Xin0u** [RivrsMc/SeasonSky-Issues#289]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Xinou

### Pseudo discord

Xinou

### Que s'est-il passé ?

j'ai cliqué sur certain bloc et arpès ceci ils se sont transformés en bloc musicaux 

### Étapes à suivre pour reproduire le bug

1- aller au spawn 
2- cliqué sur certain bloc 
3- se dire qu'il faut créé une issue :)

### Qu'aurait-il dû arriver ?

les blocs de se changent pas en bloc musicaux 

### Date et heure de la production du bug

08/08/2023 à 20:31

### Serveur

spawn

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139914502/dec5f990-07c3-42a5-a7a8-fecc71211b4a)

**Comment by LuluxClient** [comment]
Chaque redem ils seront fix mais je vais tenter de les updates manuellement pour que ce soucis n'y arrive plus. effectif dès la prochaine maj
