### ISSUE TITLE
[BUG] XP Jobs mineurs

### ISSUE THREAD

**Issue by Alex96x2** [RivrsMc/SeasonSky-Issues#29]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

alex96x2

### Pseudo discord

alex96x2

### Que s'est-il passé ?

Je ne gagne pas d'xp lorsque je fait cuire le fer, le cuivre et l'or.

### Étapes à suivre pour reproduire le bug

Faire cuire du fer, de l'or, du cuivre et le récupérer.

### Qu'aurait-il dû arriver ?

Je devrai gagner de l'xp lorsque je fait cuire du fer de l'or ou du cuivre

### Date et heure de la production du bug

09-07 10:25:18

### Serveur

island-01

### Information supplémentaire

UUID: f65b8a07-d770-46b7-8fc1-f24c89ac73ce
Position: -7199 100 9000 SuperiorWorld
Ping: 22ms

**Comment by NoHere32** [comment]
action smelt non fonctionnelle

**Comment by Acterax** [comment]
Même problème de config ici @LuluxClient

**Comment by LuluxClient** [comment]
Fixed
