### ISSUE TITLE
[BUG]  Clé royale coffre premium

### ISSUE THREAD

**Issue by Zwartkat** [RivrsMc/SeasonSky-Issues#290]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Zwartkat 

### Pseudo discord

Zwartkat 

### Que s'est-il passé ?

Lorsqu'on ouvre un coffre premium et qu'on gagne une clé royale, on ne l'a reçoit pas

### Étapes à suivre pour reproduire le bug

1. Ouvrir un coffre premium et gagner la clé 

### Qu'aurait-il dû arriver ?

Réception de la clé royale

### Date et heure de la production du bug

17:40 9/08

### Serveur

Tous

**Comment by LuluxClient** [comment]
Fixed
