### ISSUE TITLE
[BUG] quête Facile d'enchante

### ISSUE THREAD

**Issue by gogo820000** [RivrsMc/SeasonSky-Issues#292]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

gogo82000

### Pseudo discord

gogo

### Que s'est-il passé ?

Bonjour, je fait des quêtes d'enchante des armures en or et des épées en diams et quand j'enchante des épées en diams cela me fait valider la quête d'enchante des armures en or et vise versa .

### Étapes à suivre pour reproduire le bug

1.Avoir la quête d'enchante des armures en or ou d'enchante des épées en diams.
2.Enchante une épées en diams ou une armures en or avec la quête de l'autre
3.Regarder et voir le résultat. 

### Qu'aurait-il dû arriver ?

cela n'aurait pas du valider la quête des armures en or alors que j'enchanter des épées en diams.

### Date et heure de la production du bug

21h30

### Serveur

seasonsky

**Comment by gogo820000** [comment]
cela marche meme avec les armures en diams

**Comment by LuluxClient** [comment]
Merci du report, ceci a été fix et sera effectif au redem ! Pour report les prochains bugs plus rapidement tu pourras faire /bugreport en jeu qui pré rempliera avec des informations !
