### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by JokeRr-37** [RivrsMc/SeasonSky-Issues#293]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

JokeRr_

### Pseudo discord

_mattam

### Que s'est-il passé ?

Le coffre du fermier (récompense du niveau 48 du métier de fermier) ne peut pas être posé et donc utilisé par la suite.
Lorsque l'on essaye de le poser ce message apparait : "Coffre de Ventre - Vous n'avez pas la permission de placer ce coffre fermier"

 

### Étapes à suivre pour reproduire le bug

Prendre le coffre et essayer de le poser

### Qu'aurait-il dû arriver ?

Qu'il se pose et qu'ensuite puisse être utiliser comme un coffre royal

### Date et heure de la production du bug

09/08 à 22h00

### Serveur

island 05

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/55343978/afbbd7d5-e0bc-48e0-bd0f-2a47d74b2d92)

**Comment by LuluxClient** [comment]
Fixed
