### ISSUE TITLE
[BUG] Bonus Pet

### ISSUE THREAD

**Issue by LLucrece** [RivrsMc/SeasonSky-Issues#294]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Lucrece

### Pseudo discord

Lucrece

### Que s'est-il passé ?

Le bonus du pet ne s'applique pas correctement 
il devrait donner 15% d'xp en plus alors qu'il ne donne que 5% 

Par exemple sur les morues (qui donnent 0.99 pts d'xp sans bonus)
avec le pet on passe à 1.04 pts d'xp

de meme pour les revenu métiers

j'ai bien déco/reco et retester plusieurs fois

### Étapes à suivre pour reproduire le bug

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de la production du bug

09/08 à 22h35

### Serveur

serv2

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/135556343/7b317d4a-7e42-4c73-b1b0-31e48f72ad23)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/135556343/621c87d7-7895-432a-b6b3-62e8236b2f6a)

**Comment by LLucrece** [comment]
Idem Pour floral qui ne donne pas le bon bonus par exemple les lapins sont censé passer de 0.3 à 0.345 point d'xp
le bonus est enfaite de 5% arrondi à l'entier inferieur
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/135556343/c40ef9c5-d6ad-41cd-aeca-f698a89b4495)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/135556343/fcd3735c-12be-44f9-ac76-c3c3e8b52f13)

**Comment by LLucrece** [comment]
Le pet gribouille ne revend pas les cultures avec un bonus de 10%
le bonus semble etre de zero x)

**Comment by LuluxClient** [comment]
Fixed
