### ISSUE TITLE
[BUG] cumules de plusieurs bonus de pet

### ISSUE THREAD

**Issue by LLucrece** [RivrsMc/SeasonSky-Issues#295]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Lucrece

### Pseudo discord

Lucrece

### Que s'est-il passé ?

il n'est pas possible de multiplier deux bonus identiques
Par exemple : 

Sans bonus je vend une pomme de terre 2.5 $
en rajoutant le pet pingu (qui me donne un bonus de revente de 20% sur la pomme de terre)
je monte à 3 $ puis quand je rajoute frankenstein (qui me donne aussi un bonus de revente de 20% sur la pomme de terre) 
je reste à 3 $ de revente

pourtant ce n'est pas le pet frankenstein qui bug mais bien le fait qu'il ne soit pas possible de cumuler deux bonus identique 
j'ai bien déco/reco et j'ai bien verifié plusieurs fois

### Étapes à suivre pour reproduire le bug

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de la production du bug

09/08 à23h05

### Serveur

serv2

### Screen / vidéo

.

### Information supplémentaire

.

**Comment by LuluxClient** [comment]
Hello je vois le soucis mais cela ne vient pas de nous donc les devs du plugin ont été contacté, dès que j'ai un patch il sera en prod au plus vite !

**Comment by Alexis700** [comment]
Hélas on n'a aucun impact sur le bug, on a transmis le bug mais on a toujours pas retour, je ferme donc l'issue
