### ISSUE TITLE
[BUG]  Pack emoji coffre premium 

### ISSUE THREAD

**Issue by Zwartkat** [RivrsMc/SeasonSky-Issues#296]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Zwartkat 

### Pseudo discord

Zwartkat 

### Que s'est-il passé ?

On peut obtenir plusieurs fois le même Pack emoji dans le coffre premium 

### Étapes à suivre pour reproduire le bug

1. Ouvrir plusieurs coffres premium

### Qu'aurait-il dû arriver ?

Ne pas avoir le même Pack d'emoji que ceux qu'on a déjà 

### Date et heure de la production du bug

17:30 09/08

### Serveur

Tous

**Comment by LuluxClient** [comment]
Fixed
