### ISSUE TITLE
[BUG] perte d'item  /condense 

### ISSUE THREAD

**Issue by LLucrece** [RivrsMc/SeasonSky-Issues#297]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Lucrece

### Pseudo discord

Lucrece

### Que s'est-il passé ?

en faisant /condense, des blocs disparaissent (7 blocs)
cf image

### Étapes à suivre pour reproduire le bug

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de la production du bug

09/08 à 23h47

### Serveur

serv2

### Screen / vidéo

avant 
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/135556343/d3f75f27-4f88-4ba8-b76e-f3cf8098dc16)
aprés condense
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/135556343/71b10da5-9ce5-426c-9cb4-b6426e509e81)

**Comment by Alexis700** [comment]
C'est normal le joueur est censé avoir le menu principal dans le slot 9 hotbar
