### ISSUE TITLE
[BUG] Les items retire les effets du joueurs

### ISSUE THREAD

**Issue by Flyppea** [RivrsMc/SeasonSky-Issues#298]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Flyppea

### Pseudo discord

Flyppea

### Que s'est-il passé ?

L'effet speed 2 sur la houe du pirate prend le dessus sur les effets speed des pets, je m'explique:
J'ai 1 pets qui donne Speed 2
Lorsque je prend la houe dans mon inv
je n'ai plus l'effet speed du pets
et je n'ai speed que lorsque je prend la houe dans ma main

Je ne sais pas si vous avez compris il faut le voir pour le comprendre mdr

### Étapes à suivre pour reproduire le bug

Je m'explique:
J'ai 1 pets qui donne Speed 2
Lorsque je prend la houe dans mon inv
je n'ai plus l'effet speed du pets
et je n'ai speed que lorsque je prend la houe dans ma main

Je ne sais pas si vous avez compris il faut le voir pour le comprendre mdr

### Qu'aurait-il dû arriver ?

Avoir speed tout le temps grâce au pets

### Date et heure de la production du bug

?

### Serveur

is 5

### Information supplémentaire

Faire en sorte que l'item ne retire pas l'effet qu'il est sensé donné si le joueur le possède déjà

**Comment by ArDiDEx** [comment]
Hey
Un potentiel fix sera mis sur le serveur dans les prochains jours pour ça, cependant:
Mettre un pets speed 2 -> ensuite prendre la houe -> prendre autre chose dans la main ne retirera plus l'effet speed
mais
prendre la houe -> mettre un pets speed 2 -> prendre autre chose lui enlèvera bien l'effet
Merci du report
