### ISSUE TITLE
[BUG] Potion de soin Splash et potion d'xp

### ISSUE THREAD

**Issue by MyNIIs** [RivrsMc/SeasonSky-Issues#299]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MyNIIs

### Pseudo discord

_mynameis

### Que s'est-il passé ?

J'ai voulu me soigner avec des potions de soins 2 en splash mais ça n'a pas fonction et j'ai perdu les potions.

Vu que n'a plus d'xp sur les monstres, j'ai voulu utiliser des potions d'xp pour reparler mon armure, mais elles
 ne s'utilisent pas.

### Étapes à suivre pour reproduire le bug

Potion de soin 2 splash
1) Allez au monde aventure canyon des profondeurs.
2) Utilisé une potion de soin 2 en splash.
3) Elle  disparaît sans soigner.

Potion d"Xp
1) Allez au monde aventure canyon des profondeurs.
2) Utilisée des porions d"Xp.
3) Ne s'utilisent pas mais contrairement à celle de soin, ne disparaissent pas

### Qu'aurait-il dû arriver ?

1) Potion de soin
Me soigné

2) Potion d'xp
Me donner l'xp qui est dedans.

### Date et heure de la production du bug

vers 14h15-20 +-

### Serveur

Spawn-02

### Screen / vidéo

![Screenshot_1](https://github.com/RivrsMc/SeasonSky-Issues/assets/141928485/98cb933e-4137-4f7d-ae71-d8b94313c809)

**Comment by LuluxClient** [comment]
Hello normalement tu peux faire /bugreport en jeu et cliquer sur le lien et ça va préremplir les informations que tu as mis dans "SCREEN / VIDÉO" sinon le bug devrait être fix
