### ISSUE TITLE
[BUG] Lenteur lorsqu'on quitte une cinématique

### ISSUE THREAD

**Issue by itsme-to** [RivrsMc/SeasonSky-Issues#3]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Skyssy

### Pseudo discord

@itsme.to

### Que s'est-il passé ?

Lorsqu'on `/spawn`, déconnecte ou toutes autres actions qui fait quitter la cinématique. 
On garde l'effet de lenteur lorsqu'on reconnecte ou le changement de serveur.

### Étapes à suivre pour reproduire le bug

Commencé une cinématique et faire /spawn

### Qu'aurait-il dû arriver ?

Clear l'effect

### Date et heure de la production du bug

08-07 16:48:30

### Serveur

Spawn-02

### Information supplémentaire

UUID: 8f5ab77e-625c-486d-8d38-22a85bbaecb8
Position: 223 143 -1109 world
Ping: 31ms

**Comment by Acterax** [comment]
L’effet est supprimé a la deco
