### ISSUE TITLE
[BUG] Caisses de votes, récompenses bonbons

### ISSUE THREAD

**Issue by Slylokss** [RivrsMc/SeasonSky-Issues#30]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Slyyyyy_

### Pseudo discord

Sly

### Que s'est-il passé ?

Les joueurs qui ouvrent des caisses de votes et tombent sur un bonbon ne le récupèrent pas. Le problème a été vu et report par plusieurs joueurs différents et vérifié en vocal.

### Étapes à suivre pour reproduire le bug

Ouvrir une caisse vote avec une clé de vote, tomber sur l'item bonbon

### Qu'aurait-il dû arriver ?

Obtenir la récompense promise, ici, le bonbon.

### Date et heure de la production du bug

8 Juillet, 22h.

### Serveur

Tous servers

**Comment by NoHere32** [comment]
good au prochain redem
