### ISSUE TITLE
[BUG] houe des dieux

### ISSUE THREAD

**Issue by GodSiwax** [RivrsMc/SeasonSky-Issues#300]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Siwax_x

### Pseudo discord

GodSiwax

### Que s'est-il passé ?

Bonjour,

Apres une maj la houe royale et pirate replantent mais la houe des dieux (qui est sensé être la meilleur du moment et la plus rare) ne replante pas j'ai fait un ticket et m'a dit que c'était pas normal et de report le bug ici

### Étapes à suivre pour reproduire le bug

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de la production du bug

depuis le patchnote du 03/08 sur discord

### Serveur

is 02

**Comment by LupusArctos4** [comment]
C'est pas écrit dans le patch note donc je ne vois pas pourquoi elle serait aussi modifiée

**Comment by LuluxClient** [comment]
Fixed, c'était un bug
