### ISSUE TITLE
[BUG] Lvl 68 chasseurs 

### ISSUE THREAD

**Issue by Jspppppp** [RivrsMc/SeasonSky-Issues#301]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Jspppppp

### Pseudo discord

Mathéo#8230 / Jspppppp (l'ours)

### Que s'est-il passé ?

Je suppose qu'au niveau 68 chasseurs c'est une épée divine qu'on reçois et non une hache divine comme écrit

### Étapes à suivre pour reproduire le bug

Faire /job
Regarde le lvl 68 
Voir que c'est écrit Hache Divine 

### Qu'aurait-il dû arriver ?

Que ça sois écrit " Epée Divine " 

### Date et heure de la production du bug

Tout le temp

### Serveur

All

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139492099/8b5f8962-b0ed-4948-904f-7aaa32d68ea9)

**Comment by mrsxnshxne** [comment]
Hello, c'est corrigé, c'est bel et bien une Épée divine !
