### ISSUE TITLE
[BUG] Houe Royale / Houe du pirate

### ISSUE THREAD

**Issue by Clscf** [RivrsMc/SeasonSky-Issues#302]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Concombrehappy

### Pseudo discord

Concombre#6378

### Que s'est-il passé ?

La Houe Royale et la houe du pirate ne replante plus en cassant les cultures

### Étapes à suivre pour reproduire le bug

.

### Qu'aurait-il dû arriver ?

Replanter en même de casser

### Date et heure de la production du bug

19h

### Serveur

Tout les serv

### Screen / vidéo

https://youtu.be/nXblBBZICmE

**Comment by LuluxClient** [comment]
Fixed
