### ISSUE TITLE
[BUG] Boss Pirate invincible et met aucun dégât

### ISSUE THREAD

**Issue by imtheluk** [RivrsMc/SeasonSky-Issues#303]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

xdimtheluk

### Pseudo discord

imtheluk

### Que s'est-il passé ?

Le boss pirate a spawn à 20h, mais il ne prenait aucun dégât et, malgré le fait qu'on prend les hits, ne retire pas de vie et ne fais aucun dégât lui-même

### Étapes à suivre pour reproduire le bug

Attendre que le boss spawn

### Qu'aurait-il dû arriver ?

Le boss prend des dégâts normalement et meurt au bout de quelques secondes

### Date et heure de la production du bug

10-08 20:09:06

### Serveur

island-04

### Information supplémentaire

UUID: a192cfdf-2d68-410c-b2a9-3a927ee9d33f
Position: -7203 100 1 SuperiorWorld
Ping: 2ms

**Comment by LuluxClient** [comment]
Fixed
