### ISSUE TITLE
Bug Houe de pirate 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#304]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0isan

### Pseudo discord

Nami_san

### Que s'est-il passé ?

L'effet de la Houe qui replante n'a plus du tout son effet qui plante 

### Étapes à suivre pour reproduire le bug

Essayer de cultiver et de replanter par la suite 

### Qu'aurait-il dû arriver ?

Pouvoir replanter automatiquement avec

### Date et heure de la production du bug

10/08 22h03

### Serveur

Global

**Comment by LuluxClient** [comment]
fixed
