### ISSUE TITLE
Alpha bleu vert

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#305]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0isan

### Pseudo discord

Nami_san

### Que s'est-il passé ?

En gros il y a soucis de description sur le pets voir image ci dessous
Il est censé donner des éclats de prismarine mais tout les effets sont liés avec les enderpearl donc on sait pas du coup lequel est le bon 

### Étapes à suivre pour reproduire le bug

Du coup bah soit éclat de prismarine soit enderpearl 

### Qu'aurait-il dû arriver ?

/ 

### Date et heure de la production du bug

10/08 22h13

### Serveur

Global

### Screen / vidéo

![image-32](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/1041daec-71b4-4e86-8306-422ae87bf56f)

**Comment by mrsxnshxne** [comment]
Hello c'est corrigé, le pet produit bien des enderpearl, c'est dispo au prochain redem
