### ISSUE TITLE
[BUG] Up Rang Ambassadeur 

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#306]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267 

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

Il n’est pas possible d’où rang Ambassadeur car l’inventaire peut contenir maximum 9*4 stack soit 36 stack or le rang nous en demande plus que 36 avec tout les items 

### Étapes à suivre pour reproduire le bug

1. Être rang gardien
2. Voir up rang

### Qu'aurait-il dû arriver ?

On devrait pouvoir ajouter les items comme en fin de v3 avec le rang divin ou l’on ajouter les items dans la mémoire du up rang

### Date et heure de la production du bug

11/08/2023 01:50

### Serveur

All

**Comment by LuluxClient** [comment]
un fix est en cours

**Comment by mrsxnshxne** [comment]
Hello, je viens de finir le système de dépot comme en V3, il sera dispo dès demain
