### ISSUE TITLE
[BUG] On ne peux que taper le boss pirate en gamemode créative

### ISSUE THREAD

**Issue by hija621** [RivrsMc/SeasonSky-Issues#307]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Hija621

### Pseudo discord

hija621

### Que s'est-il passé ?

Quand le boss pirate spawn, on ne peux pas le taper en survie, juste en mode créatif

### Étapes à suivre pour reproduire le bug

Aller tapper le boss, essayer un survie (marche pas) essayer en créatif (marche)

### Qu'aurait-il dû arriver ?

Pouvoir le taper en survie

### Date et heure de la production du bug

11-08 10:11:34

### Serveur

Spawn-02

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/135941180/4b0f21b0-2c21-42e9-a7b1-362e13326b36)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/135941180/5ef9f787-cc33-47e2-b10b-f8f5e0c21d5c)

### Information supplémentaire

UUID: 2ab5499c-84d4-4a73-8c73-c919bc501510
Position: -67 -45 -52 IslandPirate
Ping: 30ms

**Comment by LuluxClient** [comment]
Fixed
