### ISSUE TITLE
[BUG] Les grades "Légende" on un délai lorsqu'il se téléporte en /pw

### ISSUE THREAD

**Issue by NASTOUUH** [RivrsMc/SeasonSky-Issues#308]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

NASTOUH

### Pseudo discord

Chris Graph - NASTOUH

### Que s'est-il passé ?

Les joueurs ayant le grade "Légende" ont un cooldown de téléportation dans le /pw

### Étapes à suivre pour reproduire le bug

• Avoir le grade légende
• Ce téléporter à un /pw

### Qu'aurait-il dû arriver ?

Les grades légende ne devraient pas avoir de cooldown lorsqu'ils se téléporte

### Date et heure de la production du bug

11-08 12:06:03

### Serveur

Spawn01

### Information supplémentaire

UUID: 4a462900-9930-4570-a0ed-5a0d8187aa01
Position: 8993 108 8990 SuperiorWorld
Ping: 5ms

**Comment by LuluxClient** [comment]
Fixed
