### ISSUE TITLE
[BUG] Solidité inefficace contre projectile custom

### ISSUE THREAD

**Issue by Founny** [RivrsMc/SeasonSky-Issues#309]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

résumé ticket

### Pseudo discord

résumé ticket

### Que s'est-il passé ?

L'enchantement solidité n'est pas pris en compte quant aux dégats reçus par des projectiles de mobs customs (de sûr les taupes du canyon)

### Étapes à suivre pour reproduire le bug

1. Être équipé d'une armure avec solidité
2. Se faire toucher par un projectile

### Qu'aurait-il dû arriver ?

À l'aide de l'enchantement la durabilité des armures devrait être moins impactée

### Date et heure de la production du bug

14:30

### Serveur

Aventure

**Comment by Alexis700** [comment]
Fix
