### ISSUE TITLE
[BUG] Seau d'eau infini deviens un seau d'eau basique

### ISSUE THREAD

**Issue by Slylokss** [RivrsMc/SeasonSky-Issues#31]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Slyyyyy_

### Pseudo discord

Sly

### Que s'est-il passé ?

Le seau d'eau infini se place et s'utilise comme un seau d'eau basique ce qui ne devrait pas être son cas. Quand le joueur essaye de placer une source d'eau, le contenant du seau se vide comme un seau basique.

### Étapes à suivre pour reproduire le bug

Obtenir le seau d'eau infini dans les récompenses de jobs fermier, puis l'utiliser.

### Qu'aurait-il dû arriver ?

Pouvoir placer des sources d'eau a l'infini.

### Date et heure de la production du bug

8 Juillet, 22h.

### Serveur

Server île

**Comment by LLucrece** [comment]
déja report ? 
https://github.com/RivrsMc/SeasonSky-Issues/issues/26

**Comment by Slylokss** [comment]
> 

On m’a fait part de ce bug en vocal hier soir et je ne l’ai pas vu dans le bug report.

**Comment by LLucrece** [comment]
> > 
> 
> On m’a fait part de ce bug en vocal hier soir et je ne l’ai pas vu dans le bug report.

pas de probleme ^^ c'etait juste pour te prevenir

**Comment by ArDiDEx** [comment]
https://github.com/RivrsMc/SeasonSky-Issues/issues/26#issuecomment-1627836792
