### ISSUE TITLE
[BUG] Notif des tournois 

### ISSUE THREAD

**Issue by Saakrr** [RivrsMc/SeasonSky-Issues#310]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Saakrr

### Pseudo discord

.sakr

### Que s'est-il passé ?

Coucou,

Le bug c'est sur la notif des tournois.

On a la notif "un concours va débuter dans 5min" mais la notif pop 5 secondes avant le début et non pas 5 minutes

### Étapes à suivre pour reproduire le bug

N/A

### Qu'aurait-il dû arriver ?

La notif pop plus tôt ou corriger la notif et afficher 5 secondes

### Date et heure de la production du bug

11-08 16:22:03

### Serveur

island-06

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139631462/0e6c361f-a6df-49de-b848-f11cecc9f77c)

### Information supplémentaire

UUID: 9ba038b3-4f7f-4f2d-b461-4c723f294e6a
Position: -8984 90 8935 SuperiorWorld
Ping: 21ms

**Comment by LuluxClient** [comment]
Fixed

**Comment by Saakrr** [comment]
Hello, le bug n'est pas fix, il y a eu la notif 5 secondes avant le tournoi de 16h avec toujours le même intitulé

**Comment by LuluxClient** [comment]
Il faut attendre un redem
