### ISSUE TITLE
[BUG] Eclozr ne fonctionne plus (manque d'info)

### ISSUE THREAD

**Issue by GearTrips** [RivrsMc/SeasonSky-Issues#311]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

flox23

### Pseudo discord

GearTrips

### Que s'est-il passé ?

Mon eclozr ne fonctionne pas et je n'arrive pas a mettre mes pets dedans

### Étapes à suivre pour reproduire le bug

aucune bug de base 

### Qu'aurait-il dû arriver ?

ca doit fonctionne je veux un geste commercial je galere depuis le debut sans ca x')

### Date et heure de la production du bug

01-08 18:09:45

### Serveur

island-05

### Information supplémentaire

UUID: c6779b3a-728b-4576-bc4f-4923875a33f1
Position: -28809 95 30612 SuperiorWorld
Ping: 24ms

**Comment by GearTrips** [comment]
grrr

**Comment by LuluxClient** [comment]
Bonjour @GearTrips je n'ai aucun soucis avec l'eclozr, tu peux détailler un peu plus ton problème ? Si ton eclozr est bug et ne fonctionne plus du tout tu peux faire un ticket sur le discord pour un remboursement !

**Comment by LuluxClient** [comment]
Aucune réponse
