### ISSUE TITLE
[BUG] Mauvaise texture coffre premium

### ISSUE THREAD

**Issue by CorieTutTut** [RivrsMc/SeasonSky-Issues#312]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Corie__

### Pseudo discord

tuttut_corie

### Que s'est-il passé ?

La texture du coffre premium n'est pas la bonne, c'est une texture de la clé estivale 

### Étapes à suivre pour reproduire le bug

1- avoir une caisse premium
2- regarder sa texture et voir que c'est la mauvaise texture

### Qu'aurait-il dû arriver ?

1- avoir une caisse premium
2- regarder sa texture et voir que c'est la bonne texture

### Date et heure de la production du bug

11-08 23:45:28

### Serveur

island-06

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/137453358/125b6b70-ff83-41a6-a74c-71be2597ee19)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/137453358/2ee62b42-a1dd-44de-9dcc-9d73f7c522da)

### Information supplémentaire

UUID: 1480f47e-4cab-4ffc-b129-8a4822196324
Position: 9030 109 -16124 SuperiorWorld
Ping: 6ms

**Comment by LuluxClient** [comment]
Fixed dès la prochaine maj
