### ISSUE TITLE
[BUG] Houe des dieux

### ISSUE THREAD

**Issue by leroidesgames** [RivrsMc/SeasonSky-Issues#313]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Leroidesgames

### Pseudo discord

Leroidesgames

### Que s'est-il passé ?

La houe des dieux ne plante plus en 3x3, alors que c'est son utilité.

### Étapes à suivre pour reproduire le bug

Farmer les champs

### Qu'aurait-il dû arriver ?

Elle devrait planter en 3x3 comme indiquer 

### Date et heure de la production du bug

12/08

### Serveur

Island 6

**Comment by LuluxClient** [comment]
Elle replante bien comme indiqué
