### ISSUE TITLE
Les quest de pêche 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#314]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0isan

### Pseudo discord

Nami_san

### Que s'est-il passé ?

Alors les quest de pêche : selle, arc, coquille de nautile et bien d'autres ne fonctionne apparemment pas depuis un moment cela avec n'importe quel canne à pêche.

### Étapes à suivre pour reproduire le bug

Ouvrir une quest pêche tomber sur une quest arc par exemple essayer de pêcher avec. 

### Qu'aurait-il dû arriver ?

Compléter la quest. 

### Date et heure de la production du bug

12 août 14h37

### Serveur

Global 

### Screen / vidéo

![Screenshot_20230812_135452_com discord](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/3bfb40d3-9ace-4cae-a182-f0e53dd93fa3)

**Comment by ePlanete** [comment]
il a raison, les quêtes de pêches marchent pas, j'ai essayé avec 183710284 de canne à pêche, les coquilles de Nautiles ne fonctionnent pas :/

**Comment by LuluxClient** [comment]
Ils ont été remove

**Comment by Nam0i** [comment]
Hey les quest ne fonctionne malheureusement toujours pas je viens de recevoir pas mal de joueur dans le même cas
