### ISSUE TITLE
Houe du soleil 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#315]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0isan

### Pseudo discord

Nami

### Que s'est-il passé ?

Alors la Houe du soleil elle a bien été patch pour le forgeron hormis ceux du /ah

### Étapes à suivre pour reproduire le bug

Regarder dans /ah 

### Qu'aurait-il dû arriver ?

Avoir le patch aussi 

### Date et heure de la production du bug

12/08 14h51

### Serveur

Global

### Screen / vidéo

![Screens
![2023-08-12_12 02 46-1](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/a03abe1d-4312-4ecc-9365-b71f9a871d1d)
![2023-08-12_12 02 41-1](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/ad2313fc-a2df-40d8-83bf-b00499537a14)
hot_20230812_144122_com discord](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/66eff739-5644-4504-bdac-8a2870f14d7c)
![Screenshot_20230812_144105_com discord](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/aeb1979a-147e-4310-b716-41baa3afc541)

**Comment by LLucrece** [comment]
il faut peut être l'utiliser une fois pour actualiser le lore

**Comment by LuluxClient** [comment]
Il faut l'utiliser 1 fois pour update le lore et enxuite faite /forgeron
