### ISSUE TITLE
[BUG] Nouveaux Pet non obtenable

### ISSUE THREAD

**Issue by Warnel0** [RivrsMc/SeasonSky-Issues#316]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Warnell

### Pseudo discord

warnel0

### Que s'est-il passé ?

L'obtention des nouveaux pets apparut lors de la dernière Maj dans le /pokedex n'est pas activé dans la table de loot des œufs

### Étapes à suivre pour reproduire le bug

Ouvrir un oeuf

### Qu'aurait-il dû arriver ?

Drop les nouveaux pets

### Date et heure de la production du bug

13-08 00:32:38

### Serveur

island-05

### Information supplémentaire

UUID: 6966561c-144c-40a6-b117-95d6af9b10ea
Position: -5488 0 1859 SuperiorWorld
Ping: 11ms

**Comment by LuluxClient** [comment]
Après verification tout les pets sont bien dans l'oeuf légendaire sauf ceux des îles qui sont exclusif aux îles
