### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Warnel0** [RivrsMc/SeasonSky-Issues#317]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Warnell

### Pseudo discord

warnel0

### Que s'est-il passé ?

7 runes de vente stack, lors de l'utilisation, cela a réduit la durabilité à 29/30 pour les 7 qui était stack au lieu d'en enlever 6 du stack et d'utiliser la dura sur une seule rune

### Étapes à suivre pour reproduire le bug

utiliser plusieurs rune de ventes 

### Qu'aurait-il dû arriver ?

enlever 6 du stack et d'utiliser la dura sur une seule rune

### Date et heure de la production du bug

13-08 03:14:31

### Serveur

island-05

### Information supplémentaire

UUID: 6966561c-144c-40a6-b117-95d6af9b10ea
Position: -5489 11 1825 SuperiorWorld
Ping: 11ms

**Comment by LuluxClient** [comment]
Ne stack pas tes runes de repair
