### ISSUE TITLE
[BUG] Crabe fleuve secret

### ISSUE THREAD

**Issue by Jspppppp** [RivrsMc/SeasonSky-Issues#318]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Jspppppp

### Pseudo discord

Mathéo#8230 / Jspppppp (l'ours)

### Que s'est-il passé ?

Les crabes du monde aventure : " Fleuve secret " sont bug on vois des zombies rename et des zombies noyés renames

### Étapes à suivre pour reproduire le bug

Être batisseur
Aller au monde aventure : " Fleuve secret " 
Voir que certain crabe on la texture bug 

### Qu'aurait-il dû arriver ?

Voir la bonne texture

### Date et heure de la production du bug

13/08/23 à 16h30

### Serveur

Aventure : " Fleuve secret "  

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139492099/01c75cf4-248d-4490-972f-5f440a608107)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139492099/72f4a3cf-739b-4f92-b172-ae47f6d34421)

**Comment by LuluxClient** [comment]
Fixed au redem

**Comment by Jspppppp** [comment]
Cc @LuluxClient, apparament le bug et encore présent mais très rarement 
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139492099/c545bb64-4be6-4b2b-80f0-f8f287b1fd45)
