### ISSUE TITLE
[BUG] Quete des briques de Bob du canyon

### ISSUE THREAD

**Issue by DieuPap** [RivrsMc/SeasonSky-Issues#319]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Psychopate_Man

### Pseudo discord

dieup

### Que s'est-il passé ?

La quete des briques de Bob du canyon ne fonctionne pas, le nombre de briques fabriqué ne monte pas 

### Étapes à suivre pour reproduire le bug

avoir la quete

### Qu'aurait-il dû arriver ?

Pouvoir faire monter le nombre de briques fabriqué

### Date et heure de la production du bug

14/08/2023 02:38

### Serveur

island 01

**Comment by LuluxClient** [comment]
Fixed au redem, il te demande de craft de la stone brick donc tu peux faire ça en attendant le redem et après ce sera bel et bien la brique
