### ISSUE TITLE
[BUG] Pioche des ombres ne récupère aucuns items/blocs

### ISSUE THREAD

**Issue by Slylokss** [RivrsMc/SeasonSky-Issues#32]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Slyyyyy_

### Pseudo discord

Sly

### Que s'est-il passé ?

La pioche des ombres, qui vend automatiquement le charbon miné, ne permet pas de récupérer d'autres bloc/items. Certains joueurs, ont perdu des blocs assez importants comme des entonnoirs, tables d'enchantements etc.

### Étapes à suivre pour reproduire le bug

Utiliser la pioche des ombres sur un autre bloc que minerais de charbon.

### Qu'aurait-il dû arriver ?

Pouvoir miner et récupérer d'autres blocs/items que les minerais de charbon.

### Date et heure de la production du bug

8 Juillet, 22h.

### Serveur

Server île

**Comment by NoHere32** [comment]
good au prochain redem
