### ISSUE TITLE
[BUG] Reward lvl 73 Aventurier

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#321]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

c'est écrit : 1 2 oeuf legendaire au lieu de 2 oeuf légendaire

### Étapes à suivre pour reproduire le bug

1. faire /jobs
2. aller dans le jobs aventurier
3. aller au pallier 73 pour voir le reward

### Qu'aurait-il dû arriver ?

il devrait etre écrit 2 oeuf legendaire

### Date et heure de la production du bug

14/08/2023 14:33

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/6caa0f12-f7af-442e-b20d-dddafb6501d0)

**Comment by LuluxClient** [comment]
Fixed

**Comment by LupusArctos4** [comment]
merci je regarderais s'il y a toujours un problème dans les prochains jours
