### ISSUE TITLE
[BUG] Compacteur niv.2 - lvl 70 alchi

### ISSUE THREAD

**Issue by IDeltaCocoI** [RivrsMc/SeasonSky-Issues#323]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Delta_Coco

### Pseudo discord

Delta_Coco

### Que s'est-il passé ?

Je n'ai pas eu le compactor niv.2 du niveau 70 d'alchi

### Étapes à suivre pour reproduire le bug

1.Etre lvl 70 alchi
2./jobs claim
3.Pleurer car on la pas

### Qu'aurait-il dû arriver ?

Avoir le compactor niv.2

### Date et heure de la production du bug

16:16

### Serveur

island-2

**Comment by LuluxClient** [comment]
Fixed et remboursé !
