### ISSUE TITLE
[BUG] Description de la vente des items de box aventure au pnj

### ISSUE THREAD

**Issue by Founny** [RivrsMc/SeasonSky-Issues#324]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Isaac______

### Pseudo discord

isaac____

### Que s'est-il passé ?

La description de l'onglet pour vendre les items des box aventure au pnj prévu à cet effet n'est pas assez précise.
Il y a écrit: "échanger vos objets gagnés en caisse de l'île contre de l'argent" cependant les items de toutes les box aventure sont pris en compte

### Étapes à suivre pour reproduire le bug

1. Parler au pnj des zones aventure pour revendre les loots des box aventure

### Qu'aurait-il dû arriver ?

Avoir une description adéquate

### Date et heure de la production du bug

14/08 - 21h

### Serveur

Tous

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/39631165/9f7cf6f7-d0c4-49c1-881d-a5214a2bdad9)

**Comment by Louise253** [comment]
@mrsxnshxne
