### ISSUE TITLE
[BUG] Récompense 60 pêcheur

### ISSUE THREAD

**Issue by Isweazu** [RivrsMc/SeasonSky-Issues#325]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Isweazu

### Pseudo discord

xx4040

### Que s'est-il passé ?

Suite ticket : la récompense de 350 scoins n'est pas donnée au passage du niveau 60 jobs pêcheurs

### Étapes à suivre pour reproduire le bug

Passer level 60 pêcheur => /jobs claim

### Qu'aurait-il dû arriver ?

Recevoir les 350 scoins

### Date et heure de la production du bug

21h le 14/08

### Serveur

island 06

**Comment by LuluxClient** [comment]
aucun soucis de mon côté, assure toi de bien faire /jobs claim
