### ISSUE TITLE
[BUG] Affichage Pallier verrouillé forge mage

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#326]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

le pallier est afficher comme verrouillé

### Étapes à suivre pour reproduire le bug

1. etre lvl 50 forgemage avant la mise a jour des métiers
2. faire /jobs 
3. aller dans forgemage pour regarder le pallier 51

### Qu'aurait-il dû arriver ?

il devrait etre écrit déverrouillé et avoir afficher le nombre d'xp pour le prochain pallier

### Date et heure de la production du bug

14/08/2023 22:51

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/8c1a489b-347d-4c9f-8d37-8f79baa2a11a)

**Comment by LuluxClient** [comment]
Fixed

**Comment by LupusArctos4** [comment]
merci je regarderais s'il y a toujours un problème
