### ISSUE TITLE
[BUG] Hopper de farm - lvl 60 fermier

### ISSUE THREAD

**Issue by IDeltaCocoI** [RivrsMc/SeasonSky-Issues#327]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Delta_Coco

### Pseudo discord

Delta_Coco

### Que s'est-il passé ?

Je n'ai pas eu le hopper de farm au level 60 du métier fermier

### Étapes à suivre pour reproduire le bug

1. Etre lvl 60 fermier
2. /jobs claim
3. Pleurer car on la pas :(

### Qu'aurait-il dû arriver ?

Avoir le hopper de farm

### Date et heure de la production du bug

15-08 00:54:34

### Serveur

island-02

### Information supplémentaire

UUID: 164a1969-f1b8-404a-b30c-bf5006af3fbf
Position: -1616 1 -1952 SuperiorWorld
Ping: 18ms

**Comment by LuluxClient** [comment]
La récompense a été changé en x2 oeufs de dragon au lieu du hopper de farm, tu as été remboursé
