### ISSUE TITLE
[BUG] Catégorie pet /ah

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#328]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

les nouveaux pet ne se mettent pas dans la catégorie pet dans le ah

### Étapes à suivre pour reproduire le bug

1. faire /ah
2. voir qu'il y a des nouveaux pet au ah
3. aller dans la catégorie pet
4. ne pas voir les nouveaux pet dans la catégorie

### Qu'aurait-il dû arriver ?

les nouveaux pets devraient apparaitre dans la catégorie pet dans le ah

### Date et heure de la production du bug

15/08/2023 18:38

### Serveur

all

**Comment by LupusArctos4** [comment]
c'est aussi le cas avec les missions pirate qui n'apparaissent pas dans la catégorie divers comme les autres missions

**Comment by LuluxClient** [comment]
Salut @LupusArctos4 pourrais-tu nous indiquer les pets qui ne sont pas dans la catégorie ?

**Comment by LupusArctos4** [comment]
je n'ai pas tout les pets en ma possession donc ca m'est compliqué mais je crois que c'est tout ce qui viennent de la mise a jour métier + nouvelle dimension (Fondcombe)
car on retrouve pas le Lothar, l'Alpha bleu vert (chasseur lvl 55), le Limbo Gris dorée
J'ai pu faire les test qu'avec ce là qu'on a, ma team et moi, en notre possession

**Comment by itsme-to** [comment]
Effectif au prochain redémarrage.

**Comment by LupusArctos4** [comment]
merci ça aidera tout le monde à trouver plus facilement les pets dans le /ah
