### ISSUE TITLE
[BUG] Perms d'ile - Voler

### ISSUE THREAD

**Issue by Warnel0** [RivrsMc/SeasonSky-Issues#329]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Warnell

### Pseudo discord

warnel0

### Que s'est-il passé ?

Il est impossible d'empecher les joueurs légend, visitant notre ile, d'utiliser sur le fly de leurs grade via la permission d'ile voler

### Étapes à suivre pour reproduire le bug

Inviter un joueur non membre de l'ile et desactiver le fly

### Qu'aurait-il dû arriver ?

le fly ne devrais pas pouvoir etre activer (meme reactiver apres le changement de la permission des non membres)

### Date et heure de la production du bug

15-08 21:02:25

### Serveur

island-05

### Information supplémentaire

UUID: 6966561c-144c-40a6-b117-95d6af9b10ea
Position: -5433 170 1761 SuperiorWorld
Ping: 12ms

**Comment by LuluxClient** [comment]
Bug déjà report https://github.com/RivrsMc/SeasonSky-Issues/issues/280
