### ISSUE TITLE
[BUG] Houe du fermier fou ne marche pas

### ISSUE THREAD

**Issue by Clscf** [RivrsMc/SeasonSky-Issues#330]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Concombrehappy

### Pseudo discord

Concombre#6378

### Que s'est-il passé ?

La houe du fermier fou ne replante pas

### Étapes à suivre pour reproduire le bug

casser un champ

### Qu'aurait-il dû arriver ?

Soit de faire comme la houe royale et pirate ou alors replanter comme la houe des dieux avant ( ce qui serait le mieux )

### Date et heure de la production du bug

15/08/2023 21h

### Serveur

global

### Screen / vidéo

https://youtu.be/NXpkFzRDWUI

**Comment by LuluxClient** [comment]
La houe fonctionne bien, je n'ai aucun soucis de mon côté, pourrais-tu nous fournir une vidéo de ton problème ?

**Comment by Clscf** [comment]
https://youtu.be/cHdezAbT8ig
voilà une nouvelle vidéo
J'essaie de replanter avec le clic droit mais ça ne marche pas

**Comment by ArDiDEx** [comment]
Hey, le bug devrait être réglé au prochain restart
Merci du report
