### ISSUE TITLE
[BUG] Zombie noyé 

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#332]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267 

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

Les zombies quand on les noie quand ils sont en stack ne transfo pas tous en même temps 

### Étapes à suivre pour reproduire le bug

1. Avoir un stack de 1024 de zombie
2. Les noyés 

### Qu'aurait-il dû arriver ?

Tout le stack devrait être transformé en noyé 

### Date et heure de la production du bug

16/08/2023 23:10

### Serveur

All

**Comment by LuluxClient** [comment]
Les zombies ne sont pas sensé se transformer, je vais analyser ce problème dans la semaine

**Comment by LupusArctos4** [comment]
c'est dommage mise a par si vous rajouter un spawner de drowned par la suite

**Comment by LuluxClient** [comment]
> c'est dommage mise a par si vous rajouter un spawner de drowned par la suite

J'ai corrigé vu que j'ai check et il n'y a rien qui était indiqué comme quoi on devait bloquer cela, effectif au redem !

**Comment by LupusArctos4** [comment]
d'accord merci
