### ISSUE TITLE
[BUG] Pet Herbi bug

### ISSUE THREAD

**Issue by Pelleyy** [RivrsMc/SeasonSky-Issues#333]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Pelley_

### Pseudo discord

pelleyy

### Que s'est-il passé ?

Le pet Herbi donne 5% d'xp de fermier au lieu du 15% mentionné dans sa description. 
Et ce avec toutes les cultures. 

### Étapes à suivre pour reproduire le bug

Activé le pet et comparer avec l'xp non actif dans la description du job

### Qu'aurait-il dû arriver ?

Il doit donné l'xp correctement, 

Exemple bettraves : Sans boost -- 0.25xp
                                Herbi Boost -- 0.26 xp (Ce n'est qu'un up de 5%) 0.25*1.05 = 0.2625xp
                                Herbi Boost comme qu'il se doit = 0.25*1.15 = 0.2875xp

### Date et heure de la production du bug

17h 2023-08-16

### Serveur

Eldoria

**Comment by LuluxClient** [comment]
Fixed au redem !
