### ISSUE TITLE
[BUG] EPEE EFLIQUE NE SE REPARE PAS AU /FORGERON

### ISSUE THREAD

**Issue by ImDriinxx** [RivrsMc/SeasonSky-Issues#335]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

ImDriinx

### Pseudo discord

ImDriinx

### Que s'est-il passé ?

Il est écrit dans la description de l'épée qu'elle est censée se réparer à l'aide du /foregeron. Or, ca ne fonctionne pas du tout. Même un /repair ou /repair all ne la répare pas. Elle est irréparable à l'heure actuelle et c'est très problématique !

### Étapes à suivre pour reproduire le bug

Baisser un peu la durabilité de l'épée et faire /forgeron

### Qu'aurait-il dû arriver ?

L'épée aurait du être réparé avec le /forgeron

### Date et heure de la production du bug

Peu importe

### Serveur

Peu importe

**Comment by LuluxClient** [comment]
Fixed au redem
