### ISSUE TITLE
[BUG] pioche des ombres ne drop la contenu des coffres

### ISSUE THREAD

**Issue by slogers** [RivrsMc/SeasonSky-Issues#336]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Mickey_la_winx

### Pseudo discord

Slogers

### Que s'est-il passé ?

Bonjour, je viens de m'apercevoir à mes dépends qu'en cassant un coffre avec la pioche des ombres, le coffres de drop pas les items qu'il contient

### Étapes à suivre pour reproduire le bug

1. placer un coffre
2. mettre un item quelconque à l'intérieur
3. casser le coffre avec la pioche des ombres

### Qu'aurait-il dû arriver ?

les items auraient à l'intérieur du coffre auraient du se drops

### Date et heure de la production du bug

17-08 21:59:35

### Serveur

island-04

### Information supplémentaire

UUID: a2a2c298-b140-49a0-95f0-5790a3b54596
Position: 8971 -4 -7188 SuperiorWorld
Ping: 11ms

**Comment by ArDiDEx** [comment]
Hey
Le bug a été réglé et le patch sera effectif dans les prochains jours (évite d'utiliser la pioche des ombres pour casser les coffres entre temps)
Merci du report
