### ISSUE TITLE
[BUG] Farm-contest

### ISSUE THREAD

**Issue by Warnel0** [RivrsMc/SeasonSky-Issues#337]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Warnell

### Pseudo discord

warnel0

### Que s'est-il passé ?

La rotation du farm contest qui est indiquer comme journalier ne l'ai pas

### Étapes à suivre pour reproduire le bug

/farm-contest et accéder à la boutique rotative

### Qu'aurait-il dû arriver ?

la boutique devrait changer tous les jours

### Date et heure de la production du bug

17-08 23:52:31

### Serveur

island-05

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/112425048/4e49c6c6-d47b-4acf-a689-e965ce6bb725)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/112425048/862dcc0b-fe58-460b-a448-1a4b5b387701)

### Information supplémentaire

UUID: 6966561c-144c-40a6-b117-95d6af9b10ea
Position: -5388 148 1786 SuperiorWorld
Ping: 12ms

**Comment by Alexis700** [comment]
Déjà report dans issue 195 je ferme donc cette issue
