### ISSUE TITLE
[BUG] Description pet Kitsune

### ISSUE THREAD

**Issue by Warnel0** [RivrsMc/SeasonSky-Issues#338]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Warnell

### Pseudo discord

warnel0

### Que s'est-il passé ?

Erreur description pet Kitsune au niveau 15

### Étapes à suivre pour reproduire le bug

voir screen

### Qu'aurait-il dû arriver ?

icone NIV.15

### Date et heure de la production du bug

18-08 04:10:59

### Serveur

island-05

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/112425048/23ccc580-c362-4f6b-84c0-956bb4c64f86)

### Information supplémentaire

UUID: 6966561c-144c-40a6-b117-95d6af9b10ea
Position: -5400 196 1791 SuperiorWorld
Ping: 16ms

**Comment by LuluxClient** [comment]
Fixed au redem (il faut bien assurer de remove le pet et le remettre dans le gui /pets car je n'ai aucun soucis)
