### ISSUE TITLE
[BUG] Mission Zombie

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#339]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

Les Husk (zombie momified) ne sont pas comptés dans les missions tuer des zombies.

### Étapes à suivre pour reproduire le bug

1. avoir une mission zombie
2. taper des husk
3. voir que la quete monte pas

### Qu'aurait-il dû arriver ?

Ils devraient tres pris en compte dans les missions car c'est un type particulier de zombie tout comme les villageois zombie ou les drowned (zombie noyé)

### Date et heure de la production du bug

18/08/2023 20:06

### Serveur

all

**Comment by LuluxClient** [comment]
J'ai rajouté les husk et drowned dans les quêtes "tuer des zombies" effectif au redem. 

Edit: j'ai revert les changements, tu dois belle et bien uniquement tuer des zombies et non les autres variantes, j'ai rajouté une quête "tuer des husk" pour compenser et des les quêtes "tuer des monstres" également

**Comment by LupusArctos4** [comment]
merci
