### ISSUE TITLE
[BUG] Pallier vote

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#34]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

Les palliers vote ne fonctionne pas mise a par le premier car on est bloquer à 5 dans notre compteur

### Étapes à suivre pour reproduire le bug

1. voté plus de 10x
2. faire /vote
3. regarder les pallier de vote

### Qu'aurait-il dû arriver ?

on devrait débloquer les nouveaux pallier

### Date et heure de la production du bug

09/07/2023 12:20

### Serveur

all

**Comment by NoHere32** [comment]
patch

**Comment by LupusArctos4** [comment]
patch au prochain redem ? parce que si oui on perd quand meme tout les votes qu'on fait depuis l'open là
