### ISSUE TITLE
[BUG] Ambassadeur 

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#341]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

bug dans l'affichage entre l'affichage 

### Étapes à suivre pour reproduire le bug

1. etre gardian
2. vouloir passer le rang ambassadeur
3. voir que l'interface et l'interface enclume est différent et ca ne nous permet pas de rang up si on avait pas les 450 lvl mais ca en a prix que 400

### Qu'aurait-il dû arriver ?

avoir le bon nombre dans l'une des deux interface et qu'il fonctionne 

### Date et heure de la production du bug

19/08/2023 14:09

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/13bb621b-9251-4b15-aee6-b710efc39217)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/c3be368e-e4fd-4bcd-b3ac-9f772ccd025f)

**Comment by LuluxClient** [comment]
Fixed

**Comment by LupusArctos4** [comment]
merci
