### ISSUE TITLE
[BUG] Runes de ventes

### ISSUE THREAD

**Issue by IDeltaCocoI** [RivrsMc/SeasonSky-Issues#343]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Delta_Coco

### Pseudo discord

Delta_Coco

### Que s'est-il passé ?

Les runes de ventes ne se cumulent pas avec les boost de vente des pets

### Étapes à suivre pour reproduire le bug

1. Avoir une rune de vente
2. Avoir un pet qui augmente le prix de vente
3. Vendre un item avec la rune
4. Vendre le même item avec un /sell all
5. Comparer les prix 

### Qu'aurait-il dû arriver ?

Les runes doivent se cumuler avec les pets de vente

### Date et heure de la production du bug

19-08 20:47:12

### Serveur

island-02

### Screen / vidéo

![Capture d’écran 2023-08-19 192503](https://github.com/RivrsMc/SeasonSky-Issues/assets/141357456/43bdba5c-cdef-41d2-bc7c-89f4f840229f)
Avec /sell all

![Capture d’écran 2023-08-19 192452](https://github.com/RivrsMc/SeasonSky-Issues/assets/141357456/3ab8e535-c5c7-497a-a217-07fb6114b354)
Avec la rune

Pour un stack de verrue, je vend moins chère avec la rune alors que mes pets sont équipé. Le prix doit être équivalent ou supérieur au /sell all normalement.

### Information supplémentaire

UUID: 164a1969-f1b8-404a-b30c-bf5006af3fbf
Position: -1616 -41 -1976 SuperiorWorld
Ping: 20ms

**Comment by ArDiDEx** [comment]
Hey
Le bug sera fix avec le restart de cette nuit
Merci du report
