### ISSUE TITLE
[BUG] Possibilité de placer de la redstone dans les zones protégés 

### ISSUE THREAD

**Issue by imtheluk** [RivrsMc/SeasonSky-Issues#344]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

xdimtheluk

### Pseudo discord

xdimtheluk

### Que s'est-il passé ?

LastArtificer a envoyé un message dans le chat disant qu'il peut poser de la redstone dans la mine du Canyon, je me suis /tpa à lui et en effet, avec la redstone en offhand il a pu clique droit et la poser par terre, mais évidemment, impossible de l'enlever

### Étapes à suivre pour reproduire le bug

Prendre de la redstone, appuyer sur la touche pour mettre l'item dans sa deuxième main et clique droit sur le sol

### Qu'aurait-il dû arriver ?

Ne pas y avoir de redstone à terre

### Date et heure de la production du bug

20-08 14:45:21

### Serveur

Spawn-04

### Screen / vidéo

![2023-08-20_14 43 13](https://github.com/RivrsMc/SeasonSky-Issues/assets/141948375/e394b22d-066b-46ac-8ddb-9487a841223b)

### Information supplémentaire

UUID: a192cfdf-2d68-410c-b2a9-3a927ee9d33f
Position: -421 -14 608 Island
Ping: 7ms

**Comment by ArDiDEx** [comment]
Hey le bug devrait être fix cette nuit
Merci du report
