### ISSUE TITLE
[BUG] Table enchante au spawn

### ISSUE THREAD

**Issue by LLucrece** [RivrsMc/SeasonSky-Issues#345]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

lucrece

### Pseudo discord

Lucrece

### Que s'est-il passé ?

la table d'enchant n'a rien à faire la
ca fait plus d'une semaine déja

### Étapes à suivre pour reproduire le bug

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de la production du bug

20-08 16:20:24

### Serveur

Spawn-03

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/135556343/881ed3e8-9522-4466-964b-617efb937b3e)

### Information supplémentaire

UUID: 66a43a59-81b5-4ac7-923a-67ba4e9e1d9d
Position: 210 136 -1191 world
Ping: 37ms

**Comment by LuluxClient** [comment]
Fixed au redem
