### ISSUE TITLE
[BUG] /pay impossible si island différent

### ISSUE THREAD

**Issue by Warnel0** [RivrsMc/SeasonSky-Issues#346]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Warnell

### Pseudo discord

warnel0

### Que s'est-il passé ?

le /pay pour un joueur ,n'étant pas sur l'island-05 ne fonctionne pas toujours, voir screen

### Étapes à suivre pour reproduire le bug

payer un joueur dans une autre dimension que l'island-05

### Qu'aurait-il dû arriver ?

pas de message d'erreur sur le screen

### Date et heure de la production du bug

20-08 18:49:15

### Serveur

island-05

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/112425048/10727b91-c294-4668-a2ed-1fcb62ad04b4)

### Information supplémentaire

UUID: 6966561c-144c-40a6-b117-95d6af9b10ea
Position: -5424 146 1823 SuperiorWorld
Ping: 35ms

**Comment by ArDiDEx** [comment]
Hey le bug devrait être fix avec le restart de cette nuit
Merci du report
