### ISSUE TITLE
[BUG] /pay absent dans le tchat 

### ISSUE THREAD

**Issue by Warnel0** [RivrsMc/SeasonSky-Issues#347]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Warnell

### Pseudo discord

warnel0

### Que s'est-il passé ?

La commande /pay a été effectué pour un joueur présent sur le même serveur (island-05) mais aucun message dans le tchat n'a été affiché pour indiquer que le paiement a bien été envoyé, j'ai mp le joueur qui m'a pourtant confirmé bien avoir reçu l'argent, voir clip vidéo

### Étapes à suivre pour reproduire le bug

/pay un joueur

### Qu'aurait-il dû arriver ?

voir dans le tchat "vous avez envoyé X :coins: à X

### Date et heure de la production du bug

21-08 00:14:38

### Serveur

island-05

### Screen / vidéo

https://youtu.be/NvMBoe51sHE

### Information supplémentaire

UUID: 6966561c-144c-40a6-b117-95d6af9b10ea
Position: -5408 153 1746 SuperiorWorld
Ping: 12ms

**Comment by ArDiDEx** [comment]
Hey, le bug devrait être fix avec le restart de cette nuit
Merci du report
