### ISSUE TITLE
[BUG] Perte de durabilité astronomique Epée avec le /forgeron

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#348]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

les épées avec le /forgeron (exemple : épée royale, sabre pirate, épée du chasseur fou) perde beaucoup de durabilité quand il y a des mobs stackés
Plus clairement si on tape des mobs ou il y a différents types de mobs (exemple les tours a mobs) le sweeping edge s'active et utilise X durabilité par rapport au mobs que ca touche (voir séquence vidéo pour montrer la perte astronomique de la durabilité)

### Étapes à suivre pour reproduire le bug

1. avoir une tour a mob ou aller au /pw solamobs et aller dans l'une des tours a mobs car il y a plein de stack de mobs
2. avoir une épée qui fonctionne avec la réparation en /forgeron
3. taper et voir que la dura tombe X par X et non 1 par 1 pour les coup données

### Qu'aurait-il dû arriver ?

les épées ne devrait perde que la dura dû au fait qu'elles tapent qu'un mob de façon pur et qu'elles tapent X mobs avec le sweeping edge

### Date et heure de la production du bug

21/08/2023 13:13

### Serveur

all

### Screen / vidéo

https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/d2b4acf3-d8af-4323-97bb-8407ff3d2b23

### Information supplémentaire

Les épées avec le /forgeron sont donc d'aucune utilité pour les joueurs si ca prend X de durabilité par coup car en quelques minute l'épée n'a plus de durabilité ce qui rend l'intéret des tours a mobs voir des spawner inutile

**Comment by ArDiDEx** [comment]
Hey, le bug devrait être fix avec le restart de cette nuit
Merci du report

**Comment by LupusArctos4** [comment]
D'accord merci
