### ISSUE TITLE
[BUG] Pet Boulbi Magenta - lvl 70 fermier

### ISSUE THREAD

**Issue by IDeltaCocoI** [RivrsMc/SeasonSky-Issues#349]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Delta_Coco

### Pseudo discord

Delta_Coco

### Que s'est-il passé ?

Le pet Boulbi Magenta obtenable au niveau 70 fermier ne donne pas les effets :
- 20% revente des Verrues du Nether
- 10% de doubler les Verrues du Nether

### Étapes à suivre pour reproduire le bug

1. Monter 70 fermier et /jobs claim
2. Vendre verrues au /sell all sans pets
3. Équiper le pets et vendre a nouveau
4. Le prix est le même

### Qu'aurait-il dû arriver ?

Avoir le boost de vente 20% sur les Verrues du Nether et le boost 10% de chance de doubler les Verrues

### Date et heure de la production du bug

21-08 17:17:59

### Serveur

island-02

### Information supplémentaire

UUID: 164a1969-f1b8-404a-b30c-bf5006af3fbf
Position: -1616 -47 -1877 SuperiorWorld
Ping: 17ms

**Comment by LuluxClient** [comment]
Fixed dès le prochain patch
