### ISSUE TITLE
[BUG] Les xp bottle du /xpbottle se font vendre au /sell all

### ISSUE THREAD

**Issue by Amateur2Drapeau** [RivrsMc/SeasonSky-Issues#35]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MaelEnFrance

### Pseudo discord

maelenfrance

### Que s'est-il passé ?

Un joueur avait 6 bottlexp créé avec le /bottlexp et lorsqu'il a /sell all elles se sont vendus

### Étapes à suivre pour reproduire le bug

Avoir des bottle du /bottlexp et /sell all

### Qu'aurait-il dû arriver ?

Elles n'auraient pas dû se vendre

### Date et heure de la production du bug

09-07 13:30:31

### Serveur

island-06

### Information supplémentaire

UUID: ccf4c91d-a9da-442e-94df-2a03f6b3cb1a
Position: 5375 38 -3594 SuperiorWorld
Ping: 14ms

**Comment by NoHere32** [comment]
Ajout possibilité de changer le material / custom model data dans le module pour faire une diff dans le shop

**Comment by itsme-to** [comment]
Fixé
