### ISSUE TITLE
[BUG] Message d’alerte BM

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#350]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267 

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

Les messages d’alerte du black marcket n’est présent que dans les spawner alors qu’au début on l’avait même quand on était sur les monde Island 

### Étapes à suivre pour reproduire le bug

1. Être sur un monde island
2. Attendre 19h

### Qu'aurait-il dû arriver ?

Il devrait être afficher même si on se situe dans les mondes island

### Date et heure de la production du bug

21/08/2023 20:07

### Serveur

All

**Comment by LuluxClient** [comment]
J'ai appliqué un petit patch, tu me diras si demain tu as encore le soucis ^^

**Comment by LupusArctos4** [comment]
Merci et je te tiens au courant

**Comment by LupusArctos4** [comment]
@LuluxClient on n'a pas eu le message dans le serveur island 02 donc j'imagine que c'est la meme chose sur les autres serveurs

**Comment by LuluxClient** [comment]
> @LuluxClient on n'a pas eu le message dans le serveur island 02 donc j'imagine que c'est la meme chose sur les autres serveurs

j'ai pu tester et je n'ai aucun soucis: https://gyazo.com/5f46eb1e63db222e29e0b08648aaf3de (sur le island02)

**Comment by LupusArctos4** [comment]
C'est bizarre effectivement, je vais aller voir mes logs pour voir si je l'ai vraiment et qu'il est passer au travers dans le chat

**Comment by LupusArctos4** [comment]
ah mais c'est une annonce pour dire dans 15min, pourquoi ne pas en faire une 1min avant aussi ?
et je n'ai pu trouver de logs de mon chat, ils sont corrompus faut que je check pourquoi
je vais demander a mes mates de faire attention au message pour voir s'ils fonctionne vu que je ne peux pas etre présent

**Comment by LuluxClient** [comment]
> ah mais c'est une annonce pour dire dans 15min, pourquoi ne pas en faire une 1min avant aussi ? et je n'ai pu trouver de logs de mon chat, ils sont corrompus faut que je check pourquoi je vais demander a mes mates de faire attention au message pour voir s'ils fonctionne vu que je ne peux pas etre présent

Il y a une annonce:
- 900s 
- 600s
- 300s
- 60s
- 30s
- 15s
- 5s
avant le début des enchères

**Comment by LupusArctos4** [comment]
ah oui s'il y en a autant on l'aurai vu, c'est peut etre parce que tu es en mod admin que tu as pu le voir non ?

**Comment by LupusArctos4** [comment]
@LuluxClient regarde j'ai pas eu le message du BM dans les mondes islands par contre dans les mondes du spawn il y a bien les messages qui sont envoyer (c'est l'heure canadienne donc il faut faire +6h donc il est 19h en France
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/b4c4e784-62d0-430c-95a8-09bbfeb4dd0b)

**Comment by LuluxClient** [comment]
Hmm j'ai changé le système, tu me dirais si demain c'est tjr d'actu ou non ce soucis

**Comment by LupusArctos4** [comment]
je check ca samedi demain je ne suis pas dispo à 19h

**Comment by LupusArctos4** [comment]
je suis sur l'island 02 je n'ai toujours pas eu de message

**Comment by LupusArctos4** [comment]
aujourd'hui aussi je ne l'ais pas eu, et l'un de mes mates aussi alors qu'il était dans le spawn 03
je pense que le message ne s'affiche que dans le spawn 01 vu que l'un de mes mates était dans le spawn 01 et  à bien eu le message

je pense que pour palier à ce problème il faudrait faire le meme systeme que pour les jeux de chat, que le message est envoyer dans tous les serveurs en meme temps ou sur le chat global, je ne sais pas comment c'est gérer avec le multi serveur

**Comment by LuluxClient** [comment]
Je verrais ce soucis là car le message est un simple /broadcast et la
commande fonctionne bel et bien mais je vais voir si c un problème au
niveau du scheduler ou autre

Le dim. 3 sept. 2023 à 19:09, LupusArctos4 ***@***.***> a
écrit :

**Comment by LupusArctos4** [comment]
Ok très bien merci
