### ISSUE TITLE
[BUG] Casque divin level 71 fermier 

### ISSUE THREAD

**Issue by N4m4xx** [RivrsMc/SeasonSky-Issues#352]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Namaxx 

### Pseudo discord

Namaxx 

### Que s'est-il passé ?

Le casque divin n'est pas donné avec la commande /jobs claim au level 71 du job fermier

### Étapes à suivre pour reproduire le bug

1 Monter le job fermier au level 71
2 Faire la commande /jobs claim

### Qu'aurait-il dû arriver ?

Avoir le casque divin avec la commande /jobs claim

### Date et heure de la production du bug

19/08 vers 3h30

### Serveur

Is 03 

### Screen / vidéo

![image-10](https://github.com/RivrsMc/SeasonSky-Issues/assets/142924791/ede2675d-a5bc-428f-b12c-39b76ee2b877)

**Comment by LuluxClient** [comment]
Hello le casque divin n'est plus en récompense, l'affichage sera mis à jour dès la prochaine maj
