### ISSUE TITLE
[BUG] Coffre du fermier légendaire level 75 fermier 

### ISSUE THREAD

**Issue by N4m4xx** [RivrsMc/SeasonSky-Issues#353]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Namaxx 

### Pseudo discord

Namaxx 

### Que s'est-il passé ?

Le coffre du fermier légendaire n'est pas donné avec la commande /jobs claim au level 75 du job fermier

### Étapes à suivre pour reproduire le bug

1 Monter le job fermier au level 75
2 Faire la commande /jobs claim

### Qu'aurait-il dû arriver ?

Avoir le coffre du fermier légendaire avec la commande /jobs claim

### Date et heure de la production du bug

20/08 vers 23h30

### Serveur

Is 03 

### Screen / vidéo

![image-9](https://github.com/RivrsMc/SeasonSky-Issues/assets/142924791/e04ad7ac-39b1-4c0e-b882-6bce424e1a3e)

**Comment by LuluxClient** [comment]
Fixed dès la prochaine maj avec un remboursement, n'hésite pas à me mentionner sur cet issue pour ton remboursement **après** la maj

**Comment by N4m4xx** [comment]
Si jamais j'ai pas eu de remboursement

**Comment by LuluxClient** [comment]
> Namaxx

Desolé de l'attente, tu as été remboursé !
