### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by kenzotrindade** [RivrsMc/SeasonSky-Issues#354]
### Confirmation

- [x] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Sekigan__

### Pseudo discord

sekiigan_

### Que s'est-il passé ?

Je ne peux pas participer de concours de farm.

### Étapes à suivre pour reproduire le bug

Lorsque je casse la culture demandée lors du concours de farm cela n'augmente pas mes points.

### Qu'aurait-il dû arriver ?

J'aurais dû gagner des points

### Date et heure de la production du bug

23/08/2023 16h03

### Serveur

Seasonsky

### Screen / vidéo

https://youtu.be/JiSeGnHYOvk?si=Jy6yb7wR-abdU49Y

**Comment by LuluxClient** [comment]
Salut pourrais-tu m'indiquer le serveur ou tu étais (island01; island02...) et également si tu étais sur ton île et c'était quel culture ?

**Comment by kenzotrindade** [comment]
Je suis sur le Islande 02, j'étais bien sûr mon île lors du commencement du concours et la ressource était le blé, je teste tout les jours et aucune culture n'a l'air de marchée !
Je vous envoie un clip, sur ce clip la culture était la carotte !
https://youtu.be/JiSeGnHYOvk?si=Jy6yb7wR-abdU49Y

**Comment by LuluxClient** [comment]
Je n'arrive pas à reproduire ton soucis, mais @Kalouchette pourra enquêter aka l'auteur du plugin

**Comment by kenzotrindade** [comment]
Ah, mais ducoup sa fait déjà un moi que je ne peux faire aucun concours de farm, et donc la je pense 2 mois, je suis dégoûtée même si je sais que vous faites tout votre possible. 😐

**Comment by Alexis700** [comment]
Corrigé
