### ISSUE TITLE
[BUG] Table d'enchantement désactivée

### ISSUE THREAD

**Issue by Aschmeda** [RivrsMc/SeasonSky-Issues#355]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Aschmeda

### Pseudo discord

Scrowinchester

### Que s'est-il passé ?

Lors d'une deco reco j'ai constaté que toutes les tables d'enchantement etaient  désactivée. J'ai essayer une nouvelle fois une reconnexion puis de relancer le launcher Minecraft. Rien n'a changer. Je suis en 1.19.4, je n'utilise aucun client autre que Minecraft Launcher Vanilla. 

### Étapes à suivre pour reproduire le bug

Entrer dans l'interface de la table d'enchantement. Déposer un item à enchanter et ajouter le lapis lazuli.

### Qu'aurait-il dû arriver ?

Enchanter une cisaille.

### Date et heure de la production du bug

23 Aout 2023 aux alentours de 16h

### Serveur

Seasonsky (je ne sais pas sur quel serveur est mon île)

### Screen / vidéo

![20230823_155240](https://github.com/RivrsMc/SeasonSky-Issues/assets/143004887/b3223811-5d62-472c-9a4e-4b6e8d29572e)

**Comment by LuluxClient** [comment]
Salut @Aschmeda sur Minecraft on ne peut pas enchanter de cisailles dans la table d'enchantement, c'est une mécanique vanilla ! Merci d'utiliser une enclume pour l'enchanter !
