### ISSUE TITLE
[BUG] probléme d'accent sur les nom de /pw

### ISSUE THREAD

**Issue by LLucrece** [RivrsMc/SeasonSky-Issues#356]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

lucrece

### Pseudo discord

Lucrece

### Que s'est-il passé ?

Je posséde le /pw clé
un joueur possede le /pw cle

se joueur à  voulu faire une sponso avec son /pw cle et c'est moi qui ai obtenu la sponso avec le /pw clé

### Étapes à suivre pour reproduire le bug

prendre le nom d'un pw avec ou sans les accents

### Qu'aurait-il dû arriver ?

soit la creation du /pw est impossible soit le plugin les differencie correctement 

### Date et heure de la production du bug

23-08 17:05:06

### Serveur

tous

### Information supplémentaire

UUID: 66a43a59-81b5-4ac7-923a-67ba4e9e1d9d
Position: 16236 250 10737 SuperiorWorld
Ping: 66ms

**Comment by LuluxClient** [comment]
Hey le bug a déjà été fix mais les joueurs sont compté comme "dupliqué" il faudrait que tu rename ton warp ou vice versa mais merci de faire un ticket pour cela
