### ISSUE TITLE
[BUG]  Récompense palier 14 Alchimiste 

### ISSUE THREAD

**Issue by Zwartkat** [RivrsMc/SeasonSky-Issues#357]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Zwartkat 

### Pseudo discord

Zwartkat 

### Que s'est-il passé ?

La liste des récompenses dans l'interface n'est pas correcte pour le niveau 14 Alchimiste 

### Étapes à suivre pour reproduire le bug

1. /Jobs -> alchimiste 

### Qu'aurait-il dû arriver ?

Ne pas afficher 6 bonbons à la fraises dans les récompenses 

### Date et heure de la production du bug

23/08 18h

### Serveur

Tous

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/123319486/a92bb469-19f8-475d-a14f-22d67444fbe7)
![IMG_6287](https://github.com/RivrsMc/SeasonSky-Issues/assets/123319486/d6f413f1-c0f6-45c6-8a0c-b597d04777de)
##
# Information supplémentaire

_No response_

**Comment by LuluxClient** [comment]
Fixed et effectif dès la prochaine maj
