### ISSUE TITLE
[BUG] Zombie de la Zombiland Fleuve Secret

### ISSUE THREAD

**Issue by Jspppppp** [RivrsMc/SeasonSky-Issues#358]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Jspppppp

### Pseudo discord

Mathéo#8230 / Jspppppp (l'ours)

### Que s'est-il passé ?

Il y a un zombie de la zone aventure Zombiland dans la zone du Fleuve secret 

### Étapes à suivre pour reproduire le bug

Se rendre au cordonée du screen et voir le zombie

### Qu'aurait-il dû arriver ?

0 Zombie de la ZombieLand 

### Date et heure de la production du bug

All

### Serveur

Aventure : " Fleuve secret " 

### Screen / vidéo

![2023-08-23_19 54 43](https://github.com/RivrsMc/SeasonSky-Issues/assets/139492099/1439acd1-6370-41a0-83ea-2988740d617f)

**Comment by LuluxClient** [comment]
Il ne devrait plus apparaître dès la prochaine maj
