### ISSUE TITLE
[BUG] Husk Mission montres

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#359]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

les husk ne comptent plus dans les quetes montres depuis le patch note de lundi

### Étapes à suivre pour reproduire le bug

1. tuer des husk avec la mission montres dans l'inventaire

### Qu'aurait-il dû arriver ?

il devrait compté dans montres si on n'a pas de missions tuer des husk sur soit

### Date et heure de la production du bug

23/08/2023 19:11 (heure canadienne) 

### Serveur

all

**Comment by LuluxClient** [comment]
Hello ! Tu avais quelle difficulté de mission puisque je n'ai aucun soucis de mon côté ?

**Comment by LupusArctos4** [comment]
C'était une erreur j'ai oublier de le close
