### ISSUE TITLE
[BUG] Scoins caisse premium monde aventure 

### ISSUE THREAD

**Issue by Zwartkat** [RivrsMc/SeasonSky-Issues#36]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Zwartkat 

### Pseudo discord

Zwartkat 

### Que s'est-il passé ?

Impossible d'acheter les boxes premium des mondes aventures avec Scoins 

### Étapes à suivre pour reproduire le bug

1. Avoir des Scoins pour essayer d'acheter

### Qu'aurait-il dû arriver ?

Achat de la caisse (sûrement ancienne config pas adapté aux nouveaux Scoins)

### Date et heure de la production du bug

13:50 9/07

### Serveur

Spawn

**Comment by NoHere32** [comment]
good au prochain redem
