### ISSUE TITLE
[BUG] Pépite d'or

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#360]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

les coffres de vente type royal et fermier ne vendent pas les pépites d'or car elles ne sont pas présente dans le /shop 

### Étapes à suivre pour reproduire le bug

1. avoir un coffre de vente (fermier ou royal)
2. mettre en mode vente sans destruction
3. le charger pour qu'il vend les items de son coffre
4. mettre des pépites d'or
5. voir qu'apres 10s (temps entre chaque vente du coffre) les pépites sont toujours dans le coffre de vente

### Qu'aurait-il dû arriver ?

le lingot d'or est a 7$ donc il faudrait que la pépite d'or soit à 0.8$ afin que les coffres de vente automatique puisse les vendres

### Date et heure de la production du bug

24/08/2023 17:33 (heure canadienne) 

### Serveur

all

**Comment by LuluxClient** [comment]
Tu as une option pour supprimer les items qui ne se vendent pas néanmoins le pépites d'or vont être rajouté dès la prochaine maj et cela devrait bien fonctionner
