### ISSUE TITLE
[BUG] Clé

### ISSUE THREAD

**Issue by DuFxonz** [RivrsMc/SeasonSky-Issues#361]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Octambulle

### Pseudo discord

Octambulle

### Que s'est-il passé ?

Lorsque j'ai des clés de vote et que j'obtiens un loot consommable (plume de fly, rune de vente, ...) celui-ci s'active directement après avoir utilisé ma dernière clé.

### Étapes à suivre pour reproduire le bug

Prendre UNE clé de vote, esperer tomber sur un loot consommable (plume de fly, rune de vente, ...) et elle s'active

### Qu'aurait-il dû arriver ?

Qu'elle ne s'active pas

### Date et heure de la production du bug

23h35

### Serveur

Eldoria

**Comment by Warnel0** [comment]
Garde une plume de chaque dans ton inventaire, les prochaines seront stack avec normalement ce qui t'empêchera de les utiliser

**Comment by DuFxonz** [comment]
> Garde une plume de chaque dans ton inventaire, les prochaines seront stack avec normalement ce qui t'empêchera de les utiliser

Oui c'est une solution mais ça reste quand même un bug présent xD

**Comment by ArDiDEx** [comment]
Hello le bug sera fix au prochain redem
Merci du report
