### ISSUE TITLE
[BUG] redstone lors de la connexion du compte

### ISSUE THREAD

**Issue by xXcobrarougeXx** [RivrsMc/SeasonSky-Issues#362]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

xXcobrarougeXx

### Pseudo discord

cobrarouge58

### Que s'est-il passé ?

Depuis 2 jours, dès que je me co, les circuits redstones sont disfonctionnelles alors que ça fonctionner très bien avant (circuit en courant continue et wagonné à l'arret complet). Report faite sur demande de la modération.

### Étapes à suivre pour reproduire le bug

Juste se connecter et spawn sur l'ile 

### Qu'aurait-il dû arriver ?

que les circuits fonctionnent normalement comme avant.

### Date et heure de la production du bug

25-08 01:19:29

### Serveur

island-03

### Information supplémentaire

UUID: f2118b72-24df-4be8-a2e8-1c20ff068acb
Position: 34215 89 -3587 SuperiorWorld
Ping: 43ms

**Comment by Warnel0** [comment]
la redstone est sensible si elle est setup sur plusieurs chunk peut-etre pour ça ?

**Comment by LuluxClient** [comment]
Salut @xXcobrarougeXx je ne vois pas de soucis, néanmoins si le chunk est déchargé il se peut que la redstone ne fonctionne plus !

**Comment by xXcobrarougeXx** [comment]
Bonjour,

Depuis quelques jours le soucis a disparu sans rien faire. Peut être une
instabilité temporaire. Merci d'avoir pris le temps de regarder.

Bonne journée,

Cordialement

Le mar. 29 août 2023, 14:53, Luca Améaume ***@***.***> a
écrit :
