### ISSUE TITLE
[BUG] Amétiste limite 

### ISSUE THREAD

**Issue by SuityChan** [RivrsMc/SeasonSky-Issues#363]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

SuityChan

### Pseudo discord

_suity

### Que s'est-il passé ?

Lorsqu'on pose 10 amétiste sur l'is, il est impossible de le casser en ensuite le reposer. Comme le bug des spawners il fut un temps. 

### Étapes à suivre pour reproduire le bug

Posé 10 druse d'amétiste, en cassé 1 et vouloir en reposé 1

### Qu'aurait-il dû arriver ?

La druse aurais du se poser car la limité était pas atteinte

### Date et heure de la production du bug

24/08/2023

### Serveur

SeasonSky

**Comment by LuluxClient** [comment]
Hello tu mines ta druse avec quel pioche (ses encahntements et effets)
