### ISSUE TITLE
[BUG] pet fantasia cyan

### ISSUE THREAD

**Issue by ourstordu** [RivrsMc/SeasonSky-Issues#364]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

ourstordu

### Pseudo discord

ourstordu

### Que s'est-il passé ?

Le pet fantasia cyan quand il est au niveau 15 donne un effet de brillance. Cependant si l'on a déjà d'équiper le pet, il nous donne bien l'effet mais si l'on va au spawn ou que l'on est téléporté n'importe où l'effet s'arrête et pour le réactiver il faut déséquiper le pet et le rééquiper.

### Étapes à suivre pour reproduire le bug

1. Mettre un pet fantasia cyan au niveau 15
2. Equiper le pet dans le familier actif sur soi 
3. Voir que l'effet de surbrillance fonctionne
4. Ce téléporter au spawn ou dans un monde aventure
5. Voir que l'effet ne s'applique plus
6. Déséquiper et rééquiper le pet pour que l'effet refonctionne

### Qu'aurait-il dû arriver ?

Le pet aurait du nous donner l'effet même si on se téléporte autre part sans avoir besoin de le déséquiper et de le rééquiper.

### Date et heure de la production du bug

26/08/23

### Serveur

Tous

### Screen / vidéo

J'ai une vidéo mais elle est trop lourde dites moi si vous la voulez vraiment.

**Comment by LuluxClient** [comment]
Le soucis provient peut être du système de glow qui clear ton effet

**Comment by ArDiDEx** [comment]
Hey ça devrait être réglé au prochain redémarrage
Merci du report
