### ISSUE TITLE
[BUG] Epée avec le /forgeron

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#365]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

apres les problèmes corrigés, on a découvert un nouveau problème
quand on touche un mob avec le sweeping edge mais qu'il meurt par le cramming entity, une durabilité est consommé à l'épée ce qui utiliser par moment plus d'une vingtaine de durabilité en une seule coup

### Étapes à suivre pour reproduire le bug

1. avoir une épée avec /forgeron (l'épée du fou est parfaite pour les test car elle a un moins bon niveau de sweeping edge)
2. avoir des mobs qui dépasse le cramming entity (de préférence les enderman car ils ont plus de PV)
3. taper et voir que la durabilité baisse bien plus qu'un coup

### Qu'aurait-il dû arriver ?

la durabilité devrait etre réduit de 1
par pallier à cela faudrait peut etre essayer de configurer le fait qu'elle perd 1 de durabilité par utilisation et pas par touche de mobs

### Date et heure de la production du bug

26/08/2023 21:51 (heure canadienne) 

### Serveur

all

**Comment by LuluxClient** [comment]
Je viens de voir que l'entity cramming n'a pas été augmenté comme indiqué en prod, normalement il a bien été up partout donc ton problème ne devrait plus y arriver, néanmoins pour ton souci que tu as report je pense que c'est lié au fonctionne de minecraft vu que le mob meurt et que tu avais ton épée en main. Je laisse ce report de côté pour le moment

**Comment by LupusArctos4** [comment]
ok mais du coup si l'entity cramming est augmenté ça voudrait dire que le problème sera encore plus présent avec l'épée du fou qui a un sweeping edge lvl 3 qui est beaucoup moins puissant dans les grosses tours a mobs donc au lieu de prendre genre 50 durabilité par coup, ca prendra peut etre 100 de durabilité 
par conséquent, il faudrait peut etre changer la méthode de décompte d'une utilisation /forgeron

**Comment by LuluxClient** [comment]
> ok mais du coup si l'entity cramming est augmenté ça voudrait dire que le problème sera encore plus présent avec l'épée du fou qui a un sweeping edge lvl 3 qui est beaucoup moins puissant dans les grosses tours a mobs donc au lieu de prendre genre 50 durabilité par coup, ca prendra peut etre 100 de durabilité par conséquent, il faudrait peut etre changer la méthode de décompte d'une utilisation /forgeron

Non vu que j'ai augmenter le nombre de mob qu'il faut pour qu'ils prennent des dégâts donc il ne devront plus mourrir par la suffocation mais comme indiqué je laisse ce problème de côté puisqu'on travail sur quelque chose à ce niveau

**Comment by LupusArctos4** [comment]
ok d'accord
