### ISSUE TITLE
Épée elfique 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#366]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0isan

### Pseudo discord

Nami

### Que s'est-il passé ?

Alors l'épée elfique est censé se réparer au forgerons sauf que cela ne fonctionne pas du tout vu avec deux joueurs déjà. 

### Étapes à suivre pour reproduire le bug

Prendre l'épée elfique en main faire le /forgeron
Cliquer dessus 

### Qu'aurait-il dû arriver ?

Pouvoir le réparer avec le forgeron 

### Date et heure de la production du bug

27/08 12h38

### Serveur

Global

**Comment by LuluxClient** [comment]
fixed
