### ISSUE TITLE
[BUG] pets chasseur ne marche pas 

### ISSUE THREAD

**Issue by carotteorange** [RivrsMc/SeasonSky-Issues#367]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

carotteorange

### Pseudo discord

carotteorange

### Que s'est-il passé ?

les pets qui donne 20 15% de metier chasseur ne marche pas 

### Étapes à suivre pour reproduire le bug

equiper les pets puis taper des mobs revien au meme que sans 

### Qu'aurait-il dû arriver ?

avoir + 20% en plus niveau xp donner

### Date et heure de la production du bug

27/08 23h

### Serveur

le serveur 4

**Comment by LuluxClient** [comment]
Hello pourrais-tu m'indiquer les noms des pets qui posent problème
