### ISSUE TITLE
[BUG] Armes évolutives 

### ISSUE THREAD

**Issue by IDeltaCocoI** [RivrsMc/SeasonSky-Issues#369]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Delta_Coco

### Pseudo discord

Delta_Coco

### Que s'est-il passé ?

On ne peut pas améliorer les armes évolutives à partir du niveau 3. L'affichage est bug.

### Étapes à suivre pour reproduire le bug

1.	Avoir une arme évolutive
2.	La monter niv. 3
3.	Voir que ça bug

### Qu'aurait-il dû arriver ?

Pouvoir améliorer son arme évolutive au dessus du niveau 3

### Date et heure de la production du bug

28-08 00:15:45

### Serveur

island-02

### Screen / vidéo

![Capture d'écran 2023-08-28 001458](https://github.com/RivrsMc/SeasonSky-Issues/assets/141357456/4de9cd2a-2a42-40b5-aa65-590443fce2f3)

### Information supplémentaire

UUID: 164a1969-f1b8-404a-b30c-bf5006af3fbf
Position: -1786 100 -1802 SuperiorWorld
Ping: 18ms

**Comment by LuluxClient** [comment]
Bonjour ! Merci du report, l'item fonctionne bien uniquement l'affichage est bug, Ardidex est dessus pour appliquer un petit fix au plus vite !

**Comment by ArDiDEx** [comment]
Hello
ça devrait être fix
Merci du report
