### ISSUE TITLE
[BUG] Synchronisation du tab

### ISSUE THREAD

**Issue by Slylokss** [RivrsMc/SeasonSky-Issues#37]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Slyyyyy_

### Pseudo discord

Sly

### Que s'est-il passé ?

Le système de tab rencontre des problèmes de synchronisation entre les servers spawn et île, ainsi, nous ne pouvons pas voir tout les joueurs connectés, d'autres apparaissent au dessus des hauts staff et nous ne pouvons pas rechercher un joueur avec tab. 

### Étapes à suivre pour reproduire le bug

Faire tab et consulter la liste des joueurs actifs ou bien rechercher un joueur avec tab.

### Qu'aurait-il dû arriver ?

Afficher tous les joueurs connectés et les placer au bon endroit et les afficher lors de la cherche par pseudo.

### Date et heure de la production du bug

8 Juillet, 16h.

### Serveur

Tous servers

**Comment by LuluxClient** [comment]
Le tab n'est pas syncro pour le moment.
