### ISSUE TITLE
[BUG] Commande avec caractère en MAJ

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#370]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

certaines commandes peuvent etre écrit en maj et d'autres non 

### Étapes à suivre pour reproduire le bug

1. faire /farm et /FARM => fonctionne
2. faire /ah et /AH => ne fonctionne pas

### Qu'aurait-il dû arriver ?

ca devrait toujours fonctionner si on se base sur la table ASCII 
on peut utiliser : toLowerCase() si le code est en java / javascript pour les plugins lors de l'exécution de la commande

### Date et heure de la production du bug

27/08/2023 20:59 (heure canadienne) 

### Serveur

all

**Comment by LuluxClient** [comment]
C'est les dernières version de minecraft, plus aucun commande devrait fonctionner avec des majs

**Comment by LupusArctos4** [comment]
mais du coup pourquoi /farm peut etre écrit en majuscule et en minuscule sans poser de problème ?
