### ISSUE TITLE
[BUG] Mission Casser de la terre

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#371]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

la mission casser de la terre ne prend pas en compte les variantes de la terre comme le podzol, rooted ou la coarse dirt ainsi que la grass

### Étapes à suivre pour reproduire le bug

1. avoir une quete miner de la dirt
2. miner les différents type de dirt

### Qu'aurait-il dû arriver ?

miner n'importe quel type de dirt devrait compté dans la mission

### Date et heure de la production du bug

28/08/2023 13:43 (heure canadienne) 

### Serveur

all

**Comment by LuluxClient** [comment]
Bonjour et merci du report ! J'ai rajouté le support des variantes de terre qui devront être effectif dès la prochaine maj
