### ISSUE TITLE
[BUG] Boost Actif

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#372]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

on ne sait pas quand on active combien il reste de temps alors que dans la boss bar il y a un indicateur qui devrait fonctionner

### Étapes à suivre pour reproduire le bug

1. avoir un boost (ici un boost xp global)
2. l'activer
3. rien ne se passe dans la boss barre

### Qu'aurait-il dû arriver ?

un compteur devrait se lancer en fonction de la durée du boost

### Date et heure de la production du bug

28/08/2023 22:37 (heure canadienne) 

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/7fc9bed3-6e5d-4b08-8f39-06c5abfd70d9)

**Comment by LuluxClient** [comment]
Hello pourrais-tu m'indiquer quel boost tu utilises qui ne s'affichent pas ? j'ai pu débug de mon côté et test pas mal de choses mais pour m'assurer que tout fonctionne bien avant de le mettre en prod

**Comment by LupusArctos4** [comment]
C'était un boost qu'on obtient dans le pass donc je crois que c'est un 30% classique qu'on obtient sans le /vip

**Comment by LupusArctos4** [comment]
voici tres exactement le boost utiliser : 
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/73d23b26-7eeb-43a8-8389-94ad6651998b)

**Comment by Alexis700** [comment]
Fix
