### ISSUE TITLE
[BUG] /pass pallier #19

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#373]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

j'ai reçu 2 fois la récompense ce qui correspond au fait que je sois premium or je ne le suis pas

### Étapes à suivre pour reproduire le bug

1. passer le pallier #19 farmium 
2. récuper la récompense sans etre premium

### Qu'aurait-il dû arriver ?

on ne devrait recevoir qu'une fois la récompense car ca nous fait monter de 10 lvl skyblock au lieu de 5

### Date et heure de la production du bug

28/08/2023 22:39 (heure canadienne) 

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/5fb004af-6dbc-41af-9f93-3e0876c777c7)

**Comment by Alexis700** [comment]
Corriger
