### ISSUE TITLE
[BUG] x3 loot !!! Canne a peche royale

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#374]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

avec la canne a peche royale la compétence de pécher double est en fait de pécher triple, je m'explique, quand on peche on a une probabilité de pécher double (ce qui est marquer sur la description de l'item) mais ca donne l'item pécher + 2 items en double du coup et non juste + 1

### Étapes à suivre pour reproduire le bug

1. avoir une canne a peche royale
2. pecher exemple un livre
3. avoir 3 fois le livre au lieu de 2

### Qu'aurait-il dû arriver ?

on aurait du avoir 2 items au lieu de 3 en finalité

### Date et heure de la production du bug

29/08/2023 09:33 (heure canadienne) 

### Serveur

all

**Comment by LuluxClient** [comment]
Fixed dès la prochaine maj !
