### ISSUE TITLE
[BUG] Bouton retirer tous les cosmétiques

### ISSUE THREAD

**Issue by Jspppppp** [RivrsMc/SeasonSky-Issues#375]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Jspppppp

### Pseudo discord

Mathéo#8230 / Jspppppp (l'ours)

### Que s'est-il passé ?

On n'a pas la perm d'utiliser le bouton

### Étapes à suivre pour reproduire le bug

Faire /cosmetics
Clique sur le bouton en bas à droit
Regarder son tchat pour voir : " Vous n'avez pas la permission de le faire ! " 

### Qu'aurait-il dû arriver ?

Pouvoir utiliser le bouton

### Date et heure de la production du bug

All

### Serveur

Spawn (partout je pence)

**Comment by LuluxClient** [comment]
Fixed
