### ISSUE TITLE
[BUG] Houe Ultime

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#377]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

la description à un problème dans la partie du /forgeron : 4000 / 2000

### Étapes à suivre pour reproduire le bug

1. avoir ou voir une houe divine

### Qu'aurait-il dû arriver ?

elle devrait etre à 4000 / 4000

### Date et heure de la production du bug

30/08/2023 07:19 (heure canadienne) 

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/53342422-30da-420e-abd0-900dc3b74ab0)

**Comment by mrsxnshxne** [comment]
Hey !
Le soucis était le 4000, la durabilité est à 2000, merci du report je ferme l'issue !
