### ISSUE TITLE
Bug épée chasseur fou

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#378]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0iSan

### Pseudo discord

Nami

### Que s'est-il passé ?

En gros Quand nous avons un arc en deuxième mains et qu'on utilise l'arc l'épée perd une dura, ensuite quand tu tape des mobs pendant x temps, l'épée continue a s'utiliser comme sur la vidéo et ça lui fait perdre de la dura et le 25% de vitesse d'attaque en plus (pour moi en tout cas) ne fonctionne plus

Ticket @cleroxis 

### Étapes à suivre pour reproduire le bug

Farm avec les deux 

### Qu'aurait-il dû arriver ?

. 

### Date et heure de la production du bug

30/08 17h19

### Serveur

Global

### Screen / vidéo

https://youtu.be/Z6dprku9eTs

**Comment by LupusArctos4** [comment]
l'épée perd de la dura "toute seule" car << c'est lié au fonctionne de minecraft vu que le mob meurt et que tu avais ton épée en main >> (lulux dans le ticket #365 )

**Comment by LuluxClient** [comment]
La vidéo n'est pas la bonne et comme expliqué tout est dans l'issue #365
