### ISSUE TITLE
[BUG] Multitool

### ISSUE THREAD

**Issue by Pireus91** [RivrsMc/SeasonSky-Issues#379]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Pireus

### Pseudo discord

Pireus

### Que s'est-il passé ?

Le multitool du pirate ne s'ajoute pas a la collection malgré le /collections
J'ai essayer de faire un forgeron et cela n'as rien changer.
je reste a 16/17 dans la collection

### Étapes à suivre pour reproduire le bug

faire un /collection avec le multitool en main

### Qu'aurait-il dû arriver ?

avoir l'items dans la collection

### Date et heure de la production du bug

30/08/2023 à 19h02

### Serveur

island-03

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139948498/ad9f05d5-3f8c-484b-bd19-f8a5dbf1702f)

### Information supplémentaire

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139948498/f3d4e7b4-2da5-475b-90dd-35858a6ba3d4)

**Comment by LuluxClient** [comment]
Hello je n'ai pas le souci en dev ni en prod, j'ai changé ta multi tool pour voir si ça fix le problème sinon je t'invite à me ping ici lorsque tu es co pour voir ça ensemble !

**Comment by Pireus91** [comment]
@LuluxClient bonjour, le problème n'ai pas régler, toujours pas de multitools afficher dans la collection
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139948498/3f1a9777-9294-4263-b7a0-77e99a1f4c40)

**Comment by LuluxClient** [comment]
Hello tu peux me ping lorsque tu es dispo en vocal / connecté IG pour voir ça
