### ISSUE TITLE
[BUG] Compacteur ghost bloc

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#38]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

casser le bloc sous un compacteur 

### Étapes à suivre pour reproduire le bug

1. poser un compacteur
2. casser le bloc sous le compacteur

### Qu'aurait-il dû arriver ?

il ne devrait pas avoir a buger comme ca

### Date et heure de la production du bug

09/07/2023 15:06

### Serveur

island 02

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/2f592adf-a9e8-41b1-84d2-5c1d8f66516f)

**Comment by LuluxClient** [comment]
Salut je n'ai pas trop compris le soucis, pourrais-tu détaillé un peu plus ?

**Comment by LupusArctos4** [comment]
en gros on avait un compacteur et un eclozr de poser mais on a casser les blocs en dessus de ses derniers et c'est devenu des ghost bloc qu'un staff (isweazu) et venu nous remboursé

**Comment by LupusArctos4** [comment]
d'ailleurs si on veut le reposer au meme endroit ca nous dit ca : 
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/b93b9c0b-f8bc-4c11-a7d2-2eb40f8e5852)

**Comment by LuluxClient** [comment]
Je n'arrive pas à le reproduire en mettant des blocs en dessous et au dessus et en les cassants, si tu peux me faire une vidéo je ne dis pas non

**Comment by LupusArctos4** [comment]
moi non plus je n'arrive plus a le faire
mais le screen au dessus voila le record
https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/87cd4dec-3499-45fd-b918-54cbff12b858

**Comment by itsme-to** [comment]
Normalement corrigé
