### ISSUE TITLE
[BUG] /cosmetic

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#380]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

on ne peut pas retrouver en arriere dans le /cosmetic dans la page des chapeaux

### Étapes à suivre pour reproduire le bug

1. faire /cosmetic
2. aller a la page suivante dans la catégorie chapeau

### Qu'aurait-il dû arriver ?

on devrait pouvoir revenir en arriere

### Date et heure de la production du bug

30/08/2023 17:49 (heure canadienne) 

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/2120d275-23b9-4344-bfab-819766cc7324)

**Comment by mrsxnshxne** [comment]
Hey, je viens de corriger le bug :
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/84781573/d3455f96-76b3-4ca5-9ac7-8aad232a56d0)
Merci du report ! Je ferme l'issue
