### ISSUE TITLE
[BUG] Epée Ultime

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#382]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

l'épée ultime ne vend pas automatiquement

### Étapes à suivre pour reproduire le bug

1. avoir l'épée ultime
2. taper des mobs

### Qu'aurait-il dû arriver ?

ca devrait vendre auto comme l'indique sa description

### Date et heure de la production du bug

30/08/2023 18:16 (heure canadienne) 

### Serveur

all

**Comment by LuluxClient** [comment]
Merci du report, cela sera fix dès le redem de ce soir !

**Comment by LuluxClient** [comment]
Petit soucis de dernière minute qui doit annuler mon patch, je le réouvre et on travail dessus

**Comment by ArDiDEx** [comment]
Hey le bug sera réglé au prochain restart
Merci du report
