### ISSUE TITLE
[BUG] tunique pirate

### ISSUE THREAD

**Issue by Shymul** [RivrsMc/SeasonSky-Issues#383]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Shymul

### Pseudo discord

shymul

### Que s'est-il passé ?

depuis le 30/08 ma tunique pirate ne me procure plus l'effet speed 2  (g déja essayé de la mettre dans ma main et de clic droit / de déco reco )

### Étapes à suivre pour reproduire le bug

aucune idée

### Qu'aurait-il dû arriver ?

la tenue aurait du continué de me donné ses effets 

### Date et heure de la production du bug

ver 16h au moment de ma connexion le 30/08

### Serveur

tous

### Screen / vidéo

![Capture d’écran (135)](https://github.com/RivrsMc/SeasonSky-Issues/assets/139829298/83579aa0-b7a3-4feb-bd4e-e3e17482e084)
![Capture d’écran (136)](https://github.com/RivrsMc/SeasonSky-Issues/assets/139829298/89924a6e-5eec-469f-a44d-0442e13c61a5)

**Comment by LuluxClient** [comment]
Hello je n'ai pas de soucis en dev ni en prod, assure toi de faire un clic droit avec ton objet dans ta hotbar et ça devrait bien te donner l'effet !

**Comment by Shymul** [comment]
bonjour est ce qu'il serait au moins possible que je vous rende ma tunique
mending  et que vous m'en donniez une autre car  faire clic droit ne marche
pas .
