### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Noelenoob** [RivrsMc/SeasonSky-Issues#384]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

noelenoob

### Pseudo discord

noelenoob

### Que s'est-il passé ?

Ecorcer le bois d'un arbre (warped trees précisément) avant de le miner empêche le métier de bûcheron d'évoluer, alors qu'en principe n'importe quel type de bois écorcé rapporte plus d'expérience que le bois brut. (J'ai essayé la hache héroïque, hache du charpentier et hache en diamant classique, ça ne fonctionnait pas. Le seul arbre pour lequel cela a fonctionné est un arbre d'une vingtaine de bloc environ (hasard ?). Lorsque je me suis reconnecté quelques heures plus tard également, un arbre déjà écorcé m'a rapporté de l'xp mais pas les autres, et les troncs que j'ai écorcé par la suite non plus. Le bois brut en revanche procure de l'expérience sans soucis.

### Étapes à suivre pour reproduire le bug

1) Ecorcer un arbre
2) Casser le tronc avec une hache

### Qu'aurait-il dû arriver ?

J'aurais dû recevoir de l'expérience et faire avancer mon métier de bûcheron, mais cela ne fonctionne pas du tout. 

### Date et heure de la production du bug

31-08 19:44:02

### Serveur

island-02

### Information supplémentaire

UUID: e4345a7c-7f20-4bb1-a113-5d6735ced999
Position: -35971 100 27010 SuperiorWorld
Ping: 10ms

**Comment by Alexis700** [comment]
ça ne sera pas changé, c'est dû au fait que tu fasses 2 actions trop rapidement, c'est pour éviter des potentiels problèmes qu'il y a cette restriction
