### ISSUE TITLE
[BUG] Affichage des textures dans les pnj des mondes aventures

### ISSUE THREAD

**Issue by IDeltaCocoI** [RivrsMc/SeasonSky-Issues#385]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Delta_Coco

### Pseudo discord

Delta_Coco

### Que s'est-il passé ?

La texture et le nom des items des monde aventures n'a pas changé.

### Étapes à suivre pour reproduire le bug

1.  /aventure
2. Aller sur un monde aventure
3. Ouvrir le pnj pour les taux de drop
4. Voir que les items n'ont pas changés

### Qu'aurait-il dû arriver ?

Modification de la texture des items des mondes aventures dans les pnj

### Date et heure de la production du bug

01-09 00:47:48

### Serveur

island-02

### Screen / vidéo

![2023-09-01_00 46 51](https://github.com/RivrsMc/SeasonSky-Issues/assets/141357456/7dff00dd-1b95-4d14-a140-33c1ff0927b5)
![2023-09-01_00 47 02](https://github.com/RivrsMc/SeasonSky-Issues/assets/141357456/6867dcce-95e0-4e77-be2e-bb745ab40bb7)
![2023-09-01_00 47 15](https://github.com/RivrsMc/SeasonSky-Issues/assets/141357456/a7fd7aa8-330d-4b4d-b4c3-c7a37d1b351b)
![2023-09-01_00 47 23](https://github.com/RivrsMc/SeasonSky-Issues/assets/141357456/8df261f2-c0db-49fe-9d53-121371dd1c82)
![2023-09-01_00 46 44](https://github.com/RivrsMc/SeasonSky-Issues/assets/141357456/2bf16e06-e646-41a9-a925-fb6119c4287e)

### Information supplémentaire

UUID: 164a1969-f1b8-404a-b30c-bf5006af3fbf
Position: -1760 177 -1792 SuperiorWorld
Ping: 9ms

**Comment by mrsxnshxne** [comment]
Hello !
Merci du report, c'est corrigé au prochain redémarrage !
