### ISSUE TITLE
[BUG] Classement farmium

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#386]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

le classement farmium a été reset en meme temps que le pass ce qui fausse le classement de cette fin de semaine

### Étapes à suivre pour reproduire le bug

1. faire /farm
2. voir que le classement à changer (le nombre de points que les gens ont à changer)

### Qu'aurait-il dû arriver ?

ca n'aurait pas du reset aussi avec le changement de mois, les données liées à la semaine devraient eter dissocié dans la BDD au donnée du mois lors du reset (clear des données du mois)

### Date et heure de la production du bug

31/08/2023 22:23 (heure du québec)

### Serveur

all

**Comment by mrsxnshxne** [comment]
Hello !
Malheureusement, maintenant clear nous ne pouvons pas faire machine arrière.
Le bug quant à lui a été fix, je ferme l'issue, merci du report !
