### ISSUE TITLE
[BUG] Craft Bois maléfique

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#387]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

on peut crafter le bois maléfique avec la tazanite violette obtenu lors d'un vieux bug dans une dimension (qui avait été très vite corriger mais les personnes qui en ont en leur possession peuvent les utiliser à la place de la Malachite violette qui à la meme texture)

### Étapes à suivre pour reproduire le bug

1. avoir de la tanzanite violette
2. crafter le bois maléfique

### Qu'aurait-il dû arriver ?

on ne devrait pas pouvoir utiliser la tanzanite violette dans le craft du bois maléfique

### Date et heure de la production du bug

31/08/2023 22:45 (heure du québec)

### Serveur

all

**Comment by mrsxnshxne** [comment]
Hello, 
Je note le soucis et je regarde ça!
La tanzanite était anciennement la malachite, elle s'obtenait de la même façon donc ce n'est pas tant un grand soucis
