### ISSUE TITLE
[BUG] Tuto island partie IS level

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#388]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

dans le tuto de l'island, un moment ca nous demande de mettre de la sélénite brute (donner par le tuto) dans le cristal or le minerais ayant changer la quete ne peut plus se faire de plus le principe d'is level ayant changer meme avec le nouveau minerais cela ne pourrait pas fonctionner

### Étapes à suivre pour reproduire le bug

1. etre un nouveau joueur
2. faire le tuto
3. essayer de mettre la sélénite brut dans le cristal comme demander

### Qu'aurait-il dû arriver ?

ca devrait nous donner un cristal renforcé car lui on peut l'ajouter dans le cristal afin que ca compte dans les is level

### Date et heure de la production du bug

31/08/2023 22:55 (heure du québec)

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/95fb4327-1072-4176-b840-e8ecbe6a1e1e)

### Information supplémentaire

Rien à voir avec le report : merci à isaac____ pour le report (et bon dodo à toi si tu passes par là)

**Comment by mrsxnshxne** [comment]
Hello !
La sélénite a ét changé par un bloc d'émeraude, ça sera effectif au prochain redémarrage !
