### ISSUE TITLE
[BUG] Philo beige job alchi

### ISSUE THREAD

**Issue by hija621** [RivrsMc/SeasonSky-Issues#389]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Hija621

### Pseudo discord

hija621

### Que s'est-il passé ?

Quand nous passons au lvl 40 du jobs alchimiste, nous  n'obtenons pas le pet "philo beige" en récupérant les récompenses

### Étapes à suivre pour reproduire le bug

Récupérer les récompenses du palier alchimiste

### Qu'aurait-il dû arriver ?

Obtention du pet

### Date et heure de la production du bug

01/09 9h

### Serveur

All

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/135941180/87775e6a-b868-483f-94f5-37eb228da090)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/135941180/bc724436-7db0-4b98-8b97-b0c6185c0754)

**Comment by LuluxClient** [comment]
Salut le pet se donne virtuellement dans ton /pets !
