### ISSUE TITLE
[BUG] Boulbi doré 

### ISSUE THREAD

**Issue by Zwartkat** [RivrsMc/SeasonSky-Issues#39]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Zwartkat 

### Pseudo discord

Zwartkat 

### Que s'est-il passé ?

Summon du Boulbi jaune doré avec texture du nain de la mine 

### Étapes à suivre pour reproduire le bug

1. Summon du pet Boulbi jaune doré 

### Qu'aurait-il dû arriver ?

Texture de Boulbi jaune doré sur le pet summon

### Date et heure de la production du bug

16:20 09/07

### Serveur

Tous

**Comment by NoHere32** [comment]
good au prochain redem
