### ISSUE TITLE
[BUG] Impossibilité de mettre la sélénite brune dans le crystal pour le tutoriel

### ISSUE THREAD

**Issue by hija621** [RivrsMc/SeasonSky-Issues#390]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Hija621

### Pseudo discord

hija621

### Que s'est-il passé ?

Quand un nouveau joueur arrive sur le serveur, le tuto lui demande toujours d'entrer de la sélénite brune, hors avec le nouveau mois, cela à été bloqué

### Étapes à suivre pour reproduire le bug

être nouveau sur le serveur et faire le tuto, vouloir mettre la sélénite

### Qu'aurait-il dû arriver ?

Pouvoir la mettre, mais qu'elle ne rapporte 0 lvls (mieux ça que de la limiter à une car si le joueur le fait en rejoignant l'is de son ami qui l'a déjà fait, impossible non plus pour lui de le mettre)

### Date et heure de la production du bug

01/09 9h

### Serveur

All

### Screen / vidéo

Pas de sélénite :x
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/135941180/a8a478a5-3b38-4ee7-98bf-f5681d58c6ec)

**Comment by mrsxnshxne** [comment]
Hello, la sélénite a été changé, désormais un bloc d'emeraude est give et sera l'objet à déposer dans le cristal !
