### ISSUE TITLE
[BUG] npc aventure 

### ISSUE THREAD

**Issue by Jspppppp** [RivrsMc/SeasonSky-Issues#391]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Jspppppp

### Pseudo discord

Mathéo#8230 / Jspppppp (l'ours)

### Que s'est-il passé ?

Les npcs monde aventure ne donne pas de récompense 

### Étapes à suivre pour reproduire le bug

Faire une quête npc 
Voir que y'a rien dans le tchat et que rien n'a augmenter

### Qu'aurait-il dû arriver ?

On aurais du gagner une récompense

### Date et heure de la production du bug

All

### Serveur

Aventure

**Comment by LuluxClient** [comment]
Hello je n'ai pas de soucis, dès que tu termines la quête tu reçois la récompense, c'est pas durant que tu parles au npc que tu reçois les récompenses

**Comment by LuluxClient** [comment]
Réouverture, j'ai des soucis en prod, je vais investiguer ça

**Comment by Jspppppp** [comment]
Jvais t'envoyer un rec

**Comment by Jspppppp** [comment]
Hello @LuluxClient du coup voila un rec joueur (si tu vois pas bien je referais un rec je l'avais envoyer à Groche pour voir si c'était normal)
https://github.com/RivrsMc/SeasonSky-Issues/assets/139492099/5fcc606f-bae9-40e7-90c3-9e501c25c849

**Comment by Alexis700** [comment]
Corrigé, ça sera sur le prod dès que possible
