### ISSUE TITLE
[BUG] interface rang (page 2 et 3)

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#392]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

l'interface est décaler et en plus dans les page 2 et 3 il manque le changement de saison en hiver

### Étapes à suivre pour reproduire le bug

1. faire /rang

### Qu'aurait-il dû arriver ?

corriger le problème des interfaces décaler et des interfaces de mauvais

### Date et heure de la production du bug

01/09/2023 08:14 (heure du québec)

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/04435a2f-0b01-4a74-99a6-03dcebaf0238)

**Comment by mrsxnshxne** [comment]
Hello, déco reco le serveur, lors de la maintenance tu as surement pas déconnecter le serveur tout court, tu es resté sur le hub et le pack n'a pas pu se mettre à jour de ton côté correctement
