### ISSUE TITLE
[BUG] Super compacteur (ou les lvl 2)

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#393]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

j'ai voulu compacté des items avec le super compacteur mais au lieu de me prendre 640 item il ne m'a pris que 320 items ce qui correspondrait à la création de 2 item compacté or il m'en donne 4
Bug sur les nouveaux items : 
- redstone
- lapis
- planche
- diamant 
- fer
- poisson tropical
- puffer fish
- morue
- livre
- os

### Étapes à suivre pour reproduire le bug

1. avoi run eclozr lvl 2 (ou un super compacteur vu que c'est pareil)
2. faire un item compacté

### Qu'aurait-il dû arriver ?

on devrait en obtenir que 2 ou que ca nous compte 640 items et non 320

### Date et heure de la production du bug

02/09/2023 00:15 (heure canadienne)

### Serveur

all

**Comment by LupusArctos4** [comment]
par contre les anciens items qui y étaient déjà ne se font que 2 par 2 avec la consommation de 320 (équivalent de 2 item) or la description dit 4 par 4 avec une consommation d'item de 640

**Comment by LuluxClient** [comment]
Fixed !
