### ISSUE TITLE
[BUG] Ecorcer un arbre ne rapporte pas d'exp

### ISSUE THREAD

**Issue by Sayukoooo** [RivrsMc/SeasonSky-Issues#394]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Sayuko_o

### Pseudo discord

Saayuko

### Que s'est-il passé ?

Aucune xp récupérer sur un bois écorcer. Un arbre pousse si vous faite clique droit dessus avec une hache et ensuite que vous le casser vous récuperer aucune xp.

### Étapes à suivre pour reproduire le bug

Arbre > clique droit > casser > aucune xp

### Qu'aurait-il dû arriver ?

Il devrait avoir de l'xp vue que c'est un arbre :'(

### Date et heure de la production du bug

02-09 13:32:20

### Serveur

island-04

### Screen / vidéo

azd

### Information supplémentaire

UUID: 4311785a-1e69-4493-9904-21daf99f394e
Position: 12612 100 34194 SuperiorWorld
Ping: 41ms

**Comment by LuluxClient** [comment]
Salut cela est désactivé temporairement du à un bug ! Il sera de retour dès que le bug sera fix
