### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Sayukoooo** [RivrsMc/SeasonSky-Issues#395]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Sayuko_o

### Pseudo discord

Saayuko

### Que s'est-il passé ?

Bonhome de neige fais pas de neige

### Étapes à suivre pour reproduire le bug

PAS DE NEIGE

### Qu'aurait-il dû arriver ?

Ou es la neige ?

### Date et heure de la production du bug

02-09 15:26:46

### Serveur

island-04

### Information supplémentaire

UUID: 4311785a-1e69-4493-9904-21daf99f394e
Position: 12584 104 34184 SuperiorWorld
Ping: 52ms

**Comment by LuluxClient** [comment]
Salut les biomes "plains, swamplands, beaches et mushroom" ne laisseront pas de neige derrière un bonhomme de neige ! C'est une mécanique vanilla de minecraft et sur vos île c'est normalement que des plains
