### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Wylow0** [RivrsMc/SeasonSky-Issues#396]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Wylow

### Pseudo discord

wylow

### Que s'est-il passé ?

Notre ile ne gagne pas d'xp en tuant les golems de fer serveur (island-04), on est plusieurs à avoir testé

### Étapes à suivre pour reproduire le bug

taper les golems 

### Qu'aurait-il dû arriver ?

02/09

### Date et heure de la production du bug

02-09 15:28:46

### Serveur

island-04

### Screen / vidéo

https://clips.twitch.tv/ManlySmoggyBearFUNgineer-717IfyEXuq_WyAK0

### Information supplémentaire

UUID: 53a9e889-da14-4ade-80a3-bc9447bec5fe
Position: 37790 99 -18023 SuperiorWorld
Ping: 26ms

**Comment by LuluxClient** [comment]
Salut @Wylow0 les golems de fer ne drop pas d'exp ! C'est une mécanique vanilla https://minecraft.fandom.com/wiki/Iron_Golem
