### ISSUE TITLE
[BUG] Première récompense premium du pass farm obtenable sans avoir le pass

### ISSUE THREAD

**Issue by Naunau99** [RivrsMc/SeasonSky-Issues#397]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Naunau99

### Pseudo discord

naunau99

### Que s'est-il passé ?

Lorsque l'on récupère la première récompense du pass farm nous obtenons aussi la récompense premium.

### Étapes à suivre pour reproduire le bug

1/ Entrer la commande /jobs; 2/ cliquer sur pass farm en haut; 3/ récupérer la première récompense.

### Qu'aurait-il dû arriver ?

Ne pas recevoir la récompense premium.

### Date et heure de la production du bug

02/09/2023 vers 14h30

### Serveur

SeasonSky

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/134328190/4af678a9-5e2d-4aa9-931d-aadec7b9a297)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/134328190/52173f96-4441-4343-99fc-aa82905f0158)

**Comment by Naunau99** [comment]
pareil pour le palier 9

**Comment by Naunau99** [comment]
pareil pour le 10

**Comment by LuluxClient** [comment]
Salut normalement ceci a été fix, peux-tu me dire si c'est toujours d'actualité ?

**Comment by Naunau99** [comment]
Bonsoir, je ne pourrais te dire ca que le mois prochain car elles sont déjà récupéré.

**Comment by LuluxClient** [comment]
Fixed
