### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Asurx31** [RivrsMc/SeasonSky-Issues#398]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Asurx31

### Pseudo discord

Its-me-the-R

### Que s'est-il passé ?

Rien de méchant mais dans le compacteur le lapis et renommé "diamant compacté"

### Étapes à suivre pour reproduire le bug

Aller dans un compacteur

### Qu'aurait-il dû arriver ?

Qu'il soit marquer la bonne chose

### Date et heure de la production du bug

03-09 15:52:05

### Serveur

island-02

### Screen / vidéo

![Capture d'écran 2023-09-03 155556](https://github.com/RivrsMc/SeasonSky-Issues/assets/143947053/b6d794a7-2d82-4b0a-bb33-7f90f5215b66)

### Information supplémentaire

UUID: afedfc0a-b6b5-4782-a800-0ac6f660bf4d
Position: 28791 -55 27018 SuperiorWorld
Ping: 42ms

**Comment by LuluxClient** [comment]
Merci du report je l'ai fix et ce sera effectif dès le redem / prochaine maj !
