### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Sayukoooo** [RivrsMc/SeasonSky-Issues#399]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Sayuko_o

### Pseudo discord

Saayuko

### Que s'est-il passé ?

Les vaches se reproduise pas. Ce qui es embêtant vue qu'on est sensé gagner de l'xp en les faisant reproduire

### Étapes à suivre pour reproduire le bug

Avoir 2 vache

### Qu'aurait-il dû arriver ?

Elle aurais du se reproduire.

### Date et heure de la production du bug

03-09 17:14:20

### Serveur

island-04

### Information supplémentaire

UUID: 4311785a-1e69-4493-9904-21daf99f394e
Position: 12597 118 34202 SuperiorWorld
Ping: 107ms

**Comment by LuluxClient** [comment]
Les vaches via les spawners ne vont pas se reproduire pas vu qu'ils n'ont pas d'intelligence artificiel, uniquement si tu as un oeuf de vache
