### ISSUE TITLE
[BUG] Mauvaises perm grade Legende

### ISSUE THREAD

**Issue by Amateur2Drapeau** [RivrsMc/SeasonSky-Issues#40]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MaelEnFrance

### Pseudo discord

maelenfrance

### Que s'est-il passé ?

Les grades legendes ont 24h de cooldown sur le /repair all au lieu de 1h
Ils ne peuvent pas /nick

### Étapes à suivre pour reproduire le bug

Etre legende

### Qu'aurait-il dû arriver ?

Avoir les bons cooldown

### Date et heure de la production du bug

x

### Serveur

x

**Comment by NoHere32** [comment]
good au prochain redem
