### ISSUE TITLE
[BUG] /jobs claim Alchimiste lvl 73

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#400]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

on ne recoit pas les cristaux de seasons lorsqu'on jobs claim

### Étapes à suivre pour reproduire le bug

1. etre lvl 73 alchimiste
2. faire /jobs claim

### Qu'aurait-il dû arriver ?

on devrait avoir le cristal de season

### Date et heure de la production du bug

03/09/2023 12:47 (heure du québec)

### Serveur

all

**Comment by LuluxClient** [comment]
Merci du report, tu as été remboursé et j'ai fix le bug !
