### ISSUE TITLE
Faute description item 

### ISSUE THREAD

**Issue by Wylow0** [RivrsMc/SeasonSky-Issues#401]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Wylow

### Pseudo discord

wylow

### Que s'est-il passé ?

Typo dans la description de l'item "Cristal"

### Étapes à suivre pour reproduire le bug

1. Passer la souris sur l'item "Cristal"
2. Lire la description

### Qu'aurait-il dû arriver ?

Il aurait dû être écrit "Déposez sur une des mission pour la compléter.

### Date et heure de la production du bug

03/09 22h14

### Serveur

partout

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/81411349/a64c17fd-4ab8-4f61-b052-a7cf2fa4936e)

**Comment by LuluxClient** [comment]
Merci du report, cela a été fix et sera effectif dès la prochaine maj ou redem
