### ISSUE TITLE
[BUG] Compacteur enlever reste

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#402]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

les compacteurs après qu'ils soit enlever reste de manière visuel et si l'on fait un shift + click droit on peut les faire tourner comme s'il était dans un item frame

### Étapes à suivre pour reproduire le bug

1. avoir un compacteur niveau 1 ou niveau 2 
2. le poser et enlever en boucle

### Qu'aurait-il dû arriver ?

il ne devrait pas persister de manière visuel

### Date et heure de la production du bug

03/09/2023 21:19 (heure du québec)

### Serveur

all

**Comment by LuluxClient** [comment]
Salut je n'arrive pas à le reproduire, est ce que le bug est toujours d'actualité ? https://gyazo.com/f9fcb099ee5732049c898d142055901d

**Comment by LupusArctos4** [comment]
De ce qu'on a pu voir et tester, ce n'est pas en les posant et enlever à l'infini qui va les faire buger mais plus en les posant en les utilisant puis en les enlevant qu'il avait à buger
Image des compacteurs qui ont buger hier après midi et soir :
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/d1fa21ec-0ba2-4260-882e-1cbb0b3e4fd6)

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/01ea7385-e79e-41cc-8679-01e8d75f4f02)

**Comment by LupusArctos4** [comment]
L'autre jour j'ai réussi à faire pareil mais avec les eclozr, je ne pensais pas que c'était possible mais j'ai réussi
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/2c922e8a-371b-48cb-bbae-edce582e66c2)
PS : le rouge c'est pour cacher mon island

**Comment by Alexis700** [comment]
ça ne vient pas de nous, on ne pourra rien y faire
