### ISSUE TITLE
[BUG] Manque de blocks forêt mystique

### ISSUE THREAD

**Issue by hija621** [RivrsMc/SeasonSky-Issues#403]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Hija621

### Pseudo discord

hija621

### Que s'est-il passé ?

Il manque des blocks dans la zonne aventure de la foret mystique aux coordonées ci dessous (blocks invisibles):
-26 -25 -38
-27 25 -39 
-28 25 -39
-29 25 -39

### Étapes à suivre pour reproduire le bug

Aller en zonne aventure

### Qu'aurait-il dû arriver ?

Y avoir des blocks invisibles

### Date et heure de la production du bug

05-09 18:47:06

### Serveur

Spawn-03

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/135941180/5fbca90b-1b8e-4ff8-aab7-d65b11eaaa85)

### Information supplémentaire

UUID: 2ab5499c-84d4-4a73-8c73-c919bc501510
Position: -27 -25 -43 Island3
Ping: 2629ms

**Comment by LuluxClient** [comment]
Merci du report, cela sera fix dès la prochaine maj
