### ISSUE TITLE
[BUG] Le boost de vente émeraude du pet mimique et terri vert marche pas

### ISSUE THREAD

**Issue by GodSiwax** [RivrsMc/SeasonSky-Issues#404]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Siwax_x

### Pseudo discord

GodSiwax

### Que s'est-il passé ?

Mimique ne donne pas 50% de boost 
je passe de 106 de vente à 127

et terri vert ne change pas la vente 

### Étapes à suivre pour reproduire le bug

Titre

### Qu'aurait-il dû arriver ?

Donner le boost de vente

### Date et heure de la production du bug

06/09/2023 minuit

### Serveur

is1

**Comment by LuluxClient** [comment]
Salut je n'ai pas de soucis, regarde si tu n'as pas d'autre pets / objets qui boost la vente de l'emeraude au shop d'activé ce qui peut faire un peu bug les multiplicateur de vente. et le prix "127" est normal vu que le prix inital est de 85 et 50% en plus de 85 c'et 127.5

**Comment by LupusArctos4** [comment]
@LuluxClient quand on met le pet mimique on passe de 85 à 127.5 comme tu l'as dit mais le pet Terri vert a également un boost de 20% de revente des émeraudes
si le fonctionnement des boost de revente est similaire à celui des boost de métier, c'est à dire qu'ils sont cumulables, ça voudrait dire qu'on devrait arriver à 144.5 (50% du mimique et 20% du Terri vert)

j'ai pu tester avec des pets fermier pour la culture de netherwart avec les pets Froussard et Boulbi Magenta, les bonus de reventent ne se cumulent pas et prend seulement le plus gros multiplicateur qui ici est de 20% pour le pet Froussard ce qui fait passer la netherwart de 2.5 à 3

**Comment by GodSiwax** [comment]
> Salut je n'ai pas de soucis, regarde si tu n'as pas d'autres animaux / objets qui boostent la vente de l'émeraude au shop d'activé ce qui peut faire un peu bug le multiplicateur de vente. et le prix "127" est normal vu que le prix initial est de 85 et 50% en plus de 85 c'et 127.5

Non le prix 127.5 n'est pas normal, il compte que le boost du mimique et pas du terri vert
il compte seulement le pets /objet le plus haut
mimique ne se mélange donc pas avec le terri vert et la potion de richesse royale, mais par contre il se mélange bien avec le sceptre royal (165.75$)

**Comment by Alexis700** [comment]
Problème normalement corrigé, si ce n'est pas le cas merci de refaire un ticket
