### ISSUE TITLE
[BUG] armure aventurier effet

### ISSUE THREAD

**Issue by gabrielfrnd** [RivrsMc/SeasonSky-Issues#405]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

kawatsuki_

### Pseudo discord

kawatsuki_

### Que s'est-il passé ?

mon armure aventurier ne donne aucun effet

### Étapes à suivre pour reproduire le bug

equiper celle ci

### Qu'aurait-il dû arriver ?

mettre les effets speed et force 

### Date et heure de la production du bug

18h52

### Serveur

seasonsky

### Screen / vidéo

.

### Information supplémentaire

.

**Comment by LuluxClient** [comment]
Hello je n'ai pas de soucis, essaye de retirer et de remettre ton armure plusieurs fois (sur ton île pour bien tester) jusqu'à que tu as l'effet !
