### ISSUE TITLE
[BUG] /pass pallier 15

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#406]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

on ne peut pas avoir 2 fois l'item si on l'a deja recu

### Étapes à suivre pour reproduire le bug

1. faire 2 fois le pass

### Qu'aurait-il dû arriver ?

on devrait avoir une compensation en money ou 50 scoins si on a deja le cosmétique

### Date et heure de la production du bug

09/09/2023 09:05 (heure du canada)

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/8404d471-7d45-4bcb-a75a-dac3ccf64890)

**Comment by LuluxClient** [comment]
Pour le moment on ne peut pas modifier ça pour ce mois mais le prochain mois on fera quelque chose

**Comment by LupusArctos4** [comment]
D'accord très bien, hate de voir ce qui sera changer au mois d'octobre

**Comment by LupusArctos4** [comment]
@LuluxClient possible de réouvrir l'issue parce que ca n'a pas changer :
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/b563b870-07f0-46d1-87ff-01871e64bece)
