### ISSUE TITLE
[BUG] Epée Ultime

### ISSUE THREAD

**Issue by LinxEagleBear** [RivrsMc/SeasonSky-Issues#407]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

LinxEagleBear

### Pseudo discord

dieu_du_soleil

### Que s'est-il passé ?

L'arme "épée ultime" a un bug sur le looting qui ne fonctionne n'y en monde aventure se qui est logique mais il ne fonctionne pas non plus sur nos "is" ou sur les "warp".

### Étapes à suivre pour reproduire le bug

il n'y à pas d'étape il faut juste avoir l'épée et tapé un mob

### Qu'aurait-il dû arriver ?

que les drops soit en énorme quantité au lieu de tuer 200 monstres et avoir 3 pauvres item.

### Date et heure de la production du bug

30/08/2023

### Serveur

SeasonSky

**Comment by LuluxClient** [comment]
Salut l'épée ultime est sensé vendre automatiquement les loots donc tu ne devrais pas avoir de drops au sol, un patch a été appliqué recemment sur ça, je t'invite à attendre le redémarrage automatique à 5h du matin et me dire si le bug persiste !
