### ISSUE TITLE
[BUG] Arc ultime pas modifiable

### ISSUE THREAD

**Issue by hija621** [RivrsMc/SeasonSky-Issues#408]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Hija621

### Pseudo discord

hija621

### Que s'est-il passé ?

Dans la description de l'arc ultime il est dit qu'on peu le modifier, hors, impossible d'ajouter des enchantements comme mending.

### Étapes à suivre pour reproduire le bug

Avoir un arc ultime (être riche quoi)
Essayer de l'enchanter

### Qu'aurait-il dû arriver ?

Pouvoir l'enchanter

### Date et heure de la production du bug

10/09 10h

### Serveur

Tous

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/135941180/d28e7eae-28d1-4e92-8248-4ad3e9ab487c)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/135941180/75439e34-f339-47d3-bd89-34e6cd381a71)

### Information supplémentaire

C'est un livre mending sur le screen 2

**Comment by LupusArctos4** [comment]
Normal que tu ne puisses pas mettre meeding c'est un enchant incompatible avec l'enchantement infinity hors mode creatif

**Comment by LupusArctos4** [comment]
Pour moi il faudrait soit rajouter meeding de base et enlever le faut qu'il soit modifiable
Et si vous ne rajouter pas meeding faut enlever qu'il soit modifiable car dans tout les cas il n'est pas modifiable

**Comment by Volrod678** [comment]
J'ai retiré l'enchantement infinity afin que le joueurs sois libre de choisir infinity ou mending

**Comment by hija621** [comment]
Salut! ça a été push? Car l'arc a toujours l'enchantement via le items gui
