### ISSUE TITLE
Coquilles sur descriptions d'items

### ISSUE THREAD

**Issue by Slylokss** [RivrsMc/SeasonSky-Issues#409]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Slyyyyy_

### Pseudo discord

Slyyyyy_

### Que s'est-il passé ?

Des descriptions d'items et crafts ne correspondent pas a l'item ou au craft final.

### Étapes à suivre pour reproduire le bug

Lire la description de l'epée du chasseur fou et du craft de lapis compacté.

### Qu'aurait-il dû arriver ?

Avoir les bonnes desriptions

### Date et heure de la production du bug

10 Septembre, 12h

### Serveur

Tous servers

### Screen / vidéo

![1_3](https://github.com/RivrsMc/SeasonSky-Issues/assets/139008396/85cd3689-4a02-4968-9628-cc384cbb4561)
![1](https://github.com/RivrsMc/SeasonSky-Issues/assets/139008396/1102403b-b4c1-4f5d-9d2d-dac6d749ab17)

**Comment by LuluxClient** [comment]
Salut merci du report cela a été fix et sera effectif dès la prochaine maj ou redem !
