### ISSUE TITLE
[BUG]  Pioche des ombres qui casse l'Eclozr 

### ISSUE THREAD

**Issue by Zwartkat** [RivrsMc/SeasonSky-Issues#41]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Zwartkat 

### Pseudo discord

Zwartkat 

### Que s'est-il passé ?

Les eclozr (bloc invisible) peut être cassé par la pioche des ombres

### Étapes à suivre pour reproduire le bug

1. Taper un eclozr avec la pioche

### Qu'aurait-il dû arriver ?

Rien

### Date et heure de la production du bug

17:10 9/07

### Serveur

Ile

**Comment by NoHere32** [comment]
Etiquette Notion : Items Effect manquant / modification

**Comment by ArDiDEx** [comment]
hey cela est patch, les items peuvent désormais plus casser les blocs invisible
