### ISSUE TITLE
[BUG] /farm

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#410]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

quand le classement se reset le lundi soir à 23h58 +/- 1min on ne recoit pas les récompenses du classement que ça soit le tag ou les scoins
avant une correction sur le reset du mois qui avait reset aussi celui de la semaine, un patch avait été, est-ce le patch fait pour le bug qui à causer se bug, c'est ce que je pense (bug report #386 )

### Étapes à suivre pour reproduire le bug

1. etre dans le top 4 farmium de la semaine
2. etre lundi soir 23h58 +/- 1min

### Qu'aurait-il dû arriver ?

on aurai du avoir nos récompenses comme pendant le mois d'aout

### Date et heure de la production du bug

11/09/2023 18:03 (heure du canada)

### Serveur

all

**Comment by LuluxClient** [comment]
Salut je n'ai aucun soucis et tout les bugs lié à ça sont normalement fix et je viens de retester directment, cela peut être lié à la charge assez grosse peut être mais je n'ai pas d'environnement pour le tester à 100%

Egalement le top 4 ne reçoit pas de tags.

Pour essayer de contrer les bugs lié à ça j'ai accélérer le système pour give les récompenses etc...
