### ISSUE TITLE
[BUG] Drop monde aventure avec Epée ultime

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#411]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

Les megaTaupe drop les loots des golems en les tuant avec l'épée ultime mais il drop également les loots du monde aventure
Mes mates ont pu tester dans les autres dimensions (ne pouvant pas tester car je suis citoyen) mais tous les mobs codés sur des golems de fer drops les loots de la table de loot vanilla (fer + poppy) avec l'épée ultime car celle-ci essaie de vendre automatiquement mais n'étant pas sur les mondes island, les loots dropent au sol.

### Étapes à suivre pour reproduire le bug

1. avoir une épée ultime
2. tuer des mobs codés sur des golems du monde aventure

### Qu'aurait-il dû arriver ?

en tuant avec l'épée ultime, les mobs codés sur des golems ne devrait pas loot les items du golem (fer + poppy)

### Date et heure de la production du bug

12/09/2023 10:54 (heure du canada)

### Serveur

all

### Screen / vidéo

Record avec l'épée ultime ou ça drop du fer et des poppy 
Record avec l'épée divine ou ca fonctionne correctement (sans drop des items du golem)
https://youtu.be/uwFY38Hmrw0
https://youtu.be/_x7sbDeWmPs

**Comment by LuluxClient** [comment]
Ils ne sont pas sensé drop du fer, je vais corriger ça et cela sera effectif dès la prochaine maj !

**Comment by LupusArctos4** [comment]
@LuluxClient il drop aussi des poppy
