### ISSUE TITLE
[BUG] Super compacteur

### ISSUE THREAD

**Issue by Isweazu** [RivrsMc/SeasonSky-Issues#412]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Isweazu

### Pseudo discord

xx4040

### Que s'est-il passé ?

Les super compacteur, obtenus dans le jobs alchimiste sont sensé compacter 640 items pour 4 items compactés, celui-ci prend bien les 640 items mais n'en donne que 2.
Test avec les verrues pas le reste, et ne m'en donne que 2 par 2 me prenant bien les 640 items, testé sur 2 compacteur, celui d'un joueur obtenus début de semaine, et le second give en tant que Super-modo pour le tester.
J'ai un rec au besoin suffit de le demander.

CORRECTION : après test sur chaque serveur, le soucis n'apparait que sur le serveur island 06

### Étapes à suivre pour reproduire le bug

Prendre un super compacteur, prendre 640 verrues, les compacter et récupérer

### Qu'aurait-il dû arriver ?

Avoir les 4 items compactés au lieu de seulement 2

### Date et heure de la production du bug

2h13 le 14/09

### Serveur

Island 06

**Comment by LupusArctos4** [comment]
étonnant car je n'ai pas le problème avec mes compacteurs (tester avec verrue du nether au moment de voir le bug et sinon avec beetroot et bois de chêne mais aucun problème même après une très grosse quantité)
pour information, les compacteurs ont été bouger avant de les utiliser et on était obtenu tous avant le 7 septembre pour le plus recent
