### ISSUE TITLE
[BUG] Faute d'orthographe dans l'eclozr

### ISSUE THREAD

**Issue by myolo2610** [RivrsMc/SeasonSky-Issues#413]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

myolo2610

### Pseudo discord

myolo2610

### Que s'est-il passé ?

bah dans l'éclozr ça dit stockage actuelle mais ben en fait ça devrait être écrit actuel parce que on dit pas la stockage donc c'est masculin

### Étapes à suivre pour reproduire le bug

1. clique sur l'éclozr 2. glisse ta sourie sur le stockage 3.lis ce qui est écrit

### Qu'aurait-il dû arriver ?

que ce soit écrit stockage actuel pas stockage actuelle

### Date et heure de la production du bug

15-09 01:56:17

### Serveur

island-03

### Information supplémentaire

UUID: de1b4ea5-b84d-40ed-a1a0-b2422ed6e29c
Position: 39589 100 -27015 SuperiorWorld
Ping: 90ms

**Comment by ArDiDEx** [comment]
Hello ça devrait être réglé au prochain redémarrage
Merci du report
