### ISSUE TITLE
[BUG] /condense perte d'item

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#414]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

quand on fait un /condense avec un inventaire full on à une perte de 7 blocs, les 7 blocs corresponde à 63 items ce qui fait que les 63 premier item pris lors de l'exécution de la commande seront toujours perdu car de ce que je comprend de la commande :
1. elle ouvre une pseudo table de craft
2. elle craft un bloc et le met si possible de l'inventaire (ne fonctionne pas car pas de place pour les 7 premiers blocs) => répète tant que le nombre item de départ est inférieur à 9
3. dès qu'elle n'a plus d'item à compacter ou plus assez, le console envoie dans le chat du joueur le message suivant : _SeasonSky ▪ Vous venez de compacter votre inventaire !_

### Étapes à suivre pour reproduire le bug

1. etre l'inventaire full d'un item compactable, comme du fer
2. faire /condense

### Qu'aurait-il dû arriver ?

pour résoudre le problème ca devrait crafter dans la pseudo table de craft les blocs par le plus grand nombre en même temps, comme si on faisait un shift + click gauche dans le recipe book

### Date et heure de la production du bug

14/09/2023 23:36 (heure du canada)

### Serveur

all

**Comment by Alexis700** [comment]
Tu n'es pas censé utiliser le ton full inventaire pour le /condense car le slot numéro 9 de ta hotbar est la boussole d'où la perte de 7 blocs qui correspond environ à un stack

**Comment by LupusArctos4** [comment]
@Alexis700 possible de me passer ton email que je t'add a la vidéo qui est en privé pour te montrer que non même avec le slot 9 prit par la boussole il y a toujours une perte d'item ? si je n'ai pas de réponse je réouvrirais une issue
https://youtu.be/4EANTEpjJ2Q
