### ISSUE TITLE
[BUG] Item evolutif

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#415]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

ne fonctionne pas sur une is qui n'est pas la notre

### Étapes à suivre pour reproduire le bug

1. avoir un item évolutif
2. faire son action (tuer, couper, miner) dans une autre is que la notre

### Qu'aurait-il dû arriver ?

on devrait pouvoir la monter meme si on n'est pas sur notre is

### Date et heure de la production du bug

15/09/2023 16:43 (heure du canada)

### Serveur

all

**Comment by ArDiDEx** [comment]
Hello, malheureusement ça ne sera pas patch et restera comme t-elle
Merci quand même du report
