### ISSUE TITLE
[BUG] perte de dura epee

### ISSUE THREAD

**Issue by Naruto83130** [RivrsMc/SeasonSky-Issues#416]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

naruto83130

### Pseudo discord

Flex_Juju_Le_Boss-83#8544

### Que s'est-il passé ?

Quand je trappe avec l épée du chasseur fou, et qu' il y a l entety craming avec les mobs, la durabilité de l épée descend toute seul

### Étapes à suivre pour reproduire le bug

Trappe des mobs avec une épée, a cause de l entety craming la dura baisse toute seul 

### Qu'aurait-il dû arriver ?

La durabilité de descend pas toute seul 

### Date et heure de la production du bug

La semaine dernière (toujours d actu)

### Serveur

All

### Screen / vidéo

https://youtu.be/6q6pPeDi0KE

**Comment by LupusArctos4** [comment]
je me permets de te répondre (je ne suis pas un staff de season) mais ce sujet à déjà était traité au #365 et ils ne peuvent y faire
