### ISSUE TITLE
[BUG] Fly

### ISSUE THREAD

**Issue by AeroVeza** [RivrsMc/SeasonSky-Issues#418]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

AeroVeza

### Pseudo discord

Hannya

### Que s'est-il passé ?

Lorsque les permissions de fly de mon ile sont sur mon grade ou au dessus, je ne peux plus fly que ce soit sur mon ile ou au spawn.
Lorsque l'on essaye de fly et que le bug fait effets, la commande ne renvoie aucune information; c'est comme si nous n'avions jamais fait la commande (d'un point de vue joueurs en tout cas).

Pour pouvoir fly de nouveau il faut que le paramètre de fly soit à 1 rang en dessous de soit même. (Lorsque le leader de mon ile règle le paramètre de fly sur leader il ne peut plus fly non plus).
Mais le paramètre fait que lorsque l'on règle sur admin la commande définit le fly pour ceux qui on un rang au dessus de Admin

### Étapes à suivre pour reproduire le bug

1. faire/is panel
2. Aller dans "Permission d'ile"
3. dans la catégorie "Voler" régler sur son propre rangs sur l'ile (Admin dans mon cas"
4. faire /fly

### Qu'aurait-il dû arriver ?

Lorsque je regle les autorisation de fly sur mon ile sur "admin" touts les admin et supérieur doivent pouvoir voler.

### Date et heure de la production du bug

16/09/2023 16h30

### Serveur

Island 02 / Spawn

### Screen / vidéo

https://github.com/RivrsMc/SeasonSky-Issues/assets/112935315/5e010027-8b9f-4ddd-8c58-36b7c86b7d02

**Comment by Khreight** [comment]
Moi aussi j'ai aussi ca encore maintenant

**Comment by Asherate** [comment]
Fix au prochain redémarrage
