### ISSUE TITLE
[BUG] du /vip avec les clés rotative

### ISSUE THREAD

**Issue by TheLouuKa** [RivrsMc/SeasonSky-Issues#419]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

LouuKa_

### Pseudo discord

.-.louka

### Que s'est-il passé ?

Dans le /vip quand on veux acheté 10 clés sa nous dit que c'est 3500scoins mais dans la validation sa dit 6000scoins pour l'achat 

### Étapes à suivre pour reproduire le bug

/vip -> Clés > Clés Rotative x10

### Qu'aurait-il dû arriver ?

être débiter de 3500 et non 6000

### Date et heure de la production du bug

18-09 20:17:32

### Serveur

Spawn-02

### Screen / vidéo

![2023-09-18_20 16 13](https://github.com/RivrsMc/SeasonSky-Issues/assets/140109392/90a545c7-0cb3-4e10-8a4e-ec6d8f82f675)
![2023-09-18_20 16 02](https://github.com/RivrsMc/SeasonSky-Issues/assets/140109392/a1152640-b880-4aef-b598-97d6df8a057f)

### Information supplémentaire

UUID: 3717550f-f4f3-4597-bee9-6176808b32be
Position: 227 138 -1146 world
Ping: 38ms

**Comment by TheLouuKa** [comment]
De même pour les x5 x1
![2023-09-18_20 24 16](https://github.com/RivrsMc/SeasonSky-Issues/assets/140109392/01b30f34-eca9-433b-8c9d-20911f6e5a66)
![2023-09-18_20 24 11](https://github.com/RivrsMc/SeasonSky-Issues/assets/140109392/372c8dcb-6cdf-4e62-a21c-35ab031f9097)
![2023-09-18_20 24 21](https://github.com/RivrsMc/SeasonSky-Issues/assets/140109392/e95b70f5-f151-4a2e-89c8-b80b194835fa)
![2023-09-18_20 24 19](https://github.com/RivrsMc/SeasonSky-Issues/assets/140109392/629526a7-ed81-49e4-873b-eda5d03ef4ce)

**Comment by TheLouuKa** [comment]
Alors pour le coup c'est juste graphique, tu est débité 3500 mais c'est affiché 6000
de même pour les x5 / x1

**Comment by Alexis700** [comment]
Fix
