### ISSUE TITLE
[BUG] Métier Mineur - Gains Cuisson

### ISSUE THREAD

**Issue by jejeworld** [RivrsMc/SeasonSky-Issues#42]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

jejeworld

### Pseudo discord

jejeworld

### Que s'est-il passé ?

Les moyens de monter le métier Mineur en cuisant des ressources ne fonctionnent pas.

### Étapes à suivre pour reproduire le bug

/

### Qu'aurait-il dû arriver ?

Gagner des points, argent et xp

### Date et heure de la production du bug

/

### Serveur

All

### Screen / vidéo

/

### Information supplémentaire

/

**Comment by Acterax** [comment]
Faut edit dans la config et mettre les items resultat et pas le minerai
