### ISSUE TITLE
[BUG] Temps d'afk bottes alchimiste

### ISSUE THREAD

**Issue by DeadPour2Vrai** [RivrsMc/SeasonSky-Issues#420]
### Confirmation

- [x] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

dead140 / iDead_

### Pseudo discord

deadpour2vrai

### Que s'est-il passé ?

Bonjour j'ai acheté récemment les bottes d'alchimistes pour mon double compte.
Cependant quand je les ai équipé après test je me suis aperçu qu'elles ne rajoutaient pas les 10 minutes supplémentaire d'afk annoncé 

### Étapes à suivre pour reproduire le bug

Obtenir des bottes d'alchimistes et s'en équipé 

### Qu'aurait-il dû arriver ?

Le temps aurait du passé de 15 à 25 minutes d'afk

### Date et heure de la production du bug

20h27

### Serveur

island-04

### Screen / vidéo

![bug bottes alchi](https://github.com/RivrsMc/SeasonSky-Issues/assets/140292975/a324c05a-b0a2-4dbb-bb7b-55f4f1e3d923)

**Comment by Socro007** [comment]
Un autre bug lié à celui-ci : lorsque l'on a le grade légende, le temps passe de 1 heure à 15 minutes au lieu de 1 heure et 10 minutes. Un message nous notifie que nous avons été kickés après 25 minutes.

**Comment by Alexis700** [comment]
Le temps d'afk a été retiré
