### ISSUE TITLE
[BUG] /farm-contest Ne Fonctionne Plus

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#421]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

MAJ dans le dernier message de cet issue

le farm contest miner de l'or ne fonctionne pas qu'on mine avec un pioche fortune 1 en diamant, toucher de soie en diamant, avec une pioche qui tp dans l'inventaire et avec le pioche evolutive niveau 3

### Étapes à suivre pour reproduire le bug

1. miner de l'or avec un pioche fortune 1 en diamant, toucher de soie en diamant, avec une pioche qui tp dans l'inventaire et avec le pioche evolutive niveau 3
2. rien ne se passe

### Qu'aurait-il dû arriver ?

ca devrait augmenté le compteur comme sur les anciens event farm

### Date et heure de la production du bug

18/09/2023 15:45 (heure du canada)

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/bbe72578-5c5f-4724-b749-263be1b16efc)

**Comment by LupusArctos4** [comment]
le tournois a buger avec ca modification, d'ailleurs il n'y a pas eu d'information quant à la modification des tournois de farm dans le patch note publier ce matin
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/01728f99-c655-41f1-98d5-9b925e131999)

**Comment by LupusArctos4** [comment]
Je ne vais pas tout modifier car ca serait trop long mais je vais mettre a jour l'information ici directement car ça sera beaucoup plus simple :
Le tournois de farm présent au horaire de 16h ; 18h ; 20h ; 22h ne fonctionne pas avec les nouveaux items nouvellement rajouter comme le minerais d'or et la canne à sucre (sachant qu'une info dans le patch note n'a été écrite se sont les seuls qu'on sait qu'ils ne fonctionnent pas apres des tests)

**Comment by LupusArctos4** [comment]
l'event se lance avant les anciennes heure prévu (il c'est lancer a 21h40 au lieu de 22h comme avant), l'event ici farmer de la carotte fonctionner avant la mise a jour de lundi 18 septembre et ne fonctionne meme plus, donc je pense que c'est un bug du plugin complet

**Comment by LupusArctos4** [comment]
erreur inter serveur (spawn 03 et island 02)

1er screen en horaire canadien donc en france il est 22h
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/bfeda9bb-8ace-4479-9110-44ea476b18f9)
2nd screen en horaire francais
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/343888c0-2619-4745-a3ab-9a1c80bba526)

**Comment by Asherate** [comment]
@LupusArctos4 je comprend pas bien l'erreur avec les screens ?

**Comment by LupusArctos4** [comment]
@Asherate l'erreur a été patch depuis mais l'issue n'a pas été fermée
mais maintenant on à #489 un problème qu'il y avait au tout début de la version et que vous aviez patch assez rapidement
