### ISSUE TITLE
[BUG] lootbox premium

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#422]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

il y a toujours la clé estival dans les loots de la box premium

### Étapes à suivre pour reproduire le bug

1. /abo
2. LootBox premium

### Qu'aurait-il dû arriver ?

elle ne devrait plus etre présente

### Date et heure de la production du bug

18/09/2023 17:11 (heure du canada)

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/aa7b7851-6870-44a2-8bf3-0f90c0c542b0)

**Comment by Alexis700** [comment]
Fix
