### ISSUE TITLE
[BUG] Erreur jeux chat Animation

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#424]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

il y a une erreur d'orthographe du mot Filtre qui est écrit Philtre

### Étapes à suivre pour reproduire le bug

1. etre connecté
2. avoir le mot dans l'animation du jeu chat

### Qu'aurait-il dû arriver ?

le mot devrait etre Filtre de Résistance et non Philtre de Résistance

### Date et heure de la production du bug

19/09/2023 00:35 (heure du canada)

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/3ee4848b-80db-4a48-8001-b6cbf8d0a454)

**Comment by Alexis700** [comment]
Il n'y a pas de faute, c'est un breuvage donc -> Philtre, comme philtre d'amour

**Comment by LupusArctos4** [comment]
je n'avais pas pensé à ça d'autant plus que j'avais chercher sur internet vite fait
