### ISSUE TITLE
[BUG] Recompense metier pecheur

### ISSUE THREAD

**Issue by Viliky** [RivrsMc/SeasonSky-Issues#425]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Viliky

### Pseudo discord

Viliky

### Que s'est-il passé ?

J'ai atteint le lvl 3 du metier pecheur, j'ai ensuit fait /job claim pour recevoir la canne a peche du pecheur, mais je n'ai rien recu dans mon inventaire. 
Mon inventaire avait bien des slot vides

### Étapes à suivre pour reproduire le bug

atteindre le lvl 3 du metier pecheur et faire /job claim

### Qu'aurait-il dû arriver ?

J'aurais du recevoir la canne a peche du pecheur

### Date et heure de la production du bug

19/09/2023  10h00

### Serveur

island-04

### Information supplémentaire

Dans mons inventaire j'avais quelques missions dont:
-pecher 7 poissons globes
-voyager 764 metres
-miner 50 deepslates x2

J'avais des oak sapling dans la main gauche et une canne a peche luck of the sea 2 lure 2 U3 dans la main principale

**Comment by Asherate** [comment]
@Acterax j'ai testé le bug, en arrivant palier 3 pêcheur j'ai reçu les récompenses mais en double, aucune idée d'où cela peu venir, mais pour le joueur de l'issue il n'as rien reçu, la config semble bonne, si jamais t'as un moment pour regarder

**Comment by Alexis700** [comment]
Bug qui est arrivé une seule fois, je t'invite à faire un ticket
