### ISSUE TITLE
[BUG] permission interagir avec un objet

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#427]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

redacted

### Étapes à suivre pour reproduire le bug

redacted

### Qu'aurait-il dû arriver ?

redacted

### Date et heure de la production du bug

19/09/2023 18:56 (heure du canada)

### Serveur

all

**Comment by LupusArctos4** [comment]
redacted

**Comment by ArDiDEx** [comment]
Je vais check ça

**Comment by ArDiDEx** [comment]
Hello
le bug devrait être réglé au prochain restart
Merci du report
