### ISSUE TITLE
Pet arby ne donne pas le bonus 30% sur l'xp et le farmium

### ISSUE THREAD

**Issue by Quentingx** [RivrsMc/SeasonSky-Issues#428]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Arosk_

### Pseudo discord

Arosk

### Que s'est-il passé ?

J'ai passé mon pet Arby lvl 20 pour avoir le bonus 30% sur le farmium apres plusieur essaies  avec arby comme seul pet et avec plusieur pet le bonus de 30% sur le metier de bucheron n'est pas attribué

### Étapes à suivre pour reproduire le bug

résoudre le probleme de bonus metier sur arby faire en sorte qu'il donne 30% d'xp d'argent et de farmium comme les autres pets

### Qu'aurait-il dû arriver ?

apres avoir passer mon pet lvl 20 j'aurais du obtenir 30% suplémentaire sur le farmium en revanche le bonus est attribuer que au gains d'éxpérience et non sur l'argent et le farmium 

### Date et heure de la production du bug

19/09/2023 ~20h

### Serveur

seasonsky

### Screen / vidéo

![2023-09-19_21 23 17](https://github.com/RivrsMc/SeasonSky-Issues/assets/145566866/4944eb29-b6f8-460d-b311-e1f329eeb3e9)
![2023-09-19_21 24 22](https://github.com/RivrsMc/SeasonSky-Issues/assets/145566866/4cc56d7f-7db5-465d-a54b-08c621183a82)
![2023-09-19_21 24 32](https://github.com/RivrsMc/SeasonSky-Issues/assets/145566866/be3aaaa9-fee4-4acc-84df-221eb77fbb01)
![2023-09-19_21 25 44](https://github.com/RivrsMc/SeasonSky-Issues/assets/145566866/e29469ea-fadb-4ca2-acf9-69ad10c48ced)
![2023-09-19_21 47 39](https://github.com/RivrsMc/SeasonSky-Issues/assets/145566866/e5774f65-7a05-482f-a3c0-13a4008b4976)

**Comment by LupusArctos4** [comment]
@Quentingx on a bien le meme pet ?
parce que c'est écrit **gain d'exp sur le métier bucheron** et non gain d'exp farmium ou gain de monnaie sur le metier bucheron
donc perso je ne comprends pas pourquoi il y a un problème
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/b6f9fdd9-cc67-42f8-accc-082d773a96f8)

**Comment by Quentingx** [comment]
Sur tout les pets c’est écris ça

**Comment by Quentingx** [comment]
![Uploading IMG_3333.jpeg…]()

**Comment by Quentingx** [comment]
Et sur  les autres le bonus est actif sur l’ensemble

**Comment by LupusArctos4** [comment]
l'image ne charge pas
mais je comprends ce que tu veux dire mais ca ne devrait pas up le tout les bonus normalement

**Comment by Quentingx** [comment]
![Uploading 2023-09-20_18.52.38.png…]()

**Comment by Quentingx** [comment]
par exemple la j'ai retirer tout mes pets le farmium est a 0,1 avec les pets je suis a 0,13 et avec arby je reste a 0,13 logiquement je devrais passer a 0,15

**Comment by Quentingx** [comment]
![2023-09-20_18 52 38](https://github.com/RivrsMc/SeasonSky-Issues/assets/145566866/b62fca20-ced1-48cf-ba3f-2dd0b20ebbbf)

**Comment by LupusArctos4** [comment]
pour moi le farmium ne devrait pas etre augmenté tout comme le gain de monnaie car c'est écrit XX % gain d'exp sur le métier X

**Comment by Quentingx** [comment]
![2023-09-20_18 56 43](https://github.com/RivrsMc/SeasonSky-Issues/assets/145566866/bee6cdcd-2092-4dda-bfb1-40c2b601939c)

**Comment by Quentingx** [comment]
je comprend ton point de vue mais pourtant sur tout les autres pets et metier cela fonctionne

**Comment by Quentingx** [comment]
![2023-09-20_18 55 47](https://github.com/RivrsMc/SeasonSky-Issues/assets/145566866/752403c5-8c1c-4c7b-99f1-2de604b30536)

**Comment by LupusArctos4** [comment]
bas peut etre que ce pet a été correctement configuré et non les autres

**Comment by Quentingx** [comment]
pourtant a plusieur reprise la question a été posé et les modérateur on répondu que oui cela fonctionnais pour le farmium

**Comment by LupusArctos4** [comment]
oui ca fonctionne mais la question est plutôt : est-ce que ça devrait fonctionner ou est-ce une erreur de configuration répéter sur tous les pets à leur création ?

**Comment by Quentingx** [comment]
oui mais ca peut aussi être une erreur de déscription (ce qui m'arrangerais car j'en ai chier pour le passer lvl 20 pour le farmium) mdrrr

**Comment by LupusArctos4** [comment]
je doute les autres c'est aussi écrit XX% gain d'exp métier X

**Comment by Quentingx** [comment]
oui mais dans le sens xp en général farmium et argent compris
