### ISSUE TITLE
[BUG] Durabilité Épée du Chasseur Fou

### ISSUE THREAD

**Issue by bri4uche** [RivrsMc/SeasonSky-Issues#429]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

bri4uche

### Pseudo discord

bri4uche

### Que s'est-il passé ?

Je m'adonnais à la tâche familière de pourfendre des créatures hostiles à l'aide de l'épée qui répond au nom distingué de "L'Épée du Chasseur Fou". À un moment donné, il m'a été impossible de ne pas remarquer que la résistance de cette arme se trouvait être excessivement problématique, car elle ne décroissait pas en proportion des assauts portés, comme le font ordinairement toutes les épées, mais plutôt en corrélation avec les niveaux d'expérience que j'accumulais... En résumé, il m'était nécessaire d'entreprendre une réparation quasi-constante de l'arme, même si celle-ci jouissait d'une robustesse intrinsèque indéniable.

### Étapes à suivre pour reproduire le bug

Pour reproduire le bug, il suffit d'avoir une zone avec beaucoup de mobs hostiles jusqu'à même que ces derniers suffoquent et il suffit tout simplement par la suite de taper sur les mobs avec l'épée nommée « Épée du Chasseur Fou » pour remarquer que la durabilité de cette dernière diminue beaucoup trop rapidement

### Qu'aurait-il dû arriver ?

La durabilité de l'épée est normalement basée sur le nombre de coups données aux mobs et non par l'expérience reçue par le joueur

### Date et heure de la production du bug

18/09/2023 à 2h00 du matin

### Serveur

SeasonSky Eldoria

**Comment by bri4uche** [comment]
Lien vers une vidéo montrant le bug : https://www.veed.io/view/a338b39b-f1ab-4aea-820f-76776f8842e6?panel=share

**Comment by LupusArctos4** [comment]
ce problème est déjà connu et n'est pas facilement corrigeable, pour voir les explications de ce report déjà effectuer vous avez juste a clické sur => #365
