### ISSUE TITLE
[BUG] Rune de sagesse

### ISSUE THREAD

**Issue by Isweazu** [RivrsMc/SeasonSky-Issues#430]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Isweazu

### Pseudo discord

xx4040

### Que s'est-il passé ?

Suite ticket, explication du joueur :

Hello, 

J'ai apppliqué une rune de la sagesse ultime sur une épée ultime. En théorie l'épée donne 25% xp et la rune donne également 25% d'xp ce qui devrait donc faire 50% d'xp. J'ai donc fais des tests sur des zombies sachant qu'un zombie donne 5 xp vanilla je devrais faire 5 -> 7/8 en fonction de l'arrondis avec 50% d'xp en plus. Hors je fais 5 -> 6 ce qui correspond à 1 seul des 25% actifs. Soit c'est normal et les 2 effets se cumulent pas et dans ce cas bloqué l'ajout de la rune sur les épées possédant déjà cet effet, soit c'est pas normal et dcp bah y'a 25% qui s'applique pas.

### Étapes à suivre pour reproduire le bug

Appliquer une rune de sagesse ultime sur une épée ultime puis taper des mobs et comparer avec et sans 

### Qu'aurait-il dû arriver ?

Prendre en compte correctement lemultiplicateur ?

### Date et heure de la production du bug

22h le 21 septembre 

### Serveur

Island 02

**Comment by Socro007** [comment]
la même chose pour la rune de force aucun changement sur les dégat quand on a force 3

**Comment by ArDiDEx** [comment]
Hello! Le multiplicateur devrait être réglé au prochain restart
Merci du report
