### ISSUE TITLE
[BUG]  Epée Ultime ne frappe pas 30% plus vite

### ISSUE THREAD

**Issue by Socro007** [RivrsMc/SeasonSky-Issues#431]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Socro

### Pseudo discord

.socro

### Que s'est-il passé ?

Je ne vois aucun changement  de vitesse  de frappe avec cette épée et une épée classique.

le temps indiqué en description est de 1.6 elle devrait etre de 1,12 

le butin 5  de cette épée est similaire au butin 3  de l'épée corsaire en terme  de loot. 

### Étapes à suivre pour reproduire le bug

frapper avec une épée ultime et comparer avec une épée classique.

### Qu'aurait-il dû arriver ?

frapper plus vite que une épée classique

### Date et heure de la production du bug

debut de l'objet

### Serveur

seasonsky

**Comment by ArDiDEx** [comment]
Hello, la vitesse d'attaque dans la description est celle de base d'une épée en netherite et ne montre pas la réelle valeur, comme tu peux le voir dans le screen ci-dessous la vitesse d'attaque monte bel et bien lorsque j'ai une épée ultime dans la main (130% de 1.6 est 2.08)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/48607042/3287c678-be40-44a5-9e71-904b868fdfe3)

Je ferme donc l'issue, bon jeu !
