### ISSUE TITLE
[BUG] erreur dans la description

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#432]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

il y a une erreur dans la description dans l'achat de la commande /ase : c'est écrit **_permet de changer les positions des armors stands_** or la commande permet de tout modifier donc je pense qu'il faudrait modifier et mettre : **_permet d'utiliser les fonctionnalités de la commande /ase_**

### Étapes à suivre pour reproduire le bug

1. faire /vip
2. aller dans la catégorie : autre
3. regarder la description de la commande /ase

### Qu'aurait-il dû arriver ?

je pense qu'il faudrait modifier la description et mettre : **_permet d'utiliser les fonctionnalités de la commande /ase_**

### Date et heure de la production du bug

22/09/2023 09:05 (heure du canada)

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/bb716a93-1520-4d2a-8288-9b2ab04b143c)

**Comment by Alexis700** [comment]
Fix
