### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by UnNainCendie** [RivrsMc/SeasonSky-Issues#433]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

UnNainCendie

### Pseudo discord

Trois3#0999

### Que s'est-il passé ?

Je gagne 3.51xp par betterave casser avec la houe pirate + pets 20% + booster 30%
Je dois en gagner 7.02

### Étapes à suivre pour reproduire le bug

pas compris

### Qu'aurait-il dû arriver ?

Jsp

### Date et heure de la production du bug

22-09 15:46:07

### Serveur

island-05

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/145780479/f3414236-63c7-43aa-80a2-53aceac79b83)

### Information supplémentaire

UUID: ef7196ad-9987-48b2-8a07-77ce7f607bf4
Position: -10927 67 1806 SuperiorWorld
Ping: 46ms

**Comment by Asherate** [comment]
@UnNainCendie pourrait-tu me dire si c'est toujours d'actualité, et si oui, quels sont les pets utilisés, ainsi que les boosts, merci.

**Comment by UnNainCendie** [comment]
Boost De Savoir 1h avec Pingu lv20

**Comment by Asherate** [comment]
Les boosts ne sont pas cumulables, c'est le plus gros qui va prendre le dessus si je ne me trompe pas
