### ISSUE TITLE
[BUG] houe ultime 

### ISSUE THREAD

**Issue by J7KL** [RivrsMc/SeasonSky-Issues#434]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

J7KL_

### Pseudo discord

J7KL_

### Que s'est-il passé ?

La houe ultime ne peut replanter en 5x5 quand une houe royal est dans l'inventaire, toute fois la disposition des items est crucial si c'est dans le sens houe royal  puis houe ultime la houe ultime replanteras en 3x3 cependant si c'est la houe ultime puis houe royal la houe ultime replanteras en 5x5 et la houe royal redeviendras en 3x3, je sais pas si c'est compréhensible, mp moi sur discord pour une meilleur explications en voc 

### Étapes à suivre pour reproduire le bug

changer de place la houe

### Qu'aurait-il dû arriver ?

un replantage optimale

### Date et heure de la production du bug

12h40

### Serveur

SeasonSky (island 6)

**Comment by ArDiDEx** [comment]
Hello, je n'arrive pas à comprendre le bug, pourrais tu prendre une vidéo ?

**Comment by Alexis700** [comment]
ça fonctionne
