### ISSUE TITLE
[BUG] Top Animation

### ISSUE THREAD

**Issue by Jspppppp** [RivrsMc/SeasonSky-Issues#436]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Jspppppp

### Pseudo discord

Mathéo#8230 / Jspppppp (l'ours)

### Que s'est-il passé ?

Le top animation est complétement bug le 1 er à 42 victoires j'en ai 76 et jsuis 5 ème

### Étapes à suivre pour reproduire le bug

Faire /animation 
Voir que c'est pas dans l'ordre

### Qu'aurait-il dû arriver ?

Que le /animation sois dans l'ordre

### Date et heure de la production du bug

Tout le temp

### Serveur

Island 3 (et autre je suposse)

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139492099/fd76a860-3332-4175-82d6-afb92d03f550)

**Comment by Asherate** [comment]
fix
