### ISSUE TITLE
Disparition d'item inventaire 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#438]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0isan

### Pseudo discord

Nami

### Que s'est-il passé ?

Bonjour, voilà je fais un github voir si c'est possible de vérifier de votre côté c'est le 5 ème ticket en 2 jour sur la disparition d'item spawner épée.... Etc

Je sais pas si il y a eu un réglage en rapport avec les inventaires mais si c'est possible de faire une vérification de soucis.

C'est peut-être du un soucis entre les serveur quand la personne se tp et reviens sur son is l'item disparaît automatiquement. 

### Étapes à suivre pour reproduire le bug

Avoir un item voyager entre les is et voir l'item disparaître

### Qu'aurait-il dû arriver ?

Ne pas faire disparaître d'item du tout

### Date et heure de la production du bug

11h01 25/09

### Serveur

Global

### Screen / vidéo

![Screenshot_20230925_110401_com discord](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/832cf71e-f97b-487f-bb0a-b3ec99b4b269)
![Screenshot_20230925_110348_com discord](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/b8d06b59-366e-4ebe-9122-c6827561d273)
![Screenshot_20230925_110320_com discord](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/84267af5-eb33-4f08-96c9-a636e62f8b83)

**Comment by Alexis700** [comment]
Fix
