### ISSUE TITLE
[BUG] Armure caisse rotative ignore le temps d'afk des grade

### ISSUE THREAD

**Issue by Lotifiz** [RivrsMc/SeasonSky-Issues#439]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Lotifiz

### Pseudo discord

Tesoro (TAG : lotifiz)

### Que s'est-il passé ?

Bonjour (Ou bien bonsoir), Je viens aujourd'hui vous présenter un BUG sur le principe de temps d'AFK autorisé par grade a un joueur qui est bugué avec la nouvelle armure de la caisse rotative.

Cela se produit quand nous enfilons la paire de bottes intitulée "Bottes de l'alchimiste" Qui nous permet de gagner 10Minutes supplémentaire d'AFK. SAUF QUE, cela réinitialise le temps affecté par les grades.

Par Exemple : Je suis Eternel, soit je possède le droit d'AFK 60 Minutes sans me faire Kick. Quand j'enfile les Botte de l'Alchimiste, ca me fait en sorte de posséder le droit d'AFK d'un grade du début (en soit voyageur donc 15Minutes d'AFK) + les 10Minutes des Bottes Donc 25 Minutes.

Donc en soit, ca ne prend pas en compte le grade possédé par le joueurs au moment ou il porte les bottes en questions.

### Étapes à suivre pour reproduire le bug

1 - Ouvrir la caisse Rotative.
2 - Gagner les Bottes de l'Alchimiste
3 - Posséder un grade pouvant permettre un temps d'AFK plus long que 15 Minutes.
4 - Enfiler les Bottes de l'Alchimiste
5 - Attendre 25 Minutes
6 - Se faire Kick car le Système ne te compte que en temps que "Voyageur" (Le Grade Basique)
7 - Report le BUG :D

### Qu'aurait-il dû arriver ?

Si ce n'était pas un BUG, il y aurait dû se passer le fait d'avoir le droit à 70Minutes d'AFK et non 25 alors que je possède le grade "Eternel".

### Date et heure de la production du bug

25-09 20:45:10

### Serveur

island-03

### Screen / vidéo

Screen en question du BUG : https://prnt.sc/gbjwJcwTG5Rx

### Information supplémentaire

UUID: f5412352-c0ae-4808-bffa-caaf60ed0096
Position: -12536 291 -34265 SuperiorWorld
Ping: 8ms

**Comment by Alexis700** [comment]
Retiré car infixable
