### ISSUE TITLE
[BUG] Métier Alchi xp anormalement haute

### ISSUE THREAD

**Issue by Amateur2Drapeau** [RivrsMc/SeasonSky-Issues#44]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MaelEnFrance

### Pseudo discord

maelenfrance

### Que s'est-il passé ?

Une larme de ghast à 500/u + une fiole = 100x d'alchi
avec un stack de larme (32k) on peut se faire 200k

### Étapes à suivre pour reproduire le bug

x

### Qu'aurait-il dû arriver ?

x

### Date et heure de la production du bug

09-07 19:14:30

### Serveur

island-06

### Information supplémentaire

UUID: ccf4c91d-a9da-442e-94df-2a03f6b3cb1a
Position: 5386 38 -3596 SuperiorWorld
Ping: 16ms

**Comment by NoHere32** [comment]
Hello un patch est déjà en attente de redémarrage
