### ISSUE TITLE
[BUG] classement farmium calculer trop tot

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#440]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

je suis passer entre 23h50 et 23h55 à la troisième place et je n'ai recu que la récompense du 4e

### Étapes à suivre pour reproduire le bug

1. changer de position dans le classement farmium dans les dernieres 5min (voir plus)

### Qu'aurait-il dû arriver ?

le calcul final pour donner les récompenses devrait être fait avec les valeurs dans la minute du gain des récompenses et pas 5min avant

### Date et heure de la production du bug

25/09/2023 18:14 (heure du canada)

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/248b5346-6c12-45e3-825c-0242c4240160)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/427b7fe2-7fe3-4168-a8e5-3ab2fe371ee4)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/d9c2e8d4-81d6-4219-8403-eca1812a279a)

**Comment by Asherate** [comment]
Problème lié aux placeholders classements qui sont pas actualisés assez souvent, je ferme pour l'instant en attendant les nouveaux classements.
