### ISSUE TITLE
[BUG] Gain Xp mineur => Pioche Ultime

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#442]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

la pioche ultime ne donne pas d'xp jobs mineur quand on mine avec

### Étapes à suivre pour reproduire le bug

1. avoir une pioche ultime
2. miner sur son is et voir que l'xp jobs n'augmente pas

### Qu'aurait-il dû arriver ?

elle devrait donner l'xp du jobs mineur quand on mine avec

### Date et heure de la production du bug

26/09/2023 00:14 (heure du canada)

### Serveur

island

### Screen / vidéo

https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/83accdfb-66ec-40e8-a515-8bdbe1202e94

**Comment by ArDiDEx** [comment]
Hello le bug est réglé et le patch sera effectif dans les prochains jours
Merci du report
