### ISSUE TITLE
Report Marteau royal 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#447]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0iSan

### Pseudo discord

Nami

### Que s'est-il passé ?

Bonjour je report un ticket de quelqu'un en rapport avec les chunck je vous laisse voir par vous même sur la vidéo si j'arrive à le mettre

Mais en gros à chaque fois fin toute les 2 moins au moins ça laisse un trou en pleins milieu du 3x3 cela fait la même chose avec la pioche du condamné

Est-ce que le générateur doit-elle respecter les chunck pour éviter ce genre de chose ? 

### Étapes à suivre pour reproduire le bug

https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/95978d44-a4b9-4e26-86a4-fe419a9c9b9c

### Qu'aurait-il dû arriver ?

Ne pas faire du trou à chaque fois

### Date et heure de la production du bug

3h40 30/09

### Serveur

Global

**Comment by LupusArctos4** [comment]
J'ai une question, ça lui arrive à chaque fois sur son générateur ou c'était la première fois et il n'a jamais réussi à le refaire ?
Parce que si c'est ça première fois et ça dernière en date c'est possiblement juste un bug momentané de plugin

**Comment by Alexis700** [comment]
Fix
