### ISSUE TITLE
[BUG] Le NBT fragments zombie

### ISSUE THREAD

**Issue by Naruto83130** [RivrsMc/SeasonSky-Issues#448]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

naruto83130

### Pseudo discord

Flex_Juju_Le_Boss-83#8544

### Que s'est-il passé ?

Le NBT a était changer comme les engrenage, donc les fragment obtenu avant la maj/redem du 01/10/23 ne sont plus stackable avec ceux obtenu avant la maj.

### Étapes à suivre pour reproduire le bug

Avoir un fragment d'avant la maj
Obtenir un fragment après la maj, 
Voir que l on ne peut pas les stacks

### Qu'aurait-il dû arriver ?

Les fragments se stack entre eux

### Date et heure de la production du bug

01/10/23

### Serveur

All

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/144606026/703fb271-e92d-45c9-8626-a3b5fbea443d)

**Comment by LupusArctos4** [comment]
Tout les nbt ont été changer donc tout les anciens items ne sont plus stackable avec les anciens, on a le problème avec tout nos compacter perso

**Comment by Alexis700** [comment]
Faire un ticket pour échanger les anciens items avec les nouveaux
