### ISSUE TITLE
[BUG] Set aventurier

### ISSUE THREAD

**Issue by Jspppppp** [RivrsMc/SeasonSky-Issues#449]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Jspppppp

### Pseudo discord

Mathéo#8230 / Jspppppp (l'ours)

### Que s'est-il passé ?

On vois les lignes de code (fin je suposse que c'est sa) dans la description des nouveaux items aventuriers (obtenu après le redem/maj) " FFFFFFFFFCe plastron [...] " 

### Étapes à suivre pour reproduire le bug

Obtenir une pièce aventurier après le redem/maj du 01/10/2023

### Qu'aurait-il dû arriver ?

Qu'on ne vois pas les FFFF ect

### Date et heure de la production du bug

Tout le temp

### Serveur

Tous je suposse

### Screen / vidéo

Buger : 
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139492099/4af64d8b-207a-44dd-8961-a5246f90bd5a)

Pas Buger : 
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139492099/3a688371-c46c-4be3-926f-e9a800949802)

**Comment by Jspppppp** [comment]
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139492099/e6da1ee7-eaf5-4f0b-aae3-257cf1817b24)
Screen de Trois3 (unnaincendie)

**Comment by Alexis700** [comment]
Fix
