### ISSUE TITLE
Grade légende (afk et le repair all) 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#45]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0iSan 

### Pseudo discord

Nami_san

### Que s'est-il passé ?

Afk = Il te kick tout de même après 15min d'afk et non après 1h
Repair all (pour l'armure ou outils) il est censé être débloqué normalement chaque heure hors là c'est tout les 24h 

### Étapes à suivre pour reproduire le bug

Faire les commande 

### Qu'aurait-il dû arriver ?

Être afk durant 1h
Ainsi que faire une réparation all toutes les heures 

### Date et heure de la production du bug

20h21 9juillet

### Serveur

Global

### Screen / vidéo

![Screenshot_20230709-202054-956](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/301b9b7b-04be-49d6-8d77-da549c894dd2)
![Screenshot_20230709-202015-116](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/3b5b90b6-8b60-431f-80c5-dc02ebb1ee15)

**Comment by LuluxClient** [comment]
Hello c'est fix normalement !
