### ISSUE TITLE
[BUG] Ouverture clés votes

### ISSUE THREAD

**Issue by EziWix** [RivrsMc/SeasonSky-Issues#452]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

EziWix

### Pseudo discord

eziwix

### Que s'est-il passé ?

Quand on ouvre des clés votes et qu'on obtient le fly cela consomme automatiquement le fly.
Je vous mets un exemple ou on peut voir que quand on ouvre la dernière clé, cela marque d'en ouvrir une autre, alors qu'on ne clique même pas.

### Étapes à suivre pour reproduire le bug

Ouvrir une clé vote, et vous verrez que cela consomme le fly directement

### Qu'aurait-il dû arriver ?

Ne pas consommer le fly

### Date et heure de la production du bug

01-10 18:44:25

### Serveur

Spawn-01

### Screen / vidéo

https://clipchamp.com/watch/HyXzlQMP1jm

### Information supplémentaire

UUID: 83489a48-39a8-4d5d-8d7e-3013e97d0f47
Position: 213 138 -1135 world
Ping: 8ms

**Comment by Asherate** [comment]
@EziWix  Je viens de voir ta vidéo, et quand tu gagne le fly il est mis dans ton inventaire et n'est pas consommé, donc je comprend pas très bien le bug, pourrais tu m'en dire plus ?

**Comment by Alexis700** [comment]
Pas de bug
