### ISSUE TITLE
[BUG] houe évolutive

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#453]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

j'ai voulu monter ma houe évolutive mais arrivé à 5 culture casser elle a changer de niveau au lieu de 5000 et hein de suite pour les autres tiers, il manque le facteur 1000 pour les palliers

### Étapes à suivre pour reproduire le bug

1. avoir une houe évolutive
2. casser des cultures (inférieur à 100)
3. la houe est deja level max (soit lvl 5)

### Qu'aurait-il dû arriver ?

il faut rajouter dans le code le facteur 1000 

### Date et heure de la production du bug

01/10/2023 15:17 (heure canadienne)

### Serveur

all

**Comment by LupusArctos4** [comment]
il m'a fallu 3 culture pour qu'elle passe lvl 3
pareil 3 culture pour qu'elle passe lvl 4

et pour les pallier 3 et 4 et 5 c'est écrit : 
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/4eb8b54d-48d6-4add-bab6-2ee248078260)

**Comment by ArDiDEx** [comment]
Hello ça devrait être réglé au restart!
Merci du report
