### ISSUE TITLE
[BUG] casque du survivant

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#454]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

je ne peux pas équipé ni mettre avec la commande /hat le casque du survivant, ca me revoit d'ailleurs une erreur quand je tente de le mettre avec le /hat

### Étapes à suivre pour reproduire le bug

1. avoir le casque du survivant
2. l'équiper ou faire /hat

### Qu'aurait-il dû arriver ?

je devrais pouvoir l'équiper sans passez par le /hat qui au passage ne fonctionne quand meme pas pour cette item

### Date et heure de la production du bug

01/10/2023 23:19 (heure canadienne)

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/46e78955-cfe6-4f78-892e-de407cb3d679)

**Comment by Asherate** [comment]
@LupusArctos4 un simple click-droit pour l'équiper ne fonctionne pas ? Quand je test ça fonctionne pour moi, j'attend ton retour avant de tenter un fix.

**Comment by LupusArctos4** [comment]
@Asherate c'est bon, j'avais juste un pb coté client
