### ISSUE TITLE
[BUG] déconnection joueur message envoyer

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#456]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

quand une personne ne l'is quitte (se déconnecte) ca envoie 8 messages pour dire qu'elle se déconnecte

### Étapes à suivre pour reproduire le bug

1. avoir une personne de connecter de son island
2. lui demander de se déconnecté pour montrer le problème

### Qu'aurait-il dû arriver ?

on devrait voir qu'un seul message de déconnection

### Date et heure de la production du bug

02/10/2023 15:17 (heure canadienne)

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/25c26372-75e8-4e30-a13a-2ffe1575829b)

**Comment by ArDiDEx** [comment]
Hello le bug est réglé et sera sur le serveur dans la semaine
Merci du report
