### ISSUE TITLE
[BUG] vente item pirate collector dans les pnj des dimensions

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#457]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

le grappin pirate a été vendu avec les pnj des dimensions avec le bouton pour tout vendre alors que ca n'était pas le cas avant les dernière mise a jour

### Étapes à suivre pour reproduire le bug

1. avoir un grappin pirate sur soit
2. vendre au pnj de la dimension zombiland avec le bouton tout vendre dans l'inventaire

### Qu'aurait-il dû arriver ?

le grappin pirate n'aurait pas du etre vendu

### Date et heure de la production du bug

02/10/2023 15:27 (heure canadienne)

### Serveur

all

### Information supplémentaire

demande de remboursement refusé de la part d'un staff alors que c'est une erreur de plugin / de nbt-tag
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/af2101ea-cee6-4bf2-a312-152924f9f3c6)

**Comment by Asherate** [comment]
@LupusArctos4 il va être retiré du recycleur, j'autorise le remboursement, si tu as besoin de me ping dans un ticket pour que j'approuve n'hésite pas.

**Comment by LupusArctos4** [comment]
@Asherate d'accord merci mais nous nous l'étions fait quand meme en expliquant le problème à un autre staff mais merci
