### ISSUE TITLE
[BUG] /prestige (commande inconnue)

### ISSUE THREAD

**Issue by Leeniiux** [RivrsMc/SeasonSky-Issues#458]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Leeniiux

### Pseudo discord

clementthibo

### Que s'est-il passé ?

Je remarque que la commande "/prestige" apparaît en rouge dans le tchat, mais elle fonctionne parfaitement.
Elle manque certainement dans le plugin.yml et n'est pas détectée comme une commande.

J'ai tenté plusieurs fois de redémarrer, et le bug semble persister, donc je ne pense pas qu'il vienne de moi.

Bon courage !

### Étapes à suivre pour reproduire le bug

1. Ouvrir le tchat
2. Commencer à écrire /prestige

### Qu'aurait-il dû arriver ?

La commande devrait être blanche et autoriser l'autocomplétion avec la touche tabulation.

### Date et heure de la production du bug

Constante

### Serveur

SeasonSky en général

**Comment by LupusArctos4** [comment]
c'est juste la commande n'est pas en auto complete comme d'autre mais je ne les ai plus en tête
