### ISSUE TITLE
[BUG] texture du pet non changer pour le pet de la box rotative

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#459]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

la texture du pet de la box rotative n'a pas changer ce qui peut poser des problèmes lors des ventes comme si c'était une tentative d'arnaque.

### Étapes à suivre pour reproduire le bug

1. aller voir la box
2. regarder le nouveau pet
3. aller dans le pokedex page 2 et 3 et voir que les pets de la box rotative sont les memes

### Qu'aurait-il dû arriver ?

le nouveau pet nommée **cerich** devrait avoir une autre texture qui represente le bucheron et non un poisson clown

### Date et heure de la production du bug

04/10/2023 13:42 (heure canadienne)

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/290d0b6f-c3e2-4b47-b3bb-510e2e590393)

**Comment by Louise253** [comment]
tu dois charger ton pack déco reco

Merci du report !

**Comment by LupusArctos4** [comment]
ok dommage qu'il y ai pas eu un redem complet du coup ca aurai pu ne pas le faire, mais si c que texture pack niquel
