### ISSUE TITLE
[BUG] Pet Saumon Item (bubbles rouges)

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#46]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

Le pet Saumon donne des morues dans l'eclozr

### Étapes à suivre pour reproduire le bug

1. débloquer le pet saumon
2. le mettre dans un éclozr

### Qu'aurait-il dû arriver ?

ca devrait donner des saumons

### Date et heure de la production du bug

09/07/2023 21:09

### Serveur

island 02

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/2dbe80b5-3ce3-4654-8d77-1628af3e8807)

https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/40d19e49-7944-4173-8cd5-9167f8ea0e0b

**Comment by NoHere32** [comment]
good au prochain redem
