### ISSUE TITLE
[BUG] Pets Cecirh et Gullet ne donnent pas la ressource affichée

### ISSUE THREAD

**Issue by DrimHack** [RivrsMc/SeasonSky-Issues#460]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

DrimHack

### Pseudo discord

DrimHack

### Que s'est-il passé ?

Bonjour, je viens d'acheter sur le serveur Seasonsky les familiers Cecirh et Gullet et tout deux ne donne pas la ressources affichées lorsque je les mets dans mes Eclozr.
Le Gullet devrait donner de la terre cuite mais il donne des slimeballs, le Cecirh devrait donner du gravier mais lui aussi donne des slimeballs.

### Étapes à suivre pour reproduire le bug

1- Avoir les familiers Cecirh et Gullet
2- Les mettre dans des Eclozr
3-Vérifier que la ressource produite n'est pas celle écrite sur les familiers

### Qu'aurait-il dû arriver ?

Autres descriptions des ressources sur les familiers, indiquer la vrai ressource que vont donner les familiers

### Date et heure de la production du bug

4/10/2023 à 22h37

### Serveur

Eldoria

**Comment by Asherate** [comment]
Fix
