### ISSUE TITLE
[BUG] [i] dans le chat

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#461]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

on peut [i] les armor stand rename avec un name tag et ca affiche la couleur dans le chat

### Étapes à suivre pour reproduire le bug

1. rename un name tag avec le code couleur de minecraft et le texte que l'on veut mettre
2. mettre le name tag sur un armor stand pour le rename et ainsi avoir un texte flottant
3. casser l'armor stand
4. le reprendre dans la main
5. faire [i] dans le chat avec l'armor stand dans la main

### Qu'aurait-il dû arriver ?

on ne devrait pas fonctionner avec l'armor stand mais seulement avec tout les items au moins ca éviterait des bouts de messages coloré dans le chat

### Date et heure de la production du bug

04/10/2023 18:03 (heure canadienne)

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/478dd10b-c109-45bc-ba44-0ad29560820b)

**Comment by Alexis700** [comment]
ça ne sera pas corrigé

**Comment by Asherate** [comment]
C'est corrigé
