### ISSUE TITLE
[BUG] Casque du mineur

### ISSUE THREAD

**Issue by Isweazu** [RivrsMc/SeasonSky-Issues#463]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Isweazu

### Pseudo discord

xx4040

### Que s'est-il passé ?

Une fois le casque du mineur équipé, nous ne recevons pas les 6% d'argent du métier en +

### Étapes à suivre pour reproduire le bug

équipé un casque du mineur et aller miner

### Qu'aurait-il dû arriver ?

Avoir les 6 % d'argent en %

### Date et heure de la production du bug

5/10 à 22h42

### Serveur

all

**Comment by Asherate** [comment]
@ArDiDEx comme #499

**Comment by ArDiDEx** [comment]
Hello
ça ne pourra pas être réglé
Merci quand même du report
