### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Ornlo** [RivrsMc/SeasonSky-Issues#464]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Ornlo

### Pseudo discord

Ornlo

### Que s'est-il passé ?

pas recus une récompense apres avoir claime job pecheur nv.3

### Étapes à suivre pour reproduire le bug

monter nv.3 pecheur et /jobs claim

### Qu'aurait-il dû arriver ?

recevoir ma récompense

### Date et heure de la production du bug

~1h30

### Serveur

Eldoria

### Information supplémentaire

j'avais de la place dans mon inventaire

**Comment by LupusArctos4** [comment]
Issue #425
