### ISSUE TITLE
[BUG] Crystaux de saison non déposables 

### ISSUE THREAD

**Issue by Lucy-2077** [RivrsMc/SeasonSky-Issues#465]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

DefiDegue

### Pseudo discord

lucy2077_

### Que s'est-il passé ?

Il est impossible de déposer les cristaux de saison

### Étapes à suivre pour reproduire le bug

1 - Tenter de déposer des cristaux de saison dans le crystal d'ile

### Qu'aurait-il dû arriver ?

Qu'il soit déposé dans le crystal d'ile

### Date et heure de la production du bug

06/10/2023 à 12h00

### Serveur

Skyblock

### Screen / vidéo

https://github.com/RivrsMc/SeasonSky-Issues/assets/20909184/7bdf0373-63d6-4d6b-a235-e082b886f843

**Comment by LupusArctos4** [comment]
_info pour les dev_ Je pense que c'est du au fait que le nbt des cristaux ont changer et que celui dans le cristal n'est quant à lui pas changer

**Comment by Asherate** [comment]
fix
