### ISSUE TITLE
[BUG] bonus de vie infini

### ISSUE THREAD

**Issue by Bellanny** [RivrsMc/SeasonSky-Issues#466]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Bienou

### Pseudo discord

Bellanny

### Que s'est-il passé ?

Hier soir après le retour en ligne du serveur, j'ai acheté des clés halloween, j'ai été voir rapidement le monde halloween et les caisse puis je suis revenu au spawn pour les clés. parfois je prenais des dégâts sans savoir d'où ça venait, ni perte de cœur. J'ouvres mes clés puis de retour sur mon ile (celle de mon dc) je m'amuse à mettre l'armure Jason (il me manque que la chemise) et quand je retire mon armure pirate pareil reprise de dégâts avec perte cœur (je les avais encore tous) et je l'a pose sur une armor stand et quand je la reprend pour la remettre, c'est là que je constate un manque de cœur. Je retire l'amure les cœur ne remonte pas, je déco reco pareil et ce matin à ma co c'est encore le cas peu de cœur. Par contre et ça je ne l'avais pas vu hier mais j'ai bonus de vie en infini sans savoir ce que c'est ni d'où ça vient. C'est peut être ça le truc

### Étapes à suivre pour reproduire le bug

Je ne sais pas d'où est venu le bonus de vie infini car je n'avais pas encore ouvert mes rune mystères (ouverte que ce matin)
La rune de vitalité des ombres donne bien le bonus vie mais ne rajoute que 5 cœurs et non infini et je n'avais pas encore ouvert de runes mystères

### Qu'aurait-il dû arriver ?

Ne pas avoir le bonus de vie infini mais bien 5 coeurs avec la rune

### Date et heure de la production du bug

06/10/2023 à 22h40

### Serveur

island 3

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/49778895/2d7b589b-fe16-453e-8791-0bfdb6aed202)

![image2](https://github.com/RivrsMc/SeasonSky-Issues/assets/49778895/d5a3f426-7f8e-4768-9d39-8e5176c0fe9f)

### Information supplémentaire

Le bonus de vie infini à été retiré après avoir bu un seau de lait

**Comment by Zwartkat** [comment]
j'ai trouvé un bug qui pourrait être la cause , le masque de jockey donne l'effet bonus de vie en main. Lorsqu'on enlève le masque en le posant sur un porte armure ou un cadre l'effet est conservé

**Comment by ArDiDEx** [comment]
Hello ça devrait être fix
Merci du report

**Comment by ArDiDEx** [comment]
Oups trompé d'issue my bad

**Comment by Alexis700** [comment]
Fix
