### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ind3ciss** [RivrsMc/SeasonSky-Issues#467]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Leteckk

### Pseudo discord

leteck

### Que s'est-il passé ?

Quand on met en vente un deuxieme item sur un coffre vendant deja un item, l'item flottant du deuxieme item mis en vente spawn en 2 fois et ne se supprime pas meme avec le redémarrage des serveurs.

### Étapes à suivre pour reproduire le bug

Ajouter un premier à vendre sur un coffre shop, en mettre un deuxieme en vente sur le meme coffre.

### Qu'aurait-il dû arriver ?

Que le deuxieme item ne sois pas apparu en 2 fois

### Date et heure de la production du bug

08/10/2023 19H29

### Serveur

island-04

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/63777308/146c8c34-97fc-4809-9008-798d7fb44f26)

**Comment by Asherate** [comment]
Bug du plugin utilisé pour les shops, toujours pas de fix de la part du développeur, en attente.
