### ISSUE TITLE
Coffre de vente /qs

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#47]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0iSan 

### Pseudo discord

Nami_san

### Que s'est-il passé ?

En gros une fois que quelqu'un passe le rang il accès à 5 coffres de vente avec le /qs 
Hors les joueurs ils ne peuvent aller au delà des 3coffres de ventes 

### Étapes à suivre pour reproduire le bug

1. Passer le rang voyageurs
2. Faire des coffres des ventes
3. Vendre les objets cliquant

### Qu'aurait-il dû arriver ?

Avoir les 5 coffres de vente au lieu de 3

### Date et heure de la production du bug

21h31 9juillet

### Serveur

Global

### Screen / vidéo

![Uploading image-47.png…]()

**Comment by NoHere32** [comment]
good au prochain redem
