### ISSUE TITLE
[BUG] La pioche des ombres ne vend pas automatiquement le charbon

### ISSUE THREAD

**Issue by Mak-kennedy** [RivrsMc/SeasonSky-Issues#472]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Makkennedy

### Pseudo discord

Mak-Kennedy

### Que s'est-il passé ?

Cassé du charbon avec la pioche des ombres, le charbon est drop par terre mais quand on le récupère, rien ne se passe.
Sa donne dans l'inventaire 1-2 charbon.

### Étapes à suivre pour reproduire le bug

Avoir une pioche des ombres
Miner un minerai de charbon

### Qu'aurait-il dû arriver ?

La vente auto du charbon ( indiqué dans la description de la pioche)

### Date et heure de la production du bug

09/10/23 à 21h17

### Serveur

SeasonSky

**Comment by Alexis700** [comment]
Fix
