### ISSUE TITLE
[SUGGESTION] Rajoutez si c’est possible le titre en obligatoire pour les issues

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#473]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

Suggestion : rajouter l’obligation de remplir le titre en plus de juste [BUG] car pour trouver un bug qui a déjà été report ou pour savoir les bugs qu’il y a en ce moment / récent, c’est compliqué de savoir

### Étapes à suivre pour reproduire le bug

Voir section « que s’est il passé ? »

### Qu'aurait-il dû arriver ?

Voir section « que s’est il passé ? »

### Date et heure de la production du bug

09/10/2023 22:54 (heure canadienne)

### Serveur

GitHub

**Comment by Asherate** [comment]
@LuluxClient je sais pas si jamais tu passes par là et que tu peux faire quelque chose pour ça

**Comment by LuluxClient** [comment]
Je vais voir ce que je peux faire mais vu que je préremplie "[BUG]" je risque de juste le retirer et edit 2-3 trucs pour tester

**Comment by LupusArctos4** [comment]
j'essaie de mon coté des choses aussi pour voir

**Comment by LupusArctos4** [comment]
personnellement j'ai trouver que ce n'était pas possible, sinon le moyen et de mettre une case à cocher mais pas avec les 2 premières pour ne pas que les gens click sur les 3 déjà que les gens ne regarde pas s'il y a déjà une issue d'ouvert sur ce qu'ils reportent alors si tu le mets au même endroit ne vont juste pas lire, pour moi faudrait la mettre tout en bas au moins ca leur dit quand il valide mais ca reste mon avis
