### ISSUE TITLE
[BUG] Solde d'argent passé en négatif

### ISSUE THREAD

**Issue by DrimHack** [RivrsMc/SeasonSky-Issues#474]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

DrimHack

### Pseudo discord

DrimHack

### Que s'est-il passé ?

En me reconnectant sur le serveur SeasonSky, je me suis rendu compte que mon solde d'argent était de -1.5m. Lorsque je déco je laisse toujours l'intégralité de mon argent sur le compte de banque, j'avais donc 0 lorsque je me suis déconnectais et me voilà à -1 million 5 cents mille en négatif lors de ma reconnexion et ce malgré des ventes que j'ai effectué en étant déconnecté, pour un total de 845 000$. J'ai donc au total perdu 2 345 000$

### Étapes à suivre pour reproduire le bug

1. Ce déconnecter du serveur Seasonsky
2. Ce reconnecter
3. Observer son solde en négatif
4. Remarquer que certains objets avaient été vendus et que mon solde est de -1.5m

### Qu'aurait-il dû arriver ?

Se déconnecter du serveur Seasonsky, se reconnecter, voir son solde en positif, observer les objets vendu pendant la déconnexion et voir l'argent des objets vendus sur son solde, soit 845 000$

### Date et heure de la production du bug

21h environ

### Serveur

Eldoria

### Screen / vidéo

![minecraft -1 5m](https://github.com/RivrsMc/SeasonSky-Issues/assets/146998485/133b79ab-e4b8-4f5c-a484-9bb89d425124)
![date de vente et heure](https://github.com/RivrsMc/SeasonSky-Issues/assets/146998485/6de632ea-b63a-40d9-8c03-db9f57400e10)
![vente numéro 1 25000](https://github.com/RivrsMc/SeasonSky-Issues/assets/146998485/b842e335-fe5c-432a-8648-519790b784ef)
![vente numéro 2 200 000](https://github.com/RivrsMc/SeasonSky-Issues/assets/146998485/b69e81e5-8299-47e2-b279-80d3d79f6d00)
![vente numéro 3 595 000](https://github.com/RivrsMc/SeasonSky-Issues/assets/146998485/e9a53f63-44b0-4ca2-a9b6-ac5d1168ef1a)
![vente numéro 4 25000](https://github.com/RivrsMc/SeasonSky-Issues/assets/146998485/a20632ad-6ea5-4f36-bda4-e47d7b868c2a)

**Comment by ArDiDEx** [comment]
Hello le bug devrait être fix depuis hier 5:00
Merci du report
