### ISSUE TITLE
[BUG] Redstone qui s'etaint

### ISSUE THREAD

**Issue by Naruto83130** [RivrsMc/SeasonSky-Issues#476]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

naruto83130

### Pseudo discord

Flex_Juju_Le_Boss-83#8544

### Que s'est-il passé ?

Nous avons rencontré un bug sur la redstone sur notre is, quand on s'éloigne de la clock cette dernière se désactive, a environ 50block de distance. J avais demander a stephane2000 pour savoir si il en savait quelque chose: "non je n en sais rien"
Donc j ai ticket mais on ma dit qu'il faut att un haut staff pou faire juste un report bug. 

### Étapes à suivre pour reproduire le bug

Avoir une clock, s'éloigner d environ de 50block, donc plus de signale de redstone 

### Qu'aurait-il dû arriver ?

La clock ne s arrête pas a un certain nombre de block. (les pistons reste en mode pousser.)   

### Date et heure de la production du bug

Toujours

### Serveur

All

**Comment by Alexis700** [comment]
Fix
