### ISSUE TITLE
[BUG]  Générateur prestige 0

### ISSUE THREAD

**Issue by Zwartkat** [RivrsMc/SeasonSky-Issues#477]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Zwartkat 

### Pseudo discord

Zwartkat 

### Que s'est-il passé ?

On a la possibilité de changer de générateur sans passer le prestige 1 donc on ne peut pas revenir au générateur à minerais sans avoir le premier prestige . On est donc bloquer avec un générateur sans minerais 

### Étapes à suivre pour reproduire le bug

/générateur -> cliquer sur la génération en bas à gauche (andesite, granite,etc...) 

### Qu'aurait-il dû arriver ?

Possibilité de remettre le générateur du prestige 0 

### Date et heure de la production du bug

11/10 23h

### Serveur

Ile

**Comment by Alexis700** [comment]
Oui on ne peut pas reprendre le générateur 0, mais il donne juste un petit pourcentage de charbon, logiquement c'est même pas rentable de miner dessus, il faut mieux aller dans le canyon pour ça, donc on n'ajoutera pas le 0
