### ISSUE TITLE
[BUG] Faux de la mort

### ISSUE THREAD

**Issue by gus04** [RivrsMc/SeasonSky-Issues#478]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

robin_gus

### Pseudo discord

robin.3003

### Que s'est-il passé ?

avec les champs opti la houe bug 

elle ne vend pas toute les verrues (certaine tombe au sol) de plus, elle casse les ficelle alors que hier dans la nuit ne le faisais pas pour ma part 

### Étapes à suivre pour reproduire le bug

prendre la houe + champs opti 

l'utiliser de façon normal 

### Qu'aurait-il dû arriver ?

revente de verrue automatique + ne pas casser les ficelle 

### Date et heure de la production du bug

13 

### Serveur

island 2

**Comment by NASTOUUH** [comment]
**Testé en jeu avec le joueur**, effectivement **quelques verrues ne sont pas vendu** et **une ficelle c'est cassé**, mais en dehors de ca je ne pense pas que l'on puisse y faire grand chose

**Comment by Isweazu** [comment]
> **Testé en jeu avec le joueur**, effectivement **quelques verrues ne sont pas vendu** et **une ficelle c'est cassé**, mais en dehors de ca je ne pense pas que l'on puisse y faire grand chose

Il n'y a pas que la ficelle, celle-ci casse aussi des verrues, on peut retrouver des trous dans les champs après un passage à la houe, les trois sont causé par la houe, elle ne le faisait pas hier, je pense qu'il y a eu une mauvaise manipulation sur celle-ci et que quelque chose a été touché, mais ça serais bien de vérifier afin d'éviter de casser entièrement un champs à force de passer dedans ^^

**Comment by Asherate** [comment]
@Isweazu j'ai tenté un fix pour les ficelles, tu pourras me faire demain si c'est toujours d'actualité ?

**Comment by LupusArctos4** [comment]
J'ai pu faire des tests depuis le patch et je n'ai pas trouver de nouveau problème donc pour moi le patch fonction

**Comment by Alexis700** [comment]
Corrigé
