### ISSUE TITLE
[BUG] Texture /aventure Halloween

### ISSUE THREAD

**Issue by TheLouuKa** [RivrsMc/SeasonSky-Issues#479]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

LouuKa_

### Pseudo discord

.-.louka

### Que s'est-il passé ?

Dans un serveur 02 du /aventure Halloween, on peux voir quelque chunck qui n'ont pas de texture 
J'ai fait la vérif avec un autre Guide, il ne les vois pas les texture non plus 

### Étapes à suivre pour reproduire le bug

Allez au aventure Halloween (serveur-02)

### Qu'aurait-il dû arriver ?

Voir les texture

### Date et heure de la production du bug

17h50

### Serveur

Aventure Halloween serveur 02

### Screen / vidéo

https://www.xbox.com/play/media/de6XTdpELm

**Comment by Alexis700** [comment]
Bug de chargement du pack on peut rien y faire
