### ISSUE TITLE
[BUG]  Fusion livre bibliothécaire 

### ISSUE THREAD

**Issue by Zwartkat** [RivrsMc/SeasonSky-Issues#48]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Zwartkat 

### Pseudo discord

Zwartkat 

### Que s'est-il passé ?

Mettre les enchantements des livres de la bibliothécaire sur un item ne fonctionne pas

### Étapes à suivre pour reproduire le bug

1. Avoir un livre d'enchantement obtenu de façon random par la bibliothécaire 
2. Essayer de fusionner le livre avec l'item pouvant avoir l'enchantement 

### Qu'aurait-il dû arriver ?

Enchantements du livre  mis sur l'item dans l'enclume

### Date et heure de la production du bug

19:30 9/07

### Serveur

Spawn

**Comment by NoHere32** [comment]
pas compris

**Comment by Zwartkat** [comment]
Si tu utilises un livre obtenu par la bibliothécaire du spawn (après ouverture) , tu peux pas mettre l'enchantement du livre sur un item

**Comment by itsme-to** [comment]
Effectif au prochain merge !
