### ISSUE TITLE
[BUG] Achat clé rotative /vip

### ISSUE THREAD

**Issue by IDeltaCocoI** [RivrsMc/SeasonSky-Issues#481]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Delta_Coco

### Pseudo discord

Delta_Coco

### Que s'est-il passé ?

Lors de l'achat de clé de la box rotative. Je clique une première fois, sur le nombre de clé que je veux acheter, ici une seul qui coute 350 Scoins. Puis, lorsque je doit confirmer mon achat il me dit que cette dernière coute x2 plus chère soir ici 700 Scoins.

### Étapes à suivre pour reproduire le bug

1. /vip
2. Achat clé
3. Sélectionner le nombre de clés box rotative souhaiter
4. Voir que lors de la confirmation le prix à doublé

### Qu'aurait-il dû arriver ?

Le prix doit être le même lorsqu'on choisie le nombre de clé et lors de la confirmation.

### Date et heure de la production du bug

12/10/2023 23h50

### Serveur

Serveur island-02

### Screen / vidéo

![2023-10-12_23 57 13](https://github.com/RivrsMc/SeasonSky-Issues/assets/141357456/15370d29-1dc4-4f38-afec-0f66dd282f21)
![2023-10-12_23 57 10](https://github.com/RivrsMc/SeasonSky-Issues/assets/141357456/636c04fe-8815-4b50-b56d-689be87a3742)

**Comment by Alexis700** [comment]
Fix
