### ISSUE TITLE
[BUG] L'affiche des récompenses pour un vote diffère entre in-game et le site internet.

### ISSUE THREAD

**Issue by MrR4P70R** [RivrsMc/SeasonSky-Issues#483]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MrR4P70R

### Pseudo discord

MrR4P70R

### Que s'est-il passé ?

Seulement une différence d'information entre les informations affichées in-game et les informations affichées sur le site internet.

### Étapes à suivre pour reproduire le bug

**In-game**

1. Ouvrir le menu en envoyant /vote
2. Passer sa souris sur le gros bouton du milieu **voter serveur**.

**Sur le site**
1. Se rendre sur la page de vote du site internet
2. Se connecter pour afficher les 2 boutons pour accéder aux 2 sites de votes.

### Qu'aurait-il dû arriver ?

Les informations de récompense devraient être alignées entre-elles.
La réalité (actuellement du moins) correspond aux informations sur le site internet.

### Date et heure de la production du bug

13-10 23:54:53

### Serveur

Spawn-02

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/81534506/2630c5f1-c2d6-4016-8883-497c44b016b6)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/81534506/dfc8d41e-034d-4867-8255-2bbf443f0524)

### Information supplémentaire

UUID: eba21f8f-ed86-4113-881e-1c07312b8a38
Position: 233 138 -1134 world
Ping: 19ms

**Comment by Alexis700** [comment]
Fix
