### ISSUE TITLE
[BUG] Canne Ultime/Rune Robustesse

### ISSUE THREAD

**Issue by Aelotra** [RivrsMc/SeasonSky-Issues#487]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Aelotra

### Pseudo discord

Aelotra

### Que s'est-il passé ?

La Rune de Robustesse ne s'applique pas sur la Canne a Pêche Ultime, malgré le fait quelle possède une durabilité custom

### Étapes à suivre pour reproduire le bug

1. Prendre une Rune de Robustesse
2. Clique Gauche avec la Rune sur la Canne Ultime

### Qu'aurait-il dû arriver ?

Le menu d'application des runes devrait s'afficher

### Date et heure de la production du bug

16/10/2023 17:55

### Serveur

all

**Comment by ArDiDEx** [comment]
Hello
ça devrait être régler au prochain restart
Merci du report
