### ISSUE TITLE
[BUG] Trou dans le monde aventure de la Foret Mystique

### ISSUE THREAD

**Issue by 1therence** [RivrsMc/SeasonSky-Issues#488]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

therence1

### Pseudo discord

Thérence

### Que s'est-il passé ?

Je me suis baladé dans le monde Aventure (Foret Mystique), et je suis tombé dans l'eau. Je constate qu'il y a un trou dans les blocs au sol (-27 -25 -39).
Possible de reparer ça ?

### Étapes à suivre pour reproduire le bug

Aller au coordonnés
Vous tomberez dans l'eau

### Qu'aurait-il dû arriver ?

Ne pas Tomber dans l'eau.

### Date et heure de la production du bug

16/10. 20h10

### Serveur

Spawn-01

**Comment by Alexis700** [comment]
Fix
