### ISSUE TITLE
[BUG] Hache royale ne fonctionne plus pour les quetes

### ISSUE THREAD

**Issue by LLucrece** [RivrsMc/SeasonSky-Issues#49]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Lucrece

### Pseudo discord

Lucrece

### Que s'est-il passé ?

Aprés le patch de la hache : la  Hache royale ne fonctionne plus pour les quetes "casser .."

### Étapes à suivre pour reproduire le bug

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de la production du bug

09/27 à 23h52

### Serveur

serv2

**Comment by TopeEstLa** [comment]
Yop normal, les items avec des action custom ne compte pas pour les quête.
