### ISSUE TITLE
[BUG] Pioche des ombres impossible de miner le générateur

### ISSUE THREAD

**Issue by Razakeal** [RivrsMc/SeasonSky-Issues#490]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Razakeal

### Pseudo discord

Razakeal

### Que s'est-il passé ?

Lorsque l'on mine les blocs du générateur avec la pioche des ombres, ils sont brûlés instantanément dans la lave du générateur.

### Étapes à suivre pour reproduire le bug

1 Créer un générateur classique
2 Miner avec la pioche des ombres
3 Les blocs se brûlent 

### Qu'aurait-il dû arriver ?

Les blocs auraient du être drop

### Date et heure de la production du bug

16.10.23 21:35

### Serveur

S4

### Information supplémentaire

Le générateur fonctionne avec une pioche classique 
Bouger le générateur ne résout pas le bug

**Comment by Alexis700** [comment]
Ne pas miner à côté de la lave?
