### ISSUE TITLE
[BUG] generateur custom inefficaces sur certains blocs

### ISSUE THREAD

**Issue by Alexandre-Gregoire** [RivrsMc/SeasonSky-Issues#494]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Que s'est-il passé ?

Bonjour alors c'est assez compliquer a expliquer mais je vais essayer : 

- moi et mon amis on construit une ferme a mousse et étant donné que la mousse ne transforme que la stone les minerais en trop sont récupéré dans un stockage
- on se rend compte qu'une ligne ne génère pas de minerais (donc 1 seul block et avec le générateur a deepslate il ya de la stone a la place de la deepslate seulement a cet endroit la) on décide donc de faire un ticket
- dans le ticket serbiere regarde avec moi et me dit d'essayer plusieurs chose comme casser tout les blocs ou reposer la lave mais rien ne marche il me dit d'attendre le restart du matin
- le lendemain le bug étant toujours présent (malgré le reset) je me décide de reconstruire la farm a un autre endroit elle a marché 1 jour et apres cette date la elle commence a rebug et cette fois ci sur 2 ligne et cela m'embete un peux de devoir reconstruire la farm chaque jour

/!\ c'est bien une ferme a stone et pas une ferme a cobble
edit : je viens de faire le screen et j me rend compte qu'il y'a une ligne qui a été "debug" je ne sais pas comment mais c'est le cas

### Étapes à suivre pour reproduire le bug

faire la ferme a mousse et attendre 
- le tuto https://www.youtube.com/watch?v=-xaHoR-z5as

### Qu'aurait-il dû arriver ?

que le generateur soit actif et ne genere pas de la stone constamment

### Date et heure de la production du bug

18-10 16:03:21

### Serveur

island-04

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/114668095/1e551264-7738-4d0a-808a-080b00b5d0b9)
j'ai plus les screens de la premiere machien mais le bugs était le meme sauf que c'etait sur la 3 eme ligne ici c'est sur la 5eme

### Information supplémentaire

UUID: 3041e8a8-a07b-4ca4-9df2-d272302b3bc9
Position: 16156 100 -46809 SuperiorWorld
Ping: 14ms

**Comment by Alexis700** [comment]
J'ai essayé de reproduire le bug avec ta machine, elle fonctionne très bien donc je sais pas d'où ça pourrait venir, si jamais tu peux me montrer le bug n'hésite pas à me contacter sur discord
