### ISSUE TITLE
[BUG] Rune de vitesse ultime inutilisable

### ISSUE THREAD

**Issue by MathoRzZz** [RivrsMc/SeasonSky-Issues#495]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MathoRGrr

### Pseudo discord

mathorzzz

### Que s'est-il passé ?

Lorsque j'essaye d'équiper une rune de vitesse ultime sur n'importe quel stuff (épée/bottes/pantalon/plastron) ça n'a aucun effet et donc je ne peux pas l'utiliser. Je sais comment ça s'utilise normalement car j'ai déjà utilisé une rune de force ultime sur mon épée.

### Étapes à suivre pour reproduire le bug

Essayer d'utiliser la rune de vitesse ultime.

### Qu'aurait-il dû arriver ?

Utiliser l'item et effectuer la probabilité de réussite de la rune.

### Date et heure de la production du bug

18/10 17h

### Serveur

tous 

### Screen / vidéo

https://github.com/RivrsMc/SeasonSky-Issues/assets/148364597/237f28e2-7f26-44c6-9ee6-63d250aa0836

**Comment by MathoRzZz** [comment]
Visiblement, le bug a été corrigé mais le github n'a pas été fermé

**Comment by ArDiDEx** [comment]
Hello, sûrement que les serveurs îles n'avaient pas été redémarré et qu'il ne reconnaissait donc pas encore la rune, si cependant ta rune est toujours bug je t'invite à faire un ticket pour te faire échanger ta rune
