### ISSUE TITLE
[BUG] Problème avec la réception de clé vote

### ISSUE THREAD

**Issue by Dam-B** [RivrsMc/SeasonSky-Issues#496]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Kaamiii

### Pseudo discord

@Damzers

### Que s'est-il passé ?

Lors des deux dernières fois ou j'ai voté je n'ai reçu aucune clé vote et seulement un message dans le chat indiquant "vous avez reçu 2 votes"
M'étant reconnecté sur un compte qui était actif lors de la précédente saison et n'ayant pas eu d'activité depuis 8 mois je me demande si le problème ne viendrai pas de la !
Merci pour votre lecture !

### Étapes à suivre pour reproduire le bug

1. Connection depuis le lien in-game au site de vote avec saisi du pseudo
2. Effectuer les votes pour les deux sites
3. Re-login le compte inactif sur le site seasonsky.fr
4. Problème lors de la réception du message en jeu

### Qu'aurait-il dû arriver ?

Si mes souvenirs sont bon le message devrait être "vous avez reçu 2 clé vote" et non pas "vous avez reçu 2 votes"

### Date et heure de la production du bug

19-10 01:45:14

### Serveur

Spawn-01

### Information supplémentaire

UUID: ed928aed-a9ca-4170-bea2-a1a70cc63483
Position: 214 138 -1146 world
Ping: 33ms

**Comment by ArDiDEx** [comment]
Hello les votes doivent désormais être récupérer via le menu /vote avec le bouton "récupérer"
Effectivement c'est différent d'en V3 ou les clés étaient directement données, la "virtualisation" des votes a été mis en place depuis la V4

Si tu as toujours des questions de comment récupérer tes votes n'hésite pas à contacter le staff sur discord ou ingame
Bon jeu à toi
