### ISSUE TITLE
[BUG] épée ultime

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#497]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

l'épée ultime ne vend pas :
- fer
- redstone
- glowstone
- morue / saumon (crue / cuit)
- poisson globe et tropical

### Étapes à suivre pour reproduire le bug

1. avoir une épée ultime
2. tuer des mobs avec la table de loot présent au dessus (sorcière, golem de fer / zombie, gardian)

### Qu'aurait-il dû arriver ?

l'épée ultime devrait vendre les items

ajouter les fioles et stick de bois pour les spawner a sorcière ??

### Date et heure de la production du bug

18/10/2023 22:58 (heure du canada)

### Serveur

all

**Comment by Asherate** [comment]
Fix
