### ISSUE TITLE
[BUG] vote party

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#498]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

le vote party s'active quand il atteint 505 / 500

### Étapes à suivre pour reproduire le bug

1. atteindre les 500 / 500 en vote global du serveur

### Qu'aurait-il dû arriver ?

il devrait s'activer quand il atteint 500 et non 505

### Date et heure de la production du bug

20/10/2023 10:03 (heure canadienne)

### Serveur

all

**Comment by Asherate** [comment]
@ArDiDEx le vp s'actualise par forcément dès qu'il atteint l'objectif

**Comment by LupusArctos4** [comment]
d'accord merci
