### ISSUE TITLE
[BUG] Chapeau du fermier

### ISSUE THREAD

**Issue by LaBaane** [RivrsMc/SeasonSky-Issues#499]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

LaBaane_

### Pseudo discord

labananeflambee_

### Que s'est-il passé ?

Le Chapeau du fermier obtenable dans la box rotative ne fonctionne pas. Dans la description de celui ci est marqué "+6% d'argent du métier fermier", le problème est que ce boost de 6% ne s'applique pas, peu importe la manière d'équiper le chapeau (cliquer glissé dans l'inv ou click droit avec l'item en mains). J'ai porter le chapeau pendant plusieurs heures, même en faisant un /spawn pour changer de serv et mettre a jour les stats de jobs ça ne fonctionne pas. 

### Étapes à suivre pour reproduire le bug

1- Retirer tout pet ou quelconque boost qui pourrais changer les stats du jobs fermier 
2- /jobs info fermier (verifier les stats pour un item ex: patates)
3- clique droit avec le chapeau en mains pour l'équiper
4- Attendre quelques seconde ou se tp sur un serv différent pour mettre a jour les stats
5- /jobs info fermier (verifier les stats du meme item que dans l'étape 1)

### Qu'aurait-il dû arriver ?

le chapeau devrait appliquer un boost de 6% sur l'argent reçus en récoltant une culture pour le jobs fermier.

### Date et heure de la production du bug

21-10 17:15:41

### Serveur

island-03

### Screen / vidéo

[https://youtu.be/PWwSMPBI0kI?si=su4fuY5zIBjbejo6](url)

### Information supplémentaire

UUID: 96778800-7c9b-49d7-bcad-f7cf2a70a206
Position: -5294 187 -1701 SuperiorWorld
Ping: 22ms

**Comment by Asherate** [comment]
L'action EQUIP_COMMAND ne semble pas fonctionner sur les casques custom, en l'occurence ici RAW_IRON, même effet testé sur un chestplate, fonctionne parfaitement @ArDiDEx

**Comment by ArDiDEx** [comment]
Hello
ça ne pourra pas être réglé
Merci quand même du report
