### ISSUE TITLE
[BUG] Erreur de texte sur le /pay

### ISSUE THREAD

**Issue by seishiiinsan** [RivrsMc/SeasonSky-Issues#5]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Shxnrxnyoku

### Pseudo discord

Shxnrxnyoku

### Que s'est-il passé ?

Lorsqu'on qu'un joueur se /pay à lui-même (presque personne fait ça mais bon) cela affiche "Evolucraft"

### Étapes à suivre pour reproduire le bug

**1.** /pseudo <son-pseudo> <somme>

### Qu'aurait-il dû arriver ?

Cela doit écrire "SeasonSky" au lieu de "Evolucraft"

### Date et heure de la production du bug

08/07/2023 à 18h30

### Serveur

Partout

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/109074399/a2cc965f-2b27-4f79-a5aa-7fb33db8ce47)

**Comment by LuluxClient** [comment]
C'est fix !
