### ISSUE TITLE
[BUG] Stacking chicken & drop Egg

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#50]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

Les poulets sont stack en 64 et non en 1024 comme les autres mobs
Ils font donc drop beaucoup trop d'oeuf qui ne sont par ailleurs pas vendable au /shop

### Étapes à suivre pour reproduire le bug

1. avoir des spawner a poulet
2. les stack son en 64 et non 1024

### Qu'aurait-il dû arriver ?

il devrait etre stack en 1024 comme les autre mobs et par la meme occasion ca réduirez les oeuf dropper.

### Date et heure de la production du bug

10/07/2023 10:31

### Serveur

island 02

**Comment by itsme-to** [comment]
Effectif au prochain merge !
