### ISSUE TITLE
[BUG] Jason nv2

### ISSUE THREAD

**Issue by Pireus91** [RivrsMc/SeasonSky-Issues#500]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Pireus

### Pseudo discord

Pireus

### Que s'est-il passé ?

Sur le spawn01 du monde Halloween, lorsque l'on tue Jason au nv2, il ne donne aucune récompense et on reste dans l'arène.
Je l'ai tuer 4 fois pour être sur et a chaque fois le même résultat

### Étapes à suivre pour reproduire le bug

01 - Aller sur le spawn 10 du monde halloween
02 - Porter dans jason au nv2
03 - le tuer.

### Qu'aurait-il dû arriver ?

Avoir une récompense et être dehors l'arène 

### Date et heure de la production du bug

22/10/2023 a 11h05

### Serveur

Seasonsky

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139948498/9b1a5794-5a00-455e-b005-edf6d13338b9)

**Comment by Asherate** [comment]
Fix
