### ISSUE TITLE
[BUG] Ventre de betterave compacté 

### ISSUE THREAD

**Issue by Rayzeur91** [RivrsMc/SeasonSky-Issues#501]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Rayzeur91

### Pseudo discord

!⎛⎝Rayzeur⎠⎞#3021

### Que s'est-il passé ?

J'ai acheté des béttrave compacté a 900 u/ sur le pw ReaggesShop 
Pour les revendre sur le LERSA qui les rachette 5000 U 
Je l'es fait une fois tous ses passé nickel 
J'ai re rachetté tous le stock 44 bétrave 
Et impossible des les vendres meme a l'unité il me dise que j'ai pas de bétrave dans mon sac 
J'ai donc filé ses 44 bétrave a bellany

### Étapes à suivre pour reproduire le bug

Aucune idée =/ j'ai expliqué tous mon bug + haut 

### Qu'aurait-il dû arriver ?

Vendre les bétrave et gagné de l'argent 

### Date et heure de la production du bug

22-10 20:05:00

### Serveur

island-05

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/60102862/d30750d4-2319-4a3b-bdea-08fce06a181e)

### Information supplémentaire

UUID: 989145b6-5688-48db-a368-6e9d4ac89b74
Position: 1674 176 -1864 SuperiorWorld
Ping: 9ms

**Comment by Rayzeur91** [comment]
Update elle ma rendu mes 44 bétrave bug et elle ne ce stack meme pas avec les nouvelles créee

**Comment by Rayzeur91** [comment]
Béttrave pausé dans un coin de mon iles 
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/60102862/96f2030c-1d18-4df3-a435-db9133529843)

**Comment by Rayzeur91** [comment]
Update Bétrave swap par un super modo sur le discord

**Comment by Alexis700** [comment]
Fix
