### ISSUE TITLE
[BUG] Frost Walker - Aventure

### ISSUE THREAD

**Issue by Aelotra** [RivrsMc/SeasonSky-Issues#503]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Aelotra

### Pseudo discord

Aelotra

### Que s'est-il passé ?

l'effet Frost Walker fournit par les pets fonctionnent en aventure et gèle les courants d'eau

### Étapes à suivre pour reproduire le bug

se balader avec un pet frost walker

### Qu'aurait-il dû arriver ?

les courant ne devrait pas geler

### Date et heure de la production du bug

24/10/2023 - 16:21

### Serveur

O2

### Screen / vidéo

![Capture](https://github.com/RivrsMc/SeasonSky-Issues/assets/44052000/60a60eef-a32c-46cc-8490-5722f40fe736)

**Comment by Asherate** [comment]
Fix au prochain redem
