### ISSUE TITLE
[BUG] pet boulbi rouge

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#504]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

j'ai monté au niveau 20 le pet Boulbi Rouge pour avoir les 10% de beetroot en plus mais ca ne change rien si on utilise des houes custom en 3x3

### Étapes à suivre pour reproduire le bug

1. avoir un boulbi rouge
2. le monter lvl 20
3. casser des beetroot à la houe pirate ou royale

### Qu'aurait-il dû arriver ?

je devais avoir un 10% de double drop de beetroot comme quand je casse à la main (je l'ai bien que je casse a la main)

### Date et heure de la production du bug

24/10/2023 11:20 (heure canadienne)

### Serveur

island

**Comment by ArDiDEx** [comment]
Hello ça ne sera pas fix
Merci quand même du report
