### ISSUE TITLE
[BUG] Ender Perles ne peuvent pas être utilisées sur IS

### ISSUE THREAD

**Issue by Kirzox** [RivrsMc/SeasonSky-Issues#505]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Tiloux

### Pseudo discord

Tiloux

### Que s'est-il passé ?

Utilisation impossible des ender pearls dans notre is alors que les permissions sont baissées au minimum et que je suis Leader.

Ne peux pas jeter d'ender pearl sur son ile  (Message d'erreur) (You are not permitted to leave this area)

### Étapes à suivre pour reproduire le bug

1. Vérifier les permissions
2. Envoyer une ender pearl
3. rien ne ce passe que ce soit pour moi ou mon ami sachant que les permissions sont au plus basses

### Qu'aurait-il dû arriver ?

Une téléportation classique d'une ender pearl

### Date et heure de la production du bug

24/10/2023 à 18h45

### Serveur

Island-03

### Screen / vidéo

Impossibilité de faire une vidéo donc message d'erreur vérifier directement en live du jeu par [Guide] LouuKa_

![ticket](https://github.com/RivrsMc/SeasonSky-Issues/assets/148947401/bf874512-790f-425b-9b43-381ef3e935de)

screen de la permission activée avec les multiples messages d'erreurs lorsqu'on lance une ender pearl dans le chat.

### Information supplémentaire

Permission pour voler est également activé de la même manière et mon ami à le même problème sur mon is et nous n'essayons en aucun cas de la lancer hors des limites de l'is, uniquement dans notre zone d'accès.

Nom de l'is : nox

:ticket1: Serveur :  Island-03
:ticket2: Pseudo :  Tiloux
:ticket3: Problème : Ne peux pas jeter d'ender pearl sur son ile  (Message d'erreur) (You are not permitted to leave this area)
:ticket4: Demande : Remettre la permission
:ticket5: Staff concerné :  Super Modérateur

**Comment by Asherate** [comment]
Pour le fly ça va être fixé au prochain patch, et pour les enderspearl le message d'erreur semble indiquer que vous essayez de quitter l'île, tu me confirme bien que tu lance bien l'enderpearl dans les territoires de ton is ? @Kirzox

**Comment by Kirzox** [comment]
Oui comme mentionné dans le message au dessus, nous avons exclusivement envoyés nos ender pearls sur le territoire de mon is.
Si besoin je peu refaire une démonstration en live sur le discord.

**Comment by Kirzox** [comment]
J'ai le même problème avec la TNT

Voici la permission activé :

![TNT](https://github.com/RivrsMc/SeasonSky-Issues/assets/148947401/a3bac77c-fd1d-4140-9e46-79173bfcb757)

Et voici le message d'erreur :

![TNT erreur](https://github.com/RivrsMc/SeasonSky-Issues/assets/148947401/bb794008-489f-45da-960b-496c31a2cd9f)

**Comment by LupusArctos4** [comment]
pour ce qui est des TNT c'est normal qu'elles ne sont pas actives, c'est pour évité la duplication de tnt, les farme qui lag etc

**Comment by Kirzox** [comment]
d'accord je comprends pour la TNT, mais quand es t'il des enderpearls ?

**Comment by LupusArctos4** [comment]
les ont peut-être été désactivé après un problème qui permettait de tout traverser dans les islands donc sur des pw qui sont dans des boites, ça causé des problèmes ou les gens pouvait quand même visité les iles
