### ISSUE TITLE
[BUG] description item rune de vitesse box rotative

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#506]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

la description de la rune de vitesse dans la box n'est pas la bonne

### Étapes à suivre pour reproduire le bug

1. regarder la box rotative

### Qu'aurait-il dû arriver ?

il ne devrait pas etre évrit boost : PV mais boost : Vitesse

### Date et heure de la production du bug

25/10/2023 10:20 (heure canadienne)

### Serveur

spawn

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/0046cd44-538e-4a2c-a76f-4d9e8bc8f627)

**Comment by Alexis700** [comment]
Fix
