### ISSUE TITLE
[BUG] /is chat

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#507]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

quand je fais /is chat ca ne me lock par le chat de l'is que je sois au spawn ou sur mon is

### Étapes à suivre pour reproduire le bug

1. faire /is chat pour basculer mon chat en mode chat d'is
2. envoyer un message

### Qu'aurait-il dû arriver ?

quand je fais /is chat je devrais parler que dans le chat de l'is et non dans le chat global

### Date et heure de la production du bug

25/10/2023 10:27 (heure canadienne)

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/0f28547a-e80b-470f-b235-5eb2ca05b785)

### Information supplémentaire

si je fais : `/is chat mon message` et que j'envoie ca marche bien mais c'est le toggle is chat fait avec la commande `/is chat` qui ne fonctionne plus

**Comment by Alexis700** [comment]
Fix
