### ISSUE TITLE
[BUG] faux de la mort

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#508]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

la faux de la mort ne fait plus rien, elle replante plus automatiquement, elle ne casse plus en 3x3 et ne vend plus automatiquement

### Étapes à suivre pour reproduire le bug

1. avoir une faux de la mort
2. casser des cultures (tester avec netherwart)

### Qu'aurait-il dû arriver ?

elle devrait fonctionner comme avant la mise a jour du 25/10/2023 et apres son patch qui avait été fait quelques jours avant

### Date et heure de la production du bug

25/10/2023 11:33 (heure canadienne)

### Serveur

island

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/ad4e577d-9e82-4ded-82c4-42a5c2d66e8a)

**Comment by Alexis700** [comment]
Fix
