### ISSUE TITLE
[BUG] Bug xp pets

### ISSUE THREAD

**Issue by Pireus91** [RivrsMc/SeasonSky-Issues#509]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Pireus

### Pseudo discord

Pireus

### Que s'est-il passé ?

l'xp des bonbon donner au pet ne reflète pas l'xp marquer sur le pets
les bonbon donnes soit 15 ou 45xp.
apres 7 bonbon vert mon pets est a 27.5 d'xp.

### Étapes à suivre pour reproduire le bug

1-invoquer le pet
2-donner des bonbon
3-regarder l'xp du pet

### Qu'aurait-il dû arriver ?

l'xp du pet ne devrait pas être a 27.5xp car ce n'est pas un multiple de 15

### Date et heure de la production du bug

25/10/2023 a 19h05

### Serveur

Seasonsky

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139948498/19a97767-6b36-4013-93b3-3526675f67f5)

**Comment by Alexis700** [comment]
C'est normal car les besoins d'xp pour les pets peuvent être avec un 0.5
![2023-10-26_09 38 39](https://github.com/RivrsMc/SeasonSky-Issues/assets/143590319/aa03399f-7ab4-4045-92b5-1b1f795c1e33)
