### ISSUE TITLE
[BUG] Quête "Miner du bois"

### ISSUE THREAD

**Issue by Enozia** [RivrsMc/SeasonSky-Issues#51]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Enozia

### Pseudo discord

Enozia

### Que s'est-il passé ?

Certains types de bûches de bois ne fonctionnent pas pour les quêtes "miner du bois". 

Bûches concernées : 
- Bûche de palétuvier 
- Tout time de bois compacté (4 bûches de bois dans la table de craft) 

### Étapes à suivre pour reproduire le bug

1. Prendre une quête miner du bois 
2. Casser du bois 

### Qu'aurait-il dû arriver ?

Tous les types de bois devraient être comptabilisés pour cette quête. 

### Date et heure de la production du bug

10/07/2023 10H40

### Serveur

Island-02

### Screen / vidéo

https://github.com/RivrsMc/SeasonSky-Issues/assets/138040525/164c92fb-5789-459f-a2a2-d3db065f42e1

**Comment by NoHere32** [comment]
Ajout du mangrove au prochain transfert
