### ISSUE TITLE
[BUG] spawn marchand ambulant serveur island

### ISSUE THREAD

**Issue by serbiere** [RivrsMc/SeasonSky-Issues#510]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Serbiere

### Pseudo discord

Serbiere

### Que s'est-il passé ?

Un marchand ambulant à spawn sur un serveur island 

### Étapes à suivre pour reproduire le bug

attendre qu'un marchand ambulant spawn

### Qu'aurait-il dû arriver ?

il n'aurait pas du pouvoir spawn

### Date et heure de la production du bug

25/10/23 19H10

### Serveur

island-07

**Comment by Alexis700** [comment]
Corrigé
