### ISSUE TITLE
[BUG] Pet Ninjons description

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#511]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

il y a un oublie dans la description du pet Ninjons

### Étapes à suivre pour reproduire le bug

1. voir le pet
2. regarde sa description

### Qu'aurait-il dû arriver ?

il devrait être écrit +25 **%** dégâts sur les montres et non +25 dégâts sur les montres

### Date et heure de la production du bug

26/10/2023 14:38 (heure canadienne)

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/ff5fd03b-150d-4e9c-9008-75fa5f1a806d)

**Comment by Alexis700** [comment]
Corrigé
