### ISSUE TITLE
[BUG] Effet ninjons lvl 1 non fonctionnel 

### ISSUE THREAD

**Issue by BlZeroTw0** [RivrsMc/SeasonSky-Issues#512]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Bl_ZeroTw0

### Pseudo discord

blzerotw0

### Que s'est-il passé ?

l'effet du ninjons ne fonctionne pas peut importe le mob sur le quel on test ( mobs halloween compris ) 

### Étapes à suivre pour reproduire le bug

- activer le pets 
- taper un mob

### Qu'aurait-il dû arriver ?

l'effet des 25% devrai s'appliquer prenons l'exemple du pioche en diams qui fait respectivement 5 de dmg avec le pet les dégâts devrai être de 6.25 sauf que cela ne fonctionne pas 

### Date et heure de la production du bug

27/10 a 1h45

### Serveur

Island 7

### Screen / vidéo

![RVVTkVCFRUCdMbnTPRxCfw](https://github.com/RivrsMc/SeasonSky-Issues/assets/138042781/878abbbb-cd49-4450-a3da-732fa6b1c46d)
![5Ld81KZ5SYCNsLgrfwaXvQ](https://github.com/RivrsMc/SeasonSky-Issues/assets/138042781/1f252902-adac-4ebd-8fe8-0d1c28045351)
![vhblOLZvTqKRPep8RUJUcw](https://github.com/RivrsMc/SeasonSky-Issues/assets/138042781/8adadc69-7a35-4e13-bb8f-f26b4bf06ecc)

**Comment by Alexis700** [comment]
Corrigé
