### ISSUE TITLE
[BUG] Multiplicateur revente Crokket

### ISSUE THREAD

**Issue by Pas2bol68** [RivrsMc/SeasonSky-Issues#513]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Pas2bol1

### Pseudo discord

pas2bol

### Que s'est-il passé ?

Le pet Crokket est sensé revendre +60% les cristaux de prismarines, le prix de base est de 3$ et avec le pet équipé il passe à 3.9$, ce qui correspond à une augmentation de 30% et non de 60%, le prix devrait être de 4.8$.

### Étapes à suivre pour reproduire le bug

Il suffit d'équiper le pet et regarder dans le /shop

### Qu'aurait-il dû arriver ?

Le prix de vente est de 3.9 et non de 4.8 comme il le devrait.

### Date et heure de la production du bug

Tout le temps

### Serveur

Ile

**Comment by Alexis700** [comment]
Corrigé
