### ISSUE TITLE
[BUG] Mauvaise couleur Plastron l'Explorateur

### ISSUE THREAD

**Issue by FaustinLegrand** [RivrsMc/SeasonSky-Issues#514]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nirimo

### Pseudo discord

Faustin

### Que s'est-il passé ?

Lorsque j'ai reçu le Plastron l'Explorateur Niveau 1 la couleur pour afficher les bonus n'est pas mise

### Étapes à suivre pour reproduire le bug

Afficher la couleur pour le bonus d'Armure Complète, le mot est en blanc + les chiffres

### Qu'aurait-il dû arriver ?

Il aurait du afficher le message mais avec la couleur

### Date et heure de la production du bug

27-10 18:41:57

### Serveur

island-02

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/74976456/27d8ba2e-740b-46ac-b91e-6d667c15c9bb)

### Information supplémentaire

UUID: f127c3be-cb29-42b1-8b46-75c2060ee302
Position: -46801 97 -37797 SuperiorWorld
Ping: 38ms

**Comment by Alexis700** [comment]
Corrigé
