### ISSUE TITLE
[BUG] Houe & Leaves

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#515]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

quand on casse des feuilles avec des houes 3x3, types houe halloween ou houe pirate, cela utilise de la durabilité (ce qui ne devrait pas arriver) mais ne les casses pas (ce qu'il faut)

### Étapes à suivre pour reproduire le bug

1. poser des feuilles
2. casser les feuilles avec des houes 3x3

### Qu'aurait-il dû arriver ?

les houes ne devrait pas perdre de durabilité

### Date et heure de la production du bug

27/10/2023 18:18 (heure canadienne)

### Serveur

island

**Comment by Alexis700** [comment]
C'est l'effet de replanter qui fait ça, il faut mieux utiliser une autre houe pour les feuilles
