### ISSUE TITLE
[BUG]  Rune de Force Ultime

### ISSUE THREAD

**Issue by Aelotra** [RivrsMc/SeasonSky-Issues#516]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Aelotra

### Pseudo discord

Aelotra

### Que s'est-il passé ?

Apres avoir équipé une Rune de Force Ultime sur une épée divine, lors d'un dps check ,
(plus le fait quelle ait les même stats que l'épée ultime avec une rune de même multiplicateur)
je me suis aperçue quelle faisait 5 point de dégâts de moins (fait avec force 3)

### Étapes à suivre pour reproduire le bug

1 - Installer une rune de force ultime sur une arme
2 - Taper des mobs (de préférence avec un indicateur de vie)

### Qu'aurait-il dû arriver ?

l'épée divine aurais du faire autant de dégâts que l'épée ultime

### Date et heure de la production du bug

27/10/2023 - 15H25

### Serveur

all

### Screen / vidéo

https://github.com/RivrsMc/SeasonSky-Issues/assets/44052000/2f9c0229-72ae-4cba-aa05-fcc91e037c16

https://github.com/RivrsMc/SeasonSky-Issues/assets/44052000/ec5774be-8550-4575-8696-cae37a515506

**Comment by Alexis700** [comment]
Alors le problème ne venait pas de la rune de force mais de l'épée en elle même, c'est donc corrigé, je t'invite à faire un ticket quand le patch note sortira (pas avant car ça sera pas encore corrigé sur le prod)
