### ISSUE TITLE
[BUG] compacteur => poche d'encre + colorant noir

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#517]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

Super Compacteur
les poches d'encre ne peuvent pas se compacter
le colorant noir se compacte avec 10 stacks de poches d'encre

Compacteur simple
le colorant noir ne se compacte pas dans le compacteur simple

### Étapes à suivre pour reproduire le bug

1. voir compacter avec compacteur simple et super

### Qu'aurait-il dû arriver ?

on devrait pouvoir compacter les colorants noir et les poches d'encre quelque soit le compacteur

### Date et heure de la production du bug

29/10/2023 09:20 (heure canadienne)

### Serveur

all

**Comment by Alexis700** [comment]
Corrigé
