### ISSUE TITLE
[BUG] Modification du "Masque de Jason"

### ISSUE THREAD

**Issue by Goujonino** [RivrsMc/SeasonSky-Issues#518]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Goujon54

### Pseudo discord

Le G en personne

### Que s'est-il passé ?

Impossible de modifier l'item "Masque de Jason" dans l'enclume pour y ajouter de nouveaux enchantements.

### Étapes à suivre pour reproduire le bug

1. Mettre le "Masque de Jason" dans la première case de l'enclume.
2. Mettre un livre d'enchantement compatible avec un casque dans la 2ème case de l'enclume.

### Qu'aurait-il dû arriver ?

Le "Masque de Jason" devrait apparaître dans la 3ème case de l'enclume avec les modifications apportées.

### Date et heure de la production du bug

29/10/2023 vers 15h/16h

### Serveur

SeasonSky

**Comment by Alexis700** [comment]
ça ne sera jamais possible car le plugin nous force à utiliser des items pour la texture des casques et non des vrais casques minecraft
