### ISSUE TITLE
[BUG] Réparation du KATANA (Box rotative)

### ISSUE THREAD

**Issue by TheLouuKa** [RivrsMc/SeasonSky-Issues#519]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

LouuKa_

### Pseudo discord

.-.louka

### Que s'est-il passé ?

On ne peux pas réparer le KATANA de la box rotative , ni avec le /forgeron ou le /repair 

### Étapes à suivre pour reproduire le bug

Utilisé le KATANA (Box Rotative) , puis faire /forgeron 

### Qu'aurait-il dû arriver ?

Pouvoir réparer le katana 

### Date et heure de la production du bug

//

### Serveur

//

### Screen / vidéo

Screen de l'item 
![2023-10-30_17 45 18](https://github.com/RivrsMc/SeasonSky-Issues/assets/140109392/139d2fbe-cfc7-496a-810b-22d5ad5ec9d1)

**Comment by Alexis700** [comment]
Corrigé
