### ISSUE TITLE
[BUG] description gain is top

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#520]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

le gain de l'is top dans la commande /is top n'est plus d'actualité 

### Étapes à suivre pour reproduire le bug

1. faire /is top

### Qu'aurait-il dû arriver ?

il devrait etre à 6000 scoins, 5000 scoins, 4000 scoins pour les 3 premiers

### Date et heure de la production du bug

31/10/2023 18:40 (heure du canada)

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/e8be9bff-843a-4695-b8fa-2eae4cb2f0b6)

**Comment by Alexis700** [comment]
Corrigé
