### ISSUE TITLE
[BUG] rune de vitesse des ombres sur les bottes ultimes

### ISSUE THREAD

**Issue by J7KL** [RivrsMc/SeasonSky-Issues#522]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

J7KL_

### Pseudo discord

J7KL_

### Que s'est-il passé ?

je ne peut pas mettre la rune de vitesse des ombres sur mes bottes ultime

### Étapes à suivre pour reproduire le bug

mettre la rune sur les bottes

### Qu'aurait-il dû arriver ?

ça aurais du etre demandé si je pouvais l'appliquer

### Date et heure de la production du bug

03-11 12:40:16

### Serveur

island-06

### Information supplémentaire

UUID: 5eb6640e-ac7e-40d1-a01c-0c2cc6ca30ba
Position: -5448 100 -1803 SuperiorWorld
Ping: 13ms

**Comment by Alexis700** [comment]
C'est normal, il faut la mettre sur l'arme principal
