### ISSUE TITLE
[BUG] /shop

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#523]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

le shop de saison présent dans le /shop n'a pas été changer en début de mois tout comme son interface

### Étapes à suivre pour reproduire le bug

1. faire /shop

### Qu'aurait-il dû arriver ?

le shop aurai du être changer en meme temps que le craft des is level et des interfaces, l'interface du /shop n'a pas été changer non plus

### Date et heure de la production du bug

03/11/2023 09:58 (heure canadienne)

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/699197c5-854f-4f1c-a962-4fc5cb44b3ff)

**Comment by Alexis700** [comment]
Alors je savais pas que ça changeais mais c'est pas très très grave, ça changera en janvier
