### ISSUE TITLE
[BUG] rune robustesse des ombres

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#524]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

quand on a une houe halloween avec une rune de robustesse il faut la réparer 2 fois

### Étapes à suivre pour reproduire le bug

1. avoir une houe halloween vide de durabilité avec une rune de robustesse
2. faire 2 fois le /forgeron

### Qu'aurait-il dû arriver ?

on ne devrait pas avoir besoin de la réparer 2 fois avec le /forgeron

### Date et heure de la production du bug

08/11/2023 14:58 (heure canadienne)

### Serveur

all

**Comment by ArDiDEx** [comment]
Hello ça devrait être fix au prochain restart
Merci du report
