### ISSUE TITLE
[BUG] /profil => money

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#525]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

dans on regarde le profil d'une personne (ici benj6735) qui possède plus de 2.147 B$ ca ne peut pas afficher plus alors que dans le /money pseudo (ici benj6735) ca affiche 2.23 B

### Étapes à suivre pour reproduire le bug

1. faire /money pseudo
2. faire /profil pseudo

### Qu'aurait-il dû arriver ?

dans le /profil, la catégorie MONEY n'est pas actualisé apres 2.147 B d'argent sur soit

### Date et heure de la production du bug

09/11/2023 09:57 (heure canadienne)

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/82398475-4f6b-4f63-8c1d-7a2441cdc565)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/2d9dcce5-bae7-4d4b-b20c-0d60324ee615)

**Comment by Alexis700** [comment]
C'est le maximum qu'on peut ressortir avec ce plugin il faudrait refaire un plugin pour faire plus :/
