### ISSUE TITLE
[BUG] /tournoi => canne a sucre

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#527]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

le tournoi de farm type Canne à sucre ne fonctionne pas

### Étapes à suivre pour reproduire le bug

1. casser de la canne a sucre pendant un tournoi de ce type

### Qu'aurait-il dû arriver ?

lorsque l'on casse de la canne à sucre, les points de tournoi devrait compter lors d'un tournois canne à sucre

### Date et heure de la production du bug

09/11/2023 15:44 (heure canadienne)

### Serveur

all

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/df5fd3e3-a133-49bb-b2a1-fb8cd808ad55)

### Information supplémentaire

tournoi qui s'est dérouler le 09/11/2023 à 21h40 (heure francaise)

**Comment by mrsxnshxne** [comment]
Hello, pour éviter d'autres soucis j'ai supprimé la canne à sucre du tournoi, elle reviendra une fois corrigée à 100%
