### ISSUE TITLE
[BUG] Impossible de déposer des items dans le cristal de l'île

### ISSUE THREAD

**Issue by BistiFire** [RivrsMc/SeasonSky-Issues#529]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Bisti_Fire

### Pseudo discord

Bisti_Fire

### Que s'est-il passé ?

Lorsque nous souhaitons déposer des items dans le cristal de l'île afin d'augmenter son niveau d'île, l'interface de celui-ci est vide et n'affiche rien. Cela est d'autant plus embêtant pour les nouveaux joueurs car le tutoriel nécessite de déposer un bloc d'émeraude dedans afin de le poursuivre.

### Étapes à suivre pour reproduire le bug

1. Ouvrir le cristal de l'île
2. Cliquer sur le menu de droite 
3. Constater le souci

### Qu'aurait-il dû arriver ?

Normalement, il y a la liste de tous les items qui peuvent être posés dans le cristal de l'île.

### Date et heure de la production du bug

11/11/2023 vers 11H

### Serveur

Island

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/138015584/1f9098b0-88ca-44d3-95e1-c25e6f301b11)

**Comment by ArDiDEx** [comment]
Hello c'est fix
Merci du report
