### ISSUE TITLE
[BUG] repair deux fois la faux de la mort

### ISSUE THREAD

**Issue by YelaWolf58** [RivrsMc/SeasonSky-Issues#533]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

YelaWolf58

### Pseudo discord

YelaWolf58

### Que s'est-il passé ?

Mon pote m'as passé sa faux de la mort avec une rune robustesse seulement je dois la repair deux fois via le /forgeron 

### Étapes à suivre pour reproduire le bug

Prendre la faux de la mort
La vidé de sa dura
Essayer de la repait via le /forgeron

### Qu'aurait-il dû arriver ?

Ca doit repair l'objet (pas deux fois)

### Date et heure de la production du bug

15-11 00:43

### Serveur

SeasonSky

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/119886130/3dc7c4cc-6d08-4432-b39f-8b0ff04b3ae3)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/119886130/c11d1dbf-1d2f-4d98-89b0-aede470ee961)

**Comment by LupusArctos4** [comment]
Duplicata #524

**Comment by LupusArctos4** [comment]
re tester  à l'instant (apres la maj draconique) et cela ne fonctionne toujours pas m'aggrés un patch + fonctionnel au restart ( #524 )

**Comment by Alexis700** [comment]
Corrigé
