### ISSUE TITLE
[BUG] Bug de la MAJ et des raids

### ISSUE THREAD

**Issue by xGnTK** [RivrsMc/SeasonSky-Issues#536]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

xGnTK

### Pseudo discord

xGnTK

### Que s'est-il passé ?

Bonjour, après avoir farm pendant une quinzaine de minutes sur le monde aventure "Le fleuve secret" le kills des mobs n'augmente pas le nombre de mobs kills pour faire apparaitre le dragon.

### Étapes à suivre pour reproduire le bug

/aventure -> Fleuve secret
Tuer des mobs 
/raids et regarder la barre de progression

### Qu'aurait-il dû arriver ?

ça devrait faire avancer la barre et ne pas être bloquée sur 0

### Date et heure de la production du bug

16-11 17:47:14

### Serveur

island-02

### Information supplémentaire

UUID: 10b19259-ca58-4086-8982-9fcea587d4e3
Position: -41424 273 23372 SuperiorWorld
Ping: 10ms

**Comment by Alexis700** [comment]
Corrigé
