### ISSUE TITLE
[BUG] IS Level => Compacteur lvl 2 => tout les nouveaux items du mois de novembre

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#538]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

le compactage des planches carmins avec les compacteur niveau 2 ne donnent que 1 planche compacté au lieu de 4 et consomment bien les 10 stack comme c'est écrit

### Étapes à suivre pour reproduire le bug

1. avoir un compacteur lvl 2
2. compacter des planches carmins

### Qu'aurait-il dû arriver ?

avec 10 stack on devrait avoir 4 item compactés comme c'est le cas pour les autres

### Date et heure de la production du bug

16/10/2023 15:29 (heure canadienne)

### Serveur

all

**Comment by LupusArctos4** [comment]
Je rajoute un commentaire pour dire que ce n'est pas simplement les planches mais tous les items qui ont été rajoutés pour les crafts du mois de novembre

**Comment by Alexis700** [comment]
Corrigé
