### ISSUE TITLE
[BUG] Druses d'améthyste 

### ISSUE THREAD

**Issue by Naruto83130** [RivrsMc/SeasonSky-Issues#539]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

naruto83130

### Pseudo discord

Flex_Juju_Le_Boss-83#8544

### Que s'est-il passé ?

Quand je veux déplacer mes druses d'améthyste, cette dernière se casse, mais n est pas récupérer, (même avec silk touch)
ni tp inv

### Étapes à suivre pour reproduire le bug

Avoir une druse d'améthyste
Avoir une pioche (avec silk touch ou non)
casser la druse

### Qu'aurait-il dû arriver ?

Que la druse se tp dans l inv

### Date et heure de la production du bug

Toujours

### Serveur

All

**Comment by Alexis700** [comment]
Fait
