### ISSUE TITLE
Pets 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#54]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0iSan 

### Pseudo discord

Nami_san

### Que s'est-il passé ?

En gros les gens qui reçoit les œufs de pets lors de la pêche 
Les box avec les pet comme le pet mineur des profondeurs (je sais plus le nom) 
Ils ne reçoivent pas leurs pets dans leurs inventaire.

### Étapes à suivre pour reproduire le bug

Pêcher jusqu'à l'obtention d'un œuf de pet et gagner un pet mineur
Plusieurs joueurs me l'ont fait savoir 

### Qu'aurait-il dû arriver ?

Recevoir les pets dans l'inventaire 

### Date et heure de la production du bug

14h21 10/07

### Serveur

Global

**Comment by NoHere32** [comment]
Tu ne peux pas pecher d'oeuf de pets 
Le gain des oeuf de pets c'est avec le jobs
