### ISSUE TITLE
[BUG] fragment eflique non utilisable ( coffres off)

### ISSUE THREAD

**Issue by sebpap974** [RivrsMc/SeasonSky-Issues#541]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

sebpap974

### Pseudo discord

sebpap974

### Que s'est-il passé ?

fragment elfique de la zone des gardien qui ne sert a rien 

### Étapes à suivre pour reproduire le bug

aucun

### Qu'aurait-il dû arriver ?

1 box speciale(monument) pour les utilisé

### Date et heure de la production du bug

h24

### Serveur

tous

**Comment by Alexis700** [comment]
Corrigé
