### ISSUE TITLE
[BUG] faux de la mort et revente 

### ISSUE THREAD

**Issue by mortier007** [RivrsMc/SeasonSky-Issues#545]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

mortier007_v2

### Pseudo discord

Mortier007 

### Que s'est-il passé ?

Rune de robustesse ultime sur la faux et on doit la /forgeron 2 fois… De plus elle ne vend pas automatiquement le cacao 

### Étapes à suivre pour reproduire le bug

Ne plus avoir de dura 

### Qu'aurait-il dû arriver ?

La /forgeron 1 seul fois 

### Date et heure de la production du bug

N’importe quelle heure 

### Serveur

Tout les serveur seasonsky

**Comment by LupusArctos4** [comment]
duplicata #533  et #524

**Comment by Alexis700** [comment]
Déjà report et c'est normal que la houe ne revende pas automatiquement les cacaos car ce n'est pas son rôle
