### ISSUE TITLE
[BUG] Perte de dura épée draconique

### ISSUE THREAD

**Issue by Drykqo** [RivrsMc/SeasonSky-Issues#546]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Litchs

### Pseudo discord

triopsL's#5883

### Que s'est-il passé ?

Lors du kill d'un mobs (aventure) avec l'épée draconique en étant One Shot ou non l'épée perd automatiquement 2 durabilité

### Étapes à suivre pour reproduire le bug

tuer un mobs aventure avec l'épée draconique

### Qu'aurait-il dû arriver ?

l'épée devrait ne perdre qu'un de durabilité lors du kill du monstre aventure 

### Date et heure de la production du bug

27-11 13:25:57

### Serveur

Spawn-02

### Information supplémentaire

UUID: e37ff4eb-878e-4184-bfa0-fdb46df46217
Position: 82 57 -16 Island2
Ping: 20ms

**Comment by Alexis700** [comment]
On ne va pas pouvoir changer la chose, ça vient du plugin en lui même, on va dire que c'est à cause du bonus de drop des écailles
