### ISSUE TITLE
[BUG] Armure de Zeus

### ISSUE THREAD

**Issue by Poliipo** [RivrsMc/SeasonSky-Issues#547]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Poliipo

### Pseudo discord

Polipo

### Que s'est-il passé ?

J'ai acheté l'armure de zeus via le /blackfriday et la texture de celle ci bug, les effets ne sont pas appliqués. pareil pour l'eclair de zeus, pas d'effet. 

### Étapes à suivre pour reproduire le bug

acheter pack zeus via /blackfriday

### Qu'aurait-il dû arriver ?

Les textures aurait dû être bonne + effets appliqués

### Date et heure de la production du bug

27/11/2023 17h30

### Serveur

SeasonSKY

### Screen / vidéo

![rtergdfgd](https://github.com/RivrsMc/SeasonSky-Issues/assets/152204955/fc415c67-cb35-4b64-8c05-59d964f6e9d5)

**Comment by Alexis700** [comment]
Corrigé
