### ISSUE TITLE
[BUG] Pelle draco 

### ISSUE THREAD

**Issue by Ax0ne24** [RivrsMc/SeasonSky-Issues#548]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

ax0ne24

### Pseudo discord

Ax0ne

### Que s'est-il passé ?

La pelle draco fais dépop certains bloc dans sa zone d'effet

Exemple : X = cobble , O = dirt 

X X X
X O X
X X X

si je pelle la dirt, je la récupère, mais ca me casse instant les 8 bloc de cobble et les détruit instant

### Étapes à suivre pour reproduire le bug

un carré de cobble avec une dirt au milieu, coup de pelle sur la dirt 

### Qu'aurait-il dû arriver ?

Les bloc de cobble n'aurait pas du casser instant et depop

### Date et heure de la production du bug

27/11/2023 18h40

### Serveur

SeasonSky / Eldoria

**Comment by Alexis700** [comment]
C'est normal, après pour tout te dire c'est pas vraiment rentable pour un joueur de remplacer la dirt du milieu pour one shoot la stone autour
