### ISSUE TITLE
[BUG] Compacteur niveau 2

### ISSUE THREAD

**Issue by Founny** [RivrsMc/SeasonSky-Issues#549]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Isaac______

### Pseudo discord

isaac____

### Que s'est-il passé ?

Après plusieurs compactages de cobble via un compacteur niveau 2, ça me demande toujours 4x160 items mais ne me fournit que 2 items compactés
-changer de place le compacteur n'y fait rien
-bug disparait au redémarrage de 5h

### Étapes à suivre pour reproduire le bug

1. Utiliser un compacteur niveau 2 à plusieurs reprises

### Qu'aurait-il dû arriver ?

Obtenir 4 items compactés comme prévu

### Date et heure de la production du bug

28/11 - 16h

### Serveur

is02

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/39631165/62b7e97f-ef27-480d-9b92-aa5d69200ce5)

**Comment by Alexis700** [comment]
Corrigé
