### ISSUE TITLE
PNJ recyclage 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#55]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0iSan 

### Pseudo discord

Nami_san

### Que s'est-il passé ?

Je fais un petit signalement et potentiellement aussi un suggestions si c'est normal
En gros quand les personnes vont au PNJ lors du recyclage tout part (logique) mais l'armure qui est sûr nous aussi.

Si c'est pas normal régler le petit soucis si c'est normal rajouter peut être un truc en plus pour éviter les pertes d'armure.

### Étapes à suivre pour reproduire le bug

Se rendre au PNJ et faire le recyclage 

### Qu'aurait-il dû arriver ?

Ne pas perdre son armure qui est sur soi 

### Date et heure de la production du bug

14h27 10juillet 

### Serveur

Global

**Comment by NoHere32** [comment]
Un changement du pl arrive (le système sera identique au /peche shop

**Comment by ArDiDEx** [comment]
hey! j'ai oublié de répondre mais cela devrait être en prod depuis la semaine dernière
je close du coup
