### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#550]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0isan

### Pseudo discord

Nami

### Que s'est-il passé ?

Bonjour, alors lors d'une session pêche avec la canne ultime nous péchons par moment des livre enchant mais celle ci multipli en 3 je sais pas si c'est pour vous de la dupli alors je le signale ici

### Étapes à suivre pour reproduire le bug

Faire une session de pêche, pêcher des livres enchant avec la canne ultime 

### Qu'aurait-il dû arriver ?

Ne pas drop 3 livre d'un coup dans l'inventaire

### Date et heure de la production du bug

30/11 11h46

### Serveur

Global

### Screen / vidéo

Me mp pour la vidéo

**Comment by Alexis700** [comment]
C'est bizarre car il n'y à rien en config, ça doit être avec le bonus de double gain que ça doit faire buguer le truc, après c'est pas très grave, c'est un petit bonus on va dire, on devrait changer le plugin pour le corriger donc ça ne sera pas fait
