### ISSUE TITLE
[BUG] Quêtes journalière Noel=quêtes avancées

### ISSUE THREAD

**Issue by Grelako** [RivrsMc/SeasonSky-Issues#551]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Grelako

### Pseudo discord

Greläko

### Que s'est-il passé ?

En finissant une quête du /quests (ayant plusieurs quêtes sur moi je ne sais pas laquelle est concernée), c'est la quête journalière de Noel (accepté auparavant) qui c'est terminée à la place. La quête du /quests à par conséquent disparue, sans me donner les potentielles récompenses. A la place j'ai reçu la récompense de la quête de Noel du 1er décembre. Je devais couper 588 bûches de sapin pour cette dernière si je me souviens bien (j'ai pas de screen pour ça).

### Étapes à suivre pour reproduire le bug

En finissant une quête du /quests (ayant plusieurs quêtes sur moi je ne sais pas laquelle est concernée), c'est la quête journalière de Noel (accepté auparavant) qui c'est terminée à la place. La quête du /quests à par conséquent disparue, sans me donner les potentielles récompenses. A la place j'ai reçu la récompense de la quête de Noel du 1er décembre.

### Qu'aurait-il dû arriver ?

Recevoir la récompense de la quête du /quests et non celle du calendrier des quêtes de l'avent.

### Date et heure de la production du bug

01/12/2023 19h20 environ

### Serveur

SeasonSky (Global?)

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/54781374/10849403-b50c-4ee4-a7a1-d4c31c748f6b)

**Comment by Alexis700** [comment]
Bizarre le bug que tu as eu, on ne sait pas d'où ça peut venir les récompenses sont globalement les mêmes et tu as eu le flocon c'est le plus important !
