### ISSUE TITLE
[BUG] Obtention des effets de l'armure de l'aventurier

### ISSUE THREAD

**Issue by thomasroux021** [RivrsMc/SeasonSky-Issues#552]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

WynnSh4rd_

### Pseudo discord

WynnSh4rd_

### Que s'est-il passé ?

Avec l'armure complète de l'aventurier (marche peut être également avec d'autres armures mais je n'ai pas testé), si je n'équipe pas les bottes en dernier je n'obtient pas les effets bonus de l'armure.

### Étapes à suivre pour reproduire le bug

Equiper son armure de l'aventurier dans n'importe qu'elle ordre mais en n'équipant pas les bottes en dernier

### Qu'aurait-il dû arriver ?

J'aurais du recevoir les effets de l'armure 

### Date et heure de la production du bug

23h00 02/12/2023

### Serveur

Seasonsky

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/38227320/b43f6fc5-9c7a-4ea2-98a3-711bd0b78530)

### Information supplémentaire

Tant que je n'enlève pas les bottes je ne perd pas non plus mes effets

**Comment by Alexis700** [comment]
Corrigé, il est juste impossible de le faire marcher pour le casque
