### ISSUE TITLE
[BUG] La fée n'est plus présente sur les îles

### ISSUE THREAD

**Issue by xGnTK** [RivrsMc/SeasonSky-Issues#553]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

xGnTK

### Pseudo discord

xGnTK

### Que s'est-il passé ?

Hello, depuis le redémarrage ce matin la fée Azriel n'est plus présente. Ce qui est embêtant pour les nouveaux joueurs notamment vu que c'est le pnj qui permet de distribuer les quêtes de commencement.
De plus, la commande /is npcmove pour la déplacer n'est plus active non plus

### Étapes à suivre pour reproduire le bug

Créer une île
faire /is npcmove

### Qu'aurait-il dû arriver ?

La fée devrait être présente

### Date et heure de la production du bug

Depuis ce matin suite au redémarrage des is

### Serveur

Toutes les is

**Comment by Alexis700** [comment]
Corrige
