### ISSUE TITLE
[BUG] vente canne à sucre 

### ISSUE THREAD

**Issue by geminiCHgirl** [RivrsMc/SeasonSky-Issues#554]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

geminiCHgirl

### Pseudo discord

geminiCHgirl

### Que s'est-il passé ?

vente canne à sucre  par le shop saison ou shop agriculture , l'argent n'est pas comptabilisé. j'a perdu la vente de 712 canne à sucre 2 fois et une fois de 100 canne à sucre. [https://uploadnow.io/f/lm38brS] 

### Étapes à suivre pour reproduire le bug

shop , saison, canne à sucre , clic droit tout vendre , validé.

### Qu'aurait-il dû arriver ?

encaisser plus de 1'000 000 d'argent 

### Date et heure de la production du bug

04.12.2023 18h59

### Serveur

seasonsky v4 

### Screen / vidéo

[https://uploadnow.io/f/lm38brS] 

### Information supplémentaire

l'exemple c'est après deux vente de plus de 1'000 000 sans encaissement .

**Comment by Alexis700** [comment]
Alors ton report est faux car tu n'aurais jamais dû faire 1 million avec si peu de vente sachant que la vente est de 2.34 grâce au shop de saison
(712*2+100)*2.34= 3 566
