### ISSUE TITLE
[BUG] Multiplicateur de Fantasia Gold

### ISSUE THREAD

**Issue by Noelenoob** [RivrsMc/SeasonSky-Issues#555]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Noelenoob

### Pseudo discord

Noelenoob

### Que s'est-il passé ?

Lors de mon passage au niveau 65 Forgemage, j'ai obtenu le pet Fantasia Gold qui est censé avoir un multiplicateur minimum de x4 jusqu'à un maximum de x8. Pourtant, le fantasia gold que j'ai reçu a un multiplicateur x1 seulement. Il s'avère que je bugais beaucoup à ce moment et que j'ai été kick du serveur à cause de ça quelques secondes après, peut-être est-ce dû à un problème de chargement de mes données comme le suggèrent mes logs.

### Étapes à suivre pour reproduire le bug

Récupérer la récompense lvl 65 du job forgemage.

### Qu'aurait-il dû arriver ?

Obtenir un pet Fantasia Gold avec un multiplicateur de x4 minimum

### Date et heure de la production du bug

13h20

### Serveur

Eldoria

**Comment by Alexis700** [comment]
je n'ai pas retrouvé le problème donc ça doit surement venir de toi
