### ISSUE TITLE
[BUG] duplication du menu principal a l'infini

### ISSUE THREAD

**Issue by Ultra-jeux** [RivrsMc/SeasonSky-Issues#556]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [x] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Vexa_girls

### Pseudo discord

vexagirls

### **impossible  de  reproduire le bug pour avoir un dans l'inventer comment dans les images 

 **quand ta deux 1 dans l'inventer et 1 dans la barre d'action qui est infini tu peux le duplier**

![Screenshot_15](https://github.com/RivrsMc/SeasonSky-Issues/assets/111390105/f432b0a7-1014-4c4d-b556-ba13a0a697ea)
![Screenshot_16](https://github.com/RivrsMc/SeasonSky-Issues/assets/111390105/6345ca62-967a-444a-8102-dbe18e921c69) 

je fais un double clic sourir  pour le récupérais 

![Screenshot_17](https://github.com/RivrsMc/SeasonSky-Issues/assets/111390105/ab4730fa-6212-4348-ad2c-e979c49f5c41)
 
pareil mais avec le **(menu principal)**

### Qu'aurait-il dû arriver ?

juste le déplacer à un autre endroit de l'inventer ou le remettre a l'endroit par défaut 

### Date et heure de la production du bug

1/12/2023

### Serveur

tous les seveur 

### Screen / vidéo

![bug 2](https://github.com/RivrsMc/SeasonSky-Issues/assets/111390105/08f2216a-b79a-4c67-b199-f6a7d77d6e92)
![bug](https://github.com/RivrsMc/SeasonSky-Issues/assets/111390105/971ea506-79a7-42dc-b1a3-e8d667d1f2c9)
![Screenshot_14](https://github.com/RivrsMc/SeasonSky-Issues/assets/111390105/e513054d-5b84-4ba4-9c91-854bce0f1b98)

### Information supplémentaire

apes avoir fais les images  j'ai supprimer dans le vide 

                                       merci d'avace                                         Vexa

**Comment by Alexis700** [comment]
Euh je t'avoue que c'est pas réellement un problème si les joueurs arrivent à avoir le menu principale, car il ne sert concrètement un rien
Pour rappel il est interdit de le vendre
