### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Skymomo76** [RivrsMc/SeasonSky-Issues#558]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Skymomo

### Pseudo discord

skymomo.

### Que s'est-il passé ?

Je possède le pet "Crokket" (box halloween) au niveau 20, a ce niveau il est censé re vendre les cristaux de prismarines plus cher de 60%, le prix de base étant fixé à 3 il est censé revendre donc à 4.8$ , or il ne vend que 30% plus cher, le prix de revente avec le pet équipé est de 3.9$

### Étapes à suivre pour reproduire le bug

1. Monter un crokket niveau 20
2. Utiliser la commande /shop
3. Le prix de revente n'est pas le bon.

### Qu'aurait-il dû arriver ?

Le prix de revente pour les cristaux de prismarines devrait être a 4.9$/u

### Date et heure de la production du bug

09/12/2023 à 15h10

### Serveur

island-02

### Screen / vidéo

![level crokket](https://github.com/RivrsMc/SeasonSky-Issues/assets/153555233/72168ba1-b21c-4d86-83d6-6a9bf3625d6c)
Le niveau de mon pet "crokket" est bon
![prix trop b as](https://github.com/RivrsMc/SeasonSky-Issues/assets/153555233/a36df5e6-1b33-4791-a940-7895ff9f4b23)
Le prix de revente n'est pas bon

**Comment by Alexis700** [comment]
On l'a corrigé hier, il sera en prod dès qu'on aura fini de régler les autres bugs
