### ISSUE TITLE
[BUG] Affichage des items dans les rang Ingenieur et Gardien

### ISSUE THREAD

**Issue by Adartse-r** [RivrsMc/SeasonSky-Issues#559]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Adartse_r

### Pseudo discord

Adartse_r

### Que s'est-il passé ?

Ceci était d'origine un Ticket Discord mais le Moderateur Louuka_ m'a demandé d'en faire une report:
Les stacks d'item ne correspondent pas à la descriptions trouvée dans le /rang pour monter de rang.
Lors d'un rang up précédent, un item requis (Brin de Blé) en plus de 64 exemplaire n'avait un stack que de 1 (donc pas de nombre d'item affiché directement sur le stack)
Or sur les rang Ingénieur et Gardien, la plus part des items avec des stacks de 64 en demande 384, 96 et 256, avec en plus les stack de Blaze Rod et Ender Perle qui affichent 48 alors qu'il y en faut 96, comme pour les Cœurs et Bras de Zombie, eux affichés à 64.

### Étapes à suivre pour reproduire le bug

La commande "rang"

### Qu'aurait-il dû arriver ?

Ne serait-il pas plus logique de ne mettre qu'un stack de 1 item, n'affichant pas de nombre, dans le /rang pour les items requièrent plus 64?
Et surtout éviter d'afficher 48 lorsqu'il en faut le double, 48 n'étant pas le maximum d'un stack, il serai logique que la description soit elle aussi 48.

### Date et heure de la production du bug

Pas de Date et Heure précise

### Serveur

SeasonSky

**Comment by LupusArctos4** [comment]
les stack qui dépasse 64 ne peuvent pas etre noté car il n'ont pas de plugin pour afficher plus que 64 donc c'est tout a fait normal, il faut se fier a ce que la description dit et non au l'interface du rang en question ou vous pouvez vous fier a l'enclume qui se trouve en haut de l'interface qui résume tout les pré-requis ainsi que ses avantages apres obtention

**Comment by Adartse-r** [comment]
> les stack qui dépasse 64 ne peuvent pas etre noté car il n'ont pas de plugin pour afficher plus que 64 donc c'est tout a fait normal, il faut se fier a ce que la description dit et non au l'interface du rang en question ou vous pouvez vous fier a l'enclume qui se trouve en haut de l'interface qui résume tout les pré-requis ainsi que ses avantages apres obtention

Le soucis que j'ai remonté est surtout un problème de consistance. Le premier objet requit à plus de 64 exemplaire n'affichant pas de quantité mais les suivants, eux, affichaient une quantité.
Je sais que les stacks ne dépassent pas 64 mais dans le cas des Ender Perle et Blaze Rod, la quantité affiché est 48, pas 64
> avec en plus les stack de Blaze Rod et Ender Perle qui affichent 48 alors qu'il y en faut 96, comme pour les Cœurs et Bras de Zombie, eux affichés à 64.

**Comment by LupusArctos4** [comment]
ah oui je vois apres peut etre qu'il ne peuvent pas dépasser 64 qui sait

**Comment by Alexis700** [comment]
Oui on ne peut pas dépasser les 64, j'ai modifié le visuel pour les 2 grades d'avant
