### ISSUE TITLE
[BUG] Casques non modifiables

### ISSUE THREAD

**Issue by xGnTK** [RivrsMc/SeasonSky-Issues#560]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

xGnTK

### Pseudo discord

xGnTK

### Que s'est-il passé ?

Hello, il y a plusieurs casques (zeus, ares, jason..) qui sont censés pouvoir être "modifiable" mais au final ne le sont pas.

![casque](https://github.com/RivrsMc/SeasonSky-Issues/assets/95409806/b5955c9b-4960-4747-8106-0aeffc321a8d)

### Étapes à suivre pour reproduire le bug

Prendre un casque Ares par exemple, essayer de mettre un livre enchanté (respiration 3) dans l'enclume et l'enchante ne voudra pas se mettre.

### Qu'aurait-il dû arriver ?

Le casque devrait pouvoir s'enchanter et être modifié tout comme les autres stuffs.

### Date et heure de la production du bug

/

### Serveur

/

### Information supplémentaire

Les casques sont répertoriés en tant que "paper, raw iron" le soucis vient sûrement de là.

**Comment by Alexis700** [comment]
C'est normal, les casques ne sont pas modifiable car c'est à cause de la texture que l'on met dessus, on ne pourrait pas avoir des casques modifiables avec les textures qu'on met actuellement sur le serveur
