### ISSUE TITLE
[BUG] Monstre Manquant à la Liste de Zombie Land

### ISSUE THREAD

**Issue by Adartse-r** [RivrsMc/SeasonSky-Issues#561]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Adartse_r

### Pseudo discord

Adartse_r

### Que s'est-il passé ?

Un des Monstres présent dans la map aventure "ZombieLand" est manquant à la liste des Taux de Drop accessible depuis le PNJ permettant également de recycler.
N'apparaissant pas dans la liste, son nom officiel ne m'est pas connu, je l'appellerai donc le Zombie en Tenue Hazmat.

### Étapes à suivre pour reproduire le bug

Accéder à la Map Aventure "Zombie Land"
Parler au PNJ ayant l'apparence d'une Wandering Trader
Clicker sur l'item "Peinture"

### Qu'aurait-il dû arriver ?

Le Zombie en Tenue Hazmat devrait être lister, donnant 20 unité de Cervelles, contrairement à 10 pour un Zombie de Zombie Lande "Classique"
Dans les Map du "Canyon des Profondeurs", les Taupes Cavernes et Taupes Ouvrière sont distinctes avec comme seul différence la quantité de Rubis qu'elles donnent.
Cet différentiation est faite dans la "Ferme de Jean", la "Forêt Mystique" tout comme dans le "Fleuve Secret".
"Zombie Land" est la seul map m'étant accessible (N'ayant pas accès à Fontcomb, j'exclu cet Map de mon observation) ne respectant pas cette régularité, bien que les Zombies et Zombie en Tenue Hazmat soit bien deux monstres distincts, de par le comportement du Zombie en Tenue Hazmat plus proche d'un Creeper, leurs différentes valeurs de Point de Vie et de par la quantités de Cervelles de Zombies différente.

### Date et heure de la production du bug

Pas de Date et Heure précise

### Serveur

Spawn-01 et Spawn-02

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/62434967/eb73dc68-e677-45f9-8533-1f5439b2e729)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/62434967/0cf47fb7-b1b2-47af-be7e-611cfada4d65)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/62434967/88e643ec-f84c-4024-b9ea-1b422cd82dbd)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/62434967/ccabd494-50a7-4a11-b093-c3d275069f8e)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/62434967/3a3105a1-2913-4700-86cc-380a5169f1bd)

**Comment by Alexis700** [comment]
Corrigé
