### ISSUE TITLE
[BUG] Pioche draconique non fonctionnelle

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#566]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

quand je mine avec la pioche draconique ca ne me donne ni l'xp vanilla donnée habituellement lorsque l'on mine un minerais + elle ne fonctionne pas avec les quetes comme les autres marteaux (juste le bloc central compte pour les quetes)

### Étapes à suivre pour reproduire le bug

1. avoir une pioche draconique
2. miner dans un générateur

### Qu'aurait-il dû arriver ?

1. on devrait avoir de l'xp vanilla lorsque l'on casse des minerais
2. ca devrait faire avancer les quetes avec le bloc du milieu miner comme les autres marteaux

### Date et heure de la production du bug

27/12/2023 21:12

### Serveur

island

**Comment by Alexis700** [comment]
J'ai regardé le problème, je pense que c'est dû à l'autosell qui fait que le bloc n'est pas pris en compte, je vais demander à Ardidex pour voir si c'est possible de changer ça

**Comment by Alexis700** [comment]
Alors du coup il ne sera pas possible d'ajouter les quêtes et le gain d'exp, car l'autosell passe au dessus de ça, par contre la vente auto ne se fait pas sur le 3x3 mais que sur le bloc cassé, donc cela sera ajouté
