### ISSUE TITLE
[BUG] Vindicateurs non comptés comme monstres dans les quêtes

### ISSUE THREAD

**Issue by Founny** [RivrsMc/SeasonSky-Issues#567]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Isaac______

### Pseudo discord

isaac____

### Que s'est-il passé ?

Tuer des vindicateurs n'est pas compté dans les quêtes tuer des monstres

### Étapes à suivre pour reproduire le bug

Avoir une quête tuer des monstres et tuer des vindicateurs

### Qu'aurait-il dû arriver ?

Être pris en compte

### Date et heure de la production du bug

28/12 - 1h00

### Serveur

tous

**Comment by Asherate** [comment]
Ajouté
