### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ARWOBN95** [RivrsMc/SeasonSky-Issues#568]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

ARWO_BN95

### Pseudo discord

ARWO_BN95

### Que s'est-il passé ?

J'ai achete une hache royale, j'ai decider de farm les citrouille avec sauf que je ne gagne pas d'xp jobs c'est normal ? 

### Étapes à suivre pour reproduire le bug

Prendre une hache et casser des citrouille 

### Qu'aurait-il dû arriver ?

j'au du gagner de l'xp non ? 

### Date et heure de la production du bug

28-12 17:47:39

### Serveur

is

### Information supplémentaire

UUID: 875a1c72-ff03-495a-811e-68c78b278464
Position: 57580 100 -55813 SuperiorWorld
Ping: 8ms

**Comment by LupusArctos4** [comment]
cette hache est fait pour casser des arbres donc c'est possiblement à cause de ça qu'elle ne donne pas d'xp

**Comment by ARWOBN95** [comment]
Je vois, mais la hache ultime aussi ne donne pas d'xp

**Comment by mrsxnshxne** [comment]
Hello, c'est bien à cause de son effet sur les arbres que l'xp n'est pas compté, essaye avec une autre hache (par exemple une hache en diamant) et si tu as le soucis n'hésite pas à recrée une issue.
