### ISSUE TITLE
[BUG]  Palier vote Scoins

### ISSUE THREAD

**Issue by Zwartkat** [RivrsMc/SeasonSky-Issues#57]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Zwartkat 

### Pseudo discord

Zwartkat 

### Que s'est-il passé ?

Non Réception des Scoins du palier vote 30

### Étapes à suivre pour reproduire le bug

1. Récupérer le palier 

### Qu'aurait-il dû arriver ?

Réception des Scoins 

### Date et heure de la production du bug

18:20 9/07

### Serveur

Tous

### Information supplémentaire

Problème sûrement causé par le changement des commandes de give de Scoins

**Comment by NoHere32** [comment]
patch au prochain transfert
