### ISSUE TITLE
[BUG] Le compacteur lvl 2 ne peut plus compacter d'enderpearl

### ISSUE THREAD

**Issue by N4m4xx** [RivrsMc/SeasonSky-Issues#572]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Namaxx

### Pseudo discord

Namaxx 

### Que s'est-il passé ?

Le compacteur lvl 2 est censé compacté par 2 les enderpearl et non par 4 car aussi non il y a pas assez de place dans l'inventaire pour mettre tout les items requis. Donc quand on veut compacter les enderpearls le message pour dire qu'on a pas assez d'ingrédient apparait alors que l'inventaire est rempli d'enderpearls.

### Étapes à suivre pour reproduire le bug

1 Prendre 1 inventaire d'enderpearls
2 Ouvrir un compacteur lvl 2
3 Clique gauche pour compacter les enderpearls

### Qu'aurait-il dû arriver ?

Pouvoir compacter les enderpearls par 2 voir par 3

### Date et heure de la production du bug

04-01 14:11:39

### Serveur

island-03

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/142924791/44d4bb79-ecd7-420d-9522-785d743d09bd)
![2024-01-04_14 07 41](https://github.com/RivrsMc/SeasonSky-Issues/assets/142924791/55348140-e84a-4695-8935-41c66f38b665)

### Information supplémentaire

UUID: 32a204d9-62d5-4676-b860-1dc32a3ce8e6
Position: -5400 109 -1791 SuperiorWorld
Ping: 108ms

**Comment by Alexis700** [comment]
Corrigé
