### ISSUE TITLE
[BUG] Scroll et outils 

### ISSUE THREAD

**Issue by Kalslow** [RivrsMc/SeasonSky-Issues#574]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Calslow

### Pseudo discord

Calslow

### Que s'est-il passé ?

La mission Facile récolter ne fonctionne pas en utilisant la houe du soleil. Pareil pour récolter de la stone avec la pioche des ombres.

### Étapes à suivre pour reproduire le bug

1. Récolter les carrotes à la houe du soleil.
2. Le scroll "Mission Facile récolté 86 carrotes" reste à 0.

1. Miner avec "Pioche des ombres" à un générateur à stone.
2. Attendre d'avoir bien de la stone et non de la cobblestone.
3. Le scroll "Mission Facile mine 274 pierres" reste à 0.

### Qu'aurait-il dû arriver ?

Les scrolls aurait du évoluer.

### Date et heure de la production du bug

05-01 14:42:25

### Serveur

island-03

### Screen / vidéo

![2024-01-05_14 46 39](https://github.com/RivrsMc/SeasonSky-Issues/assets/155742084/9697ac08-4999-4dff-ae6c-ee428612cc61)
![2024-01-05_14 46 40](https://github.com/RivrsMc/SeasonSky-Issues/assets/155742084/f0d4bd95-570d-457d-a4e6-3752f336e6d7)

### Information supplémentaire

UUID: b888f6d5-735e-4709-ba05-193bcd05544f
Position: -57605 99 -37803 SuperiorWorld
Ping: 15ms

**Comment by LupusArctos4** [comment]
tu ne peux pas faire les quetes avec la pioche des ombres car elle vent automatiquement le charbon donc je pense que ca influe sur tous les autres minerais
et pour ce qui est de la houe du soleil étant donner qu'elle remplante automatiquement les cultures en 1x1 + le fait qu'elles les récupèrent automatiquement dans l'inventaire ne permet pas de faire les mission

**Comment by Alexis700** [comment]
Items custom donc c'est normal
