### ISSUE TITLE
[BUG] Tiges dans le jobs info cuire

### ISSUE THREAD

**Issue by Founny** [RivrsMc/SeasonSky-Issues#576]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Isaac______

### Pseudo discord

isaac____

### Que s'est-il passé ?

Les tiges carmin, biscornue ainsi que leur variante écorcée sont affichées dans l'action rémunérée cuire du job bûcheron alors qu'elles ne peuvent pas être cuites 

### Étapes à suivre pour reproduire le bug

x

### Qu'aurait-il dû arriver ?

Elles ne devraient pas y être affichées

### Date et heure de la production du bug

18/01 21h30

### Serveur

is

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/39631165/e384b756-cf1a-40b0-9982-a7953b43b529)

**Comment by mrsxnshxne** [comment]
Hello, problème réglé, j'ai supprimé les 2 types de bois

**Comment by Founny** [comment]
toujours d'actualité
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/39631165/c1e50134-33a9-4447-be5d-e0e44fc01f0f)
