### ISSUE TITLE
[BUG] Production pet " cadeau de noel "

### ISSUE THREAD

**Issue by Jspppppp** [RivrsMc/SeasonSky-Issues#577]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Jspppppp

### Pseudo discord

Jspppppp (l'Ours) 🧸

### Que s'est-il passé ?

Le pet " Cadeau de Noël " produit des lingots de cuivre alors qu'il est censé produire des MINERAIS de cuivre (celui qui pose pour casser). Dans le pokedex et sur lui on vois bien minerais de cuivre.

### Étapes à suivre pour reproduire le bug

1. Avoir le pet
2. Le mettre dans l'éclozr
3. Voir des lingots de cuivres

### Qu'aurait-il dû arriver ?

Avoir des MINERAIS de cuivres et non des LINGOTS.

### Date et heure de la production du bug

All

### Serveur

Island

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139492099/6ef92d56-3e40-4c9f-8ed9-286a0516d3a3)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139492099/3614335a-f432-47a1-baed-b9dd23b14b7c)
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/139492099/43410bd8-e6b4-40a6-9c3d-e4755c96c243)

**Comment by LupusArctos4** [comment]
faudrait tester si ces pets ont le meme problèmes : 
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/8b1b511c-8bff-41e0-9d9c-682144e9a9c0)

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/81696ee2-1275-4afb-8369-f5433dadc63b)

**Comment by Alexis700** [comment]
Corrigé
