### ISSUE TITLE
[BUG] Urgent is level

### ISSUE THREAD

**Issue by Isweazu** [RivrsMc/SeasonSky-Issues#58]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Isweazu

### Pseudo discord

xx4040

### Que s'est-il passé ?

La limite des blocs de minerais peut être dépassée malgré la limite 

### Étapes à suivre pour reproduire le bug

Remplir par exemple jusque 4999/5000 prendre un inventaire complet du bloc de minerais en question, et on peut encore mettre des stacks à l'infini et encore + infini si quelqu'un vient drop des blocs tant que la personne n'a pas quitté l'interface, une fois l'interface quitté on ne peut plus en mettre
(Pour toutes questions => le bug à été trouvé par l'ile de Divineexx

### Qu'aurait-il dû arriver ?

Ne pas pouvoir mettre au dessus de la limite indiqué 

### Date et heure de la production du bug

22h19 le 10-07

### Serveur

Island 02

### Information supplémentaire

Pour + d'infos ou si incompréhension, demander à l'ile de Divineexx and co

**Comment by ArDiDEx** [comment]
hey! la limite ne peux désormais plus être dépassé, et les blocks ajoutés en trop ne seront plus compté après un /is recalc
