### ISSUE TITLE
[BUG] Désynchro classement /is top

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#59]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

si une personne de l'is n'est pas connecté ca n'affiche pas le classement de l'is dans le /is top

### Étapes à suivre pour reproduire le bug

1. faire /is online nom_is
2. voir que personne est co + voir leur lvl d'is top
3. faire /is top
4. voir qu'il ne sont pas dans le classement

### Qu'aurait-il dû arriver ?

on devrait voir l'is dans l'is top

### Date et heure de la production du bug

11/07/2023 09:14

### Serveur

island 02

**Comment by ArDiDEx** [comment]
Hey! je viens de vérifier ingame, et non les îles même avec aucun membre connecté sont toujours affiché dans le classement
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/48607042/c185c338-3fdb-42ce-9969-4187e95d80fe)
