### ISSUE TITLE
[BUG] L'eclozr fonctionne pas

### ISSUE THREAD

**Issue by Ninjaduff** [RivrsMc/SeasonSky-Issues#6]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

OpticalD

### Pseudo discord

OpticalD

### Que s'est-il passé ?

incapable de faire quelque chose avec l'éclozr devant la machine a cobble

### Étapes à suivre pour reproduire le bug

?

### Qu'aurait-il dû arriver ?

que l'eclozr fonctionne

### Date et heure de la production du bug

08-07 18:56:14

### Serveur

island-03

### Screen / vidéo

a

### Information supplémentaire

UUID: f3e13c76-29f1-4b3b-a638-80f42aa38fa7
Position: -8992 101 8999 SuperiorWorld
Ping: 122ms

**Comment by LuluxClient** [comment]
Salut ton eclozr fonctionne à merveille, je l'ai off et déposé dans un coffre: 
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/62576432/cadfcb1d-ec23-41eb-ab59-5dcea8c4db1a)
