### ISSUE TITLE
[BUG] Glace ne se forme pas sur les îles

### ISSUE THREAD

**Issue by JustIDripp** [RivrsMc/SeasonSky-Issues#60]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

JustIDripp_

### Pseudo discord

justidripp

### Que s'est-il passé ?

Report pour AlainLeBabouin
La glace, malgré son biome Taiga activé (biome glace), ne spawn pas sur l'île d'AlainLeBabouin (et potentiellement d'autres), qu'importe la couche à laquelle sa source infinie d'eau est.

### Étapes à suivre pour reproduire le bug

Faire une source infinie d'eau, mettre le biome en Taïga et attendre. longtemps. le temps d'une vie.

### Qu'aurait-il dû arriver ?

L'eau aurait dû glacer

### Date et heure de la production du bug

11-07 13:05:10

### Serveur

island-05

**Comment by LuluxClient** [comment]
Ceci est normal, pour avoir de la glace c'est au shop / pet pingu !
