### ISSUE TITLE
[BUG] Le générateur ne produit plus d'xp pour le métier de Mineur à partir d'une certaine couche

### ISSUE THREAD

**Issue by MrHiraa** [RivrsMc/SeasonSky-Issues#63]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MrHiraa

### Pseudo discord

Hiraa

### Que s'est-il passé ?

Le générateur à cobble n'augmente pas le niveau de job au-dessus de la couche 200, le joueur ne gagne plus d 'xp

### Étapes à suivre pour reproduire le bug

Se trouver au-dessus de la couche précédemment limitée par les anciennes versions Minecraft

### Qu'aurait-il dû arriver ?

Gagner de l'xp à n'importe qu'elle couche 

### Date et heure de la production du bug

11/04/2023 - 18h00

### Serveur

SeasonSky

**Comment by LuluxClient** [comment]
Je n'ai pas de soucis, tu peux envoyer un screen de ton setup pour repdroduire le bug ? je mine du diamant en couche 300: https://gyazo.com/a9aaee7bc38391441120685ecb8d06ba

**Comment by LuluxClient** [comment]
@MrHiraa

**Comment by MrHiraa** [comment]
D’après un report joueur on ne gagne pas d’xp a une couche trop haute

**Comment by itsme-to** [comment]
Est-ce que tu peux demander plus d'information au joueur ? 
@MrHiraa

**Comment by itsme-to** [comment]
Après test, je n'ai pas réussi a reproduire le bug. Merci de rouvrir si il est toujours présent

**Comment by MrHiraa** [comment]
Mmm bizarre je ne sais pas alors
