### ISSUE TITLE
Us prestige 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#64]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0iSan 

### Pseudo discord

Nami_san

### Que s'est-il passé ?

Le prestige 2 on doit l'acheter deux fois avant le pallier 3

### Étapes à suivre pour reproduire le bug

Monter le prestige 2 une fois et voir qu'il faut le but une nouvelle fois 

### Qu'aurait-il dû arriver ?

Monter le 3 après le 2

### Date et heure de la production du bug

21h18

### Serveur

Global

### Screen / vidéo

![Screenshot_20230711-185540](https://github.com/RivrsMc/SeasonSky-Issues/assets/120673389/f61205cb-19d2-4d1d-b8fd-01fb4cdc6abe)

**Comment by itsme-to** [comment]
Effectif au prochain merge
