### ISSUE TITLE
[BUG]  Retrait compacteur 

### ISSUE THREAD

**Issue by Zwartkat** [RivrsMc/SeasonSky-Issues#65]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Zwartkat 

### Pseudo discord

Zwartkat 

### Que s'est-il passé ?

Une texture de compacteur est laissé après l'avoir récupéré (parfois)

### Étapes à suivre pour reproduire le bug

1. Retirer le compacteur
2. Compacteur récupéré et la texture reste parfois 

### Qu'aurait-il dû arriver ?

Retrait de la texture 

### Date et heure de la production du bug

23:20 11/07

### Serveur

Ile

### Information supplémentaire

J'ai pas eu plus d'informations 😕

**Comment by itsme-to** [comment]
Le bug a été normalement réglé, je n'ai pas réussi a le reproduire
