### ISSUE TITLE
[BUG] is level

### ISSUE THREAD

**Issue by Amateur2Drapeau** [RivrsMc/SeasonSky-Issues#66]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MaelEnFrance

### Pseudo discord

maelenfrance

### Que s'est-il passé ?

Le retirer tout du crystal retire vraiment tout, il ne remplit pas l'inventaire il enleve tout et le surplus est supprimé

### Étapes à suivre pour reproduire le bug

avoir moins de place dans l'inv que d'item dans le crystal

### Qu'aurait-il dû arriver ?

Remplir l'inventaire seulement

### Date et heure de la production du bug

x

### Serveur

x

### Information supplémentaire

UUID: ccf4c91d-a9da-442e-94df-2a03f6b3cb1a
Position: 5430 40 -3607 SuperiorWorld
Ping: 22ms

**Comment by itsme-to** [comment]
Le bug a été réglé
