### ISSUE TITLE
[BUG] Les pets qui font repousser avec la houe royale ne fonctionnent pas

### ISSUE THREAD

**Issue by Amateur2Drapeau** [RivrsMc/SeasonSky-Issues#67]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MaelEnFrance

### Pseudo discord

maelenfrance

### Que s'est-il passé ?

Un pet qui doit replanter automatiquement les patates utilisé avec une houe royale, ne replante que là où on casse et pas sur la zone 3x3

### Étapes à suivre pour reproduire le bug

utiliser un pet qui replante (peu importe le quel) et la houe royale

### Qu'aurait-il dû arriver ?

Replanter sur le 3x3

### Date et heure de la production du bug

x

### Serveur

x

### Information supplémentaire

UUID: ccf4c91d-a9da-442e-94df-2a03f6b3cb1a
Position: 5430 40 -3606 SuperiorWorld
Ping: 22ms

**Comment by falistos** [comment]
@TopeEstLa Ca semble être une incompatibilité entre Items et RivrsPets. Est ce que tu fire un BlockBreakEvent sur tes effets 3x3 ?

**Comment by TopeEstLa** [comment]
Bien sur que non

> @TopeEstLa Ca semble être une incompatibilité entre Items et RivrsPets. Est ce que tu fire un BlockBreakEvent sur tes effets 3x3 ?

**Comment by itsme-to** [comment]
Bonjour, ce n'est pas vraiment un bug, c'est une mécanique trop forte.
