### ISSUE TITLE
[BUG] Pas de silex ni de gravier au shop pour le /ase

### ISSUE THREAD

**Issue by Amateur2Drapeau** [RivrsMc/SeasonSky-Issues#68]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MaelEnFrance

### Pseudo discord

maelenfrance

### Que s'est-il passé ?

Si un joueur achete le /ase il ne peut pas l'utiliser car il n'y a ni gravier ni silex pour le /ase

### Étapes à suivre pour reproduire le bug

x

### Qu'aurait-il dû arriver ?

pouvoir acheter un des deux

### Date et heure de la production du bug

12-07 01:25:38

### Serveur

x

### Information supplémentaire

UUID: ccf4c91d-a9da-442e-94df-2a03f6b3cb1a
Position: 5428 40 -3602 SuperiorWorld
Ping: 20ms

**Comment by itsme-to** [comment]
Bonjour, il y a bien du gravier dans le /shop, catégorie Blocs
