### ISSUE TITLE
[BUG] Eclozr se pose en double

### ISSUE THREAD

**Issue by entropy-hub** [RivrsMc/SeasonSky-Issues#7]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Kalouche

### Pseudo discord

Kalouche

### Que s'est-il passé ?

Lorsque l'on fait un clic droit pour poser un eclozr sur une grass (la plante, pas le bloc), l'eclozr se pose au dessus de la plante, celui-ci fonctionne, et un autre eclozr se place à côté de la plante, celui-ci n'était pas utilisable, et incassable.

### Étapes à suivre pour reproduire le bug

1) prendre un eclozr dans sa main
2) essayer de le poser sur une grass (la plante)

### Qu'aurait-il dû arriver ?

L'eclozr aurait du remplacer la grass

### Date et heure de la production du bug

08-07 19:09:51

### Serveur

island-06

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/82654455/d213e43a-01a0-4b46-a94f-e199196febae)

### Information supplémentaire

UUID: cfee30a9-1ec8-4126-aeff-8739683cf7e0
Position: 14398 101 -5 SuperiorWorld
Ping: 23ms

**Comment by itsme-to** [comment]
Résolu
