### ISSUE TITLE
[BUG] urgent xp caisse vote

### ISSUE THREAD

**Issue by Isweazu** [RivrsMc/SeasonSky-Issues#70]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Isweazu

### Pseudo discord

xx4040

### Que s'est-il passé ?

Les joueurs abusent de la caisse vote, celle-ci peut donner 20 ou 30 niveau je ne sais plus trop, si nous avons imaginons 700 niveau  les 30 s'additionnent ce qui fait 730, au lieu de gagner les 1400xp des fameux 30niveaux en questions ceux-ci vont en gagner 500k voir bien + dépendant du nombre d'xp déjà mis sur la personne.
Les joueurs en abusent encore afin de pouvoir craft des doubles coffres de quêtes sans soucis 

### Étapes à suivre pour reproduire le bug

Avoir bcp de niveaux sur sois, ouvrir des clés de cotés et drop des niveaux 

### Qu'aurait-il dû arriver ?

Avoir les 30 niveaux en xp et non pas en niveaux direct 

### Date et heure de la production du bug

04.43 le 12/07

### Serveur

Tout les servs

**Comment by itsme-to** [comment]
Effectif au prochain merge
