### ISSUE TITLE
[BUG] Couleur Is permission

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#71]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

il y a un problème de description en couleur

### Étapes à suivre pour reproduire le bug

1. faire /is panel
2. aller dans permission
3. aller a la 3e page

### Qu'aurait-il dû arriver ?

le texte devrait etre d'une seule couleur

### Date et heure de la production du bug

12/07/2023 08:34

### Serveur

island 02

### Screen / vidéo

![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/124496446/69d22e0e-27f2-4cf8-8634-3b22bb1361bd)

**Comment by itsme-to** [comment]
Effectif au prochain merge
