### ISSUE TITLE
[BUG] Reward Mineur 12

### ISSUE THREAD

**Issue by Warnel0** [RivrsMc/SeasonSky-Issues#72]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Warnell

### Pseudo discord

warnel0

### Que s'est-il passé ?

Récompenses mineur level 12 donne la récompense du fermier level 12 (seau d'eau infini)

### Étapes à suivre pour reproduire le bug

monter mineur 12

### Qu'aurait-il dû arriver ?

reward mineur 12

### Date et heure de la production du bug

10h20

### Serveur

island 05

### Screen / vidéo

N/A

### Information supplémentaire

N/A

**Comment by itsme-to** [comment]
Effectif au prochain merge
