### ISSUE TITLE
[BUG] Canne royal qui n'a pas effet + ne perd pas de dura en main gauche

### ISSUE THREAD

**Issue by hija621** [RivrsMc/SeasonSky-Issues#73]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Hija621

### Pseudo discord

hija621

### Que s'est-il passé ?

L'effet de la canne royale (10% de doubler la pêche) n'a pas l'air de fonctionner, de plus le fait de le mettre en main gauche fait qu'elle ne perd pas de dura

### Étapes à suivre pour reproduire le bug

Prendre la canne
Pecher 
Pecher avec la main gauche

### Qu'aurait-il dû arriver ?

Avoir l'effet et predre de la dura

### Date et heure de la production du bug

12/07 11h30

### Serveur

Island

**Comment by LuluxClient** [comment]
Pour les 10% de doubler les lots ceci a été fix et sera effecitf à la prochaine maj !

**Comment by ArDiDEx** [comment]
Hey! Je viens d'essayer et la canne perd de la dura dans la main gauche
Peux-tu voir si tu arrives encore à faire le bug? Si non, je te laisse fermer l'issue
Merci du report

**Comment by hija621** [comment]
Salut! C'est bon! Je ferme l'issue!
