### ISSUE TITLE
[BUG] reproduction mobs

### ISSUE THREAD

**Issue by Amateur2Drapeau** [RivrsMc/SeasonSky-Issues#75]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MaelEnFrance

### Pseudo discord

maelenfrance

### Que s'est-il passé ?

Les mobs stackés ne peuvent pas se reproduire comme indiqués dans le /jobs

### Étapes à suivre pour reproduire le bug

Avoir des mobs stackés

### Qu'aurait-il dû arriver ?

Pouvoir faire reproduire les mobs stackés ou trouver une alternative

### Date et heure de la production du bug

x

### Serveur

x

**Comment by LuluxClient** [comment]
Pour des raisons d'optimizations la reproduction de mobs est désactivé, l'ai des mobs est off donc cela rend la reproduction impossible, néanmoins cela restera une possibilité dans une prochaine maj
