### ISSUE TITLE
[BUG] Respawn aléatoire à la connexion

### ISSUE THREAD

**Issue by Amateur2Drapeau** [RivrsMc/SeasonSky-Issues#76]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MaelEnFrance

### Pseudo discord

maelenfrance

### Que s'est-il passé ?

Lorsque que l'on se connecte le spawn est aléatoire, (un monde aventure ou un spawn peu importe) les joueurs se connectent au hasard

### Étapes à suivre pour reproduire le bug

Se deco reco

### Qu'aurait-il dû arriver ?

Sauvegarder la position

### Date et heure de la production du bug

x

### Serveur

x

### Information supplémentaire

UUID: ccf4c91d-a9da-442e-94df-2a03f6b3cb1a
Position: 5430 40 -3607 SuperiorWorld
Ping: 24ms

**Comment by LuluxClient** [comment]
Ceci n'est pas un bug, si tu étais dans le monde aventure sur le spawn03 et que tu vas sur ton IS et par la suite tu refais /spawn et que tu vas au spawn02, tu seras à ta position que tu étais au spawn02.
