### ISSUE TITLE
[BUG] Le générateur prestige 7 génère moins que le 5

### ISSUE THREAD

**Issue by Amateur2Drapeau** [RivrsMc/SeasonSky-Issues#77]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MaelEnFrance

### Pseudo discord

maelenfrance

### Que s'est-il passé ?

Le générateur de niveau prestige 7 ne génère plus d'emeraude alors que le 5 oui

### Étapes à suivre pour reproduire le bug

Passer prestige 7

### Qu'aurait-il dû arriver ?

Améliorer le générateur et ne pas faire regresser le generateur au prestige

### Date et heure de la production du bug

x

### Serveur

x

### Information supplémentaire

UUID: ccf4c91d-a9da-442e-94df-2a03f6b3cb1a
Position: 5438 44 -3592 SuperiorWorld
Ping: 35ms

**Comment by LuluxClient** [comment]
Aucun bug, nous avons corrigé un soucis ou en spammant le bouton de prestige tu recevais 3-5x plus les minerais que tu étais sensé avoir.
