### ISSUE TITLE
[BUG] Piston toujours compté dans la limite

### ISSUE THREAD

**Issue by Amateur2Drapeau** [RivrsMc/SeasonSky-Issues#78]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

MaelEnFrance

### Pseudo discord

maelenfrance

### Que s'est-il passé ?

Les pistons cassés à la pioche royale sont comptés dans la limite alors qu'ils sont cassés, cela n'est pas fixe avec le /is recalc

### Étapes à suivre pour reproduire le bug

Casser les pistons à la pioche royale, certaines fois le /is recalc debug mais ici ce n'est pas le cas

### Qu'aurait-il dû arriver ?

Le recalc aurait dû debug les pistons

### Date et heure de la production du bug

x

### Serveur

island-04

### Information supplémentaire

UUID: ccf4c91d-a9da-442e-94df-2a03f6b3cb1a
Position: 5431 40 -3607 SuperiorWorld
Ping: 27ms

**Comment by LuluxClient** [comment]
Les pistons et pistons collants ne seront plus activable par l'effet de la pioche et ce soucis ne devrait pas revenir. Effectif dès la prochaine maj !
