### ISSUE TITLE
[BUG] Compacteur inutilisable 

### ISSUE THREAD

**Issue by Vakashi** [RivrsMc/SeasonSky-Issues#79]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Vakashii

### Pseudo discord

Vakashi

### Que s'est-il passé ?

Bonjour, j'ai poser un 2ème compacteur et je ne peux pas l'utiliser.

### Étapes à suivre pour reproduire le bug

Poser un deuxième compacteur

### Qu'aurait-il dû arriver ?

??

### Date et heure de la production du bug

12-07 18:25:10

### Serveur

island-01

### Information supplémentaire

UUID: 71286498-5942-4e35-8281-ff607ebe1af7
Position: 16193 100 -7203 SuperiorWorld
Ping: 12ms

**Comment by itsme-to** [comment]
Le bug a normalement été résolu
