### ISSUE TITLE
[BUG] Quête île ne fonctionnant pas - Mettre un objet pour améliorer 

### ISSUE THREAD

**Issue by eliott1111** [RivrsMc/SeasonSky-Issues#8]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

eliott_1111__

### Pseudo discord

eliott#5780

### Que s'est-il passé ?

la quête de l'ile quand il faut mettre un objet pour améliorer l'ile de marche pas 

### Étapes à suivre pour reproduire le bug

fdrg

### Qu'aurait-il dû arriver ?

la quête aurai marcher 

### Date et heure de la production du bug

08-07 19:07:59

### Serveur

seasonsky

### Screen / vidéo

fdrfg

### Information supplémentaire

UUID: 52e84bc9-a9c4-400a-b2f6-5bcb4d7f8f5d
Position: -1796 99 -12599 SuperiorWorld
Ping: 32ms

**Comment by LuluxClient** [comment]
Hello @eliott1111 pourrais-tu me dire si demain c'est toujours d'actualité et si tu peux détailler la partie "Étapes à suivre pour reproduire le bug" en donnant tous les détails qu'il faut (objet posé etc...)
