### ISSUE TITLE
[BUG] Mission Briques Rouges

### ISSUE THREAD

**Issue by Dragomal** [RivrsMc/SeasonSky-Issues#80]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Martin2109

### Pseudo discord

dragomal

### Que s'est-il passé ?

J'ai acheté une quête avancé demandant de placer des briques rouges, cependant aucun type de brique ne permet d'augmenter le compteur

### Étapes à suivre pour reproduire le bug

Obtenir une quête avancé demandant de poser des briques rouges

### Qu'aurait-il dû arriver ?

Poser des briques rouges du Nether ou si c'est une erreur de Traduction le type correspondant afin d'augmenter le compteur de la quête

### Date et heure de la production du bug

18h40 - 12/07/2023

### Serveur

SeasonSky - island-03

### Screen / vidéo

![image_2023-07-12_184854492](https://github.com/RivrsMc/SeasonSky-Issues/assets/115795428/339c5361-6fd9-4137-afc9-773e31ff588c)

**Comment by Tharkuban** [comment]
Il faut poser des blocs de briques classiques
Si ça ne marche pas, c'est probablement que tu as une autre quête prioritaire dans ton inventaire (ex : placer X blocs, mais placé avant dans ton inventaire)

**Comment by Dragomal** [comment]
Oh en effet j'avais aussi une quête ou il fallait uniquement poser des blocs, il a surement pris l'ascendant dessus
