### ISSUE TITLE
[BUG] Casser le même Bloc Quête

### ISSUE THREAD

**Issue by Dragomal** [RivrsMc/SeasonSky-Issues#81]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Martin2109

### Pseudo discord

dragomal

### Que s'est-il passé ?

Pour les quêtes consistant a casser un bloc spécifique, poser et casser le même bloc en continu mais monter le compteur

### Étapes à suivre pour reproduire le bug

Avoir une quête nécessitant de casser un certain bloc, prendre le bloc en question et le poser/casser en continue

### Qu'aurait-il dû arriver ?

Que le bloc poser par un joueur ne puisse pas augmenter le compteur de la quête

### Date et heure de la production du bug

18h50 - 12/07/2023

### Serveur

SeasonSky - island-03

**Comment by Acterax** [comment]
C'est corrigé merci !
