### ISSUE TITLE
[BUG] XP cuisson haut fourneau job mineur - Duplication

### ISSUE THREAD

**Issue by FeyZor** [RivrsMc/SeasonSky-Issues#82]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

FeyZor

### Pseudo discord

feyzor_

### Que s'est-il passé ?

J'ai voulu faire cuire mon minerai de Fer Brut pour gagner de l'xp dans le jobs Mineur dans un haut fourneau mais je n'ai reçu aucune quantité d'xp.  Je précise que le bug est présent essentiellement sur les haut founeaux mais pas sur les fours basic

### Étapes à suivre pour reproduire le bug

1. Poser un haut fourneau
2. Mettre le minerai de Fer brut 
3. Mettre du charbon
4. Attendre la cuisson

### Qu'aurait-il dû arriver ?

Une fois la cuisson de minerai fini j'étais sensé recevoir de l'xp de job mineur . 

### Date et heure de la production du bug

12/07/2023  à 19h

### Serveur

Island-02

**Comment by Acterax** [comment]
@FeyZor je viens de tester et pour moi tout fonctionne, tu pourrais re-tester ?

**Comment by Alex96x2** [comment]
J'ai le même souci, il faut a chaque fois que je casse et repose les blast furnace pour que l'xp soit compter, alors que je suis seul sur mon île donc personne ne peut intéragir avec.

**Comment by itsme-to** [comment]
Issue existe déjà je close celle-ci
