### ISSUE TITLE
[BUG] /rewards , l'objet est perdu quand l'inventaire est plein

### ISSUE THREAD

**Issue by Bakultimate** [RivrsMc/SeasonSky-Issues#84]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

bakultimate

### Pseudo discord

Bakultimate

### Que s'est-il passé ?

J'ai obtenu mes récompenses de /rewards, et à l'avant-dernière, nous sommes censés recevoir un débris antique.

Quand l'inventaire est plein cependant, l'objet est complètement perdu, plutôt qu'avoir un message d'erreur indiquant qu'on a l'inventaire plein (comme pour retirer les pets du menu /pets), ou encore jeter l'objet devant soi.

### Étapes à suivre pour reproduire le bug

Récupérer un /rewards avec l'inventaire plein.

### Qu'aurait-il dû arriver ?

Je pense qu'un message d'erreur devrait nous empêcher de récupérer la récompense si l'inventaire est plein.

### Date et heure de la production du bug

12/07/2023 environ 22:08

### Serveur

Mon île perso

**Comment by LuluxClient** [comment]
Ceci n'est pas un bug mais on va voir pour rajouter un petit système qui empêche la récupération d'un reward si tu n'as pas X slots dispo dans ton inventaire.

**Comment by entropy-hub** [comment]
Un message d'avertissement sera envoyé au joueur, et la reward sera  non récupérable quand l'inventaire est plain
