### ISSUE TITLE
[BUG] Palier du /vote

### ISSUE THREAD

**Issue by NiamoR320** [RivrsMc/SeasonSky-Issues#86]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

NiamoR320

### Pseudo discord

NiamoR

### Que s'est-il passé ?

Le site et le serveur nous indique pas le même nombre de vote...

### Étapes à suivre pour reproduire le bug

1.allez en jeu pour faire /vote
2 allez sur le site dans longlet vote

### Qu'aurait-il dû arriver ?

Avoir le même nombre de vote

### Date et heure de la production du bug

Début de l'open

### Serveur

Bonne question

### Screen / vidéo

![Palier seasonsky](https://github.com/RivrsMc/SeasonSky-Issues/assets/80202399/1ebda0b1-1f24-4367-8908-a912a696dc42)

**Comment by LuluxClient** [comment]
Cela est normal, tu as les votes par mois (site) et les votes par semaine (palier) ce sont 2 choses différentes
