### ISSUE TITLE
[BUG] Stuff aventurier

### ISSUE THREAD

**Issue by Kutakimochi** [RivrsMc/SeasonSky-Issues#87]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Kutakimochi

### Pseudo discord

Kutakimochi#0879

### Que s'est-il passé ?

On ne peut pas mettre mending sur les items de l'aventurier ni aucun autre enchant alors qu'il y a écrit "Cet objet peut etre modifié

### Étapes à suivre pour reproduire le bug

1. prendre une enclume
2. prendre son item de l'aventurier
3. essayer de mettre un enchantement via un live

### Qu'aurait-il dû arriver ?

j'aurais du réussir a mettre mon enchantement

### Date et heure de la production du bug

12-07 23:41:44

### Serveur

island-04

### Screen / vidéo

eh je ne sais pas comment on met un screen

### Information supplémentaire

UUID: 9a5af67d-a45d-4d99-bac2-f922ae376afd
Position: 14418 100 3593 SuperiorWorld
Ping: 18ms

**Comment by NoHere32** [comment]
Cela devrait être good lors du prochain transfert.
