### ISSUE TITLE
[BUG] Casser un alambic ne rends pas son contenu

### ISSUE THREAD

**Issue by Dadamomo** [RivrsMc/SeasonSky-Issues#88]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Dadamo

### Pseudo discord

Dadamo

### Que s'est-il passé ?

en cassant mon alambic pour le déplacer, les bouteilles et les blaze powders ont disparus (n'ont pas drop)

### Étapes à suivre pour reproduire le bug

1. Casser l'alambic
2. seul l'alambic est drop

### Qu'aurait-il dû arriver ?

le contenu aurait drop

### Date et heure de la production du bug

00h00

### Serveur

island

**Comment by itsme-to** [comment]
Le bug existe effectivement bien lorsque c'est cassé avec la pioche Royale ou item du style.
Il existe aussi pour :
- Alambic
- Four
- Toneau
- BlastFurnace
- Smoker
- Jukebox

**Comment by itsme-to** [comment]
- Trapped Chest
