### ISSUE TITLE
[BUG] Pet Terri Rouge Foncé Non fonctionnel

### ISSUE THREAD

**Issue by jejeworld** [RivrsMc/SeasonSky-Issues#89]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

jejeworld

### Pseudo discord

jejeworld

### Que s'est-il passé ?

Le Pet Terri Rouge Foncé n'applique pas son multiplicateur correctement sur les rubis gagnés.

### Étapes à suivre pour reproduire le bug

/

### Qu'aurait-il dû arriver ?

/

### Date et heure de la production du bug

/

### Serveur

All

### Screen / vidéo

/

### Information supplémentaire

/

**Comment by Asherate** [comment]
ça multiplie bien, le message est pas actualisé avec la nouvelle valeur, mais le solde multiplié est bien crédité
