### ISSUE TITLE
Spawner 

### ISSUE THREAD

**Issue by Nam0i** [RivrsMc/SeasonSky-Issues#9]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Nam0iSan 

### Pseudo discord

Nami_san

### Que s'est-il passé ?

Problème avec les spawner à golem les Golem de Spawn pas du tout 

### Étapes à suivre pour reproduire le bug

1Acheter ou prendre le grade 
2 poser le spawner sur le sol o

### Qu'aurait-il dû arriver ?

Le Spawn de golem 

### Date et heure de la production du bug

8/07

### Serveur

Tous

**Comment by LuluxClient** [comment]
Aucun soucis de mon côté, il faut bien faire attention au blocs autour, pas d'eau normalement
