### ISSUE TITLE
[BUG] Durabilité Épée Royale

### ISSUE THREAD

**Issue by jejeworld** [RivrsMc/SeasonSky-Issues#92]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

jejeworld

### Pseudo discord

jejeworld

### Que s'est-il passé ?

La durabilité Custom de l'épée royale est mal comptée.
Elle compte le nombre de mobs touchés et non les clics.
Il faudrait passer la dura à 5000 ou alors compter seulement les clics et non les mobs touchés.
Car avec Affilage III (Sweeping Edge) trop de monstres sont touchés par coup et l'épée perd entre 5-20 dura par coup.

### Étapes à suivre pour reproduire le bug

/

### Qu'aurait-il dû arriver ?

/

### Date et heure de la production du bug

/

### Serveur

All

### Screen / vidéo

/

### Information supplémentaire

/

**Comment by Romariin** [comment]
Même chose pour les autres épée a dura custom (tu perd 2/5) pour une qui n'a pas sweeping edge

**Comment by ArDiDEx** [comment]
Hey! Ça sera fix dans la nuit avec le redémarrage
Merci du report
