### ISSUE TITLE
[BUG] Commande /nick

### ISSUE THREAD

**Issue by Ninjaduff** [RivrsMc/SeasonSky-Issues#93]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

OpticalD

### Pseudo discord

OpticalD

### Que s'est-il passé ?

Je ne peux pas /nick
![image](https://github.com/RivrsMc/SeasonSky-Issues/assets/22250027/0ca71002-a8fb-4cf9-965c-d757c7309af0)

Cela me dit que je n'est pas les permissions,

Je suis premium et Legende.

### Étapes à suivre pour reproduire le bug

Cela me dit que je n'est pas les permissions,

Je suis premium et Legende.

### Qu'aurait-il dû arriver ?

Cela me dit que je n'est pas les permissions,

Je suis premium et Legende.

### Date et heure de la production du bug

13-07 00:49:59

### Serveur

island-01

### Information supplémentaire

UUID: f3e13c76-29f1-4b3b-a638-80f42aa38fa7
Position: -1775 135 10779 SuperiorWorld
Ping: 136ms

**Comment by Asherate** [comment]
@Ninjaduff pourrait-tu me donner la commande exacte que tu as executée s'il te plait ?

**Comment by Asherate** [comment]
@Ninjaduff suite à une vérification, le /nick n'est ni présent dans le légende, ni dans le premium, il s'agit d'une commande appart que tu peut te procurer dans la boutique

**Comment by Ninjaduff** [comment]
Jai utilisé 2 commandes. /nick Duff et /Nick OpticalD Duff
