### ISSUE TITLE
[BUG] /ignore est indisponible

### ISSUE THREAD

**Issue by Tharkuban** [RivrsMc/SeasonSky-Issues#95]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Tharkuban

### Pseudo discord

Chow (Tharkuban)

### Que s'est-il passé ?

La commande /ignore est indisponible

### Étapes à suivre pour reproduire le bug

Utiliser la commande /ignore

### Qu'aurait-il dû arriver ?

Que l'on ai accès à cette commande

### Date et heure de la production du bug

//

### Serveur

//

**Comment by Asherate** [comment]
Fix
