### ISSUE TITLE
[BUG] Jobs bûcheron pas d'xp

### ISSUE THREAD

**Issue by Raggneir** [RivrsMc/SeasonSky-Issues#96]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

Raggneir

### Pseudo discord

Raggneir

### Que s'est-il passé ?

quand on fait cuir des bûches pour avoir du charcoal ça donne plus d’xp bûcheron 

### Étapes à suivre pour reproduire le bug

Cuire des bûches 

### Qu'aurait-il dû arriver ?

Donner de l’xp 

### Date et heure de la production du bug

.

### Serveur

Seasonsky

### Screen / vidéo

.

### Information supplémentaire

.

**Comment by LuluxClient** [comment]
Salut tu cuis ton bois dans un four et quel type de bois précisement ? @Raggneir

**Comment by Raggneir** [comment]
hello, avec toutes les bûches

**Comment by Raggneir** [comment]
@LuluxClient

**Comment by itsme-to** [comment]
Le bug a été réglé
