### ISSUE TITLE
PERTE DE CLASSEMENT TOP 1 ILE 

### ISSUE THREAD

**Issue by Isozuku** [RivrsMc/SeasonSky-Issues#97]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

isozuku

### Pseudo discord

zuku4973

### Que s'est-il passé ?

bonjours, nous avons farmer avec ma team le classement de l il, depuis 5h05 nous farmons les crystaux nous sommes passer premier avec 24k pts et Nous avons utiliser la commande is recalc suggere par le super modo Hijaa et nous sommes redescendu a 1000 pts pouvez vous nous aider svp?

### Étapes à suivre pour reproduire le bug

nous avons juste fais un /is recalc 

### Qu'aurait-il dû arriver ?

nous n aurions pas du perdre 22000 pts d ile et passer de premier a dernier 

### Date et heure de la production du bug

le 13/07/23 a 7H30

### Serveur

serveur Season Sky sur notre ile

### Screen / vidéo

![Minecraft_Screenshot_2023 07 13_-_07 30 10 32](https://github.com/RivrsMc/SeasonSky-Issues/assets/139431573/1f3fec0d-5e0f-4b32-ab5e-137c6bed5e2b)

### Information supplémentaire

Pouvez vous nous rendre notre top 1 classement svp

**Comment by ArDiDEx** [comment]
hey, c'était un bug temporaire avec la commande /is recalc qui a été fix il y a 3 jours environ
bon jeu
