### ISSUE TITLE
[BUG] /ignore all

### ISSUE THREAD

**Issue by LupusArctos4** [RivrsMc/SeasonSky-Issues#99]
### Confirmation

- [X] J'ai bien vérifié si le bug a déjà été report
- [X] Le bug que je report n'est pas un bug de duplication (discord ticket pour cela)

### Pseudo en jeu

darkshadows267

### Pseudo discord

loic_darkwolf

### Que s'est-il passé ?

le /ignore all enlève tout les messages mais dans le chat mais les mp passe toujours

### Étapes à suivre pour reproduire le bug

1. faire /ignore all
2. ne plus voir les msg dans le chat mais voir les mp

### Qu'aurait-il dû arriver ?

ca devrait aussi bloquer les mp

### Date et heure de la production du bug

13/07/2023 11:19

### Serveur

island 02

**Comment by NoHere32** [comment]
Si tu /ignore all tu peux également faire /msgtoggle.
